actions-add = Ekle
actions-cancel = İptal
actions-choose = Seç
actions-close = Kapat
actions-copy = Kopyala
actions-custom-study = Özel Çalışma
actions-decks = Desteler
actions-delete = Sil
actions-export = Dışarıya Aktar
actions-filter = Filtre
actions-help = Yardım
actions-import = İçeri Aktar
actions-name = Ad:
actions-new = Yeni
actions-new-name = Yeni ad:
actions-options = Seçenekler
actions-options-for = { $val } için seçenekler
actions-preview = Önizleme
actions-rebuild = Yeniden oluştur
actions-rename = Yeniden Adlandır
actions-rename-deck = Desteyi Yeniden Adlandır
actions-replay-audio = Sesi Tekrarla
actions-reposition = Yeniden Konumlandır
actions-save = Kaydet
actions-search = Ara
actions-shortcut-key = Kısayol tuşu: { $val }
actions-suspend-card = Kartı Askıya Al
actions-set-due-date = Son Tarihi Ayarla
actions-card-info = Kart Bilgisi
