adding-add-shortcut-ctrlandenter = Ekle (kısayol tuşu: ctrl+enter)
adding-added = Eklendi
adding-discard-current-input = Geçerli girdiyi atmak ister misin?
adding-keep-editing = Düzenlemeye Devam Et
adding-edit = "{ $val }" öğesini düzenle
adding-history = Geçmiş
adding-note-deleted = (Not silindi)
adding-shortcut = Kısayol: { $val }
adding-the-first-field-is-empty = İlk alan boş.
