card-stats-added = Eklendi
card-stats-first-review = İlk Gözden Geçirme
card-stats-latest-review = Son Gözden Geçirme
card-stats-interval = Aralık
card-stats-ease = Kolaylık
card-stats-review-count = Tekrarlar
card-stats-lapse-count = Sapmalar
card-stats-average-time = Ortalama Zaman
card-stats-total-time = Toplam Süre
card-stats-new-card-position = Konum
card-stats-card-template = Kart tipi
card-stats-note-type = Not Tipi
card-stats-deck-name = Deste
card-stats-note-id = Not Kimliği
card-stats-card-id = Kart ID
