card-templates-front-template = Ön Şablon
card-templates-back-template = Arka Şablon
card-templates-front-preview = Ön Görünüm
card-templates-back-preview = Arka Görünümü
card-templates-preview-box = Önizleme
card-templates-anki-couldnt-find-the-line-between = Anki, soruyla cevap arasında bağlantı kuramadı. Soru ve cevabın yerini değiştirmek için şablonu elle ayarlayın.
card-templates-at-least-one-card-type-is = En az bir kart tipi gereklidir.
card-templates-card = Kart { $val }
card-templates-card-types = Kart Tipleri
card-templates-card-types-for = { $val } için Kart Tipleri
card-templates-cloze = Kapat
card-templates-delete-the-as-card-type-and = '%(a)s' kart tipi ve ona ait %(b)s silinsin mi?
card-templates-enter-deck-to-place-new = Desteye yeni { $val } kartları yerleştirin, ya da boş bırakın:
card-templates-enter-new-card-position-1 = Yeni kart sırasını girin (1...{ $val }):
card-templates-flip = Çevir
card-templates-off =  (kapalı)
card-templates-on =  (açık)
