decks-add-new-deck-ctrlandn = Yeni Deste Ekle (Ctrl+N)
decks-are-you-sure-you-wish-to = { $val } girdisini silmek istediğinizden emin misiniz?
decks-build = Yapılandır
decks-create-deck = Deste Oluştur
decks-deck = Deste
decks-decreasing-intervals = Aralığı azaltma
decks-delete-deck = Desteyi kaldır
decks-filter = Filtre:
decks-get-shared = Deste Bul
decks-import-file = Dosyayı İçeriye Aktar
decks-increasing-intervals = Süreyi artırma
decks-latest-added-first = Son eklenen ilk
decks-limit-to = Sınırla
decks-minutes = dakîka
decks-most-lapses = En yüksek sapmalar
decks-name-for-deck = Deste adı:
decks-new-deck-name = Yeni deste adı:
decks-oldest-seen-first = En eski görülen ilk
decks-order-added = Sıralama eklendi
decks-order-due = Sıralama sonu
decks-please-select-something = Lütfen bir şey seçin.
decks-random = Rastgele
decks-reschedule-cards-based-on-my-answers = Bu destedeki cevaplarım üzerine dayanarak kartları yeniden programla
decks-study = Çalış
decks-the-provided-search-did-not-match = Sağlanan arama, hiçbir kartla eşleşmedi. Gözden geçirmek ister misiniz?
