exporting-all-decks = Bütün Desteler
exporting-anki-20-deck = Anki 2.0 Destesi
exporting-anki-deck-package = Anki deste paketi
exporting-cards-in-plain-text = Düz Metindeki Kartlar
exporting-couldnt-save-file = Dosya kaydedilemedi: { $val }
exporting-export = Dışarıya Aktar...
exporting-export-format = <b>Dışarıya Aktarım Biçimi</b>:
exporting-include = <b>Dahil</b>:
exporting-include-media = Ortam Ekle
exporting-include-scheduling-information = Zamanlama bilgisini dahil et
exporting-include-tags = Etiketleri dahil et
exporting-notes-in-plain-text = Düz Metinli Notlar
