notetypes-front-field = Ön
notetypes-back-field = Geri
notetypes-add-reverse-field = Tersini Ekle
notetypes-text-field = Metin
notetypes-basic-name = Temel
notetypes-basic-reversed-name = Temel (ve ters kart)
notetypes-basic-optional-reversed-name = Temel (seçimli ters kart)
notetypes-cloze-name = Kapat
notetypes-card-2-name = Kart 2
notetypes-card-1-name = Kart 1
notetypes-add = Ekle: { $val }
notetypes-add-note-type = Not Türü Ekle
notetypes-cards = Kartlar...
notetypes-clone = Klon: { $val }
notetypes-copy = { $val } kopyası
notetypes-delete-this-note-type-and-all = Bu not kategorisini ve içindeki tüm kartları sil
notetypes-delete-this-unused-note-type = Kullanılmayan bu not kategorisini kaldır
notetypes-fields = Alanlar...
notetypes-footer = Dipnot
notetypes-header = Başlık
notetypes-note-types = Not Tipleri
notetypes-options = Seçenekler...
notetypes-please-add-another-note-type-first = Lütfen ilk olarak başka bir not tipi ekleyin.
notetypes-type = Tip
