preferences-automatically-sync-on-profile-openclose = Açma/kapama anında profili otomatik olarak senkronize et
preferences-backups = Yedekler
preferences-basic = Temel
preferences-change-deck-depending-on-note-type = Not tipine göre desteyi değiştir
preferences-learn-ahead-limit = İleri limiti öğrenme
preferences-mins = dk
preferences-network = Ağ
preferences-next-day-starts-at = Bir sonraki gün başlar
preferences-note-media-is-not-backed-up = Not: İçerik yedeklenmedi. Güvenlik için lütfen Anki klasörünüzün periyodik yedeklemesini oluşturun.
preferences-on-next-sync-force-changes-in = Bir sonraki senkronizasyonda değişiklikleri tek yönlü yap
preferences-paste-clipboard-images-as-png = Pano resmini PNG olarak yapıştır
preferences-please-restart-anki-to-complete-language = Dil değişimin tamamlamak için lütfen Anki'yi yeniden başlat.
preferences-preferences = Seçenekler
preferences-scheduling = Yeniden Planlama
preferences-show-next-review-time-above-answer = Yanıt düğmelerinin üstünde sonraki inceleme süresini göster
preferences-show-remaining-card-count-during-review = İnceleme sırasında kalan kart sayısını göster
preferences-some-settings-will-take-effect-after = Bazı ayarlar Anki yeniden başlatıktan sonra geçerli olacaktır.
preferences-synchronisation = <b>Eşitleme</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Eşitleme</b><br> Henüz etkin değil. Ana pencerede eşitleme düğmesine tıklayarak etkinleştirin.
preferences-synchronize-audio-and-images-too = Ses ve resimleri de senkronize edin
preferences-v3-scheduler = V3 planlayıcı
preferences-scheduler = Planlayıcı
