custom-study-cards = കാർഡുകൾ
custom-study-cards-from-the-deck = ഡെക്കിൽ നിന്നുമുള്ള കാർഡുകൾ
custom-study-choose-tags = ടാഗുകൾ തിരഞ്ഞെടുക്കുക
custom-study-custom-study-session = ഇഛാനുസൃതമായ പഠന സെഷൻ
custom-study-due-cards-only = ഡ്യൂ ആയ കാർഡുകൾ മാത്രം
custom-study-new-cards-only = പുതിയ കാർഡുകൾ മാത്രം
custom-study-ok = ശരി
custom-study-review-ahead = നേരത്തെ അവലോകനം നടത്തുക
custom-study-select = തിരഞ്ഞെടുക്കുക
custom-study-select-tags-to-exclude = ഒഴിവാക്കേണ്ട ടാഗുകൾ തിരഞ്ഞെടുക്കുക:
custom-study-study-by-card-state-or-tag = കാർഡിന്റെ അവസ്ഥയോ ടാഗോ അടിസ്ഥാനമാക്കി പഠിക്കുക
