decks-add-new-deck-ctrlandn = പുതിയ ഡെക്ക് ചേർക്കുക
decks-build = നിർമിക്കുക
decks-cards-selected-by = കാർഡുകൾ തിരഞ്ഞെടുത്തതിന്റെ അടിസ്ഥാനം
decks-create-deck = ഡെക്ക് സൃഷ്ടിക്കുക
decks-custom-steps-in-minutes = ഇസ്താനുസൃതമായ ഘട്ടങ്ങൾ (മിനിറ്റുകൾക്കുള്ളിൽ)
decks-deck = ഡെക്ക്
decks-decreasing-intervals = താഴ്ന്ന ഇടവേളകളിൽ
decks-delete-deck = ഡെക്ക് ഇല്ലാതാക്കുക
decks-enable-second-filter = രണ്ടാമത്തെ ഫിൽറ്റർ പ്രാപ്തമാക്കുക
decks-filter = ഫിൽറ്റർ:
decks-filter-2 = ഫിൽറ്റർ 2
decks-get-shared = പങ്കിട്ടതു ലഭ്യമാക്കുക
decks-import-file = ഫയൽ ഇറക്കുമതി ചെയ്യുക
decks-increasing-intervals = ഉയരുന്ന ഇടവേളകൾ
decks-latest-added-first = പുതുതായി ചേർത്തത് ആദ്യം
decks-limit-to = ഒതുക്കുക
decks-minutes = മിനിറ്റുകള്‍
decks-most-lapses = ഏറ്റവും കൂടുതൽ വീഴ്ചകൾ
decks-name-for-deck = ഡെക്കിനു വേണ്ടിയുള്ള പേര്:
decks-new-deck-name = ഡെക്കിന്റെ പുതിയ പേര്:
decks-no-deck = [ഡെക്ക് ഇല്ല]
decks-oldest-seen-first = ഏറ്റവും പഴയത് ആദ്യം കാണുക
decks-order-added = ക്രമം ചേർത്തു
decks-study = പഠനം
decks-study-deck = ഡെക്ക് പഠിക്കുക
