importing-failed-debug-info = ഇറക്കുമതി പരാജയപ്പെട്ടു. ഡീബഗ്ഗിംഗ് വിവരം:
importing-aborted = ഉപേക്ഷിച്ചു: { $val }
importing-added-duplicate-with-first-field = ആദ്യ മണ്ഡലത്തിനൊപ്പം തനിപ്പകർപ്പ് ചേർത്തു: { $val }
importing-allow-html-in-fields = മണ്ഡലങ്ങളിൽ HTML അനുവദിക്കുക
importing-anki-files-are-from-a-very = anki ഫയലുകൾ Anki-യുടെ വളരെ പഴയ പതിപ്പിൽ നിന്നുള്ളതാണ്. Anki വെബ്‌സൈറ്റിൽ ലഭ്യമായ Anki 2.0, ഉപയോഗിച്ച് നിങ്ങൾക്ക് അവ ഇറക്കുമതി ചെയ്യാൻ കഴിയും.
importing-appeared-twice-in-file = ഫയലിൽ രണ്ടുതവണ പ്രത്യക്ഷപ്പെട്ടു: { $val }
importing-by-default-anki-will-detect-the = സ്ഥിരസ്ഥിതിയായി, ടാബ്, കോമ, തുടങ്ങിയ മണ്ഡലങ്ങൾക്കിടയിലുള്ള പ്രതീകം Anki കണ്ടെത്തും. Anki പ്രതീകം തെറ്റായി കണ്ടെത്തുകയാണെങ്കിൽ, നിങ്ങൾക്ക് അത് ഇവിടെ നൽകാം. ടാബിനെ പ്രതിനിധീകരിക്കുന്നതിന്  \t ഉപയോഗിക്കുക.
importing-change = മാറ്റുക
importing-colon = ഭിത്തിക
importing-comma = കോമ
importing-empty-first-field = ആദ്യ മണ്ഡലം ശൂന്യപ്പെടുത്തുക: { $val }
importing-field-mapping = മണ്ഡല മാപ്പിംഗ്
importing-field-of-file-is = { $val }<b>{ $val }</b> ഫയലിന്റെ മണ്ഡലം:
importing-identical = സമാനമായത്
importing-ignore-field = മണ്ഡലം അവഗണിക്കുക
importing-ignore-lines-where-first-field-matches = ആദ്യ മണ്ഡലം നിലവിലുള്ള കുറിപ്പുമായി പൊരുത്തപ്പെടുന്ന വരികൾ അവഗണിക്കുക
importing-ignored = <ignored>
importing-import-even-if-existing-note-has = നിലവിലുള്ള കുറിപ്പിന് ആദ്യ മണ്ഡലം ഉണ്ടെങ്കിൽ പോലും ഇറക്കുമതി ചെയ്യുക
importing-import-options = ഓപ്ഷനുകൾ ഇറക്കുമതി ചെയ്യുക
importing-importing-complete = ഇറക്കുമതി പൂർത്തിയായി.
importing-invalid-file-please-restore-from-backup = അസാധുവായ ഫയൽ. ബാക്കപ്പിൽ നിന്ന് പുനഃസ്ഥാപിക്കുക.
importing-map-to = { $val }-ലേക്ക് മാപ്പ് ചെയ്യുക
importing-map-to-tags = ടാഗുകളിലേക്കു  മാപ്പ് ചെയ്യുക
