adding-add-shortcut-ctrlandenter = 添加（快捷键：Ctrl+Enter）
adding-added = 已添加
adding-close-and-lose-current-input = 确定要关闭并放弃当前输入的内容吗？
adding-edit = 编辑"{ $val }"
adding-history = 最近添加
adding-note-deleted = （笔记已删除）
adding-shortcut = 快捷键：{ $val }
adding-the-first-field-is-empty = 首字段为空。
adding-you-have-a-cloze-deletion-note = 您选择的是填空题模板，但还没有挖空。请问要继续吗？
adding-cloze-outside-cloze-notetype = 挖空只能用于填空题笔记模板。
adding-cloze-outside-cloze-field = 挖空仅可用于使用 'cloze:' 筛选器的字段。一般是首字段。
