adding-add-shortcut-ctrlandenter = 添加（快捷键：ctrl+enter）
adding-added = 已添加
adding-close-and-lose-current-input = 关闭并放弃当前的输入吗？
adding-edit = 编辑 "{ $val }"
adding-history = 历史
adding-note-deleted = 笔记已删除
adding-shortcut = 快捷键: { $val }
adding-the-first-field-is-empty = 首字段为空.
adding-you-have-a-cloze-deletion-note = 你有一个完形填空类型的笔记，但是还没有制作任何填空内容。仍然要继续吗?
