browsing-add-notes = 添加笔记…
browsing-add-tags = 添加标签
browsing-add-tags2 = 添加标签...
browsing-addon = 插件
browsing-all-card-types = 所有卡片类型
browsing-all-fields = 所有字段
browsing-answer = 答案
browsing-any-cards-mapped-to-nothing-will = 所有孤立的卡片都会被删除，没有保存到卡片中的笔记也会丢失，您确定要继续么？
browsing-any-flag = 所有标记
browsing-browser-appearance = 浏览器外观
browsing-browser-options = 浏览器选项
browsing-buried = 被搁置
browsing-card = 卡片
browsing-card-list = 卡片列表
browsing-card-state = 卡片状态
browsing-cards-cant-be-manually-moved-into = 不能手动移动卡片到过滤牌组
browsing-change-deck = 更改所属牌组
browsing-change-deck2 = 更改所属牌组…
browsing-change-note-type = 改变笔记模板
browsing-change-note-type2 = 改变笔记模板…
browsing-change-to = 将{ $val }改为：
browsing-clear-unused = 删除未使用的
browsing-clear-unused-tags = 删除未使用的标签
browsing-created = 添加日期
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = 当前牌组
browsing-current-note-type = 当前笔记模板：
browsing-delete-notes = 删除笔记
browsing-delete-tags = 删除标签
browsing-duplicate = 复制
browsing-ease = 简易度
browsing-end = 结束
browsing-enter-tags-to-add = 输入要添加的标签：
browsing-enter-tags-to-delete = 输入要删除的标签：
browsing-filtered = 已过滤
browsing-find = <b>查找</b>
browsing-find-and-replace = 查找替换
browsing-find-duplicates = 查找重复
browsing-first-card = 第一张卡片
browsing-flag = 标注
browsing-font = <b>字体</b>:
browsing-font-size = <b>字体大小</b>:
browsing-found-as-across-bs = 在 { $whole } 中找到 { $part } 。
browsing-home = 首页
browsing-ignore-case = 忽略大小写
browsing-in = <b>选择字段</b>:
browsing-interval = 间隔
browsing-last-card = 最后一张卡片
browsing-learning = 正在进行的课程
browsing-line-size = <b>行大小</b>:
browsing-manage-note-types = 管理笔记类型…
browsing-move-cards = 移动卡片
browsing-move-cards-to-deck = 移动卡片到牌组:
browsing-nd-names = { $num }: { $name }
browsing-new = (新)
browsing-new-note-type = 新笔记类型:
browsing-no-flag = 无标注
browsing-note = 笔记
browsing-notes-tagged = 已标注的笔记
browsing-nothing = 无
browsing-only-new-cards-can-be-repositioned = 只有新卡片可以被重新定位.
browsing-optional-filter = 可选过滤器：
browsing-override-back-template = 忽略背面模版
browsing-override-font = 覆盖字体：
browsing-override-front-template = 忽略正面模版
browsing-please-give-your-filter-a-name = 请命名您的过滤器：
browsing-please-select-cards-from-only-one = 请选择同一种笔记类型的卡片.
browsing-preview-selected-card = 预览选择的卡片 ({ $val })
browsing-question = 问题
browsing-queue-bottom = 队尾: { $val }
browsing-queue-top = 队首: { $val }
browsing-randomize-order = 随机顺序
browsing-remove-current-filter = 移除当前过滤器…
browsing-remove-from-your-saved-searches = 将 { $val } 从您保存的搜索中移除？
browsing-remove-tags = 移除标签…
browsing-replace-with = <b>替换</b>:
browsing-reposition = 重新定位...
browsing-reposition-new-cards = 重新定位新卡片
browsing-reschedule = 重新安排进度
browsing-save-current-filter = 保存当前过滤器…
browsing-search-bar-hint = 搜索卡片/笔记（输入文本，然后按回车键）
browsing-search-in = 搜寻位置：
browsing-search-within-formatting-slow = 用格式搜索（耗时长）
browsing-shift-position-of-existing-cards = 改变已存在卡片状态
browsing-sidebar = 侧边栏
browsing-sidebar-filter = 侧边栏过滤器
browsing-sort-field = 排序字段
browsing-sorting-on-this-column-is-not = 不支持该列排序, 请选择另一列.
browsing-start-position = 开始位置：
browsing-step = 步幅:
browsing-suspended = 已暂停
browsing-tag-duplicates = 复制标签
browsing-tag-rename-warning-empty = 无法重命名没有笔记的标签。
browsing-target-field = 目标栏目:
browsing-toggle-mark = 切换标记
browsing-toggle-suspend = 开关暂停状态
browsing-treat-input-as-regular-expression = 以正则表达式输入
browsing-whole-collection = 全部集合
browsing-you-must-have-at-least-one = 必须至少有一列.
browsing-group =
    { $count ->
       *[other] { $count }种组合
    }
browsing-note-count =
    { $count ->
       *[other] { $count }条笔记
    }
browsing-note-deleted =
    { $count ->
       *[other] 删除 { $count } 条笔记
    }
browsing-window-title = 浏览（已选取 { $selected } 张卡片，共 { $total } 张）
browsing-sidebar-expand-children = 展开子节点
browsing-sidebar-collapse-children = 折叠子节点
browsing-sidebar-decks = 牌组
browsing-sidebar-tags = 标签
browsing-sidebar-notetypes = 笔记类型
browsing-sidebar-saved-searches = 已保存的搜索条件
browsing-sidebar-save-current-search = 保存当前搜索条件
browsing-sidebar-card-state = 卡片状态
browsing-sidebar-flags = 标注
browsing-today = 今天
browsing-studied-today = 今天学习的
browsing-added-today = 今天添加的
browsing-again-today = 今天再来一次
browsing-edited-today = 今天编辑
browsing-sidebar-due-today = 今天到期
browsing-sidebar-untagged = 无标签
browsing-sidebar-overdue = 过期
