card-templates-changes-will-affect-notes = { $count } 张使用此卡片类型的笔记将会受影响
card-templates-card-type = 卡片类型：
card-templates-front-template = 正面模版
card-templates-back-template = 背面模版
card-templates-template-styling = 样式
card-templates-front-preview = 正面预览
card-templates-back-preview = 背面预览
card-templates-preview-box = 预览
card-templates-template-box = 模板
card-templates-sample-cloze = 这是一个 { "{{c1::" }示例{ "}}" } 的完形填空。
card-templates-fill-empty = 填入空字段
card-templates-night-mode = 夜间模式
card-templates-preview-settings = 选项
card-templates-invalid-template-number = 卡片模板{ $number }有问题
card-templates-changes-saved = 更改已保存
card-templates-discard-changes = 放弃更改
