custom-study-must-rename-deck = 请先重命名已存在的自定义学习牌组。
custom-study-all-cards-in-random-order-dont = 随机排列的所有卡（不要重新安排）
custom-study-all-review-cards-in-random-order = 随机复习所有卡片
custom-study-cards = 卡片
custom-study-cards-from-the-deck = 牌组中的卡片
custom-study-choose-tags = 选择标签
custom-study-custom-study-session = 自定义学习进程
custom-study-due-cards-only = 仅到期卡片
custom-study-increase-todays-new-card-limit = 增加今天的新卡片上限
custom-study-increase-todays-new-card-limit-by = 增加了今天的新卡片上限
custom-study-increase-todays-review-card-limit = 增加今天的复习卡片上限
custom-study-increase-todays-review-limit-by = 增加了今天的复习卡片上限
custom-study-new-cards-in-deck-over-today = 集合中的新卡片超出今日上限：{ $val }
custom-study-new-cards-only = 仅新卡片
custom-study-no-cards-matched-the-criteria-you = 没有卡片满足你提供的标准.
custom-study-ok = 确定
custom-study-preview-new-cards = 预览新卡片
custom-study-preview-new-cards-added-in-the = 预览加到最后的新卡片
custom-study-require-one-or-more-of-these = 需要这些标签中的一个或者多个:
custom-study-review-ahead = 提前复习
custom-study-review-ahead-by = 提前复习按
custom-study-review-cards-forgotten-in-last = 复习最后忘记的卡片
custom-study-review-forgotten-cards = 复习忘记的卡片
custom-study-reviews-due-in-deck-over-today = 集合中到期的复习数量超出今日上限：{ $val }
custom-study-select = 选择
custom-study-select-tags-to-exclude = 选择排除的标签：
custom-study-selective-study = 选择性学习
custom-study-study-by-card-state-or-tag = 按照卡片状态或者标签学习
