editing-add-media = 添加多媒体文件
editing-align-left = 靠左对齐
editing-align-right = 靠右对齐
editing-an-error-occurred-while-opening = 当打开 { $val } 时出现一个错误
editing-attach-picturesaudiovideo = 附加图片/音频/视频
editing-bold-text = 粗体
editing-cards = 卡片
editing-center = 居中
editing-change-color = 更改颜色
editing-cloze-deletion = 挖空
editing-couldnt-record-audio-have-you-installed = 无法录制音频。您是否已安装“lame”？
editing-customize-card-templates = 自定义卡片模板
editing-customize-fields = 自定义字段
editing-cut = 剪切
editing-edit-current = 编辑当前
editing-edit-html = 编辑HTML
editing-fields = 字段
editing-html-editor = HTML编辑器
editing-indent = 增加缩进
editing-italic-text = 斜体
editing-jump-to-tags-with-ctrlandshiftandt = 用Ctrl+Shift+T跳到标签
editing-justify = 左右对齐
editing-latex = LaTeX
editing-latex-equation = LaTeX 公式
editing-latex-math-env = LaTeX数学环境
editing-mathjax-block = MathJax 块样式
editing-mathjax-chemistry = MathJax 化学公式
editing-mathjax-inline = MathJax 行样式
editing-media = 媒体
editing-ordered-list = 有序列表
editing-outdent = 减少缩进
editing-paste = 粘贴
editing-record-audio = 录制音频
editing-remove-formatting = 去除格式
editing-set-foreground-color = 设置前景色
editing-show-duplicates = 查看重复的卡片
editing-subscript = 下标
editing-superscript = 上标
editing-tags = 标签
editing-to-make-a-cloze-deletion-on = 要为现有的笔记制作一个挖空，你需要通过“笔记>更改笔记模板”，把笔记更改成填空题的模板。
editing-underline-text = 下划线
editing-unordered-list = 无序列表
editing-warning-cloze-deletions-will-not-work = 警告，在你把上方的笔记模板改成 "填空题" 之前，你的挖空将不会生效。

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = 加粗（Ctrl+B）
editing-italic-text-ctrlandi = 斜体 (Ctrl+I)
editing-underline-text-ctrlandu = 下划线 (Ctrl+U)
editing-subscript-ctrland = 下标(Ctrl+=)
editing-superscript-ctrlandand = 上标(Ctrl++)
editing-remove-formatting-ctrlandr = 清除格式 (Ctrl+R)
editing-record-audio-f5 = 录制音频 (F5)
editing-attach-picturesaudiovideo-f3 = 插入图片/音频/视频 (F3)
editing-cloze-deletion-ctrlandshiftandc = 创建填空 (Ctrl+Shift+C)
editing-change-colour-f8 = 选择颜色（F8）
editing-set-foreground-colour-f7 = 设置前景色 (F7)
editing-customize-card-templates-ctrlandl = 自定义卡片模板 (Ctrl+L)
