editing-add-media = 添加多媒体文件
editing-an-error-occurred-while-opening = 当打开 { $val } 时出现一个错误
editing-attach-picturesaudiovideo-f3 = 插入图片/音频/视频 (F3)
editing-bold-text-ctrlandb = 加粗（Ctrl+B）
editing-cards = 卡片
editing-change-colour-f8 = 选择颜色（F8）
editing-cloze-deletion-ctrlandshiftandc = 创建填空 (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = 无法录制音频。您是否已安装“lame”？
editing-customize-card-templates-ctrlandl = 自定义卡片模板 (Ctrl+L)
editing-customize-fields = 自定义字段
editing-cut = 剪切
editing-edit-current = 编辑当前
editing-edit-html = 编辑HTML
editing-fields = 字段
editing-html-editor = HTML编辑器
editing-italic-text-ctrlandi = 斜体 (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = 用Ctrl+Shift+T跳到标签
editing-latex = LaTeX
editing-latex-equation = LaTeX 公式
editing-latex-math-env = LaTeX数学环境
editing-mathjax-block = MathJax 块样式
editing-mathjax-chemistry = MathJax 化学公式
editing-mathjax-inline = MathJax  行样式
editing-media = 媒体
editing-paste = 粘贴
editing-record-audio-f5 = 录制音频 (F5)
editing-remove-formatting-ctrlandr = 清除格式 (Ctrl+R)
editing-set-foreground-colour-f7 = 设置前景色 (F7)
editing-show-duplicates = 查看重复的卡片
editing-subscript-ctrland = 下标(Ctrl+=)
editing-superscript-ctrlandand = 上标(Ctrl++)
editing-tags = 标签
editing-to-make-a-cloze-deletion-on = 要为现有的笔记制作一个挖空，你需要通过“笔记>更改笔记类型”，把笔记更改成填空题的类型。
editing-underline-text-ctrlandu = 下划线 (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = 警告，在你把上方的笔记类型改成 "完形填空" 之前，你的完形填空的填空内容将不会发挥功能。
