exporting-all-decks = 所有的牌组
exporting-anki-20-deck = Anki 2.0 版牌组
exporting-anki-collection-package = Anki集合文件
exporting-anki-deck-package = Anki 牌组包
exporting-cards-in-plain-text = 纯文本卡片
exporting-collection = 集合
exporting-collection-exported = 集合导出成功
exporting-couldnt-save-file = 不能保存文件: { $val }
exporting-export = 导出...
exporting-export-format = <b>导出格式</b>
exporting-include = <b>包含</b>:
exporting-include-html-and-media-references = 包括HTML和文件引用
exporting-include-media = 包含媒体文件
exporting-include-scheduling-information = 包含学习进度信息
exporting-include-tags = 包含标签
exporting-notes-in-plain-text = 纯文本格式的笔记
exporting-selected-notes = 选择的笔记
