fields-add-field = 添加字段
fields-delete-field-from = 从 { $val } 删除字段?
fields-editing-font = 更改字体
fields-field = 字段：
fields-field-name = 字段名称：
fields-description = 描述
fields-description-placeholder = 在编辑界面中，展示在字段名称旁的工具提示
fields-fields-for = { $val } 的字段
fields-font = 字体：
fields-new-position-1 = 新位置 (1...{ $val }):
fields-notes-require-at-least-one-field = 笔记需要至少一个字段.
fields-reverse-text-direction-rtl = 文字反向(RTL)
fields-size = 大小：
fields-sort-by-this-field-in-the = 在浏览器中按照此字段排序
fields-that-field-name-is-already-used = 卡片该面的文字已被使用。
fields-name-first-letter-not-valid = 字段名称不能以 #、^ 或 / 开头。
fields-name-invalid-letter = 字段名称不应包含「:」、「"」、{ "「{」" } 或 { "「}」" }。
