notetypes-front-field = 正面
notetypes-back-field = 背面
notetypes-add-reverse-field = 反向添加
notetypes-text-field = 文字
notetypes-basic-name = 基础
notetypes-basic-reversed-name = 基础的（和相反的卡片）
notetypes-basic-optional-reversed-name = 基础（任意相反的卡片）
notetypes-cloze-name = 填空题
notetypes-basic-type-answer-name = 基础 （输入答案）
notetypes-card-2-name = 卡片2
notetypes-card-1-name = 卡片1
