preferences-automatically-sync-on-profile-openclose = 打开和关闭账户时自动同步
preferences-backups = 备份
preferences-backups2 = 备份
preferences-backupsanki-will-create-a-backup-of = <b>备份</b><br>每次关闭和同步之后Anki都会对你的笔记进行备份
preferences-basic = 基本
preferences-change-deck-depending-on-note-type = 根据笔记模板改变牌组
preferences-changes-will-take-effect-when-you = 改变将会在重启Anki后生效。
preferences-hours-past-midnight = 点 (凌晨)
preferences-interface-language = 界面语言:
preferences-interrupt-current-audio-when-answering = 回答卡片时中断当前音频播放
preferences-keep = 保留
preferences-learn-ahead-limit = 提前学习的上限
preferences-mins = 分钟
preferences-network = 网络
preferences-next-day-starts-at = 新的一天始于
preferences-night-mode = 夜间模式
preferences-note-media-is-not-backed-up = 注意: 媒体文件没有被备份. 为了安全请定期备份你的Anki文件夹.
preferences-on-next-sync-force-changes-in = 在下一次同步时, 强制单方向的覆盖.
preferences-paste-clipboard-images-as-png = 把复制的图片保存为PNG格式
preferences-paste-without-shift-key-strips-formatting = 不按Shift键粘贴会删除格式化字符
preferences-periodically-sync-media = 定期同步媒体
preferences-please-restart-anki-to-complete-language = 请重启 Anki 以完成语言切换
preferences-preferences = 设置
preferences-scheduling = 计划
preferences-show-learning-cards-with-larger-steps = 在复习前展示步伐更长且处于学习中的卡牌
preferences-show-next-review-time-above-answer = 在回答按钮上显示下一次复习时间
preferences-show-play-buttons-on-cards-with = 在卡片上显示音频按钮
preferences-show-remaining-card-count-during-review = 在复习的时候显示剩余的卡片数量
preferences-some-settings-will-take-effect-after = 某些设置将在Anki重新启动后生效
preferences-synchronisation = <b>同步</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同步</b><br> 尚未启用，点击主界面的同步按钮启用。
preferences-synchronize-audio-and-images-too = 同时同步音频和图像
preferences-this-will-reset-any-cards-in = 这将重置所有学习中卡片，清空已筛选卡组并将改变调度器版本。继续吗？
preferences-timebox-time-limit = 提醒指定时间内的学习卡片数
preferences-user-interface-size = 用户界面尺寸
preferences-when-adding-default-to-current-deck = 当添加时，默认是当前牌组
preferences-you-can-restore-backups-via-fileswitch = 您可以通过 文件->切换用户 来恢复备份。
preferences-legacy-timezone-handling = 旧版时区处理（有问题，但 AnkiDroid 2.14 及以下版本必须使用）
preferences-default-search-text = 默认搜索文本
preferences-default-search-text-example = 例如：'deck:current '
