actions-add = එකතු කරන්න
actions-all-selected = තෝරා ඇති සියල්ල
actions-any-selected = තෝරා ඇති යම් එකක්
actions-blue-flag = නිල් කොඩිය
actions-cancel = අවලංගු කරන්න
actions-choose = තෝරන්න
actions-close = වහන්න
actions-copy = පිටපත් කරන්න
actions-custom-study = අභිරුචිය පරිදි පාඩම් කිරීම
actions-decks = කාඩ්පත් ගොනු
actions-delete = මකන්න
actions-export = පිටතට ගන්න
actions-filter = තෝරන්න
actions-green-flag = කොළ කොඩිය
actions-help = උපකාර
actions-import = ආයාත කරන්න
actions-manage = කළමනාකරණය කරන්න
actions-name = නම
actions-new = නව
actions-new-name = අලුත් නම
actions-options = අභිරුචි
actions-options-for = { $val } සඳහා අභිරුචි
actions-orange-flag = තැඹිලි කොඩිය
actions-preview = පෙරදසුන
actions-rebuild = නැවත ගොඩනගන්න
actions-red-flag = රතු කොඩිය
actions-rename = යළි නම් කරන්න
actions-rename-deck = ගොනුව යළි නම් කරන්න
actions-rename-tag = සම්බන්ධකය යළි නම් කරන්න
actions-remove-tag = සම්බන්ධකය ඉවත් කරන්න
actions-replay-audio = ශ්‍රව්‍ය මාධ්‍ය යළි අරඹන්න
actions-reposition = පිහිටීම වෙනස් කරන්න
actions-save = සුරකින්න
actions-search = සෙවුම
actions-select = තෝරන්න
actions-shortcut-key = කෙටි යතුරුපුවරු යෙදුම
actions-suspend-card = කාඩ්පත අත්හිටුවන්න
actions-set-due-date = පාඩම් කළයුතු දිනය තෝරන්න
actions-forget = අමතක කරන්න
actions-answer-card = කාඩ්පතට පිළිතුරු සපයන්න
