actions-add = Cuir Leis
actions-all-selected = Gach rud roghnaithe
actions-any-selected = A bhfuil roghnaithe
actions-blue-flag = Bratach ghorm
actions-cancel = Cealaigh
actions-choose = Roghnaigh
actions-close = Dún
actions-copy = Cóipeáil
actions-custom-study = Staidéar ar Leith
actions-decks = Pacaí
actions-delete = Scrios
actions-export = Easpórtáil
actions-filter = Scagaire
actions-green-flag = Bratach ghlas uaine
actions-help = Cabhair
actions-import = Iompórtáil
actions-manage = Bainistigh...
actions-name = Ainm:
actions-new = Nua
actions-new-name = Ainm nua:
actions-options = Roghanna
actions-options-for = Roghanna do { $val }
actions-orange-flag = Bratach bhuí
actions-preview = Réamhamharc
actions-rebuild = Tóg arís
actions-red-flag = Bratach dhearg
actions-rename = Athainmnigh
actions-rename-deck = Athainmnigh Paca
actions-rename-tag = Athainmnigh Clib
actions-remove-tag = Bain Clib
actions-replay-audio = Cas Fuaim Arís
actions-reposition = Bog
actions-save = Sábháil
actions-search = Cuardaigh
actions-select = Roghnaigh
actions-shortcut-key = Cnaipe aicearra: { $val }
actions-suspend-card = Cuir Cárta ar Fionraí
actions-set-due-date = Socraigh Dáta Staidéir
actions-forget = Lig i nDearmad
actions-answer-card = Freagair Cárta
actions-unbury-unsuspend = Tarraing Amach/Bain as Fiontraí
actions-add-deck = Cuir Paca leis
actions-add-note = Cuir Nóta leis
actions-update-tag = Nuashonraigh Clib
actions-update-note = Nuashonraigh Nóta
actions-update-card = Nuashonraigh Cárta
actions-update-deck = Nuashonraigh Paca
actions-forget-card = Lig Cárta i nDearmad
actions-set-flag = Socraigh Bratach
actions-build-filtered-deck = Tiomsaigh Paca
actions-expand-collapse = Fairsingigh/Leacaigh
actions-add-notetype = Cuir Cineál Nótaí Leis
actions-remove-notetype = Bain Cineál Nótaí
actions-update-notetype = Nuashonraigh Cineál Nótaí
