card-stats-added = Curtha leis
card-stats-first-review = Céad Athbhreithniú
card-stats-latest-review = Athbhreithniú is déanaí
card-stats-interval = Eatramh
card-stats-ease = Éascaíocht
card-stats-review-count = Athbhreithnithe
card-stats-lapse-count = Clistí
card-stats-average-time = Meánfhad
card-stats-total-time = Fad iomlán
card-stats-new-card-position = Áit
card-stats-card-template = Cineál Cárta
card-stats-note-type = Cineál Nóta
card-stats-deck-name = Paca
card-stats-note-id = Aitheantas Nóta
card-stats-card-id = Aitheantas Cárta
card-stats-review-log-rating = Rátáil
card-stats-review-log-type = Cineál
card-stats-review-log-date = Dáta
card-stats-review-log-time-taken = Am
card-stats-review-log-type-learn = Foghlaim
card-stats-review-log-type-review = Athbhreithniú
card-stats-review-log-type-relearn = Athfhoghlaim
card-stats-review-log-type-filtered = Scagtha
