custom-study-must-rename-deck = Caithfear ainm nua a thabhairt don phaca 'Staidéar ar Leith' atá ann faoi láthair.
custom-study-all-cards-in-random-order-dont = Cártaí ar fad, in ord randamach (ná déan athsceidealú)
custom-study-all-review-cards-in-random-order = Cártaí athbhreithnithe ar fad, in ord randamach
custom-study-cards = cártaí
custom-study-cards-from-the-deck = cártaí ón bpaca
custom-study-choose-tags = Roghnaigh Clibeanna
custom-study-custom-study-session = Seisiún Staidéir ar Leith
custom-study-due-cards-only = Cártaí dlite amháin
custom-study-increase-todays-new-card-limit = Ardaigh uasmhéid na gcártaí nua d'inniu
custom-study-increase-todays-new-card-limit-by = Ardaigh uasmhéid na gcártaí nua d'inniu de
custom-study-increase-todays-review-card-limit = Ardaigh uasmhéid athbhreithniithe cártaí d'inniu
custom-study-increase-todays-review-limit-by = Ardaigh uasmhéid athbhreithnithe cártaí d'inniu de
custom-study-new-cards-in-deck-over-today = Cártaí nua sa phaca thar srian an lae inniu: { $val }
custom-study-new-cards-only = Cártaí nua amháin
custom-study-no-cards-matched-the-criteria-you = Níl aon cártaí a thagann leis na critéir a luaigh tú.
custom-study-ok = OK
custom-study-preview-new-cards = Réamhamharc ar chártaí nua
custom-study-preview-new-cards-added-in-the = Réamhamharc ar chártaí nua le linn
custom-study-require-one-or-more-of-these = Teastaigh ceann/cinn de na clibeanna seo:
custom-study-review-ahead = Athbhreithnigh ar aghaidh
custom-study-review-ahead-by = Athbhreithnigh ar aghaidh le
custom-study-review-cards-forgotten-in-last = Athbhreithnigh cártaí dearmadta le linn
custom-study-review-forgotten-cards = Athbhreithnigh ar chártaí dearmadta
custom-study-reviews-due-in-deck-over-today = Cártaí dlite sa phaca thar srian an lae inniú: { $val }
custom-study-select = Roghnaigh
custom-study-select-tags-to-exclude = Roghnaí clibeanna le fágáil as:
custom-study-selective-study = Staidéar Roghnaitheach
custom-study-study-by-card-state-or-tag = Déan staidear de réir staid chárta nó de réir clibe
