editing-add-media = Cuir Meáin Leis
editing-an-error-occurred-while-opening = Bhí fadhb nuair a osclaíodh { $val }
editing-attach-picturesaudiovideo-f3 = Cuir pictiúir/fuaim/fís leis (F3)
editing-bold-text-ctrlandb = Téacs trom (Ctrl+B)
editing-cards = Cártaí
editing-change-colour-f8 = Athraigh dath (F8)
editing-cloze-deletion-ctrlandshiftandc = Sliocht Iomlánaithe (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Ní féidir taifead fuaime a dhéanamh. An bhfuil 'lame' suite?
editing-customize-card-templates-ctrlandl = Saincheap Teimpléid Chártaí (Ctrl+L)
editing-customize-fields = Saincheap Réimsí
editing-cut = Gearr
editing-edit-current = Cuir ábhar reatha in Eagar
editing-edit-html = Cuir HTML in eagar
editing-fields = Réimsí
editing-html-editor = Eagarthóir HTML
editing-italic-text-ctrlandi = Cló iodálach (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Léim go Chlibeanna le Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Cothromóid LaTeX
editing-latex-math-env = Timpeallacht mata LaTeX.
editing-mathjax-block = MathJax bloc
editing-mathjax-chemistry = MathJax Ceimic
editing-mathjax-inline = MathJax inlíne
editing-media = Meáin
editing-paste = Greamaigh
editing-record-audio-f5 = Déan taifead ar fhuaim (F5)
editing-remove-formatting-ctrlandr = Bain foirmáidiú (Ctrl+R)
editing-set-foreground-colour-f7 = Socraigh daith an tosaigh (F7)
editing-show-duplicates = Taispeáin Dúblaigh
editing-subscript-ctrland = Foscript (Ctrl+=)
editing-superscript-ctrlandand = Forscript (Ctrl++)
editing-tags = Clibeanna
editing-to-make-a-cloze-deletion-on = Chun sliocht iomlánú a dhéanamh ar nóta, caithfear cineál an nóta a athrú i dtosach, trí 'Nótaí>Athraigh Cineál Nóta'
editing-underline-text-ctrlandu = Folínigh (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Rabhadh, Caithfear 'Iomlánú' a roghnadh mar chineál thuas chun go bhfeidhmeoidh sleachta iomlánaithe.
