editing-add-media = Cuir Meáin Leis
editing-align-left = Ailínigh ar chlé
editing-align-right = Ailínigh ar dheis
editing-an-error-occurred-while-opening = Bhain earráid agus { $val } á oscailt
editing-attach-picturesaudiovideo = Cuir pictiúir/fuaim/fís leis
editing-bold-text = Téacs trom
editing-cards = Cártaí
editing-center = Láraigh
editing-change-color = Malartaigh dath
editing-cloze-deletion = Sliocht Iomlánaithe
editing-couldnt-record-audio-have-you-installed = Níorbh fhéidir taifead fuaime a dhéanamh. An bhfuil 'lame' suite?
editing-customize-card-templates = Saincheap Teimpléid Chártaí
editing-customize-fields = Saincheap Réimsí
editing-cut = Gearr
editing-edit-current = Cuir ábhar reatha in Eagar
editing-edit-html = Cuir HTML in eagar
editing-fields = Réimsí
editing-html-editor = Eagarthóir HTML
editing-indent = Méadaigh an eang
editing-italic-text = Cló iodálach
editing-jump-to-tags-with-ctrlandshiftandt = Léim go Clibeanna le Ctrl+Shift+T
editing-justify = Comhfhadaigh
editing-latex = LaTeX
editing-latex-equation = Cothromóid LaTeX
editing-latex-math-env = Timpeallacht mata LaTeX.
editing-mathjax-block = MathJax bloc
editing-mathjax-chemistry = MathJax Ceimic
editing-mathjax-inline = MathJax inlíne
editing-media = Meáin
editing-ordered-list = Liosta in ord
editing-outdent = Laghdaigh an eang
editing-paste = Greamaigh
editing-record-audio = Déan taifead ar fhuaim
editing-remove-formatting = Bain foirmáidiú
editing-set-foreground-color = Socraigh dath an tosaigh
editing-show-duplicates = Taispeáin Dúblaigh
editing-subscript = Foscript
editing-superscript = Forscript
editing-tags = Clibeanna
editing-to-make-a-cloze-deletion-on = Chun sliocht iomlánú a dhéanamh ar nóta, caithfear cineál an nóta a athrú i dtosach, trí 'Nótaí>Athraigh Cineál Nóta'
editing-underline-text = Folínigh
editing-unordered-list = Liosta gan ord
editing-warning-cloze-deletions-will-not-work = Rabhadh, ní bheidh aon mhaith sna sleachta iomlánaithe go dtí go mbeidh an cineál 'Iomlánú' roghnaithe thuas.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Téacs trom (Ctrl+B)
editing-italic-text-ctrlandi = Cló iodálach (Ctrl+I)
editing-underline-text-ctrlandu = Folínigh (Ctrl+U)
editing-subscript-ctrland = Foscript (Ctrl+=)
editing-superscript-ctrlandand = Forscript (Ctrl++)
editing-remove-formatting-ctrlandr = Bain foirmáidiú (Ctrl+R)
editing-record-audio-f5 = Déan taifead ar fhuaim (F5)
editing-attach-picturesaudiovideo-f3 = Cuir pictiúir/fuaim/fís leis (F3)
editing-cloze-deletion-ctrlandshiftandc = Sliocht Iomlánaithe (Ctrl+Shift+C)
editing-change-colour-f8 = Athraigh dath (F8)
editing-set-foreground-colour-f7 = Socraigh dath an tosaigh (F7)
editing-customize-card-templates-ctrlandl = Saincheap Teimpléid Chártaí (Ctrl+L)
