exporting-all-decks = Gach Paca
exporting-anki-20-deck = Paca Anki 2.0
exporting-anki-collection-package = Pacáiste Cnuasaigh Anki
exporting-anki-deck-package = Pacáiste Paca Anki
exporting-cards-in-plain-text = Cártaí i ngnáth-théacs
exporting-collection = cnuasach
exporting-collection-exported = Cnuasacht easpórtáilte.
exporting-couldnt-save-file = Ní féidir comhad a shábháil: { $val }
exporting-export = Easpórtáil...
exporting-export-format = <b>Formáid easpórtála</b>:
exporting-include = <b>San Áireamh</b>:
exporting-include-html-and-media-references = Cuir HTML agus tagairt meán san áireamh
exporting-include-media = Meáin san áireamh
exporting-include-scheduling-information = Sonraí sceidealaithe san áireamh
exporting-include-tags = Clibeanna san áireamh
exporting-notes-in-plain-text = Nótaí gnáth-théacs
exporting-selected-notes = Nótaí Roghnaithe
