fields-add-field = Cuir Réimse Leis
fields-delete-field-from = Scrios réimse ó { $val }?
fields-editing-font = Clófhoireann Eagarthóireachta
fields-field = Réimse:
fields-field-name = Ainm réimse:
fields-fields-for = Réimsí do { $val }
fields-font = Clófoireann:
fields-new-position-1 = Áit nua (1...{ $val }):
fields-notes-require-at-least-one-field = Teastaíonn réimse amháin (ar a laghad) i nótaí.
fields-remember-last-input-when-adding = Coinnigh ábhar le linn ionchuir
fields-reverse-text-direction-rtl = Cas an téacs droim ar ais
fields-size = Méid:
fields-sort-by-this-field-in-the = Bíodh an réimse seo mar bhunús sórtála sa bhrabhsálaí
fields-that-field-name-is-already-used = Tá an t-ainm sin ar réimse eile cheana féin.
fields-name-first-letter-not-valid = Níor cheart go mbeadh #, ^ nó / ag tús ainm an réimse.
