preferences-anki-21-scheduler-beta = Sceidealóir Anki 2.1 (beta)
preferences-automatically-sync-on-profile-openclose = Déan sioncronú go huathoibríoch nuair a dhúntar/osclaítear próifíl
preferences-backups = Cóipeanna Cúltaca
preferences-backups2 = cóipeanna cúltaca
preferences-backupsanki-will-create-a-backup-of = <b>Cúltacú</b><br>Déanfaidh Anki cúltacú de do chnuasach gach uair a dhúnfar é nó a dhéantar sioncronaigh air.
preferences-basic = Bunúsach
preferences-change-deck-depending-on-note-type = Athraigh paca de réir an chineál nóta
preferences-changes-will-take-effect-when-you = Tiocfaidh na athruithe i bhfeidhm nuair a atosófar Anki.
preferences-hardware-acceleration-faster-may-cause-display = Luathaithe crua-earraí (níos tapaidh, ach seans go mbeidh deacrachtaí léirithe ann)
preferences-hours-past-midnight = uaire tar éis mheán oíche
preferences-interface-language = Teanga comhéadain:
preferences-interrupt-current-audio-when-answering = Bris isteach ar fhuaim chun freagra a thabhairt
preferences-keep = Coinnigh
preferences-learn-ahead-limit = Srian 'Foghlaim roimh am'
preferences-mins = nóim
preferences-network = Líonra
preferences-next-day-starts-at = Tosaíonn an chéad lá eile ag
preferences-night-mode = Modh oíche
preferences-note-media-is-not-backed-up = Nóta: Níl cóip chúltaca déanta de do mheáin. Ar son na sábháilteachta, déan cúltacú rialta den fhillteán Anki.
preferences-on-next-sync-force-changes-in = An chéad sionc eile: athruithe i dtreo áirithe amháin
preferences-paste-clipboard-images-as-png = Greamaigh íomhánna gearrthaisce mar PNG
preferences-paste-without-shift-key-strips-formatting = Baintear an formáidiú nuair nach ngreamaítear agus SHIFT á bhrú
preferences-periodically-sync-media = Sionc meáin go tréimhsiúil
preferences-please-restart-anki-to-complete-language = Atosaigh Anki chun athrú teanga a chríochnú.
preferences-preferences = Roghanna
preferences-scheduling = Sceidealú
preferences-show-learning-cards-with-larger-steps = Taispeáin cártaí atá á bhfoghlaim fós ach céimeanna níos mó i gceist leo i dtosach
preferences-show-next-review-time-above-answer = Taispeáin am don chéad athbhreithniú eile thuas ar na cnaipí freagartha
preferences-show-play-buttons-on-cards-with = Taispeáin cnaipe 'seinn' ar chártaí le fuaim
preferences-show-remaining-card-count-during-review = Taispeáin líon na gcártaí atá fanta le linn athbhreithnithe
preferences-some-settings-will-take-effect-after = Tiocfaidh socruithe áirithe i bhfeidhm nuair a atosófar Anki.
preferences-synchronisation = <b>Sioncronú</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sioncronú</b><br> Níl sioncronú ar fáil faoi láthair; cliceáil an cnaipe 'Sioncronú' sa phríomhfhuinneog chun é a chur ar fáil.
preferences-synchronize-audio-and-images-too = Sioncronaigh fuaim agus iomhánna freisin
preferences-this-will-reset-any-cards-in = Athshocróidh sé seo cártaí atá á bhfoghlaim, glanfaidh sé pacaí scagtha, agus athróidh sé leagan an sceidealóra. Lean ar aghaidh?
preferences-timebox-time-limit = Teorainn ama don tréimhse shocraithe
preferences-user-interface-size = Méid an chomhéadain
preferences-when-adding-default-to-current-deck = Cuir cártaí nua leis an bpaca atá oscailte mar réamhshocrú
preferences-you-can-restore-backups-via-fileswitch = Chun cóipeanna cúltaca a thabhairt ar ais: Comhad>Athraigh Próifíl
