studying-again = Arís
studying-all-buried-cards = Gach Cárta Atá i bhFolach
studying-audio-5s = Fuaim -5s
studying-audio-and5s = Fuaim +5s
studying-buried-siblings = Siblíní i bhFolach
studying-bury = Cuir i bhFolach
studying-bury-card = Cuir Cárta i bhFolach
studying-bury-note = Cuir Nóta i bhFolach
studying-card-buried = Cárta i bhfolach.
studying-card-suspended = Cárta ar fionraí.
studying-card-was-a-leech = Súmaire arbh é an chárta.
studying-cards-will-be-automatically-returned-to = Cuirfear gach cárta ar ais sa phaca céanna as ar tháinig sé tar éis duit athbrheithniú a dhéanamh air.
studying-continue = Lean ar aghaidh
studying-delete-note = Scrios Nóta
studying-deleting-this-deck-from-the-deck = Má scriostar an paca seo ón liosta pacaí, cuirfear gach cárta ann (faoi seach) ar ais sa phaca a bhí sé ann ón gcéad lá.
studying-easy = Éasca
studying-edit = Cuir in eagar
studying-empty = Folamh
studying-finish = Críochnaigh
studying-flag-card = Cur Bratach le Cárta
studying-good = Maith
studying-hard = Deacair
studying-it-has-been-suspended = Tá sé ar fionraí.
studying-manually-buried-cards = Cártaí curtha i bhfolach de láimh
studying-mark-note = Marcáil Nóta
studying-more = Tuilleadh
studying-no-cards-are-due-yet = Níl cárta ar bith dlite fós.
studying-note-buried = Nóta i bhfolach.
studying-note-suspended = Nóta ar fionraí.
studying-pause-audio = Cuir Fuaim ar Sos
studying-please-run-toolsempty-cards = Úsáid Úirlisí->Cártaí Folmha
studying-record-own-voice = Taifead do ghuth
studying-replay-own-voice = Cas Do Ghugh Féin Arís
studying-show-answer = Taispeáin Freagra
studying-space = Spás
studying-study-now = Déan staidéar anois
studying-suspend = Cuir ar fionraí
studying-suspend-note = Cuir Nóta ar Fionraí
studying-this-is-a-special-deck-for = Paca ar leith é seo le haghaidh staidéir taobh amuigh den ghnáthsceideal.
studying-to-review = Le athbhreithniú
studying-type-answer-unknown-field = Réimse anaithnithid { $val }
studying-unbury = Tarraing amach (ábhar atá i bhfolach)
studying-what-would-you-like-to-unbury = Céard ar mhaith leat tarraingt amach?
studying-you-havent-recorded-your-voice-yet = Níor thaifead tú do ghuth fós.
