actions-add = Voeg by
actions-cancel = Kanselleer
actions-choose = Kies
actions-close = Sluit
actions-copy = Kopieër
actions-custom-study = Pasmaker Studie
actions-decks = Kaartpak
actions-delete = Skrap
actions-export = Uitvoer
actions-help = Hulp
actions-import = Invoer
actions-name = Naam:
actions-new = Nuut
actions-new-name = Nuwe naam:
actions-options = Voorkeure
actions-options-for = Opsies vir { $val }
actions-preview = Voorskou
actions-rebuild = Herbou
actions-rename = Hernoem
actions-rename-deck = Hernoem Kaartpak
actions-replay-audio = Herspeel Klank
actions-reposition = Herposisioneer
actions-search = Soek
actions-shortcut-key = Kortpad sleutel: { $val }
actions-suspend-card = Skort Kaart Op
