decks-add-new-deck-ctrlandn = Skep 'n Nuwe Pak (Ctrl + N)
decks-are-you-sure-you-wish-to = Is jy seker jy wil { $val } verwyder?
decks-build = Bou
decks-cards-selected-by = kaarte geselekteer op
decks-create-deck = Skep Kaartpak
decks-deck = Kaartpak
decks-decreasing-intervals = Verminderende tussenpouses
decks-delete-deck = Skrap Kaartpak
decks-get-shared = Kry Gedeelde
decks-import-file = Lêer Invoer
decks-increasing-intervals = Toenemende tussentye
decks-latest-added-first = Laaste bygevoeg 1
decks-limit-to = Beperk tot
decks-minutes = minute
decks-most-lapses = Meeste vergissings
decks-name-for-deck = Naam vir kaartpak:
decks-new-deck-name = Nuwe kaartpak naam:
decks-no-deck = [geen kaartpak]
decks-oldest-seen-first = Oudste eerste gesien
decks-order-added = Volgorde bygevoeg
decks-order-due = Volgorde verwag
decks-please-select-something = Kies asseblief iets.
decks-random = Lukraak
decks-relative-overdueness = Relatiewe agterstalligheid
decks-reschedule-cards-based-on-my-answers = Herskeduleer kaarte wat gebaseer is op my antwoorde in die kaartpak
decks-study = Studeer
decks-study-deck = Studeer kaartpak
decks-the-provided-search-did-not-match = Die soektog het geen resultate opgelewer nie. Wil u dit dalk hersien?
