exporting-all-decks = Alle Pakke
exporting-anki-20-deck = Anki 2,0 Pak
exporting-anki-deck-package = Anki kaartpak Pakket
exporting-cards-in-plain-text = Kaarte in Gewone Teks
exporting-collection = versameling
exporting-couldnt-save-file = Kon nie die lêer, { $val } stoor nie
exporting-export = Uitvoer ...
exporting-export-format = <b>Uitvoer formaat</b>:
exporting-include = <b>Insluitend</ b>:
exporting-include-media = Sluit media in
exporting-include-scheduling-information = Sluit skedulering inligting in
exporting-include-tags = Sluit etikette in
exporting-notes-in-plain-text = Notas in Gewone Teks
