actions-add = Aldoni
actions-all-selected = Ĉio elektita
actions-any-selected = Io ajn elektita
actions-cancel = Nuligi
actions-choose = Elekti
actions-close = Fermi
actions-discard = Forĵeti
actions-copy = Kopii
actions-create-copy = Krei kopion
actions-custom-study = Propra lernado
actions-decks = Kartaroj
actions-decrement-value = Malpliigi valoron
actions-delete = Forigi
actions-export = Elporti
actions-filter = Filtrilo
actions-help = Helpo
actions-increment-value = Pliigi valoron
actions-import = Enporti
actions-manage = Administri...
actions-name = Nomo:
actions-new = Nova
actions-new-name = Nova nomo:
actions-options = Opcioj
actions-options-for = Opcioj por { $val }
actions-preview = Antaŭmontro
actions-rebuild = Rekunmeti
actions-rename = Alinomi
actions-rename-deck = Alinomi kartaron
actions-rename-tag = Alinomi etikedon
actions-rename-with-parents = Alinomi kun gepatroj
actions-remove-tag = Forigi etikedon
actions-replay-audio = Reludi sonon
actions-reposition = Repozicii
actions-save = Konservi
actions-search = Serĉi
actions-select = Elekti
actions-shortcut-key = Fulmoklavo: { $val }
actions-suspend-card = Daŭre kaŝi karton
actions-set-due-date = Agordi limdaton
actions-answer-card = Respondi al karto
actions-unbury-unsuspend = Malkaŝi
actions-add-deck = Aldoni kartaron
actions-add-note = Aldoni noton
actions-update-tag = Ĝisdatigi etikedon
actions-update-note = Ĝisdatigi noton
actions-update-card = Ĝisdatigi karton
actions-update-deck = Ĝisdatigi kartaron
actions-forget-card = Forgesi karton
actions-build-filtered-deck = Kunmeti kartaron

## Flags

actions-flag-red = Ruĝa
actions-flag-green = Verda
