actions-add = Aldoni
actions-all-selected = Ĉio elektita
actions-any-selected = Io ajn elektita
actions-cancel = Nuligi
actions-choose = Elekti
actions-close = Fermi
actions-discard = Forĵeti
actions-copy = Kopii
actions-create-copy = Krei kopion
actions-custom-study = Propra lernado
actions-decks = Kartaroj
actions-decrement-value = Malpliigi valoron
actions-delete = Forigi
actions-export = Elporti
actions-empty-cards = Malplenaj kartoj
actions-filter = Filtrilo
actions-help = Helpo
actions-increment-value = Pliigi valoron
actions-import = Enporti
actions-manage = Administri...
actions-name = Nomo:
actions-new = Nova
actions-new-name = Nova nomo:
actions-options = Opcioj
actions-options-for = Opcioj por { $val }
actions-preview = Antaŭmontro
actions-rebuild = Rekunmeti
actions-rename = Alinomi
actions-rename-deck = Alinomi kartaron
actions-rename-tag = Alinomi etikedon
actions-rename-with-parents = Alinomi kun gepatroj
actions-remove-tag = Forigi etikedon
actions-replay-audio = Reludi sonon
actions-reposition = Repozicii
actions-save = Konservi
actions-search = Serĉi
actions-select = Elekti
actions-shortcut-key = Fulmoklavo: { $val }
actions-suspend-card = Paŭzigi karton
actions-set-due-date = Agordi limdaton
actions-answer-card = Respondi al karto
actions-unbury-unsuspend = Malkaŝi/Malpaŭzigi
actions-add-deck = Aldoni kartaron
actions-add-note = Aldoni noton
actions-update-tag = Ĝisdatigi etikedon
actions-update-note = Ĝisdatigi noton
actions-update-card = Ĝisdatigi karton
actions-update-deck = Ĝisdatigi kartaron
actions-forget-card = Forgesi karton
actions-build-filtered-deck = Kunmeti kartaron
actions-add-notetype = Aldoni nototipon
actions-remove-notetype = Forigi nototipon
actions-update-notetype = Ĝisdatigi nototipon
actions-update-config = Ĝisdatigi agordon
actions-card-info = Kartoinformo
actions-previous-card-info = Informo pri antaŭa karto
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-fullscreen-unsupported = Plenekrana reĝimo ne estas subtenata de via vidkarta pelilo. Vi povas elekti alian pelilon en la preferoj.

## Flags

actions-flag-number = Indikilo { $number }
actions-flag-red = Ruĝa
actions-flag-orange = oranĝa
actions-flag-green = Verda
actions-flag-blue = blua
actions-flag-pink = Roza
actions-flag-turquoise = turkisa
actions-flag-purple = viola
actions-set-flag = Meti indikilon
actions-nothing-to-undo = Nenio por malfari
actions-nothing-to-redo = Nenio por refari
actions-auto-advance = Aŭtomata malkaŝo
actions-auto-advance-activated = Aŭtomata malkaso estas aktiva
actions-auto-advance-deactivated = Aŭtomata malkaso estas malaktiva
