decks-add-new-deck-ctrlandn = Aldoni novan kartaron (Ctrl+N)
decks-build = Kunmeti
decks-cards-selected-by = kartoj elektitaj laŭ
decks-create-deck = Krei kartaron
decks-custom-steps-in-minutes = Propraj paŝoj (en minutoj)
decks-deck = Kartaro
decks-decreasing-intervals = malkreskaj intertempoj
decks-delete-deck = Forigi kartaron
decks-enable-second-filter = Aktivigi duan filtrilon
decks-filter = Filtrilo:
decks-filter-2 = Filtrilo 2
decks-get-shared = Elŝuti kartaron
decks-import-file = Enporti dosieron
decks-increasing-intervals = kreskaj intertempoj
decks-latest-added-first = plej laste aldonitaj unuafoje
decks-limit-to = Limigi ĝis
decks-minutes = minutoj
decks-most-lapses = Plej multaj misrespondoj
decks-new-deck-name = Nomo de la nova kartaro:
decks-no-deck = [neniu kartaro]
decks-oldest-seen-first = plej frue viditaj unuafoje
decks-order-added = ordo de aldono
decks-order-due = ordo de endeco
decks-please-select-something = Bonvolu elekti ion.
decks-random = hazarde
decks-relative-overdueness = Relativa malfruo
decks-repeat-failed-cards-after = Ripeti malsukcese lernitajn kartojn post
decks-reschedule-cards-based-on-my-answers = Replani kartojn laŭ miaj respondoj donitaj en ĉi tiu kartaro
decks-study = Lernado
decks-study-deck = Lernkartaro
decks-learn-header = Lerni
# The count of cards waiting to be reviewed
decks-review-header = Lernenda
