editing-actual-size = Baskuligi veran grandon
editing-add-media = Aldoni aŭdvidaĵon
editing-align-left = Ĝisrandigi maldekstren
editing-align-right = Ĝisrandigi dekstren
editing-an-error-occurred-while-opening = Okazis eraro dum malfermo de { $val }
editing-attach-picturesaudiovideo = Aldoni bildon/sonon/filmeton
editing-bold-text = Grasa teksto
editing-cards = Kartoj
editing-center = Centrigi
editing-change-color = Ŝanĝi koloron
editing-cloze-deletion = Truo en teksto (nova karto)
editing-cloze-deletion-repeat = Truo en teksto (la sama karto)
editing-copy-image = Kopii bildon
editing-couldnt-record-audio-have-you-installed = Ne povis registri sonon. Ĉu vi instalis la programon “lame”?
editing-customize-card-templates = Alĝustigi kartoŝablonojn
editing-customize-fields = Alĝustigi kampojn
editing-cut = Eltondi
editing-double-click-image = duoble alklaku bildon
editing-double-click-to-expand = duoble alklaku por etendi
editing-double-click-to-collapse = duoble alklaku por maletendi
editing-edit-current = Redakti nunan
editing-edit-html = Redakti HTML
editing-fields = Kampoj
editing-jump-to-tags-with-ctrlandshiftandt = Salti al etikedoj per Stir’+Majusklig’+T
editing-latex = LaTeX
editing-latex-equation = LaTeX-formulo
editing-latex-math-env = LaTeX matematika ĉirkaŭaĵo
editing-mathjax-block = MathJax bloko
editing-mathjax-chemistry = MathJax ĥemio
editing-mathjax-inline = Enlinia MathJax-Elemento
editing-media = Aŭdovidaĵo
editing-paste = Alglui
editing-show-duplicates = Montri duoblaĵojn
editing-tags = Etikedoj
editing-tags-add = Aldoni etikedon
editing-to-make-a-cloze-deletion-on = Por krei trutekston ĉe ekzistanta noto, unuafoje vi devas ŝanĝi ĝin al truteksto-tipo, ĉe Redakti > Ŝanĝi nototipon.
editing-warning-cloze-deletions-will-not-work = Averto! Trutekstaj malplenoj ne funkcios, ĝis vi supre elektos la nototipon Truteksto.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-redaktilo
