editing-actual-size = Baskuligi veran grandon
editing-add-media = Aldoni aŭdvidaĵon
editing-align-left = Ĝisrandigi maldekstren
editing-align-right = Ĝisrandigi dekstren
editing-an-error-occurred-while-opening = Okazis eraro dum malfermo de { $val }
editing-attach-picturesaudiovideo = Aldoni bildon/sonon/filmeton
editing-bold-text = Grasa teksto
editing-cards = Kartoj
editing-center = Centrigi
editing-change-color = Ŝanĝi koloron
editing-cloze-deletion = Truo en teksto (nova karto)
editing-cloze-deletion-repeat = Truo en teksto (la sama karto)
editing-copy-image = Kopii bildon
editing-couldnt-record-audio-have-you-installed = Ne povis registri sonon. Ĉu vi instalis la programon “lame”?
editing-customize-card-templates = Alĝustigi kartoŝablonojn
editing-customize-fields = Alĝustigi kampojn
editing-cut = Eltondi
editing-double-click-image = duoble alklaku bildon
editing-double-click-to-expand = duoble alklaku por etendi
editing-double-click-to-collapse = duoble alklaku por maletendi
editing-edit-current = Redakti nunan
editing-edit-html = Redakti HTML
editing-fields = Kampoj
editing-float-left = Alkroĉi maldekstre
editing-float-right = Alkroĉi dekstre
editing-float-none = Ne alkroĉi
editing-indent = Pliigi krommarĝenon
editing-italic-text = Kursiva teksto
editing-jump-to-tags-with-ctrlandshiftandt = Salti al etikedoj per Stir’+Majusklig’+T
editing-justify = Ĝisrandigi ambaŭflanken
editing-latex = LaTeX
editing-latex-equation = Formulo LaTeX
editing-latex-math-env = Matematika ĉirkaŭaĵo LaTeX
editing-mathjax-block = Bloko MathJax
editing-mathjax-chemistry = Ĥemia formulo MathJax
editing-mathjax-inline = Enlinia MathJax
editing-mathjax-placeholder = Premu la klavon { $accept } por akcepti aŭ { $newline } por enmeti linion.
editing-media = Aŭdvidaĵo
editing-open-image = Malfermi bildon
editing-show-in-folder = Montri en dosierujo
editing-ordered-list = Ordigita listo
editing-outdent = Etigi krommarĝenon
editing-paste = Alglui
editing-record-audio = Registri sonon
editing-remove-formatting = Forviŝi tekstaranĝon
editing-restore-original-size = Restarigi originalan grandon
editing-select-remove-formatting = Selekte forviŝi tekstaranĝon
editing-show-duplicates = Montri duoblaĵojn
editing-subscript = Malalta skribo
editing-superscript = Alta skribo
editing-tags = Etikedoj
editing-tags-add = Aldoni etikedon
editing-tags-copy = Kopii etikedojn
editing-tags-remove = Forigi etikedojn
editing-tags-select-all = Elekti ĉiujn etikedojn
editing-text-color = Koloro de teksto
editing-text-highlight-color = Koloro de sign-emfazo
editing-to-make-a-cloze-deletion-on = Por krei truon en teksto de la ekzista noto, unue ŝanĝu ĝian nototipon al “Truteksto” per la menuo Noto → Ŝanĝi nototipon.
editing-toggle-html-editor = Baskuligi HTML-redaktilon
editing-toggle-visual-editor = Baskuligi pervidan redaktilon
editing-warning-cloze-deletions-will-not-work = Averto! Trutekstaj malplenoj ne funkcios, ĝis vi supre elektos la nototipon Truteksto.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-redaktilo
