fields-add-field = Aldoni kampon
fields-delete-field-from = Ĉu forigi la kampon el { $val }?
fields-editing-font = Redakta tiparo
fields-field = Kampo:
fields-field-name = Nomo de kampo:
fields-description = Priskribo
fields-fields-for = Kampoj por { $val }
fields-font = Tiparo:
fields-new-position-1 = Nova pozicio (1...{ $val }):
fields-notes-require-at-least-one-field = Notoj bezonas almenaŭ unu kampon.
fields-reverse-text-direction-rtl = Tekstodirekto dekstre-maldekstren (RTL)
fields-size = Grando:
fields-sort-by-this-field-in-the = Ordigi per ĉi tiu kampo en la foliumilo
fields-that-field-name-is-already-used = Tiu kamponomo jam estas uzata.
