fields-add-field = Aldoni kampon
fields-delete-field-from = Ĉu forigi la kampon el { $val }?
fields-editing-font = Redakta tiparo
fields-field = Kampo:
fields-field-name = Nomo de kampo:
fields-description = Priskribo
fields-description-placeholder = Teksto montrata ene la malplena kampo
fields-fields-for = Kampoj por { $val }
fields-font = Tiparo:
fields-new-position-1 = Nova pozicio (1 … { $val }):
fields-notes-require-at-least-one-field = Notoj bezonas almenaŭ unu kampon.
fields-reverse-text-direction-rtl = Tekstodirekto dekstre-maldekstren (RTL)
fields-collapse-by-default = Implicite maletendi
fields-html-by-default = Implicite uzi HTML-redaktilon
fields-size = Grando:
fields-sort-by-this-field-in-the = Ordigi per tiu ĉi kampo en la foliumilo
fields-that-field-name-is-already-used = Tiu ĉi nomo de kampo jam estas uzata.
