notetypes-front-field = Antaŭo
notetypes-back-field = Reen
notetypes-add-reverse-field = Aldoni malan direkton
notetypes-text-field = Teksto
notetypes-basic-name = Baza
notetypes-basic-reversed-name = Baza (en ambaŭ direktoj)
notetypes-basic-optional-reversed-name = Baza (en unu aŭ ambaŭ direktoj)
notetypes-cloze-name = Truteksto
notetypes-basic-type-answer-name = Baza (entajpi la respondon)
notetypes-card-2-name = 2-a karto
notetypes-card-1-name = 1-a karto
