preferences-automatically-sync-on-profile-openclose = Aŭtomate samtempigi je fermo aŭ malfermo de profilo
preferences-backups = Sekurkopioj
preferences-change-deck-depending-on-note-type = ŝanĝi kartaron laŭ nototipo
preferences-changes-will-take-effect-when-you = Ŝanĝoj efikos post relanĉo de Anki.
preferences-hours-past-midnight = horoj post noktomezo
preferences-language = Lingvo
preferences-interrupt-current-audio-when-answering = Ĉesigi ludi sonon dum respondi
preferences-learn-ahead-limit = Antaŭlerna limigo
preferences-mins = minutoj
preferences-network = Samtempigo
preferences-next-day-starts-at = Sekva tago komenciĝas
preferences-media-is-not-backed-up = Sekurkopio ne enhavas aŭdvidaĵojn. Por esti sekura, regule sekurkopiu vian dosierujo Anki.
preferences-on-next-sync-force-changes-in = Dum la venonta samtempigo, devigi ŝanĝojn en unu direkto
preferences-paste-clipboard-images-as-png = Alglui tondujajn bildojn kiel PNG
preferences-paste-without-shift-key-strips-formatting = Alglui sen premi la majuskligan klavon por senigi tekstaranĝon
preferences-generate-latex-images-automatically = Generi grafikojn el LaTeX (sekureca vundeblo)
preferences-latex-generation-disabled = Generi grafikojn el LaTeX estas malaktiva en la preferoj.
preferences-periodically-sync-media = Periode samtempigi aŭdvidaĵojn
preferences-please-restart-anki-to-complete-language = Relanĉu Anki pro finfari la ŝanĝon de lingvo.
preferences-preferences = Preferoj
preferences-scheduling = Planado
preferences-show-learning-cards-with-larger-steps = Montri lernkartojn kun pli grandaj paŝoj antaŭ ripetokarojn
preferences-show-next-review-time-above-answer = Montri tempon de sekva ripeto super respondobutonoj
preferences-spacebar-rates-card = Spacostango (aŭ eniga klavo) ankaŭ montras respondon
preferences-show-play-buttons-on-cards-with = Montri lud-stirilojn ĉe kartoj kun sono
preferences-show-remaining-card-count = Montri nombron da pliaj kartoj
preferences-some-settings-will-take-effect-after = Kelkaj agordoj efektiviĝos nur post relanĉo de Anki.
preferences-tab-synchronisation = Samtempigo
preferences-synchronize-audio-and-images-too = Samtempigi ankaŭ sonojn kaj bildojn
preferences-login-successful-sync-now = Sukcese ensalutinta. Ĉu konservi preferojn kaj samtempigi nun?
preferences-timebox-time-limit = Limigo de lernada tempo
preferences-user-interface-size = Grando de fasado
preferences-when-adding-default-to-current-deck = dum aldoni, elekti la nunan kartaron
preferences-you-can-restore-backups-via-fileswitch = Vi povas rekrei sekurkopion per la menuero Dosiero → Ŝanĝi profilon.
preferences-legacy-timezone-handling = Kaduka pritraktado de horzonoj (erara, sed necesa por AnkiDroid ≤ 2.14)
preferences-default-search-text = Implicita teksto de serĉo
preferences-default-search-text-example = ekz. “deck:current”
preferences-theme = Haŭto
preferences-theme-follow-system = laŭ operaciumo
preferences-theme-light = hela
preferences-theme-dark = malhela
preferences-v3-scheduler = Planilo V3
preferences-check-for-updates = Kontroli pri ĝisdatigoj
preferences-ignore-accents-in-search = Ignori supersignojn dum serĉi (pli malrapide)
preferences-backup-explanation = Anki periode sekurkopias vian kolekton. Iuj sekurkopioj pli malnovaj ol 2 tagoj povas esti forigitaj de Anki por liberigi diskspacon.
preferences-daily-backups = Tagaj sekurkopioj por teni:
preferences-weekly-backups = Semajnaj sekurkopioj por teni:
preferences-monthly-backups = Monataj sekurkopioj por teni:
preferences-minutes-between-backups = Minutoj inter aŭtomataj sekurkopioj:
preferences-reduce-motion = Limigi efektojn
preferences-reduce-motion-tooltip = Malaktivigi diversajn movildojn kaj transpasajn efektojn de la fasado
preferences-custom-sync-url = Mem-gastigata samtempiga servilo
preferences-custom-sync-url-disclaimer = por spertulaj uzantoj – legu la gvidlibron
preferences-hide-top-bar-during-review = Kaŝi supran strion dum ripetado
preferences-hide-bottom-bar-during-review = Kaŝi malsupran strion dum ripetado
preferences-always = ĉiam
preferences-full-screen-only = nur plenekrane
preferences-appearance = Aspekto
preferences-general = Ĝeneralaj
preferences-style = Stilo
preferences-review = Ripetado
preferences-answer-keys = Respond-klavoj
preferences-distractions = Distraĵoj
preferences-minimalist-mode = Minimuma reĝimo
preferences-minimalist-mode-tooltip = Pli kompakta fasado (malpli da ornamaĵoj)
preferences-editing = Redaktado
preferences-browsing = Foliumado
preferences-default-deck = Implicita kartaro
preferences-account = AnkiWeb-konto
preferences-note = Averto
preferences-scheduler = Planado
preferences-user-interface = Fasado
preferences-import-export = Enporti/elporti
preferences-network-timeout = Templimo de konekto
preferences-reset-window-sizes = Restarigi implicitajn grandojn de fenestroj
preferences-reset-window-sizes-complete = Restarigis implicitajn grandojn kaj aranĝojn de fenestroj.

## URL scheme related


## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Baza
