actions-add = Lisää
actions-blue-flag = Sininen lippu
actions-cancel = Peruuta
actions-choose = Valitse
actions-close = Sulje
actions-copy = Kopioi
actions-custom-study = Mukautettu opiskelu
actions-decks = Pakat
actions-delete = Poista
actions-export = Vie
actions-filter = Suodatin
actions-help = Ohje
actions-import = Tuo
actions-name = Nimi:
actions-new = Uudet
actions-new-name = Uusi nimi:
actions-options = Valinnat
actions-options-for = Valinnat kohteessa { $val }
actions-preview = Esikatselu
actions-rebuild = Koosta uudelleen
actions-rename = Nimeä uudelleen
actions-rename-deck = Nimeä pakka uudelleen
actions-replay-audio = Toista äänitiedosto
actions-reposition = Uuden sijainnin määrittäminen
actions-save = Tallenna
actions-search = Etsi
actions-shortcut-key = Pikavalintanäppäin: { $val }
actions-suspend-card = Hyllytä kortti
