browsing-add-notes = Lisää muistiinpanoja...
browsing-add-tags = Lisää tunnisteita
browsing-add-tags2 = Lisää tunnisteita...
browsing-added-today = Lisätty tänään
browsing-again-today = Uudestaan tänään
browsing-all-card-types = Kaikki korttien tyypit
browsing-all-fields = Kaikki kentät
browsing-answer = Vastaus
browsing-any-cards-mapped-to-nothing-will = Kortit, joita ei ole liitetty mihinkään, poistetaan. Jos muistiinpanoon ei liity jäljelle jääviä kortteja, se katoaa. Oletko varma, että haluat jatkaa?
browsing-any-flag = Mikä tahansa lippu
browsing-browser-appearance = Selaimen ulkoasu
browsing-browser-options = Selainasetukset
browsing-buried = Haudattu
browsing-card = Kortti
browsing-card-list = Korttiluettelo
browsing-card-state = Kortin tila
browsing-cards-cant-be-manually-moved-into = Kortteja ei voi siirtää manuaalisesti suodatettuun pakkaan.
browsing-change-deck = Vaihda pakkaa
browsing-change-deck2 = Vaida pakkaa...
browsing-change-note-type = Vaihda muistiinpanotyyppiä
browsing-change-note-type2 = Vaihda muistiinpanotyyppiä...
browsing-change-to = { $val } →
browsing-clear-unused = Tyhjennä käyttämättömät
browsing-clear-unused-tags = Poista käyttämättömät tunnisteet
browsing-created = Luomisaika
browsing-current-deck = Nykyinen pakka
browsing-current-note-type = Nykyinen muistiinpanotyyppi:
browsing-delete-notes = Poista muistiinpanot
browsing-delete-tags = Poista tunnisteet
browsing-duplicate = kaksoiskappale
browsing-ease = Helppous
browsing-end = Lopetus
browsing-enter-tags-to-add = Lisättävät tunnisteet:
browsing-enter-tags-to-delete = Poistettavat tunnisteet:
browsing-filtered = (suodatettu)
browsing-find = <b>Etsi</b>
browsing-find-and-replace = Etsi ja korvaa
browsing-find-duplicates = Etsi kaksoiskappaleet
browsing-first-card = Ensimmäinen kortti
browsing-font = <b>Fontti</b>:
browsing-font-size = <b>Fonttikoko</b>:
browsing-found-as-across-bs = Löytyi %(a)s, joissa on %(b)s.
browsing-home = Aloitussivu
browsing-ignore-case = Älä huomioi kirjasinkokoa
browsing-in = <b>Kenttä</b>
browsing-interval = Kertausväli
browsing-last-card = Viimeinen kortti
browsing-learning = (opiskeltavana)
browsing-line-size = <b>Viivanleveys</b>:
browsing-manage-note-types = Hallinnoi muistiinpanotyyppejä...
browsing-move-cards = Siirrä kortit
browsing-move-cards-to-deck = Siirrä kortit pakkaan:
browsing-new = (uusi)
browsing-new-note-type = Uusi muistiinpanotyyppi:
browsing-note = Muistiinpano
browsing-notes-tagged = Merkityt muistiinpanot
browsing-nothing = ei mitään
browsing-only-new-cards-can-be-repositioned = Vain uusien korttien sijaintia pakassa voi muuttaa.
browsing-override-back-template = Syrjäytä kääntöpuolen malline:
browsing-override-font = Syrjäytä fontti:
browsing-override-front-template = Syrjäytä etupuolen malline:
browsing-place-at-end-of-new-card = Sijoita uuden korttijonon loppuun
browsing-place-in-review-queue-with-interval = Aseta kertausjonoon kertausvälillä:
browsing-please-select-cards-from-only-one = Valitse vain yhden muistiinpanotyypin kortteja.
browsing-preview-selected-card = Esikatsele valittuja kortteja ({ $val })
browsing-question = Kysymys
browsing-queue-bottom = Jonon loppu: { $val }
browsing-queue-top = Jonon alku: { $val }
browsing-randomize-order = Sekoita järjestys
browsing-replace-with = <b>Korvaus</b>
browsing-reposition = Uuden sijainnin määrittäminen...
browsing-reposition-new-cards = Määritä uusi sijainti pakassa uusille korteille
browsing-reschedule = Ajasta uudelleen
browsing-search-within-formatting-slow = Etsi muotoiluista (hidas)
browsing-shift-position-of-existing-cards = Vaihda olemassa olevien korttien sijaintia
browsing-sort-field = Lajittelukenttä
browsing-sorting-on-this-column-is-not = Lajittelu tämän sarakkeen mukaan ei ole mahdollista. Valitse toinen sarake.
browsing-start-position = Aloitussijainti:
browsing-step = Vaihe:
browsing-studied-today = Opiskeltu tänään
browsing-suspended = Hyllytetyt
browsing-tag-duplicates = Lisää tunniste kaksoiskappaleisiin
browsing-target-field = Kohdekenttä:
browsing-today = Tänään
browsing-treat-input-as-regular-expression = Tulkitse syöte säännöllisenä lausekkeena
browsing-type-here-to-search = <kirjoita tähän hakusana tai paina enteriä nähdäksesi nykyisen pakan>
browsing-whole-collection = Koko kokoelma
browsing-you-must-have-at-least-one = Pitää olla vähintään yksi sarake.
