card-templates-card-type = Korttityyppi:
card-templates-front-template = Etupuolen malline
card-templates-back-template = Kääntöpuolen malline
card-templates-template-styling = Muotoilu
card-templates-front-preview = Etupuolen esikatselu
card-templates-back-preview = Kääntöpuolen esikatselu
card-templates-preview-box = Esikatselu
card-templates-sample-cloze = Tämä on {"{{c1::"}sample{"}}"} aukkotehtävä.
card-templates-add-card-type = Lisää kortin tyyppi...
card-templates-anki-couldnt-find-the-line-between = Anki ei löytänyt kysymyksen ja vastauksen välistä rajaa. Mukauta mallinetta manuaalisesti vaihtaaksesi kysymyksen ja vastauksen välisen rajan.
card-templates-at-least-one-card-type-is = Vähintään yksi korttityyppi on annettava.
card-templates-browser-appearance = Selaimen ulkoasu...
card-templates-card = Kortti { $val }
card-templates-card-types = Korttityypit
card-templates-card-types-for = Korttityypit kohteessa { $val }
card-templates-cloze = Aukkotehtävä
card-templates-delete-the-as-card-type-and = Poistetaanko '%(a)s'-korttityyppi ja sen %(b)s?
card-templates-enter-deck-to-place-new = Syötä pakka, johon asetetaan uudet { $val } korttia tai jätä tyhjäksi:
card-templates-enter-new-card-position-1 = Syötä kortin uusi sijainti (1...{ $val }):
card-templates-flip = Käännä ympäri
card-templates-form = Lomake
card-templates-off =  (pois päältä)
card-templates-on =  (päällä)
