custom-study-must-rename-deck = Nimeä olemassa oleva mukautetun opiskelun pakka ensin uudelleen.
custom-study-all-cards-in-random-order-dont = Kaikki kortin satunnaisessa järjestyksessä (älä ajasta uudelleen)
custom-study-all-review-cards-in-random-order = Kaikki kerrattavat kortit satunnaisessa järjestyksessä
custom-study-cards = kortilla
custom-study-cards-from-the-deck = korttia pakasta
custom-study-choose-tags = Valitse tunnisteet
custom-study-custom-study-session = Mukautettu opiskeluistonto
custom-study-due-cards-only = Vain erääntyneet kortit
custom-study-increase-todays-new-card-limit = Kasvata tämän päivän uusien korttien ylärajaa
custom-study-increase-todays-new-card-limit-by = Kasvata tämän päivän uusien korttien ylärajaa
custom-study-increase-todays-review-card-limit = Kasvata tänään kerrattavien korttien ylärajaa
custom-study-increase-todays-review-limit-by = Kasvata tänään kerrattavien korttien ylärajaa
custom-study-new-cards-in-deck-over-today = Pakassa olevien tämän päivän jälkeen opittavien korttien määrä: { $val }
custom-study-new-cards-only = Vain uudet kortit
custom-study-no-cards-matched-the-criteria-you = Yksikään kortti ei vastaa annettuja ehtoja
custom-study-ok = OK
custom-study-preview-new-cards = Esikatsele uusia kortteja
custom-study-preview-new-cards-added-in-the = Esikatsele uusia kortteja, jotka on lisätty viimeisenä
custom-study-require-one-or-more-of-these = Vaadi yksi tai useampi näistä tunnisteista:
custom-study-review-ahead = Kertaa etukäteen
custom-study-review-ahead-by = Kertaa ennalta
custom-study-review-cards-forgotten-in-last = Kertaa unohdetut kortit viimeiseltä
custom-study-review-forgotten-cards = Kertaa unohdettuja kortteja
custom-study-reviews-due-in-deck-over-today = Pakassa olevien tämän päivän jälkeen kerrattavien korttien määrä: { $val }
custom-study-select = Valitse
custom-study-select-tags-to-exclude = Valitse poissuljettavat tunnisteet:
custom-study-selective-study = Valikoiva opiskelu
custom-study-study-by-card-state-or-tag = Opiskele kortteja, joilla on tietty tila tai tunniste
