decks-add-new-deck-ctrlandn = Lisää uusi pakka (Ctrl + N)
decks-are-you-sure-you-wish-to = Oletko varma, että haluat poistaa kohteen { $val }?
decks-build = Kokoa
decks-cards-selected-by = korttiin, jotka on valittu perusteella
decks-create-deck = Luo pakka
decks-deck = Pakka
decks-decreasing-intervals = Laskevat kertausvälit
decks-delete-deck = Poista pakka
decks-filter = Suodatin:
decks-get-shared = Hanki jaettu pakka
decks-import-file = Tuo tiedosto
decks-increasing-intervals = Kasvavat kertausvälit
decks-latest-added-first = Viimeisenä lisätty ensimmäisenä
decks-limit-to = Rajoita
decks-minutes = minuuttia
decks-most-lapses = Eniten virheitä
decks-name-for-deck = Pakan nimi:
decks-new-deck-name = Uuden pakan nimi:
decks-no-deck = [ei pakkaa]
decks-oldest-seen-first = Vanhin nähty ensin
decks-order-added = Järjestä lisätyt
decks-order-due = Järjestä erääntyvät
decks-please-select-something = Valitse jotain.
decks-random = Satunnainen
decks-relative-overdueness = Suhteellinen erääntyneisyys
decks-reschedule-cards-based-on-my-answers = Ajasta kortit uudestaan perustuen vastauksiini tässä pakassa
decks-study = Opiskele
decks-study-deck = Opiskele pakkaa
decks-the-provided-search-did-not-match = Annetut hakuehdot eivät vastanneet yhtään korttia. Haluatko korjata hakuehtojasi?
