decks-add-new-deck-ctrlandn = Lisää uusi pakka (Ctrl + N)
decks-build = Kokoa
decks-cards-selected-by = korttiin, jotka on valittu perusteella
decks-create-deck = Luo pakka
decks-custom-steps-in-minutes = Mukautetut askeleet (minuuteissa)
decks-deck = Pakka
decks-decreasing-intervals = Laskevat kertausvälit
decks-delete-deck = Poista pakka
decks-enable-second-filter = Käytä toista suodatinta
decks-filter = Suodatin:
decks-filter-2 = Suodatin 2
decks-get-shared = Hanki jaettu pakka
decks-import-file = Tuo tiedosto
decks-increasing-intervals = Kasvavat kertausvälit
decks-latest-added-first = Viimeisenä lisätty ensimmäisenä
decks-limit-to = Rajoita
decks-minutes = minuuttia
decks-most-lapses = Eniten virheitä
decks-new-deck-name = Uuden pakan nimi:
decks-no-deck = [ei pakkaa]
decks-oldest-seen-first = Vanhin nähty ensin
decks-order-added = Järjestä lisätyt
decks-order-due = Järjestä erääntyvät
decks-please-select-something = Valitse jotain.
decks-random = Satunnainen
decks-relative-overdueness = Suhteellinen erääntyneisyys
decks-repeat-failed-cards-after = Toista väärin vastatut kortit, kun on kulunut
decks-reschedule-cards-based-on-my-answers = Ajasta kortit uudestaan perustuen vastauksiini tässä pakassa
decks-study = Opiskele
decks-study-deck = Opiskele pakkaa
decks-filtered-deck-search-empty = Yksikään kortti ei vastannut annettua hakua. Jotkin kortit on saatettu jättää pois, koska ne ovat eri suodatetussa pakassa tai ne on hyllytetty.
decks-unmovable-cards = Näytä kaikki poissuljetut kortit
