editing-add-media = Lisää mediatiedosto
editing-an-error-occurred-while-opening = Kohdetta { $val } avattaessa tapahtui virhe
editing-attach-picturesaudiovideo-f3 = Liitä kuva/äänite/video (F3)
editing-bold-text-ctrlandb = Lihavointi (Ctrl+B)
editing-cards = Kortit
editing-change-colour-f8 = Vaihda väriä (F8)
editing-cut = Leikkaa
editing-edit-current = Muokkaa nykyistä
editing-edit-html = Muokkaa HTML:ää
editing-fields = Kentät
editing-html-editor = HTML-muokkain
editing-italic-text-ctrlandi = Kursivointi (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Siirry tunnisteisiin painamalla Ctrl+Shift+T
editing-latex-equation = LaTeX-yhtälö
editing-latex-math-env = LaTeX matem. ympär.
editing-media = Mediatiedostot
editing-paste = Liitä
editing-show-duplicates = Näytä kaksoiskappaleet
editing-tags = Tunnisteet
editing-to-make-a-cloze-deletion-on = Voidaksesi tehdä aukkotehtävän olemassa olevasta muistiinpanosta, sinun täytyy ensin muuttaa se aukkotehtävätyypiksi: Muokkaa>Vaihda muistiinpanotyyppiä
editing-warning-cloze-deletions-will-not-work = Varoitus: aukkotehtävät eivät toimi ennen kun vaihdat tyypin ylhäältä aukkotehtäväksi.
