fields-add-field = Lisää kenttä
fields-delete-field-from = Haluatko varmasti poistaa tämän kentän kohteesta { $val }?
fields-editing-font = Muokkausfontti
fields-field = Kenttä:
fields-field-name = Kentän nimi:
fields-fields-for = Kentät kohteessa { $val }
fields-font = Fontti:
fields-new-position-1 = Uusi sijainti (1...{ $val }):
fields-notes-require-at-least-one-field = Muistiinpanoissa täytyy olla vähintään yksi kenttä.
fields-remember-last-input-when-adding = Muista viimeisin syötetty tieto lisätessä
fields-reverse-text-direction-rtl = Päinvastainen tekstinsuunta (RTL)
fields-size = Koko:
fields-sort-by-this-field-in-the = Lajittele tämän kentän mukaan selaimessa
fields-that-field-name-is-already-used = Kentän nimi on jo käytössä.
