notetypes-front-field = Etupuoli
notetypes-back-field = Kääntöpuoli
notetypes-add-reverse-field = Lisää kääntöpuoli
notetypes-text-field = Teksti
notetypes-basic-name = Perusasetukset
notetypes-basic-reversed-name = Perusmalli (ja käännetty kortti)
notetypes-basic-optional-reversed-name = Perusmalli (valinnainen käännetty kortti)
notetypes-cloze-name = Aukkotehtävä
notetypes-basic-type-answer-name = Perus (kirjoita vastaus)
notetypes-card-2-name = Kortti 2
notetypes-card-1-name = Kortti 1
notetypes-add = Lisää: { $val }
notetypes-add-note-type = Lisää muistiinpanotyyppi
notetypes-cards = Kortit...
notetypes-clone = Kloonaa: { $val }
notetypes-copy = { $val } (kopio)
notetypes-create-scalable-images-with-dvisvgm = Luo skaalattavia kuvia dvisvgm:llä
notetypes-delete-this-note-type-and-all = Poistetaanko tämä muistiinpano ja kaikki sen kortit?
notetypes-delete-this-unused-note-type = Poistetaanko tämä käyttämätön muistiinpanotyyppi?
notetypes-fields = Kentät...
notetypes-footer = Alatunniste
notetypes-header = Ylätunniste
notetypes-note-types = Muistiinpanotyypit
notetypes-options = Valinnat...
notetypes-please-add-another-note-type-first = Lisää toinen muistiinpanotyyppi ensin.
notetypes-type = Tyyppi
