preferences-automatically-sync-on-profile-openclose = Synkronoi automaattisesti kun käyttäjätili avataan/suljetaan
preferences-backups = Varmuuskopiot
preferences-backups2 = varmuuskopiota
preferences-backupsanki-will-create-a-backup-of = <b>Varmuuskopiot</b><br>Anki luo varmuuskopion kokoelmastasi joka kerta kun se suljetaan tai synkronoidaan.
preferences-basic = Perusasetukset
preferences-change-deck-depending-on-note-type = Vaihda pakkaa muistiinpanotyypistä riippuen
preferences-changes-will-take-effect-when-you = Muutokset tulevat voimaan, kun käynnistät Ankin uudelleen.
preferences-hours-past-midnight = tuntia yli keskiyön
preferences-interface-language = Käyttöliittymän kieli:
preferences-interrupt-current-audio-when-answering = Keskeytä nykyinen ääni vastatessa
preferences-keep = Pidä
preferences-learn-ahead-limit = Ennalta opiskeltavien yläraja
preferences-mins = min
preferences-network = Verkko
preferences-next-day-starts-at = Uusi päivää alkaa
preferences-night-mode = Tumma tila
preferences-note-media-is-not-backed-up = Huomautus: Mediatiedostoista ei ole otettu varmuuskopiota. Ota Anki-kansiostasi säännöllisin väliajoin varmuuskopio pitääksesi tiedostosi ovat turvassa.
preferences-on-next-sync-force-changes-in = Seuraavassa synkronoinnissa pakota muutokset yhteen suuntaan
preferences-paste-clipboard-images-as-png = Liitä leikepöydän kuvat PNG-muodossa
preferences-paste-without-shift-key-strips-formatting = Liittäminen ilman vaihtonäppäintä poistaa muotoilut
preferences-periodically-sync-media = Synkronoi media ajoittain
preferences-please-restart-anki-to-complete-language = Käynnistä Anki uudelleen, niin että kielivalinnan muutos tulee voimaan.
preferences-preferences = Asetukset
preferences-scheduling = Ajasta uudelleen
preferences-show-learning-cards-with-larger-steps = Näytä opittavat kortit joilla on suuremmat askeleet ennen kertausta
preferences-show-next-review-time-above-answer = Näytä seuraava kertausaika vastauspainikkeiden yläpuolella
preferences-show-play-buttons-on-cards-with = Näytä toistopainike korteissa, joissa on ääni
preferences-show-remaining-card-count-during-review = Näytä jäljellä olevien korttien lukumäärä kertauksen aikana
preferences-some-settings-will-take-effect-after = Osa asetuksista tulee voimaan vasta Ankin uudelleenkäynnistyksen jälkeen.
preferences-synchronisation = <b>Synkronointi</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synkronointi</b><br> Synkronointi ei ole päällä. Klikkaa Synkronoi-painiketta pääikkunassa laittaaksesi sen päälle.
preferences-synchronize-audio-and-images-too = Synkronoi myös äänitiedostot ja kuvat
preferences-timebox-time-limit = Määritetyn ajan yläraja
preferences-user-interface-size = Käyttöliittymän koko
preferences-when-adding-default-to-current-deck = Kun lisätään, on oletuksena nykyinen pakka
preferences-you-can-restore-backups-via-fileswitch = Voit palauttaa varmuuskopioita valitsemalla Tiedosto>Vaihda profiilia.
preferences-legacy-timezone-handling = Vanha aikavyöhykkeiden käsittely (sisältää virheitä, mutta vaaditaan AnkiDroidin versioissa <= 2.14)
preferences-default-search-text = Oletusarvoinen hakuteksti
preferences-default-search-text-example = esim. 'deck:current'
preferences-theme-label = Teema: { $theme }
preferences-theme-follow-system = Seuraa järjestelmän asetuksia
preferences-theme-light = Vaalea
preferences-theme-dark = Tumma
preferences-v3-scheduler = V3-aikataulutusohjelma
preferences-ignore-accents-in-search = Jätä aksentit huomiotta haun yhteydessä (hitaampi)
preferences-backup-explanation =
    Anki varmuuskopioi kokoelmasi säännöllisesti, kun se on suljettu. Kun varmuuskopiot ovat yli 2 päivää vanhoja,
    Anki alkaa poistaa niistä joitakin vapauttaakseen levytilaa.
preferences-daily-backups = Säilytettävien päivittäisten varmuuskopioiden määrä:
preferences-weekly-backups = Säilytettävien viikottaisten varmuuskopioiden määrä:
preferences-monthly-backups = Säilytettävien kuukausittaisten varmuuskopioiden määrä:
