preferences-automatically-sync-on-profile-openclose = Synkronoi automaattisesti kun käyttäjätili avataan/suljetaan
preferences-backups = Varmuuskopiot
preferences-backups2 = varmuuskopiota
preferences-backupsanki-will-create-a-backup-of = <b>Varmuuskopiot</b><br>Anki luo varmuuskopion kokoelmastasi joka kerta kun se suljetaan tai synkronoidaan.
preferences-basic = Perusasetukset
preferences-change-deck-depending-on-note-type = Vaihda pakkaa muistiinpanotyypistä riippuen
preferences-changes-will-take-effect-when-you = Muutokset tulevat voimaan, kun käynnistät Ankin uudelleen.
preferences-hours-past-midnight = tuntia yli keskiyön
preferences-interface-language = Käyttöliittymän kieli:
preferences-keep = Pidä
preferences-learn-ahead-limit = Ennalta opiskeltavien yläraja
preferences-mins = min
preferences-network = Verkko
preferences-next-day-starts-at = Uusi päivää alkaa
preferences-note-media-is-not-backed-up = Huomautus: Mediatiedostoista ei ole otettu varmuuskopiota. Ota Anki-kansiostasi säännöllisin väliajoin varmuuskopio, että tiedostosi ovat turvassa.
preferences-on-next-sync-force-changes-in = Seuraavassa sykronoinnissa pakota muutokset toiseen suuntaan
preferences-paste-clipboard-images-as-png = Liitä leikepöydän kuvat PNG-muodossa
preferences-please-restart-anki-to-complete-language = Käynnistä Anki uudelleen, niin että kielivalinnan muutos tulee voimaan.
preferences-preferences = Asetukset
preferences-scheduling = Ajasta uudelleen
preferences-show-next-review-time-above-answer = Näytä seuraava kertausaika vastauspainikkeiden yläpuolella
preferences-show-remaining-card-count-during-review = Näytä jäljellä olevien korttien lukumäärä kertauksen aikana
preferences-some-settings-will-take-effect-after = Osa asetuksista tulee voimaan vasta Ankin uudelleenkäynnistyksen jälkeen.
preferences-synchronisation = <b>Synkronointi</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synkronointi</b><br> Synkronointi ei ole päällä. Klikkaa Synkronoi-painiketta pääikkunassa laittaaksesi sen päälle.
preferences-synchronize-audio-and-images-too = Synkronoi myös äänitiedostot ja kuvat
preferences-timebox-time-limit = Määritetyn ajan yläraja
preferences-user-interface-size = Käyttöliittymän koko
preferences-when-adding-default-to-current-deck = Kun lisätään, on oletuksena nykyinen pakka
