profiles-anki-could-not-read-your-profile = Anki ei voinut lukea profiilisi tietoja. Ikkunoiden koot ja synkronoinnin sisäänkirjautumistiedot on unohdettu.
profiles-anki-could-not-rename-your-profile = Anki ei voinut nimetä profiiliasi uudelleen, koska se ei voinut nimetä uudelleen levylle tallennettua profiilikansiota. Varmista, että sinulla oikeudet kansioon ”Tiedostot/Anki” eivätkä mitkään muut ohjelmat käytä profiilikansioitasi, ja yritä sitten uudelleen.
profiles-folder-already-exists = Kansio on jo olemassa
profiles-open = Avaa
profiles-open-backup = Avaa varmuuskopio...
profiles-please-remove-the-folder-and = Poista kansio ”{ $val }” ja yritä uudelleen.
profiles-profiles = Käyttäjätilit
profiles-quit = Lopeta
profiles-user-1 = Käyttäjä 1
profiles-confirm-lang-choice = Oletko varma, että haluat näyttää Ankin käyttöliittymän kielellä { $lang }?
profiles-could-not-create-data-folder = Anki ei pystynyt luomaan datakansiotaan. Tutustu käyttöoppaan Tiedostojen sijainnit -osioon ja varmista, että sijaintiin on kirjoitusoikeudet.
