actions-add = Додати
actions-blue-flag = Синій прапорець
actions-cancel = Відмінити
actions-choose = Вибрати
actions-close = Закрити
actions-copy = Копіювати
actions-custom-study = Додаткове навчання
actions-decks = Колоди
actions-delete = Видалити
actions-export = Експорт колоди в інший формат
actions-filter = Фільтр
actions-green-flag = Зелений прапорець
actions-help = Допомога
actions-import = Імпорт
actions-manage = Керування…
actions-name = Назва:
actions-new = Нові
actions-new-name = Нова назва:
actions-options = Опції
actions-options-for = Налаштування для { $val }
actions-orange-flag = Помаранчевий прапорець
actions-preview = Попередній  вигляд
actions-rebuild = Перебудувати
actions-red-flag = Червоний прапорець
actions-rename = Перейменувати
actions-rename-deck = Перейменувати колоду
actions-replay-audio = Прослухати ще раз
actions-reposition = Змінити розташування
actions-save = Зберегти
actions-search = Пошук
actions-shortcut-key = Гаряча клавіша: { $val }
actions-suspend-card = Відкласти картку
