actions-add = Додати
actions-all-selected = Усі вибрані
actions-any-selected = Будь-які вибрані
actions-cancel = Скасувати
actions-choose = Вибрати
actions-close = Закрити
actions-copy = Копіювати
actions-create-copy = Створити копію
actions-custom-study = Додаткове навчання
actions-decks = Колоди
actions-decrement-value = Зменшити значення
actions-delete = Видалити
actions-export = Експорт колоди в інший формат
actions-filter = Фільтр
actions-help = Допомога
actions-increment-value = Збільшити значення
actions-import = Імпорт
actions-manage = Керування…
actions-name = Назва:
actions-new = Нові
actions-new-name = Нова назва:
actions-options = Налаштування
actions-options-for = Налаштування для { $val }
actions-preview = Попередній  вигляд
actions-rebuild = Перебудувати
actions-rename = Перейменувати
actions-rename-deck = Перейменувати колоду
actions-rename-tag = Перейменувати мітку
actions-rename-with-parents = Перейменувати мітку разом з батьківськими
actions-remove-tag = Прибрати мітку
actions-replay-audio = Прослухати ще раз
actions-reposition = Змінити розташування
actions-save = Зберегти
actions-search = Пошук
actions-select = Вибрати
actions-shortcut-key = Гаряча клавіша: { $val }
actions-suspend-card = Призупинити картку
actions-set-due-date = Вказати дату пригадування
actions-answer-card = Відповідь на картку
actions-unbury-unsuspend = Показати/поновити
actions-add-deck = Додати колоду
actions-add-note = Додати нотатку
actions-update-tag = Оновити мітку
actions-update-note = Оновити нотатку
actions-update-card = Оновити картку
actions-update-deck = Оновити колоду
actions-forget-card = Забути картку
actions-build-filtered-deck = Створити відфільтровану колоду
actions-add-notetype = Додати тип нотатки
actions-remove-notetype = Видалити тип нотатки
actions-update-notetype = Оновити тип нотатки
actions-update-config = Оновити налаштування
actions-card-info = Інформація про картку
actions-previous-card-info = Інформація про попередню картку
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-currently-unsupported = Дана дія наразі не підтримується Вашою системою.

## Flags

actions-flag-number = { $number } прапорець
actions-flag-red = Червоний
actions-flag-orange = Помаранчевий
actions-flag-green = Зелений
actions-flag-blue = Синій
actions-flag-pink = Рожевий
actions-flag-turquoise = Бірюзовий
actions-flag-purple = Фіолетовий
actions-set-flag = Встановити прапорець
actions-nothing-to-undo = Нічого відновити
actions-nothing-to-redo = Нічого повторити
