adding-add-shortcut-ctrlandenter = Додати (скорочення клавіш: Ctrl+Enter)
adding-added = Додано
adding-discard-current-input = Видалити введені дані?
adding-keep-editing = Продовжити редагувати
adding-edit = Редагувати «{ $val }»
adding-history = Історія
adding-note-deleted = (Нотатку видалено)
adding-shortcut = Гаряча клавіша: { $val }
adding-the-first-field-is-empty = Перше поле порожнє.
adding-you-have-a-cloze-deletion-note = Вказаний тип нотатки cloze, однак Ви не створили пропусків. Продовжити?
adding-cloze-outside-cloze-notetype = Видалення тестів з пропусками працює лише для типу нотатки Cloze.
adding-cloze-outside-cloze-field = Видалення пропусків можна використовувати лише у полях, які мають фільтр 'cloze:'. Зазвичай це перше поле.
