card-stats-added = Додано
card-stats-first-review = Вперше побачена
card-stats-latest-review = Останній перегляд
card-stats-interval = Інтервал
card-stats-ease = Легкість
card-stats-review-count = Повторення
card-stats-lapse-count = Невдачі
card-stats-average-time = Середній час
card-stats-total-time = Загальний час
card-stats-new-card-position = Позиція
card-stats-card-template = Тип картки
card-stats-note-type = Тип нотаток
card-stats-deck-name = Колода
card-stats-note-id = Індекс нотатки
card-stats-card-id = Індекс картки
