custom-study-must-rename-deck = Будь ласка, спочатку перейменуйте існуючу колоду власного навчання.
custom-study-all-cards-in-random-order-dont = Всі картки у випадковому порядку (без перепланування)
custom-study-all-review-cards-in-random-order = Всі повторювані картки у випадковому порядку
custom-study-cards = картки
custom-study-cards-from-the-deck = картки з колоди
custom-study-choose-tags = Вибрати мітки
custom-study-custom-study-session = Сесія додаткового навчання
custom-study-due-cards-only = Лише очікувані картки
custom-study-increase-todays-new-card-limit = На сьогодні збільшити обмеження для нових карток
custom-study-increase-todays-new-card-limit-by = На сьогодні збільшити обмеження для нових карток на
custom-study-increase-todays-review-card-limit = На сьогодні збільшити обмеження для повторювальних карток
custom-study-increase-todays-review-limit-by = На сьогодні збільшити обмеження для повторень на
custom-study-new-cards-in-deck-over-today = Нових карток в колоді поза денним обмеженням: { $val }
custom-study-new-cards-only = Лише нові картки
custom-study-no-cards-matched-the-criteria-you = Жодна картка не відповідає вказаним критеріям.
custom-study-ok = Добре!
custom-study-preview-new-cards = Попередньо переглянути нові картки
custom-study-preview-new-cards-added-in-the = Попередньо переглянути нові картки, додані за останніх
custom-study-require-one-or-more-of-these = Потрібно одна чи кілька з цих міток:
custom-study-review-ahead = Повторити наперед
custom-study-review-ahead-by = Повторити наперед на
custom-study-review-cards-forgotten-in-last = Повторити картки, забуті за останні
custom-study-review-forgotten-cards = Повторити забуті картки
custom-study-reviews-due-in-deck-over-today = Повторити картки понад добове обмеженя: { $val }
custom-study-select = Вибрати
custom-study-select-tags-to-exclude = Вибрати мітки, які слід виключити:
custom-study-selective-study = Вибіркове навчання
custom-study-study-by-card-state-or-tag = Вчити за станом картки або міткою
