editing-add-media = Додати медіа-файл
editing-align-left = Зліва
editing-align-right = Справа
editing-an-error-occurred-while-opening = Помилка під час відкриття { $val }
editing-attach-picturesaudiovideo = Додати зображення/аудіо/відео
editing-bold-text = Жирний текст
editing-cards = Картки
editing-center = По центру
editing-change-color = Змінити колір
editing-couldnt-record-audio-have-you-installed = Не вдається записати звук. Чи встановлено у Вас «lame»?
editing-customize-card-templates = Змінити шаблон картки
editing-customize-fields = Змінити поля
editing-cut = Вирізати
editing-double-click-to-expand = Натисніть двічі, щоб показати
editing-double-click-to-collapse = Натисніть двічі, щоб приховати
editing-edit-current = Редагувати поточну
editing-edit-html = Редагувати HTML
editing-fields = Поля
editing-indent = Збільшити відступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти до міток з  Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Рівняння LaTeX
editing-latex-math-env = Математичне оточення LaTeX
editing-mathjax-block = MathJax блок
editing-mathjax-chemistry = MathJax для хімії
editing-mathjax-inline = MathJax в рядку
editing-media = Медіа-файли
editing-ordered-list = Впорядкований список
editing-outdent = Зменшити відступ
editing-paste = Вставити
editing-record-audio = Записати авдіо
editing-remove-formatting = Видалити форматування
editing-restore-original-size = Повернути початковий розмір
editing-select-remove-formatting = Оберіть форматування до видалення
editing-show-duplicates = Показати дублікати
editing-subscript = Нижній індекс
editing-superscript = Верхній індекс
editing-tags = Мітки
editing-tags-add = Додати мітку
editing-tags-copy = Копіювати мітки
editing-tags-remove = Видалити мітки
editing-tags-select-all = Обрати всі мітки
editing-text-color = Колір тексту
editing-text-highlight-color = Колір підсвічення тексту
editing-to-make-a-cloze-deletion-on = Для створення картки з тестом з пробілами по існуючій нотатці, спочатку потрібно змінити її тип на тип тесту з пробілами командою "Редагування>Змінити тип нотатки..."
editing-toggle-html-editor = Перемикач HTML редактора
editing-toggle-visual-editor = Перемикач візуального редактора
editing-toggle-sticky = Перемикач прикріплення
editing-expand = Показати
editing-collapse = Приховати
editing-expand-field = Показати поле
editing-collapse-field = Приховати поле
editing-underline-text = Підкреслений текст
editing-unordered-list = Невпорядкований список
editing-warning-cloze-deletions-will-not-work = Увага! Тести з пробілами не спрацюють, поки ви не зміните тип вгорі на Тест з пробілами.
editing-mathjax-preview = Передперегляд MathJax
editing-close-html-tags = Автоматично закривати HTML теґи

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Редактор HTML
