editing-actual-size = Перемкнути фактичний розмір
editing-add-media = Додати медіа-файл
editing-align-left = Зліва
editing-align-right = Справа
editing-an-error-occurred-while-opening = Помилка під час відкриття { $val }
editing-attach-picturesaudiovideo = Додати зображення/аудіо/відео
editing-bold-text = Жирний текст
editing-cards = Картки
editing-center = По центру
editing-change-color = Змінити колір
editing-cloze-deletion = Прихована відповідь (нова картка)
editing-cloze-deletion-repeat = Прихована відповідь (та сама картка)
editing-couldnt-record-audio-have-you-installed = Не вдається записати звук. Чи встановлено у Вас «lame»?
editing-customize-card-templates = Змінити шаблон картки
editing-customize-fields = Змінити поля
editing-cut = Вирізати
editing-double-click-image = двічі клацніть зображення
editing-double-click-to-expand = Натисніть двічі, щоб показати
editing-double-click-to-collapse = Натисніть двічі, щоб приховати
editing-edit-current = Редагувати поточну
editing-edit-html = Редагувати HTML
editing-fields = Поля
editing-indent = Збільшити відступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти до міток з  Ctrl+Shift+T
editing-justify = Обгрунтовати
editing-latex = LaTeX
editing-latex-equation = Рівняння LaTeX
editing-latex-math-env = Математичне оточення LaTeX
editing-mathjax-block = MathJax блок
editing-mathjax-chemistry = MathJax для хімії
editing-mathjax-inline = MathJax в рядку
editing-mathjax-placeholder = Натисніть { $accept }, щоб прийняти, { $newline } для нового рядка.
editing-media = Медіа-файли
editing-ordered-list = Впорядкований список
editing-outdent = Зменшити відступ
editing-paste = Вставити
editing-record-audio = Записати авдіо
editing-remove-formatting = Видалити форматування
editing-restore-original-size = Повернути початковий розмір
editing-select-remove-formatting = Оберіть форматування до видалення
editing-show-duplicates = Показати дублікати
editing-subscript = Нижній індекс
editing-superscript = Верхній індекс
editing-tags = Мітки
editing-tags-add = Додати мітку
editing-tags-copy = Копіювати мітки
editing-tags-remove = Видалити мітки
editing-tags-select-all = Обрати всі мітки
editing-text-color = Колір тексту
editing-text-highlight-color = Колір підсвічення тексту
editing-to-make-a-cloze-deletion-on = Для створення картки з тестом з пробілами по існуючій нотатці, спочатку потрібно змінити її тип на тип тесту з пробілами командою "Редагування>Змінити тип нотатки..."
editing-toggle-html-editor = Перемикач HTML редактора
editing-toggle-visual-editor = Перемикач візуального редактора
editing-toggle-sticky = Перемикач прикріплення
editing-expand = Показати
editing-collapse = Приховати
editing-expand-field = Показати поле
editing-collapse-field = Приховати поле
editing-underline-text = Підкреслений текст
editing-unordered-list = Невпорядкований список
editing-warning-cloze-deletions-will-not-work = Увага! Тести з пробілами не спрацюють, поки ви не зміните тип вгорі на Тест з пробілами.
editing-mathjax-preview = Передперегляд MathJax
editing-close-html-tags = Автоматично закривати HTML теґи
editing-from-clipboard = З буфера обміну
editing-alignment = Групування
editing-equations = Рівняння
editing-no-image-found-on-clipboard = У буфері обміну не знайдено зображення.
editing-image-occlusion-mode = Режим скритого  зображення
editing-image-occlusion-zoom-out = Зменшення
editing-image-occlusion-zoom-in = Збільшення
editing-image-occlusion-zoom-reset = Скинути масштаб
editing-image-occlusion-toggle-translucent = Перемкнути прозорість
editing-image-occlusion-delete = Видалити
editing-image-occlusion-duplicate = Дублювати
editing-image-occlusion-group = Групувати вибір
editing-image-occlusion-ungroup = Розгрупувати вибір
editing-image-occlusion-select-all = Виділити все
editing-image-occlusion-alignment = Групування
editing-image-occlusion-align-left = Вирівняти ліворуч
editing-image-occlusion-align-h-center = Відцентрувати горизонтально
editing-image-occlusion-align-right = Вирівняти праворуч
editing-image-occlusion-align-top = Вирівняти зверху
editing-image-occlusion-align-v-center = Відцентрувати вертикально
editing-image-occlusion-align-bottom = Вирівняти нижню частину
editing-image-occlusion-select-tool = Вибрати
editing-image-occlusion-zoom-tool = Збільшення
editing-image-occlusion-rectangle-tool = Прямокутник
editing-image-occlusion-ellipse-tool = Овал
editing-image-occlusion-polygon-tool = Багатокутник
editing-image-occlusion-text-tool = Текст
editing-image-occlusion-toggle-mask-editor = Перемкнути редактор масок
editing-image-occlusion-reset = Скинути скриття зображення
editing-image-occlusion-confirm-reset = Ви впевнені, що бажаєте скинути скриття зображення?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Редактор HTML
