exporting-all-decks = Усі колоди
exporting-anki-20-deck = Колода Anki 2.0
exporting-anki-collection-package = Пакунок колекції Anki
exporting-anki-deck-package = Сторінка колод Anki
exporting-cards-in-plain-text = Картки з неформатованим текстом
exporting-collection = колекція
exporting-collection-exported = Колекцію експортовано.
exporting-couldnt-save-file = Не вдалося зберегти файл: { $val }
exporting-export = Експорт ...
exporting-export-format = <b>Формат експорту </b>:
exporting-include = <b>Включити</b>:
exporting-include-html-and-media-references = Включити HTML і медіа посилання
exporting-include-media = Включити медіа-файли
exporting-include-scheduling-information = Включити інформацію про розклад
exporting-include-tags = Включити мітки
exporting-notes-in-plain-text = Нотатки у неформатованому тексті
exporting-selected-notes = Вибрані нотатки
