preferences-anki-21-scheduler-beta = Anki 2.1 планувальник (бета)
preferences-automatically-sync-on-profile-openclose = Автоматична синхронізація при відкритті/закритті профілю
preferences-backups = Резервні копії
preferences-backups2 = резервні копії
preferences-backupsanki-will-create-a-backup-of = <b>Резервні копії</b><br>Anki створюватиме резервну копію вашої колекції кожного разу при закритті або синхронізації.
preferences-basic = Базова
preferences-change-deck-depending-on-note-type = Змінити колоду в залежності від типу нотатки
preferences-changes-will-take-effect-when-you = Зміни застосуються коли Ви перезавантажинти Anki.
preferences-hardware-acceleration-faster-may-cause-display = Апаратне прискорення (швидше, але може викликати проблеми зображення)
preferences-hours-past-midnight = годин(и) після опівночі
preferences-interface-language = Мова інтерфейсу:
preferences-interrupt-current-audio-when-answering = Зупиняти відтворення звуку після відповіді
preferences-keep = Зберігати до
preferences-learn-ahead-limit = Ліміт карток для вивчення наперед на
preferences-mins = хвилин(а)
preferences-network = Синхронізація
preferences-next-day-starts-at = Наступний день починається через
preferences-night-mode = Нічний режим
preferences-note-media-is-not-backed-up = Увага: Медіа-файли не включено до резервної копії. Для певності періодично робіть резервну копію вашої теки з файлами Anki самостійно.
preferences-on-next-sync-force-changes-in = Повна примусова одностороння синхронізація при наступному запуску
preferences-paste-clipboard-images-as-png = Вставити зображення із буфера обміну у форматі PNG
preferences-paste-without-shift-key-strips-formatting = Вставлення без shift прибирає форматування
preferences-please-restart-anki-to-complete-language = Перезапустіть Anki для завершення зміни мови.
preferences-preferences = Налаштування
preferences-scheduling = Змінити розклад
preferences-show-next-review-time-above-answer = Показувати час наступного повторення над кнопками відповіді
preferences-show-play-buttons-on-cards-with = Показати кнопку «Програти» на картках із звуком
preferences-show-remaining-card-count-during-review = Показувати кількість карток, що залишилися, під час повторення
preferences-some-settings-will-take-effect-after = Деякі налаштування вступлять в силу лише після перезапуску Anki.
preferences-synchronisation = <b>Синхронізація</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронізацію</b><br> Зараз вимкнено; щоб її увімкнути, натисніть кнопку синхронізації в головному вікні.
preferences-synchronize-audio-and-images-too = Синхронізувати також медіа-файли
preferences-this-will-reset-any-cards-in = Буде скинуто усі картки, які в процесі навчання, очищено фільтровані колоди і змінено версію планувальника. Продовжити?
preferences-timebox-time-limit = Встановити ліміт таймера
preferences-when-adding-default-to-current-deck = Додавати у поточну колоду за замовчуванням
