profiles-anki-could-not-read-your-profile = Anki не може прочитати дані Вашого профілю. Розміри вікна та Ваші дані для входу для синхронізації загублено.
profiles-anki-could-not-rename-your-profile = Anki не вдалося перейменувати ваш профіль, оскільки не вдалося перейменувати теку профілю на диску. Переконайтеся, що у вас є дозвіл на запис до теки Документи/Anki і що інші програми не мають доступ до тек ваших профілів і спробуйте знову.
profiles-folder-already-exists = Тека вже існує.
profiles-open = Відкрити
profiles-open-backup = Відкривання резервної копії…
profiles-please-remove-the-folder-and = Будь ласка, видаліть теку { $val } і повторіть спробу.
profiles-profile-corrupt = Профіль пошкоджено.
profiles-profiles = Профілі
profiles-quit = Вийти
profiles-user-1 = Користувач 1
