studying-again = Знову
studying-all-buried-cards = Всі відкладені картки
studying-audio-5s = Звук -5 секунд
studying-audio-and5s = Звук +5 секунд
studying-buried-siblings = Відкладані пов'язані
studying-bury = Поховати
studying-bury-card = Поховати картку
studying-bury-note = Поховати нотатку
studying-card-buried = Картку поховано
studying-card-suspended = Картку відкладено.
studying-card-was-a-leech = Картка була приставуча.
studying-cards-will-be-automatically-returned-to = Після повторення картки автоматично повертаються до своєї оригінальної колоди.
studying-continue = Продовжити
studying-delete-note = Видалити нотатку
studying-deleting-this-deck-from-the-deck = Після видалення цієї колоди з переліку колод усі залишкові картки буде повернуто до їхньої оригінальної колоди.
studying-easy = Легко
studying-edit = Редагування
studying-empty = Спорожнити
studying-finish = Завершено
studying-flag-card = Встановити прапорець
studying-good = Пам'ятаю
studying-hard = тяжко
studying-it-has-been-suspended = Відкладено.
studying-manually-buried-cards = Вручну відкладені картки
studying-mark-note = Позначити запис
studying-more = Більше
studying-no-cards-are-due-yet = Поки нема очікуваних карток.
studying-note-buried = Нотатку поховано.
studying-note-suspended = Нотатку відкладено.
studying-pause-audio = Призупинити звук
studying-please-run-toolsempty-cards = Виконайте команду " Інструменти>Порожні картки"
studying-record-own-voice = Записати власний голос
studying-replay-own-voice = Прослухати ще раз власний голос
studying-show-answer = ВІДОБРАЗИТИ ВІДПОВІДЬ
studying-space = Пробіл
studying-study-now = Вчити зараз
studying-suspend = Відкласти
studying-suspend-note = Відкласти нотатку
studying-this-is-a-special-deck-for = Це - спеціальна колода для навчання поза встановленим графіком.
studying-to-review = Повторит
studying-type-answer-unknown-field = Введення  відповіді з клавіатури: невідоме поле { $val }
studying-unbury = Розкопати
studying-you-havent-recorded-your-voice-yet = Ви ще не записали ваш голос.
