actions-add = Přidat
actions-blue-flag = Modrý příznak
actions-cancel = Zrušit
actions-choose = Zvolit
actions-close = Zavřít
actions-copy = Kopírovat
actions-custom-study = Vlastní studium
actions-decks = Balíky
actions-delete = Smazat
actions-export = Exportovat
actions-filter = Filtrovat
actions-green-flag = Zelený příznak
actions-help = Nápověda
actions-import = Importovat
actions-manage = Spravovat...
actions-name = Název:
actions-new = Nové
actions-new-name = Nový název:
actions-options = Možnosti
actions-options-for = Možnosti pro { $val }
actions-orange-flag = Oranžový příznak
actions-preview = Náhled
actions-rebuild = Znovu sestavit
actions-red-flag = Červený příznak
actions-rename = Přejmenovat
actions-rename-deck = Přejmenovat balík
actions-rename-tag = Přejmenovat štítek
actions-remove-tag = Odstranit štítek
actions-replay-audio = Přehrát zvuk
actions-reposition = Změnit pořadí
actions-save = Uložit
actions-search = Hledat
actions-shortcut-key = Zkratka: { $val }
actions-suspend-card = Odložit kartu
actions-set-due-date = Nastavit datum zkoušení
actions-forget = Zapomenout
