editing-add-media = Přidat média
editing-an-error-occurred-while-opening = Při otvírání { $val } došlo k chybě
editing-attach-picturesaudiovideo-f3 = Připojit obrázky/zvuk/video (F3)
editing-bold-text-ctrlandb = Tučný text (Ctrl+B)
editing-cards = Karty
editing-change-colour-f8 = Změnit barvu (F8)
editing-cloze-deletion-ctrlandshiftandc = Doplňovačka (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Zvuk nebylo možné nahrát. Máte nainstalovaný „lame“?
editing-customize-card-templates-ctrlandl = Přizpůsobit šablony karet (Ctrl+L)
editing-customize-fields = Přizpůsobit pole
editing-cut = Vyjmout
editing-edit-current = Upravit tuto kartu
editing-edit-html = Upravit HTML
editing-fields = Pole
editing-html-editor = HTML editor
editing-italic-text-ctrlandi = Kurzíva (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Skočit na štítky přes Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Rovnice v LaTeXu
editing-latex-math-env = Matem. proměnná LaTeXu
editing-media = Média
editing-paste = Vložit
editing-record-audio-f5 = Nahrát zvuk (F5)
editing-remove-formatting-ctrlandr = Odstranit formátování (Ctrl+R)
editing-set-foreground-colour-f7 = Nastavit barvu popředí (F7)
editing-show-duplicates = Zobrazit duplikáty
editing-subscript-ctrland = Dolní index (Ctrl+=)
editing-superscript-ctrlandand = Horní index (Ctrl++)
editing-tags = Štítky
editing-to-make-a-cloze-deletion-on = Chcete-li přidat doplňovačku do existující poznámky, musíte její typ nejdřív změnit na doplňovačku přes „Poznámky > Změnit typ poznámky“.
editing-underline-text-ctrlandu = Podtržený text (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Pozor, doplňovačky nebudou fungovat, dokud nezměníte typ výše na Doplňovačku.
