editing-actual-size = Přepnout skutečnou velikost
editing-add-media = Přidat média
editing-align-left = Zarovnat vlevo
editing-align-right = Zarovnat vpravo
editing-an-error-occurred-while-opening = Při otvírání { $val } došlo k chybě
editing-attach-picturesaudiovideo = Připojit obrázky/zvuk/video
editing-bold-text = Tučný text
editing-cards = Karty
editing-center = Na střed
editing-change-color = Změnit barvu
editing-cloze-deletion = Doplňovačka
editing-couldnt-record-audio-have-you-installed = Zvuk nebylo možné nahrát. Máte nainstalovaný „lame“?
editing-customize-card-templates = Přizpůsobit šablony karet
editing-customize-fields = Přizpůsobit pole
editing-cut = Vyjmout
editing-edit-current = Upravit tuto kartu
editing-edit-html = Upravit HTML
editing-fields = Pole
editing-float-left = Obtékání zprava
editing-float-right = Obtékání zleva
editing-float-none = Bez obtékání
editing-html-editor = HTML editor
editing-indent = Zvětšit odsazení
editing-italic-text = Kurzíva
editing-jump-to-tags-with-ctrlandshiftandt = Skočit na štítky přes Ctrl+Shift+T
editing-justify = Do bloku
editing-latex = LaTeX
editing-latex-equation = Rovnice v LaTeXu
editing-latex-math-env = Matem. proměnná LaTeXu
editing-mathjax-block = MathJax blok
editing-mathjax-chemistry = MathJax chemie
editing-mathjax-inline = MathJax inline
editing-mathjax-placeholder = Stiskněte { $accept } pro potvrzení, { $newline } pro nový řádek.
editing-media = Média
editing-ordered-list = Číslovaný seznam
editing-outdent = Zmenšit odsazení
editing-paste = Vložit
editing-record-audio = Nahrát zvuk
editing-remove-formatting = Odstranit formátování
editing-set-text-color = Nastavit barvu textu
editing-set-text-highlight-color = Nastavit barvu zvýraznění textu
editing-show-duplicates = Zobrazit duplikáty
editing-subscript = Dolní index
editing-superscript = Horní index
editing-tags = Štítky
editing-to-make-a-cloze-deletion-on = Chcete-li přidat doplňovačku do existující poznámky, musíte její typ nejdřív změnit na doplňovačku přes „Poznámky > Změnit typ poznámky“.
editing-toggle-sticky = Přepnout přichycení
editing-underline-text = Podtržený text
editing-unordered-list = Odrážkový seznam
editing-warning-cloze-deletions-will-not-work = Pozor, doplňovačky nebudou fungovat, dokud nezměníte typ výše na Doplňovačku.

## You don't need to translate these strings, as they will be replaced with different ones soon.

