editing-add-media = Přidat média
editing-align-left = Zarovnat vlevo
editing-align-right = Zarovnat vpravo
editing-an-error-occurred-while-opening = Při otvírání { $val } došlo k chybě
editing-attach-picturesaudiovideo = Připojit obrázky/zvuk/video
editing-bold-text = Tučný text
editing-cards = Karty
editing-center = Na střed
editing-change-color = Změnit barvu
editing-cloze-deletion = Doplňovačka
editing-couldnt-record-audio-have-you-installed = Zvuk nebylo možné nahrát. Máte nainstalovaný „lame“?
editing-customize-card-templates = Přizpůsobit šablony karet
editing-customize-fields = Přizpůsobit pole
editing-cut = Vyjmout
editing-edit-current = Upravit tuto kartu
editing-edit-html = Upravit HTML
editing-fields = Pole
editing-html-editor = HTML editor
editing-indent = Zvětšit odsazení
editing-italic-text = Kurzíva
editing-jump-to-tags-with-ctrlandshiftandt = Skočit na štítky přes Ctrl+Shift+T
editing-justify = Do bloku
editing-latex = LaTeX
editing-latex-equation = Rovnice v LaTeXu
editing-latex-math-env = Matem. proměnná LaTeXu
editing-media = Média
editing-ordered-list = Číslovaný seznam
editing-outdent = Zmenšit odsazení
editing-paste = Vložit
editing-record-audio = Nahrát zvuk
editing-remove-formatting = Odstranit formátování
editing-set-foreground-color = Nastavit barvu popředí
editing-show-duplicates = Zobrazit duplikáty
editing-subscript = Dolní index
editing-superscript = Horní index
editing-tags = Štítky
editing-to-make-a-cloze-deletion-on = Chcete-li přidat doplňovačku do existující poznámky, musíte její typ nejdřív změnit na doplňovačku přes „Poznámky > Změnit typ poznámky“.
editing-underline-text = Podtržený text
editing-unordered-list = Odrážkový seznam
editing-warning-cloze-deletions-will-not-work = Pozor, doplňovačky nebudou fungovat, dokud nezměníte typ výše na Doplňovačku.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Tučný text (Ctrl+B)
editing-italic-text-ctrlandi = Kurzíva (Ctrl+I)
editing-underline-text-ctrlandu = Podtržený text (Ctrl+U)
editing-subscript-ctrland = Dolní index (Ctrl+=)
editing-superscript-ctrlandand = Horní index (Ctrl++)
editing-remove-formatting-ctrlandr = Odstranit formátování (Ctrl+R)
editing-record-audio-f5 = Nahrát zvuk (F5)
editing-attach-picturesaudiovideo-f3 = Připojit obrázky/zvuk/video (F3)
editing-cloze-deletion-ctrlandshiftandc = Doplňovačka (Ctrl+Shift+C)
editing-change-colour-f8 = Změnit barvu (F8)
editing-set-foreground-colour-f7 = Nastavit barvu popředí (F7)
editing-customize-card-templates-ctrlandl = Přizpůsobit šablony karet (Ctrl+L)
