exporting-all-decks = Všechny balíky
exporting-anki-20-deck = Anki 2.0 balík
exporting-anki-collection-package = Balík Anki kolekce
exporting-anki-deck-package = Balík Anki
exporting-cards-in-plain-text = Karty jako prostý text
exporting-collection = kolekce
exporting-collection-exported = Kolekce exportována.
exporting-couldnt-save-file = Nelze uložit soubor: { $val }
exporting-export = Exportovat...
exporting-export-format = <b>Formát pro Export</b>:
exporting-include = <b>Zahrnout</b>:
exporting-include-html-and-media-references = Zahrnout HTML a odkazy na média
exporting-include-media = Zahrnout média
exporting-include-scheduling-information = Zachovat informace o plánování
exporting-include-tags = Zahrnout štítky
exporting-notes-in-plain-text = Poznámka jako prostý text
exporting-selected-notes = Vybrané poznámky
