preferences-automatically-sync-on-profile-openclose = Automaticky synchronizovat při otevření a zavření profilu
preferences-backups = Zálohy
preferences-backups2 = zálohy
preferences-backupsanki-will-create-a-backup-of = <b>Zálohy</b><br>Anki vytvoří zálohu kolekce pokaždé, když se zavře nebo synchronizuje.
preferences-basic = Základní
preferences-change-deck-depending-on-note-type = Změnit balík v závislosti na typu poznámky
preferences-changes-will-take-effect-when-you = Změny se projeví až po restartování Anki.
preferences-hours-past-midnight = hodin po půlnoci
preferences-interface-language = Jazyk rozhraní:
preferences-interrupt-current-audio-when-answering = Po odpovědi přerušit aktuální audio
preferences-keep = Zachovat
preferences-learn-ahead-limit = Učit se navíc
preferences-mins = minut
preferences-network = Síť
preferences-next-day-starts-at = Další den začíná v
preferences-night-mode = Noční režim
preferences-note-media-is-not-backed-up = Upozornění: Média se nezálohují. Prosím vytvořte si pravidelné zálohy vašeho adresáře Anki.
preferences-on-next-sync-force-changes-in = Při příští synchronizaci vynutit změny v jednom směru
preferences-paste-clipboard-images-as-png = Vložit obrázek ze schránky jako PNG
preferences-paste-without-shift-key-strips-formatting = Vložit bez klávesy shift bez formátování
preferences-periodically-sync-media = Pravidelně synchronizovat multimédia
preferences-please-restart-anki-to-complete-language = Pro dokončení změny jazyka prosím Anki restartujte.
preferences-preferences = Předvolby
preferences-scheduling = Plánování
preferences-show-learning-cards-with-larger-steps = Zobrazit karty k učení s delšími kroky před opakováním
preferences-show-next-review-time-above-answer = Zobrazovat čas do příštího opakování nad tlačítky
preferences-show-play-buttons-on-cards-with = Zobrazovat tlačítka přehrát na kartách, které obsahují audio
preferences-show-remaining-card-count-during-review = Zobrazovat počet zbývajících karet během opakování
preferences-some-settings-will-take-effect-after = Některá nastavení se projeví až po restartu Anki.
preferences-synchronisation = <b>Synchronizace</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronizace</b><br> Neni momentálně povolena; pro zapnutí kliknětě na tlačítko „Synchronizace“ v hlavním okně.
preferences-synchronize-audio-and-images-too = Synchronizovat i obrázky a zvuky
preferences-this-will-reset-any-cards-in = To obnoví všechny karty v procesu učení, vyprázdní filtrované balíky a změní verzi plánovače. Pokračovat?
preferences-timebox-time-limit = Limit pro časový box
preferences-user-interface-size = Velikost uživatelského rozhraní
preferences-when-adding-default-to-current-deck = Při přidávání standardně nastaven aktuální balík
preferences-you-can-restore-backups-via-fileswitch = Můžete obnovit ze zálohy přes Soubor > Přepnout profil.
preferences-legacy-timezone-handling = Zastaralé zpracování časového pásma (zabugované, ale požadováno pro AnkiDroid <= 2.14)
