profiles-anki-could-not-read-your-profile = Anki nemohl přečíst vaše profilová data. Velikosti oken a vaše přihlašovací informace k synchronizaci byly zapomenuty.
profiles-anki-could-not-rename-your-profile = Anki nemohl přejmenovat Váš profil, protože nešlo přejmenovat složku profilu na disku. Oveřte si, zda máte právo pro zápis do složky Dokumenty/Anki a žádný jiný program právě nepoužívá složku Vašeho profilu a zkuste to znova.
profiles-folder-already-exists = Adresář již existuje.
profiles-open = Otevřít
profiles-open-backup = Otevřít zálohu...
profiles-please-remove-the-folder-and = Odstraňte prosím složku { $val } a zkuste to znova.
profiles-profiles = Profily
profiles-quit = Ukončit
profiles-user-1 = Uživatel 1
