adding-add-shortcut-ctrlandenter = 新增 (快速鍵: Ctrl+Enter)
adding-added = 已新增
adding-close-and-lose-current-input = 關閉並放棄當前輸入?
adding-edit = 編輯「{ $val }」
adding-history = 歷史記錄
adding-note-deleted = (筆記已刪除)
adding-shortcut = 快速鍵: { $val }
adding-the-first-field-is-empty = 第一個欄位是空的。
adding-you-have-a-cloze-deletion-note = 您有克漏字筆記類型，但尚無任何克漏字空格，確定要繼續？
