browsing-add-notes = 新增筆記...
browsing-add-tags = 新增標籤
browsing-add-tags2 = 新增標籤...
browsing-added-today = 今天新增的
browsing-addon = 附加元件
browsing-again-today = 今天按「重來」的
browsing-all-card-types = 所有卡片類型
browsing-all-fields = 所有欄位
browsing-answer = 答案
browsing-any-cards-mapped-to-nothing-will = 空白卡片會被刪除，而筆記如果沒有在卡片上也會遺失。您確定要繼續嗎？
browsing-any-flag = 任何旗標
browsing-browser-appearance = 卡片瀏覽器外觀
browsing-browser-options = 卡片瀏覽器選項
browsing-buried = 已暫停
browsing-card = 卡片
browsing-card-list = 卡片清單
browsing-card-state = 卡片狀態
browsing-cards-cant-be-manually-moved-into = 卡片無法手動移動到篩選牌組
browsing-change-deck = 變更牌組
browsing-change-deck2 = 變更牌組...
browsing-change-note-type = 變更筆記類型
browsing-change-note-type2 = 變更筆記類型...
browsing-change-to = 變更 { $val } 到:
browsing-clear-unused = 清理未使用的
browsing-clear-unused-tags = 清理未使用的標籤
browsing-created = 建立日期
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = 當前牌組
browsing-current-note-type = 當前筆記類型:
browsing-delete-notes = 刪除筆記
browsing-delete-tags = 刪除標籤
browsing-duplicate = 重複
browsing-ease = 容易程度
browsing-end = 結束
browsing-enter-tags-to-add = 輸入要新增的標籤:
browsing-enter-tags-to-delete = 輸入要刪除的標籤:
browsing-filter = 篩選...
browsing-filtered = (已篩選)
browsing-find = <b>搜尋</b>
browsing-find-and-replace = 搜尋並取代
browsing-find-duplicates = 尋找重複項目
browsing-first-card = 第一張卡片
browsing-flag = 旗標
browsing-font = <b>字型</b>:
browsing-font-size = <b>字型大小</b>:
browsing-found-as-across-bs = 在 %(b)s 中找到 %(a)s 。
browsing-home = 首頁
browsing-ignore-case = 忽略大小寫
browsing-in = <b>位於</b>:
browsing-interval = 間隔
browsing-last-card = 最後一張卡片
browsing-learning = (學習中)
browsing-line-size = <b>線條大小</b>:
browsing-manage-note-types = 管理筆記類型...
browsing-move-cards = 移動卡片
browsing-move-cards-to-deck = 移動卡片到牌組:
browsing-nd-names = %(n)d: %(name)s
browsing-new = (新卡片)
browsing-new-note-type = 新的筆記類型:
browsing-no-flag = 沒有旗標
browsing-note = 筆記
browsing-notes-tagged = 已對筆記貼上標籤。
browsing-nothing = 無
browsing-only-new-cards-can-be-repositioned = 僅新卡片能調整順序。
browsing-optional-filter = 可選篩選器:
browsing-override-back-template = 覆寫背面模板:
browsing-override-font = 覆寫字型:
browsing-override-front-template = 覆寫正面模板:
browsing-place-at-end-of-new-card = 排到新卡片佇列之後
browsing-place-in-review-queue-with-interval = 移到複習佇列中的間隔:
browsing-please-give-your-filter-a-name = 請為您的篩選器命名:
browsing-please-select-cards-from-only-one = 請僅從一種筆記類型選取卡片。
browsing-preview-selected-card = 預覽已選取的卡片 ({ $val })
browsing-question = 問題
browsing-queue-bottom = 佇列底端: { $val }
browsing-queue-top = 佇列頂端: { $val }
browsing-randomize-order = 隨機順序
browsing-remove-current-filter = 移除當前篩選器...
browsing-remove-from-your-saved-searches = 是否將{ $val }從您已儲存的搜尋中移除？
browsing-remove-tags = 移除標籤...
browsing-replace-with = <b>取代為</b>
browsing-reposition = 移動順序...
browsing-reposition-new-cards = 調整新卡片順序
browsing-reschedule = 重新排程
browsing-save-current-filter = 儲存當前篩選器...
browsing-search-in = 搜尋範圍:
browsing-search-within-formatting-slow = 搜尋 (含格式，較慢)
browsing-shift-position-of-existing-cards = 移動現有卡片的順序
browsing-sidebar = 側邊欄
browsing-sort-field = 排序欄位
browsing-sorting-on-this-column-is-not = 不支援此行排序。請選另一行。
browsing-start-position = 起始順序:
browsing-step = 學習階段:
browsing-studied-today = 今天已學習的
browsing-suspended = 已擱置
browsing-tag-duplicates = 把重複的卡片貼上標籤
browsing-target-field = 目標欄位:
browsing-today = 今天
browsing-toggle-mark = 切換標記
browsing-toggle-suspend = 切換擱置狀態
browsing-treat-input-as-regular-expression = 以正規表達式處理輸入
browsing-type-here-to-search = <在此處輸入文字以搜尋，或按下 Enter 鍵來顯示當前牌組>
browsing-whole-collection = 整個集合
browsing-you-must-have-at-least-one = 至少需要有一行。
browsing-group =
    { $count ->
       *[other] { $count } 種組合
    }
browsing-note-count =
    { $count ->
       *[other] { $count } 則筆記
    }
browsing-note-deleted =
    { $count ->
       *[other] 已刪除{ $count }則筆記。
    }
browsing-window-title = 瀏覽 (已選取 { $selected } 張卡片，共 { $total } 張)
