card-stats-added = 已新增
card-stats-first-review = 首次複習日期
card-stats-latest-review = 最近的複習
card-stats-interval = 間隔
card-stats-ease = 容易度
card-stats-review-count = 待複習卡片
card-stats-lapse-count = 忘記
card-stats-average-time = 平均時間
card-stats-total-time = 總計時間
card-stats-new-card-position = 位置
card-stats-card-template = 卡片類型
card-stats-note-type = 筆記類型
card-stats-deck-name = 牌組
card-stats-note-id = 筆記 ID
card-stats-card-id = 卡片 ID
card-stats-review-log-rating = 評等
card-stats-review-log-type = 類型
card-stats-review-log-date = 日期
card-stats-review-log-time-taken = 時間
card-stats-review-log-type-learn = 新學習卡片
card-stats-review-log-type-review = 複習
card-stats-review-log-type-relearn = 重新學習
card-stats-review-log-type-filtered = 已篩選
card-stats-review-log-type-manual = 手動
