editing-add-media = 新增媒體
editing-an-error-occurred-while-opening = 開啟 { $val } 時發生錯誤
editing-attach-picturesaudiovideo-f3 = 附加圖片/音訊/影片 (F3)
editing-bold-text-ctrlandb = 粗體 (Ctrl+B)
editing-cards = 卡片
editing-change-colour-f8 = 變更顏色 (F8)
editing-cloze-deletion-ctrlandshiftandc = 建立克漏字空格 (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = 無法錄製音訊。請檢查是否已安裝「lame」。
editing-customize-card-templates-ctrlandl = 自訂卡片模板 (Ctrl+L)
editing-customize-fields = 自訂欄位
editing-cut = 剪下
editing-edit-current = 編輯當前卡片
editing-edit-html = 編輯HTML
editing-fields = 欄位
editing-html-editor = HTML編輯器
editing-italic-text-ctrlandi = 斜體 (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = 跳至標籤 (Ctrl+Shift+T)
editing-latex = LaTeX
editing-latex-equation = LaTeX公式
editing-latex-math-env = LaTeX數學環境
editing-mathjax-block = MathJax 區塊
editing-mathjax-chemistry = MathJax 化學
editing-mathjax-inline = 行內 MathJax
editing-media = 媒體
editing-paste = 貼上
editing-record-audio-f5 = 錄製音訊 (F5)
editing-remove-formatting-ctrlandr = 移除格式 (Ctrl+R)
editing-set-foreground-colour-f7 = 設定前景色彩 (F7)
editing-show-duplicates = 顯示重複項目
editing-subscript-ctrland = 下標 (Ctrl+=)
editing-superscript-ctrlandand = 上標 (Ctrl++)
editing-tags = 標籤
editing-to-make-a-cloze-deletion-on = 若要在現有的筆記上建立克漏字空格，您必須先透過「筆記」>「變更筆記類型」將其變更為克漏字類型。
editing-underline-text-ctrlandu = 底線 (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = 警告，除非您將上方的類型改成克漏字，否則克漏字空格將不會生效。
