notetypes-front-field = 正面
notetypes-back-field = 背面
notetypes-add-reverse-field = 新增反向的資料
notetypes-text-field = 文字
notetypes-basic-name = 基本型
notetypes-basic-reversed-name = 基本型(含反向的卡片)
notetypes-basic-optional-reversed-name = 基本型(可選用反向的卡片)
notetypes-cloze-name = 克漏題
notetypes-card-2-name = 卡片 2
notetypes-card-1-name = 卡片 1
