preferences-automatically-sync-on-profile-openclose = 在開啟或關閉設定檔時自動進行同步
preferences-backups = 備份
preferences-backups2 = 個備份
preferences-backupsanki-will-create-a-backup-of = <html><head/><body><p><span style=" font-weight:600;">備份</span><br/>Anki 將在每次關閉時，為您的集合建立備份。</p></body></html>
preferences-basic = 基本
preferences-change-deck-depending-on-note-type = 牌組取決於筆記類型
preferences-changes-will-take-effect-when-you = 變更將在您重新啟動 Anki 時生效。
preferences-hours-past-midnight = 點
preferences-interface-language = 介面語言：
preferences-interrupt-current-audio-when-answering = 回答時中斷當前音訊
preferences-keep = 保留
preferences-learn-ahead-limit = 超前進度
preferences-mins = 分鐘
preferences-network = 網路
preferences-next-day-starts-at = 次日始於凌晨
preferences-night-mode = 夜間模式
preferences-note-media-is-not-backed-up = 注意：媒體不會被備份。保險起見，請定期備份 Anki 資料夾。
preferences-on-next-sync-force-changes-in = 下次同步時，強制單向變更
preferences-paste-clipboard-images-as-png = 以 PNG 格式貼上剪貼簿圖像
preferences-paste-without-shift-key-strips-formatting = 不按 shift 鍵貼上文字時清除格式
preferences-periodically-sync-media = 定期同步媒體
preferences-please-restart-anki-to-complete-language = 請重啟 Anki 完成語言變更。
preferences-preferences = 偏好設定
preferences-scheduling = 排程
preferences-show-learning-cards-with-larger-steps = 先顯示學習階段比複習卡間隔更長的學習中卡片
preferences-show-next-review-time-above-answer = 在回答按鈕上顯示下次複習時間
preferences-show-play-buttons-on-cards-with = 在卡片上顯示音訊播放按鈕
preferences-show-remaining-card-count-during-review = 複習時顯示剩餘卡片數量
preferences-some-settings-will-take-effect-after = 部分設定在重新啟動 Anki 後才會生效。
preferences-synchronisation = <b>同步處理</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同步處理</b><br> 現在尚未啟用；請按一下主視窗的同步鈕來啟用。
preferences-synchronize-audio-and-images-too = 同步音訊與圖像
preferences-this-will-reset-any-cards-in = 這會重設任何學習中的卡片、清除篩選牌組以及變更排程器版本。是否繼續？
preferences-timebox-time-limit = 計時器設定
preferences-user-interface-size = 使用者介面大小
preferences-when-adding-default-to-current-deck = 新增時，預設加入當前牌組
preferences-you-can-restore-backups-via-fileswitch = 您可以透過「檔案」>「切換設定檔」來恢復備份。
preferences-legacy-timezone-handling = 舊版時區處理（易出錯，但 AnkiDroid 2.14 及以下版本必須使用）
