preferences-automatically-sync-on-profile-openclose = 打開/關閉設定檔時自動同步
preferences-backups = 備份
preferences-basic = 基本
preferences-change-deck-depending-on-note-type = 牌組取決於筆記類型
preferences-changes-will-take-effect-when-you = 更動將在重新啟動 Anki 後生效。
preferences-hours-past-midnight = 點
preferences-interface-language = 介面語言：
preferences-interrupt-current-audio-when-answering = 回答時中斷當前音訊
preferences-learn-ahead-limit = 超前進度
preferences-mins = 分鐘
preferences-network = 網路
preferences-next-day-starts-at = 次日始於凌晨
preferences-note-media-is-not-backed-up = 注意：媒體不會被備份。保險起見，請定期備份 Anki 資料夾。
preferences-on-next-sync-force-changes-in = 下次同步時，強制單向更動
preferences-paste-clipboard-images-as-png = 貼上圖像時，將其轉換為 PNG 格式
preferences-paste-without-shift-key-strips-formatting = 貼上文字時自動清除格式，無需按下 shift 鍵
preferences-periodically-sync-media = 定期同步媒體
preferences-please-restart-anki-to-complete-language = 請重啟 Anki 完成語言更改。
preferences-preferences = 偏好設定
preferences-scheduling = 排程
preferences-show-learning-cards-with-larger-steps = 先顯示學習階段比複習卡間隔更長的學習中卡片
preferences-show-next-review-time-above-answer = 在回答按鈕上顯示下次複習時間
preferences-show-play-buttons-on-cards-with = 在卡片上顯示音訊播放按鈕
preferences-show-remaining-card-count-during-review = 複習時顯示剩餘卡片數量
preferences-some-settings-will-take-effect-after = 部分設定在重新啟動 Anki 後才會生效。
preferences-synchronisation = <b>同步處理</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同步處理</b><br> 現在尚未啟用；請按一下主視窗的同步鈕來啟用。
preferences-synchronize-audio-and-images-too = 同步音訊與圖像
preferences-timebox-time-limit = 計時器設定
preferences-user-interface-size = 使用者介面大小
preferences-when-adding-default-to-current-deck = 新增的筆記預設加入當前牌組
preferences-you-can-restore-backups-via-fileswitch = 你可以透過「檔案」>「切換設定檔」來回復備份。
preferences-legacy-timezone-handling = 舊版時區處理 (易出錯，但 AnkiDroid 2.14 及以下版本必須使用)
preferences-default-search-text = 預設搜尋文字
preferences-default-search-text-example = 例如：'deck:current '
preferences-theme-label = 主題：{ $theme }
preferences-theme-follow-system = 跟隨系統設定
preferences-theme-light = 淺色
preferences-theme-dark = 深色
preferences-v3-scheduler = V3 排程器
preferences-ignore-accents-in-search = 搜尋時忽略字母的變音符號 (速度較慢)
preferences-backup-explanation = Anki 會定期備份你的集合。Anki 會不定時刪除 2 天以前的備份以節省硬碟空間。
preferences-daily-backups = 保留備份 (每天):
preferences-weekly-backups = 保留備份 (每週):
preferences-monthly-backups = 保留備份 (每月):
preferences-minutes-between-backups = 自動備份間隔 (分鐘):
