profiles-anki-could-not-read-your-profile = Anki無法讀取您的設定檔資料。視窗大小和您的同步登入詳細資訊已遺失。
profiles-anki-could-not-rename-your-profile = 由於無法重新命名硬碟上設定檔的資料夾，所以無法重新命名設定檔。請在確認您擁有寫入到 Document/Anki 的權限以及沒有其他程式在讀取此資料夾後重試。
profiles-folder-already-exists = 資料夾已存在。
profiles-open = 開啟
profiles-open-backup = 開啟備份...
profiles-please-remove-the-folder-and = 請移除資料夾 { $val } 然後重試。
profiles-profile-corrupt = 設定檔損毀
profiles-profiles = 設定檔
profiles-quit = 離開
profiles-user-1 = 使用者 1
