profiles-anki-could-not-read-your-profile = Anki 無法讀取您的設定檔資料。視窗大小和您的同步登入詳細資訊已遺失。
profiles-anki-could-not-rename-your-profile = 由於無法重新命名硬碟上設定檔的資料夾，所以無法重新命名設定檔。請在確認您擁有寫入到 Document/Anki 的權限以及沒有其他程式在讀取此資料夾後重試。
profiles-folder-already-exists = 資料夾已存在。
profiles-open = 開啟
profiles-open-backup = 開啟備份...
profiles-please-remove-the-folder-and = 請移除資料夾 { $val } 然後重試。
profiles-profile-corrupt = 設定檔損毀
profiles-profiles = 設定檔
profiles-quit = 離開
profiles-user-1 = 使用者 1
profiles-confirm-lang-choice = 確定要以 { $lang } 來顯示 Anki 的介面嗎？
profiles-could-not-create-data-folder = 無法建立儲存 Anki 資料的資料夾。請參閱使用手冊中的檔案位置 (File Locations) 章節，並確保該位置不為唯讀。
profiles-prefs-corrupt-title = 偏好設定損毀
profiles-prefs-file-is-corrupt = Anki 的 prefs21.db 檔案已損毀並被重新建立。若您曾使用多個設定檔，請以相同的名稱新增設定檔來回復卡片。
profiles-profile-does-not-exist = 要求的設定檔不存在。
