actions-add = Hinzufügen
actions-all-selected = Alle ausgewählten
actions-any-selected = Eins der ausgewählten
actions-cancel = Abbrechen
actions-choose = Auswählen
actions-close = Schließen
actions-copy = Kopieren
actions-create-copy = Kopie erstellen
actions-custom-study = Benutzerdefiniertes Lernen
actions-decks = Stapelübersicht
actions-decrement-value = Wert verringern
actions-delete = Löschen
actions-export = Exportieren
actions-filter = Filter
actions-help = Hilfe
actions-increment-value = Wert erhöhen
actions-import = Importieren
actions-manage = Verwalten …
actions-name = Name:
actions-new = Neu
actions-new-name = Neuer Name:
actions-options = Optionen
actions-options-for = Optionen für { $val }
actions-preview = Vorschau
actions-rebuild = Neu erstellen
actions-rename = Umbenennen
actions-rename-deck = Stapel umbenennen
actions-rename-tag = Schlagwort umbenennen
actions-rename-with-parents = Mit übergeordneten Elementen umbenennen
actions-remove-tag = Schlagwort entfernen
actions-replay-audio = Erneut abspielen
actions-reposition = Position ändern
actions-save = Speichern
actions-search = Suche
actions-select = Auswählen
actions-shortcut-key = Tastenkürzel: { $val }
actions-suspend-card = Karte aussetzen
actions-set-due-date = Fälligkeitsdatum bestimmen
actions-answer-card = Karte beantworten
actions-unbury-unsuspend = Zurückstellen/Aussetzen aufheben
actions-add-deck = Stapel hinzufügen
actions-add-note = Notiz hinzufügen
actions-update-tag = Schlagwort ändern
actions-update-note = Notiz ändern
actions-update-card = Karte ändern
actions-update-deck = Stapel ändern
actions-forget-card = Karte vergessen
actions-build-filtered-deck = Stapel zusammenstellen
actions-add-notetype = Notiztyp hinzufügen
actions-remove-notetype = Notiztyp entfernen
actions-update-notetype = Notiztyp ändern
actions-update-config = Konfiguration ändern
actions-card-info = Kartenstatistik
actions-previous-card-info = Vorherige Kartenstatistik
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...

## Flags

actions-flag-number = Markierung { $number }
actions-flag-red = Rot
actions-flag-orange = Orange
actions-flag-green = Grün
actions-flag-blue = Blau
actions-flag-pink = Pink
actions-flag-turquoise = Türkis
actions-flag-purple = Lila
actions-set-flag = Markierung setzen
actions-nothing-to-undo = Nichts zum Zurücknehmen
actions-nothing-to-redo = Nichts zum Wiederherstellen
