actions-add = Hinzufügen
actions-blue-flag = blaue Markierung
actions-cancel = Abbrechen
actions-choose = Auswählen
actions-close = Schließen
actions-copy = Kopieren
actions-custom-study = Benutzerdefiniertes Lernen
actions-decks = Stapelübersicht
actions-delete = Löschen
actions-export = Exportieren
actions-filter = Filter
actions-green-flag = grüne Markierung
actions-help = Hilfe
actions-import = Importieren
actions-manage = Verwalten …
actions-name = Name:
actions-new = Neu
actions-new-name = Neuer Name:
actions-options = Optionen
actions-options-for = Optionen für { $val }
actions-orange-flag = orange Markierung
actions-preview = Vorschau
actions-rebuild = Neu erstellen
actions-red-flag = rote Markierung
actions-rename = Umbenennen
actions-rename-deck = Stapel umbenennen
actions-rename-tag = Schlagwort umbenennen
actions-replay-audio = Erneut abspielen
actions-reposition = Position ändern
actions-save = Speichern
actions-search = Suche
actions-shortcut-key = Tastenkürzel: { $val }
actions-suspend-card = Karte aussetzen
