card-stats-added = Hinzugefügt
card-stats-first-review = Erstmals wiederholt
card-stats-latest-review = Zuletzt wiederholt
card-stats-interval = Intervall
card-stats-ease = Leichtigkeit
card-stats-review-count = Wiederholungen
card-stats-lapse-count = Fehlversuche
card-stats-average-time = Durchschnittliche Zeit
card-stats-total-time = Gesamtzeit
card-stats-new-card-position = Positionsnummer
card-stats-card-template = Kartentyp
card-stats-note-type = Notiztyp
card-stats-deck-name = Stapel
card-stats-preset = Stapeloptionengruppe
card-stats-note-id = Notiz-ID
card-stats-card-id = Karten-ID
card-stats-review-log-rating = Wertung
card-stats-review-log-type = Typ
card-stats-review-log-date = Datum
card-stats-review-log-time-taken = Zeit
card-stats-review-log-type-learn = Lernen
card-stats-review-log-type-review = Wiederholen
card-stats-review-log-type-relearn = Wiedererlernen
card-stats-review-log-type-filtered = Auswahlstapel
card-stats-review-log-type-manual = Manuell
card-stats-review-log-type-rescheduled = Umgeplant
card-stats-review-log-elapsed-time = Verstrichene Zeit
card-stats-no-card = (Keine Karte zum Anzeigen.)
card-stats-custom-data = Benutzerdefinierte Daten
card-stats-fsrs-stability = Stabilität
card-stats-fsrs-difficulty = Schwierigkeit
card-stats-fsrs-retrievability = Abrufbarkeit
card-stats-fsrs-forgetting-curve-title = Vergessenskurve
card-stats-fsrs-forgetting-curve-first-week = Erste Woche
card-stats-fsrs-forgetting-curve-first-month = Erster Monat
card-stats-fsrs-forgetting-curve-first-year = Erstes Jahr
card-stats-fsrs-forgetting-curve-all-time = Gesamte Zeit

## Window Titles

card-stats-current-card = Aktuelle Karte ({ $context })
card-stats-previous-card = Vorherige Karte ({ $context })
