card-stats-added = Hinzugefügt
card-stats-first-review = Erstmals wiederholt
card-stats-latest-review = Letzte Prüfung
card-stats-interval = Intervall
card-stats-ease = Leichtigkeit
card-stats-review-count = Wiederholungen
card-stats-lapse-count = Fehlschläge
card-stats-average-time = Durchschnittliche Zeit
card-stats-total-time = Gesamtzeit
card-stats-new-card-position = Position
card-stats-card-template = Kartentyp
card-stats-note-type = Notiztyp
card-stats-deck-name = Stapel
card-stats-note-id = Notizkennung
card-stats-card-id = Kartenkennung
