editing-add-media = Medien hinzufügen
editing-an-error-occurred-while-opening = Beim Öffnen von { $val } ist ein Fehler aufgetreten
editing-attach-picturesaudiovideo-f3 = Bilder/Audio/Video anfügen (F3)
editing-bold-text-ctrlandb = Fett ausgezeichneter Text (Strg+B)
editing-cards = Karten
editing-change-colour-f8 = Farbe ändern (F8)
editing-cloze-deletion-ctrlandshiftandc = Lückentext (Strg+Umschalt+C)
editing-couldnt-record-audio-have-you-installed = Die Audioaufnahme konnte nicht durchgeführt werden. Haben Sie die Software 'lame' installiert?
editing-customize-card-templates-ctrlandl = Vorlagen für Karten anpassen (Strg+L)
editing-customize-fields = Felder anpassen
editing-cut = Ausschneiden
editing-edit-current = Angezeigte Karte bearbeiten
editing-edit-html = HTML eingeben
editing-fields = Felder
editing-html-editor = HTML-Editor
editing-italic-text-ctrlandi = Kursiv ausgezeichneter Text (Strg+I)
editing-jump-to-tags-with-ctrlandshiftandt = Mit Strg+Umschalt+T zu den Schlagwörtern springen
editing-latex = LaTeX
editing-latex-equation = LaTeX-Formel
editing-latex-math-env = LaTeX-Mathematikumgebung
editing-mathjax-block = Abgesetzes MathJax-Element
editing-mathjax-chemistry = MathJax-Chemieformel
editing-mathjax-inline = Inzeiliges MathJax-Element
editing-media = Medien
editing-paste = Einfügen
editing-record-audio-f5 = Audio aufnehmen (F5)
editing-remove-formatting-ctrlandr = Formatierung entfernen (Strg+R)
editing-set-foreground-colour-f7 = Vordergrundfarbe festlegen (F7)
editing-show-duplicates = Doppelte anzeigen
editing-subscript-ctrland = Tiefgestellter Text (Strg+=)
editing-superscript-ctrlandand = Hochgestellter Text (Strg++)
editing-tags = Schlagwörter
editing-to-make-a-cloze-deletion-on = Um einen Lückentext zu einer bereits vorhandenen Notiz hinzuzufügen, muss dieser erst der Notiztyp Lückentext zugewiesen werden. Dazu wählen Sie oben links in diesem Menü: 'Bearbeiten > Notiztyp ändern'
editing-underline-text-ctrlandu = Text unterstreichen (Strg+U)
editing-warning-cloze-deletions-will-not-work = Achtung! Lückentext wird nur korrekt angezeigt, wenn oben als Notiztyp »Lückentext« gewählt wird.
