fields-add-field = Feld hinzufügen
fields-delete-field-from = Feld aus { $val } entfernen?
fields-editing-font = Schriftart festlegen
fields-field = Feld:
fields-field-name = Feldname:
fields-fields-for = Felder für { $val }
fields-font = Schrift:
fields-new-position-1 = Neue Position (1 … { $val }):
fields-notes-require-at-least-one-field = Notizen benötigen mindestens ein Feld.
fields-remember-last-input-when-adding = Beim Erstellen einer neuen Notiz den Inhalt aus der zuvor erstellten Notiz übernehmen
fields-reverse-text-direction-rtl = Textrichtung umkehren
fields-size = Größe:
fields-sort-by-this-field-in-the = In der Kartenverwaltung nach diesem Feld sortieren
fields-that-field-name-is-already-used = Dieser Feldname ist schon vergeben.
fields-name-first-letter-not-valid = Der Feldname sollte nicht mit #, ^ oder / beginnen.
fields-name-invalid-letter = Der Feldname sollte kein :, ", { "{" } oder { "}" } enthalten.
