notetypes-front-field = Vorderseite
notetypes-back-field = Rückseite
notetypes-add-reverse-field = Gegenrichtung hinzufügen
notetypes-text-field = Text
notetypes-basic-name = Einfach
notetypes-basic-reversed-name = Einfach (beide Richtungen)
notetypes-basic-optional-reversed-name = Einfach (eine oder zwei Richtungen)
notetypes-cloze-name = Lückentext
notetypes-basic-type-answer-name = Einfach (Antwort eintippen)
notetypes-card-2-name = Karte 2
notetypes-card-1-name = Karte 1
