preferences-automatically-sync-on-profile-openclose = Beim Öffnen/Schließen eines Profils automatisch synchronisieren
preferences-backups = Sicherungskopien
preferences-backups2 = Sicherungskopien
preferences-backupsanki-will-create-a-backup-of = <html><head/><body><p><span style=" font-weight:600;">Sicherungskopien</span><br/>Jedes Mal, wenn Anki geöffnet oder synchronisiert wird, erstellt es eine Sicherungskopie Ihrer Sammlung.</p></body></html>
preferences-basic = Einfach
preferences-change-deck-depending-on-note-type = Stapel abhängig vom Notiztyp zuweisen
preferences-changes-will-take-effect-when-you = Die Änderungen werden nach einem Neustart von Anki wirksam.
preferences-hours-past-midnight = Stunden nach Mitternacht
preferences-interface-language = Sprache der Benutzeroberfläche:
preferences-interrupt-current-audio-when-answering = Audiowiedergabe beim Antworten unterbrechen
preferences-keep = Behalten
preferences-learn-ahead-limit = Grenzwert für vorgezogenes Lernen
preferences-mins = Min.
preferences-network = Netzwerk
preferences-next-day-starts-at = Neuer Tag beginnt um
preferences-night-mode = Nachtmodus
preferences-note-media-is-not-backed-up = Achtung: Von Medien wird keine Sicherungskopie erstellt. Bitte erstellen Sie daher sicherheitshalber regelmäßig Kopien des Anki-Ordners.
preferences-on-next-sync-force-changes-in = Bei der nächsten Synchronisation Änderungen in eine Richtung erzwingen
preferences-paste-clipboard-images-as-png = Bilder aus der Zwischenablage im PNG-Bildformat einfügen
preferences-paste-without-shift-key-strips-formatting = Text aus der Zwischenablage ohne Formatierung einfügen
preferences-periodically-sync-media = Medien regelmäßig synchronisieren
preferences-please-restart-anki-to-complete-language = Bitte starten sie Anki neu um die Änderung der Sprache abzuschließen.
preferences-preferences = Einstellungen
preferences-scheduling = Zeitplanung
preferences-show-learning-cards-with-larger-steps = Lernkarten mit größeren Lernstufen vor Wiederholungskarten zeigen
preferences-show-next-review-time-above-answer = Zeit für nächste Wiederholung über Antworttaste anzeigen
preferences-show-play-buttons-on-cards-with = Wiedergabesteuerelemente auf Karten mit Audiodateien anzeigen
preferences-show-remaining-card-count-during-review = Zähler für verbleibende Karten beim Lernen anzeigen
preferences-some-settings-will-take-effect-after = Einige Einstellungen werden erst nach einem Neustart von Anki wirksam.
preferences-synchronisation = <b>Synchronisierung</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronisierung</b><br> Im Moment nicht aktiviert; bitte im Hauptfenster den »Synchronisieren«-Knopf klicken, um sie zu aktivieren.
preferences-synchronize-audio-and-images-too = Tonaufnahmen und Bilder ebenfalls synchronisieren
preferences-timebox-time-limit = Zeitbegrenzung für Sitzungen
preferences-user-interface-size = Schriftgröße der Benutzeroberfläche
preferences-when-adding-default-to-current-deck = Beim Hinzufügen aktuellen Stapel als Standard festlegen
preferences-you-can-restore-backups-via-fileswitch = Sie können eine Sicherungskopie über den Menüpunkt Datei > "Profil wechseln" wiederherstellen.
preferences-legacy-timezone-handling = Veralteter Umgang mit Zeitzonen (fehleranfällig, aber für AnkiDroid <= 2.14 vorausgesetzt)
preferences-default-search-text = Standardmäßig eingestellter Suchtext
preferences-default-search-text-example = z.B. 'deck:current'
preferences-theme-label = Theme: { $theme }
preferences-theme-follow-system = System befolgen
preferences-theme-light = Hell
preferences-theme-dark = Dunkel
preferences-v3-scheduler = V3-Zeitplaner
preferences-ignore-accents-in-search = Akzente in der Suche ignorieren (langsamer)
preferences-backup-explanation = Anki erstellt regelmäßig Sicherungskopien Ihrer Sammlung, wenn es beendet wird. Sicherungskopien, die älter als 2 Tage sind, werden ggf. gelöscht, um nicht zu viel Speicherplatz zu belegen.
preferences-daily-backups = Beizubehaltende tägliche Sicherungskopien:
preferences-weekly-backups = Beizubehaltende wöchentliche Sicherungskopien:
preferences-monthly-backups = Beizubehaltende monatliche Sicherungskopien:
preferences-minutes-between-backups = Minuten zwischen automatisch erstellten Sicherungskopien:
