actions-add = Thêm
actions-cancel = Hủy
actions-choose = Chọn
actions-close = Đóng
actions-copy = Chép
actions-custom-study = Học Tùy biến
actions-decks = Bộ thẻ
actions-delete = Xóa
actions-export = Xuất
actions-filter = Lọc
actions-help = Trợ giúp
actions-import = Nhập
actions-name = Tên:
actions-new = Mới
actions-new-name = Tên mới:
actions-options = Tuỳ chọn
actions-options-for = Tùy chọn bộ thẻ { $val }
actions-preview = Xem trước
actions-rebuild = Tái tạo
actions-rename = Đổi tên
actions-rename-deck = Đổi tên Bộ thẻ
actions-replay-audio = Phát lại Âm thanh
actions-reposition = Định vị lại
actions-search = Tìm
actions-shortcut-key = Phím tắt: { $val }
actions-suspend-card = Dừng Thẻ
