browsing-add-tags = Thêm Nhãn
browsing-added-today = Đã thêm Hôm nay
browsing-again-today = Học lại Hôm nay
browsing-all-fields = Mọi Trường tin
browsing-answer = Trả lời
browsing-any-cards-mapped-to-nothing-will = Tất cả những thẻ không được ánh xạ sẽ bị xóa. Nếu một phiếu không còn thẻ nào thì phiếu đó cũng sẽ bị xóa. Bạn có chắc chắn muốn tiếp tục không?
browsing-browser-appearance = Thể hiện Trình duyệt
browsing-browser-options = Tùy chọn Trình duyệt
browsing-card = Thẻ
browsing-card-list = Danh sách Thẻ
browsing-cards-cant-be-manually-moved-into = Không thể di chuyển thủ công thẻ vào bộ thẻ lọc.
browsing-change-deck = Đổi Bộ thẻ
browsing-change-note-type = Đổi Kiểu Phiếu
browsing-change-note-type2 = Đổi Kiểu Phiếu...
browsing-change-to = Đổi { $val } thành:
browsing-created = Đã tạo
browsing-current-deck = Bộ Thẻ Hiện hành
browsing-current-note-type = Kiểu phiếu hiện hành:
browsing-delete-notes = Xóa Phiếu
browsing-delete-tags = Xóa Nhãn
browsing-duplicate = trùng
browsing-ease = Độ dễ
browsing-end = Kết thúc
browsing-enter-tags-to-add = Nhập nhãn cần thêm:
browsing-enter-tags-to-delete = Nhập nhãn cần xóa:
browsing-filtered = (lọc)
browsing-find = <b>Tìm</b>:
browsing-find-and-replace = Tìm và Thay
browsing-find-duplicates = Tìm Thẻ trùng
browsing-first-card = Thẻ Đầu
browsing-font = <b>Kiểu chữ</b>:
browsing-font-size = <b>Cỡ chữ</b>:
browsing-found-as-across-bs = Tìm thấy %(a)s trên %(b)s.
browsing-home = Gốc
browsing-ignore-case = Bỏ qua phân biệt hoa thường
browsing-in = <b>Trong</b>:
browsing-interval = Khoảng cách
browsing-last-card = Thẻ Cuối
browsing-learning = (đang học)
browsing-line-size = <b>Kích thước đường gạch</b>:
browsing-manage-note-types = Quản lý các Kiểu Phiếu...
browsing-move-cards = Di chuyển Thẻ
browsing-move-cards-to-deck = Di chuyển thẻ vào bộ thẻ:
browsing-new = (mới)
browsing-new-note-type = Kiểu phiếu mới:
browsing-note = Phiếu
browsing-notes-tagged = Đã gắn nhãn cho phiếu.
browsing-nothing = Không gì
browsing-only-new-cards-can-be-repositioned = Chỉ có thể định vị lại thẻ mới.
browsing-override-back-template = Thay thế kiểu mẫu mặt sau:
browsing-override-font = Thay thế kiểu chữ:
browsing-override-front-template = Thay thế kiểu mẫu mặt trước:
browsing-place-at-end-of-new-card = Đặt vào cuối hàng đợi thẻ mới
browsing-place-in-review-queue-with-interval = Đặt vào hàng đợi ôn tập với khoảng cách giữa:
browsing-please-select-cards-from-only-one = Vui lòng chọn thẻ chỉ thuộc một kiểu ghi chú.
browsing-preview-selected-card = Xem trước Thẻ Được chọn ({ $val })
browsing-question = Câu hỏi
browsing-queue-bottom = Cuối hàng đợi: { $val }
browsing-queue-top = Đầu hàng đợi: { $val }
browsing-randomize-order = Trộn ngẫu nhiên thứ tự
browsing-replace-with = <b>Thay Bằng</b>:
browsing-reposition = Định vị lại...
browsing-reposition-new-cards = Định vị lại Thẻ Mới
browsing-reschedule = Lập lịch lại
browsing-search-within-formatting-slow = Tìm trong định dạng (chậm)
browsing-shift-position-of-existing-cards = Dịch chuyển vị trí các thẻ hiện hữu
browsing-sort-field = Trường Sắp xếp
browsing-sorting-on-this-column-is-not = Không hỗ trợ sắp xếp trên cột này. Xin vui lòng chọn cột khác.
browsing-start-position = Vị trí bắt đầu:
browsing-step = Bước:
browsing-studied-today = Đã học Hôm nay
browsing-suspended = Dừng
browsing-tag-duplicates = Nhãn Trùng
browsing-target-field = Trường tin đích:
browsing-today = Hôm nay
browsing-treat-input-as-regular-expression = Xử lý dữ liệu nhập theo dạng biểu thức chính quy
browsing-type-here-to-search = <gõ vào đây để tìm kiếm; nhấn Enter để hiển thị bộ thẻ hiện hành>
browsing-whole-collection = Cả Bộ sưu tập
browsing-you-must-have-at-least-one = Bạn phải có ít nhất một cột.
browsing-group = { $count ->
   *[other] { $count } nhóm
  }
browsing-note-count = { $count ->
   *[other] { $count } phiếu
  }
browsing-note-deleted = { $count ->
   *[other] Đã xóa { $count } phiếu.
  }
browsing-selected = { $count ->
   *[other] { $count } được chọn
  }
