decks-add-new-deck-ctrlandn = Thêm Bộ thẻ Mới (Ctrl+N)
decks-are-you-sure-you-wish-to = Bạn có chắc chắn muốn xóa { $val }?
decks-build = Tạo
decks-cards-selected-by = thẻ được chọn theo
decks-create-deck = Tạo Bộ thẻ
decks-deck = Bộ thẻ
decks-decreasing-intervals = Khoảng cách giảm dần
decks-delete-deck = Xóa Bộ thẻ
decks-filter = Lọc:
decks-get-shared = Lấy Bộ thẻ Chia sẻ
decks-import-file = Nhập Tập tin
decks-increasing-intervals = Khoảng cách tăng dần
decks-latest-added-first = Thẻ thêm mới nhất trước
decks-limit-to = Giới hạn trong
decks-minutes = phút
decks-most-lapses = Nhiều lần hỏng nhất
decks-name-for-deck = Tên cho bộ thẻ:
decks-new-deck-name = Tên bộ thẻ mới:
decks-no-deck = [không có bộ thẻ]
decks-oldest-seen-first = Thẻ lâu nhất trước
decks-order-added = Thứ tự thêm vào
decks-order-due = Thứ tự đến hạn
decks-please-select-something = Xin vui lòng chọn một cái gì đó.
decks-random = Ngẫu nhiên
decks-relative-overdueness = Tình trạng đến hạn liên quan
decks-reschedule-cards-based-on-my-answers = Lập lịch lại thẻ các dựa trên cách tôi trả lời ở bộ thẻ này
decks-study = Học tập
decks-study-deck = Học Bộ thẻ
decks-the-provided-search-did-not-match = Yêu cầu tìm kiếm bạn cung cấp không khớp với bất kỳ thẻ nào. Bạn có muốn sửa lại không?
decks-it-has-card = { $count ->
   *[other]  Có { $count } thẻ.
  }
