notetypes-front-field = Mặt trước
notetypes-back-field = Mặt sau
notetypes-add-reverse-field = Thêm Thẻ ngược
notetypes-text-field = Văn bản
notetypes-basic-name = Cơ bản
notetypes-basic-reversed-name = Cơ bản (với thẻ ngược)
notetypes-basic-optional-reversed-name = Cơ bản (thẻ ngược tùy chọn)
notetypes-cloze-name = Điền chỗ trống
notetypes-card-2-name = Thẻ 2
notetypes-card-1-name = Thẻ 1
notetypes-add = Thêm: { $val }
notetypes-add-note-type = Thêm Kiểu Phiếu
notetypes-cards = Thẻ...
notetypes-clone = Nhân bản: { $val }
notetypes-copy = bản sao { $val }
notetypes-delete-this-note-type-and-all = Xóa kiểu phiếu này và tất cả các thẻ đi kèm?
notetypes-delete-this-unused-note-type = Xóa kiểu phiếu thừa này?
notetypes-fields = Trường tin...
notetypes-footer = Chân trang
notetypes-header = Đầu trang
notetypes-note-types = Các Kiểu Phiếu
notetypes-options = Tùy chọn...
notetypes-please-add-another-note-type-first = Xin đưa thêm một kiểu phiếu khác trước.
notetypes-type = Kiểu
