preferences-automatically-sync-on-profile-openclose = Tự động đồng bộ khi đóng/mở hồ sơ
preferences-backups = Sao lưu
preferences-backups2 = sao lưu
preferences-backupsanki-will-create-a-backup-of = <b>Sao lưu</b><br>Anki sẽ sao lưu bộ sưu tập của bạn mỗi khi thoát hoặc thực hiện đồng bộ.
preferences-basic = Cơ bản
preferences-change-deck-depending-on-note-type = Đổi bộ thẻ theo như kiểu phiếu
preferences-hours-past-midnight = giờ qua nửa đêm
preferences-interface-language = Ngôn ngữ Giao diện:
preferences-keep = Giữ
preferences-learn-ahead-limit = Giới hạn học trước
preferences-mins = phút
preferences-network = Mạng
preferences-next-day-starts-at = Ngày kế tiếp bắt đầu lúc
preferences-note-media-is-not-backed-up = Lưu ý: Dữ liệu phương tiện sẽ không được sao lưu. Xin vui lòng sao lưu định kỳ thư mục Anki của bạn để phòng xa.
preferences-on-next-sync-force-changes-in = Ở lần đồng bộ kế tiếp, bắt buộc thay đổi trong một hướng
preferences-paste-clipboard-images-as-png = Dán hình ảnh clipboard với dạng PNG
preferences-preferences = Tùy chỉnh
preferences-scheduling = Lập lịch lại
preferences-show-next-review-time-above-answer = Hiện thời gian ôn tập kế tiếp trên các nút trả lời
preferences-show-remaining-card-count-during-review = Hiện số thẻ còn lại trong lúc ôn tập
preferences-some-settings-will-take-effect-after = Một số thiết lập chỉ có hiệu lực sau khi chạy lại Anki.
preferences-synchronisation = <b>Đồng bộ hóa</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Đồng bộ hóa</b><br> Hiện đang tắt; nhấp nút đồng bộ trong cửa sổ chính để bật đồng bộ.
preferences-synchronize-audio-and-images-too = Đồng bộ cả âm thanh và hình ảnh
preferences-timebox-time-limit = Giới hạn khung thời gian
preferences-when-adding-default-to-current-deck = Khi thêm mới, mặc định thực hiện với bộ thẻ hiện hành
