preferences-automatically-sync-on-profile-openclose = Tự động đồng bộ khi đóng/mở hồ sơ
preferences-backups = Sao lưu
preferences-change-deck-depending-on-note-type = Đổi bộ thẻ theo như kiểu phiếu
preferences-changes-will-take-effect-when-you = Các thay đổi sẽ có hiệu lực khi bạn khởi động lại Anki.
preferences-hours-past-midnight = giờ qua nửa đêm
preferences-language = Ngôn ngữ
preferences-interrupt-current-audio-when-answering = Ngắt âm thanh hiện tại khi trả lời
preferences-learn-ahead-limit = Giới hạn học trước
preferences-mins = phút
preferences-network = Mạng
preferences-next-day-starts-at = Ngày kế tiếp bắt đầu lúc
preferences-on-next-sync-force-changes-in = Ở lần đồng bộ kế tiếp, bắt buộc thay đổi trong một hướng
preferences-paste-clipboard-images-as-png = Dán hình ảnh clipboard với dạng PNG
preferences-paste-without-shift-key-strips-formatting = án mà không cần thay đổi định dạng dải phím
preferences-periodically-sync-media = Định kỳ đồng bộ hóa phương tiện
preferences-please-restart-anki-to-complete-language = Vui lòng khởi động lại Anki để hoàn tất việc thay đổi ngôn ngữ.
preferences-preferences = Tùy chỉnh
preferences-scheduling = Lập lịch lại
preferences-show-learning-cards-with-larger-steps = Hiển thị thẻ học tập với các bước lớn hơn trước khi ôn tập
preferences-show-next-review-time-above-answer = Hiện thời gian ôn tập kế tiếp trên các nút trả lời
preferences-spacebar-rates-card = Trả lời bằng phím cách (hoặc phím Enter)
preferences-show-play-buttons-on-cards-with = Hiển thị nút phát trên thẻ có âm thanh
preferences-show-remaining-card-count = Hiển thị số lượng thẻ còn lại
preferences-some-settings-will-take-effect-after = Một số thiết lập chỉ có hiệu lực sau khi chạy lại Anki.
preferences-tab-synchronisation = Đồng bộ
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Đồng bộ hóa</b><br> Hiện đang tắt; nhấp nút đồng bộ trong cửa sổ chính để bật đồng bộ.
preferences-synchronize-audio-and-images-too = Đồng bộ cả âm thanh và hình ảnh
preferences-timebox-time-limit = Giới hạn khung thời gian
preferences-user-interface-size = Kích thước giao diện người dùng
preferences-when-adding-default-to-current-deck = Khi thêm mới, mặc định thực hiện với bộ thẻ hiện hành
preferences-you-can-restore-backups-via-fileswitch = Bạn có thể khôi phục các bản sao lưu thông qua Tệp> Chuyển đổi Hồ sơ.
preferences-legacy-timezone-handling = Xử lý múi giờ cũ (lỗi, bắt buộc đối với AnkiDroid <= 2.14)
preferences-default-search-text = Mẫu tìm kiếm mặc định
preferences-default-search-text-example = vd. 'bộ thẻ:hiện tại '
preferences-theme = Giao diện
preferences-theme-follow-system = Theo hệ thống
preferences-theme-light = Sáng
preferences-theme-dark = Tối
preferences-v3-scheduler = Bộ lập lịch biểu V3
preferences-ignore-accents-in-search = Bỏ qua dấu câu trong tìm kiếm (chậm hơn)
preferences-reduce-motion = Giảm hiệu ứng động
preferences-appearance = Hiển thị
preferences-editing = Chỉnh sửa
preferences-account = Tài khoản AnkiWeb
preferences-scheduler = Bộ lập lịch biểu
preferences-reset-window-sizes = Đặt lại kích cỡ cửa sổ
preferences-reset-window-sizes-complete = Đã đặt lại vị trí và kích cỡ của các cửa sổ.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Cơ bản
