statistics-due-date = Đến hạn
statistics-due-count = Đến hạn
statistics-cards-per-min = { $cards-per-minute } thẻ / phút
statistics-cards = { $cards } thẻ
statistics-reviews = { $reviews } thẻ ôn tập
statistics-today-title = Hôm nay
statistics-today-again-count = Học lại:
statistics-today-type-counts = Học: { $learnCount }, Ôn: { $reviewCount }, Học lại: { $relearnCount }, Lọc: { $filteredCount }
statistics-today-no-mature-cards = Chưa có thẻ trưởng thành học trong hôm nay.
statistics-today-correct-mature = Số trả lời đúng thẻ trưởng thành: { $correct }/{ $total } ({ $percent }%)
statistics-counts-total-cards = Tổng số thẻ
statistics-counts-new-cards = Mới
statistics-counts-young-cards = Trẻ
statistics-counts-mature-cards = Trưởng thành
statistics-counts-suspended-cards = Dừng
statistics-range-all-time = dòng đời bộ thẻ
statistics-range-deck = bộ thẻ
statistics-range-collection = bộ sưu tập
statistics-range-search = Tìm
statistics-future-due-title = Dự báo
statistics-reviews-title = Ôn tập
statistics-intervals-title = Khoảng cách
statistics-answer-buttons-title = Nút Trả lời
statistics-hours-title = Chia nhỏ Theo giờ
statistics-added-title = Đã thêm
