adding-add-shortcut-ctrlandenter = 追加 (ショートカット: Ctrl+Enter)
adding-added = 追加済み
adding-discard-current-input = 現在の入力内容を破棄しますか？
adding-keep-editing = 編集を続ける
adding-edit = “{ $val }” を編集
adding-history = 履歴
adding-note-deleted = (ノートは削除されました)
adding-shortcut = ショートカット: { $val }
adding-the-first-field-is-empty = 先頭フィールドが空です。
adding-you-have-a-cloze-deletion-note = 穴埋め問題のノートタイプが選択されていますが、穴埋め箇所がありません。続行しますか？
adding-cloze-outside-cloze-notetype = 穴埋めは、穴埋め問題のノートタイプでのみ使用できます。
adding-cloze-outside-cloze-field = 穴埋めは “cloze:” フィルターを使用するフィールドでのみ作成できます。通常は先頭のフィールドです。
