browsing-add-notes = ノートを追加...
browsing-add-tags = タグを追加
browsing-add-tags2 = タグを追加...
browsing-added-today = 今日追加したカード
browsing-addon = アドオン
browsing-again-today = 今日間違えたカード
browsing-all-card-types = 全てのカードタイプ
browsing-all-fields = 全てのフィールド
browsing-answer = 解答
browsing-any-cards-mapped-to-nothing-will = Nothing に設定したカードは削除されます。ノートにカードが残っていない場合は、そのノートが失われます。それでも処理を続行しますか。
browsing-any-flag = フラグあり
browsing-browser-appearance = 検索の表示設定
browsing-browser-options = 検索オプション
browsing-buried = 延期
browsing-card = カード
browsing-card-list = カード一覧
browsing-card-state = カードの状態
browsing-cards-cant-be-manually-moved-into = フィルターデッキには手動でカードを移動できません。
browsing-change-deck = デッキを変更
browsing-change-deck2 = デッキを変更...
browsing-change-note-type = ノートタイプを変更
browsing-change-note-type2 = ノートタイプを変更...
browsing-change-to = { $val } を以下に変更:
browsing-clear-unused = 使用されていないタグを削除
browsing-clear-unused-tags = 使用されていないタグを削除
browsing-created = 作成日
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = 現在のデッキ
browsing-current-note-type = 現在のノートタイプ:
browsing-delete-notes = ノートを削除する
browsing-delete-tags = タグを削除
browsing-duplicate = 重複
browsing-ease = 易しさ
browsing-end = 終り
browsing-enter-tags-to-add = タグを追加する：
browsing-enter-tags-to-delete = タグを削除する：
browsing-filter = フィルター...
browsing-filtered = (フィルター)
browsing-find = <b>検索文字列</b>：
browsing-find-and-replace = 検索して置換
browsing-find-duplicates = 重複を検索
browsing-first-card = 最初のカード
browsing-flag = フラグを付ける
browsing-font = <b>フォント</b>：
browsing-font-size = <b>フォントサイズ</b>：
browsing-found-as-across-bs = { $whole } の中に { $part } が見つかりました。
browsing-home = ホーム
browsing-ignore-case = 大文字小文字を区別しない
browsing-in = <b>対象</b>:
browsing-interval = 間隔
browsing-last-card = 最後のカード
browsing-learning = (基本学習中)
browsing-line-size = <b>行のサイズ</b>:
browsing-manage-note-types = ノートタイプを管理...
browsing-move-cards = カードを移動
browsing-move-cards-to-deck = カードをデッキに移動：
browsing-nd-names = { $num }: { $name }
browsing-new = (新規)
browsing-new-note-type = 変更後のノートタイプ:
browsing-no-flag = フラグなし
browsing-note = ノート
browsing-notes-tagged = ノートにタグを付けました。
browsing-nothing = なし
browsing-only-new-cards-can-be-repositioned = 新規カードだけが表示順を変更できます。
browsing-optional-filter = オプションフィルター：
browsing-override-back-template = 解答のテンプレート:
browsing-override-font = フォント:
browsing-override-front-template = 質問のテンプレート:
browsing-place-at-end-of-new-card = 新規カードの最後に設定
browsing-place-in-review-queue-with-interval = 次の期間内に復習を設定
browsing-please-give-your-filter-a-name = このフィルターに名前を付けてください:
browsing-please-select-cards-from-only-one = 一つのノートタイプからカードを選択してください。
browsing-preview-selected-card = 選択したカードをプレビューする  ({ $val })
browsing-question = 質問
browsing-queue-bottom = 最後: { $val }
browsing-queue-top = 先頭: { $val }
browsing-randomize-order = ランダムに並べ替える
browsing-remove-current-filter = このフィルターを削除
browsing-remove-from-your-saved-searches = フィルター「{ $val }」を削除しますか？
browsing-remove-tags = タグを除去...
browsing-replace-with = <b>置換文字列</b>：
browsing-reposition = 新規カードの表示順序を変更...
browsing-reposition-new-cards = 新規カードの表示順序を変更
browsing-reschedule = スケジュールを変更
browsing-save-current-filter = このフィルターを保存
browsing-search-in = 検索対象：
browsing-search-within-formatting-slow = 書式済みの内容の中まで検索 (速度が低下します)
browsing-shift-position-of-existing-cards = 既存のカードの順序を移動する
browsing-sidebar = サイドバー
browsing-sidebar-filter = サイドバーフィルター
browsing-sort-field = ソートフィールド
browsing-sorting-on-this-column-is-not = この列で並び替えることはできません。別の列を選択してください。
browsing-start-position = 開始位置:
browsing-step = 間隔:
browsing-studied-today = 今日学習したカード
browsing-suspended = 保留
browsing-tag-duplicates = 重複にタグを付ける
browsing-tag-rename-warning-empty = ノートのないタグ名を変更することはできません
browsing-target-field = 対象フィールド:
browsing-today = 今日
browsing-toggle-mark = マークを付ける/除去する
browsing-toggle-suspend = 保留/保留解除 を切り替える
browsing-treat-input-as-regular-expression = 入力条件に正規表現を使う
browsing-whole-collection = コレクション全体
browsing-you-must-have-at-least-one = 最低でも一つの列は必要です。
browsing-group =
    { $count ->
       *[other] { $count } グループ
    }
browsing-note-count =
    { $count ->
       *[other] { $count } 個のノート
    }
browsing-note-deleted =
    { $count ->
       *[other] { $count }個のノートを削除しました。
    }
browsing-window-title = 検索（{ $total }枚のカード中{ $selected }枚を選択中）
