card-templates-changes-will-affect-notes = ここでの内容の変更は、このカードタイプを使用している{ $count }個のノートに影響を与えます。
card-templates-card-type = カードタイプ:
card-templates-front-template = 表面のテンプレート
card-templates-back-template = 裏面のテンプレート
card-templates-template-styling = 書式
card-templates-front-preview = 表面のプレビュー
card-templates-back-preview = 裏面のプレビュー
card-templates-preview-box = プレビュー
card-templates-sample-cloze = これは {"{{c1::"}sample{"}}"} 穴埋め問題です。
