card-stats-added = 追加
card-stats-first-review = 最初の復習
card-stats-latest-review = 直近の復習
card-stats-interval = 間隔
card-stats-ease = 易しさ
card-stats-review-count = 復習
card-stats-lapse-count = 忘却
card-stats-average-time = 平均時間
card-stats-total-time = 合計時間
card-stats-new-card-position = 位置
card-stats-card-template = カードタイプ
card-stats-note-type = ノートタイプ
card-stats-deck-name = デッキ
card-stats-note-id = ノート ID
card-stats-card-id = カード ID
card-stats-review-log-rating = 評価
card-stats-review-log-type = ノートタイプ
card-stats-review-log-date = 日付
card-stats-review-log-time-taken = 時間
card-stats-review-log-type-learn = 基本学習
card-stats-review-log-type-review = 復習
card-stats-review-log-type-relearn = 再基本学習
card-stats-review-log-type-filtered = フィルター
card-stats-review-log-type-rescheduled = スケジュール変更
