decks-add-new-deck-ctrlandn = デッキを新規追加 (Ctrl+N)
decks-build = 作成
decks-cards-selected-by = 枚を、次の順に抜き出す:
decks-create-deck = デッキを作成
decks_create_even_if_empty = このデッキが空でも作成/更新
decks-custom-steps-in-minutes = カスタム学習ステップ（分）
decks-deck = デッキ
decks-decreasing-intervals = 間隔が大きい順
decks-delete-deck = デッキを削除
decks-enable-second-filter = ２つめのフィルターを有効にする
decks-filter = フィルター：
decks-filter-2 = フィルター２
decks-get-shared = 共有デッキをダウンロード
decks-import-file = ファイルをインポート
decks-increasing-intervals = 間隔が小さい順
decks-latest-added-first = 追加時期が新しい順
decks-limit-to = 最大
decks-minutes = 分
decks-most-lapses = 復習での忘却回数が多い順
decks-new-deck-name = 新しいデッキ名
decks-no-deck = [デッキなし]
decks-oldest-seen-first = 前回表示日時が古い順
decks-order-added = 追加した順
decks-order-due = 復習期日が古い順
decks-please-select-something = 何かを選択してください。
decks-random = 無作為
decks-relative-overdueness = 期日超過率が大きい順
decks-repeat-failed-cards-after = 「やり直し」の間隔 (分)
decks-reschedule-cards-based-on-my-answers = このデッキの解答に基づいてカードをスケジュールし直す
decks-study = 学習
decks-study-deck = 学習するデッキを選択
decks-filtered-deck-search-empty = 検索条件に一致するカードがありません。別のフィルターデッキ内にあるカードや休止中のカードが除外されている可能性があります。
decks-unmovable-cards = 除外されたカードをすべて表示
decks-learn-header = 習得中
# The count of cards waiting to be reviewed
decks-review-header = 復習
