editing-actual-size = 実寸表示を切り替える
editing-add-media = メディアを追加
editing-align-left = 左揃え
editing-align-right = 右揃え
editing-an-error-occurred-while-opening = { $val } を開く際にエラーが発生しました。
editing-attach-picturesaudiovideo = 画像・音声・動画を添付
editing-bold-text = 太字
editing-cards = カード
editing-center = 中央揃え
editing-change-color = 色を変更
editing-cloze-deletion = 穴埋めを作成 (新しいカード)
editing-cloze-deletion-repeat = 穴埋めを作成 (同じカード)
editing-copy-image = 画像をコピー
editing-couldnt-record-audio-have-you-installed = 音声を録音できませんでした。“lame” はインストールされていますか？
editing-customize-card-templates = カードテンプレートを編集
editing-customize-fields = フィールドを編集
editing-cut = 切り取り
editing-double-click-image = 画像をダブルクリック
editing-double-click-to-expand = ダブルクリックして展開
editing-double-click-to-collapse = ダブルクリックして折りたたむ
editing-edit-current = 現在のノートを編集
editing-edit-html = HTML を編集
editing-fields = フィールド
editing-float-left = 左に回り込み
editing-float-right = 右に回り込み
editing-float-none = 回り込みなし
editing-indent = インデントを増やす
editing-italic-text = 斜体
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T でタグへ移動
editing-justify = 両端揃え
editing-latex = LaTeX
editing-latex-equation = LaTeX 数式
editing-latex-math-env = LaTeX 数式環境
editing-mathjax-block = MathJax ブロック数式
editing-mathjax-chemistry = MathJax 化学式
editing-mathjax-inline = MathJax インライン数式
editing-mathjax-placeholder = 確定するには { $accept }、改行するには { $newline } を押してください。
editing-media = メディア
editing-open-image = 画像を開く
editing-show-in-folder = フォルダーに表示
editing-ordered-list = 番号付きリスト
editing-outdent = インデントを減らす
editing-paste = 貼り付け
editing-record-audio = 音声を録音
editing-remove-formatting = 書式を削除
editing-restore-original-size = 元のサイズに戻す
editing-select-remove-formatting = 削除する書式を選択
editing-show-duplicates = 重複を表示
editing-subscript = 下付き文字
editing-superscript = 上付き文字
editing-tags = タグ
editing-tag-count = { $count } 個のタグ
editing-tags-add = タグを追加
editing-tags-copy = タグをコピー
editing-tags-remove = タグを削除
editing-tags-select-all = すべてのタグを選択
editing-text-color = 文字色
editing-text-highlight-color = 文字の背景色
editing-to-make-a-cloze-deletion-on = 既存のノートで穴埋めを作成するには、先に [ノート] > [ノートタイプを変更] で穴埋め問題のノートタイプへ変更してください。
editing-toggle-html-editor = HTML エディターに切り替え
editing-toggle-visual-editor = ビジュアルエディターに切り替え
editing-toggle-sticky = 入力内容の保持を切り替える
editing-expand = 展開
editing-collapse = 折りたたむ
editing-expand-field = フィールドを展開
editing-collapse-field = フィールドを折りたたむ
editing-underline-text = 下線
editing-unordered-list = 箇条書きリスト
editing-warning-cloze-deletions-will-not-work = 警告: 画面上部のノートタイプを [穴埋め問題] に変更するまで、穴埋め箇所は機能しません。
editing-mathjax-preview = MathJax プレビュー
editing-shrink-images = 画像を縮小
editing-close-html-tags = HTMLの終了タグを自動で付ける
editing-from-clipboard = クリップボードから
editing-alignment = 配置
editing-equations = 数式
editing-no-image-found-on-clipboard = クリップボードに画像が見つかりません。
editing-image-occlusion-mode = 作成するカードの種類を選択
editing-image-occlusion-zoom-out = 縮小
editing-image-occlusion-zoom-in = 拡大
editing-image-occlusion-zoom-reset = 拡大縮小をリセット
editing-image-occlusion-toggle-translucent = マスク半透明表示の切り替え
editing-image-occlusion-delete = 削除
editing-image-occlusion-duplicate = 複製
editing-image-occlusion-group = 選択対象をグループ化
editing-image-occlusion-ungroup = 選択対象のグループ化を解除
editing-image-occlusion-select-all = すべて選択
editing-image-occlusion-alignment = 選択対象を整列
editing-image-occlusion-align-left = 左揃え
editing-image-occlusion-align-h-center = 左右方向の中央揃え
editing-image-occlusion-align-right = 右揃え
editing-image-occlusion-align-top = 上揃え
editing-image-occlusion-align-v-center = 上下方向の中央揃え
editing-image-occlusion-align-bottom = 下揃え
editing-image-occlusion-select-tool = 選択
editing-image-occlusion-zoom-tool = 画像表示のサイズ・位置の調整
editing-image-occlusion-rectangle-tool = 矩形マスク
editing-image-occlusion-ellipse-tool = 楕円形マスク
editing-image-occlusion-polygon-tool = 多角形マスク
editing-image-occlusion-text-tool = 文字
editing-image-occlusion-fill-tool = 選択した色でマスクを塗りつぶし
editing-image-occlusion-toggle-mask-editor = マスクエディタを表示
editing-image-occlusion-reset = この画像穴埋め問題をリセット
editing-image-occlusion-confirm-reset = 画像を選択する前の初期状態（画像選択用の画面）にリセットします。現在の画像上に追加したマスクや文字だけでなく、その画像自体を表示しなくなります。本当によろしいですか？

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTMLエディタ
