editing-add-media = メディアを追加
editing-an-error-occurred-while-opening = { $val } を開いた時にエラーが発生しました。
editing-attach-picturesaudiovideo-f3 = メディア(画像/音声/動画)を追加 (F3)
editing-bold-text-ctrlandb = 太字 (Ctrl+B)
editing-cards = カード
editing-change-colour-f8 = 色を変更 (F8)
editing-cloze-deletion-ctrlandshiftandc = 穴埋め (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = 音声を録音できませんでした。LAMEを
editing-customize-card-templates-ctrlandl = カードテンプレートをカストマイズする（Ctrl+L）
editing-customize-fields = カスタムフィールド
editing-cut = カット
editing-edit-current = 現在のノートを編集
editing-edit-html = HTML を編集
editing-fields = フィールド
editing-html-editor = HTML エディタ
editing-italic-text-ctrlandi = 斜体 (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T でタグフィールドに移動します。
editing-latex = LaTeX
editing-latex-equation = LaTeX インライン数式
editing-latex-math-env = LaTeX ディスプレイ数式
editing-mathjax-block = MathJaxブロック
editing-mathjax-chemistry = MathJax 化学
editing-mathjax-inline = MathJax インライン
editing-media = メディア
editing-paste = 貼り付け
editing-record-audio-f5 = 音声を録音 (F5)
editing-remove-formatting-ctrlandr = 全ての書式をクリア (Ctrl+R)
editing-set-foreground-colour-f7 = 文字の色を設定 (F7)
editing-show-duplicates = 重複を表示する
editing-subscript-ctrland = 下付き文字 (Ctrl+=)
editing-superscript-ctrlandand = 上付き文字 (Ctrl++)
editing-tags = タグ
editing-to-make-a-cloze-deletion-on = このノートに穴埋め問題を作るには、まず今のノートタイプを穴埋め問題に対応したノートタイプに変更する必要があります。[編集] > [ノートタイプを変更]から、穴埋め問題に対応したノートタイプを選択してください。（Ankiインストール時から付属しているノートタイプのうちでは、「Cloze」が穴埋め問題に対応しています。）
editing-underline-text-ctrlandu = 下線 (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = 注意: 穴埋め問題は上部にある「ノートタイプ」の設定を「Cloze」（穴埋め）タイプに変更するまで機能しません。
