empty-cards-for-note-type = ノートタイプ “{ $notetype }” の空のカード:
empty-cards-count-line = 全 { $existing_count } 枚中 { $empty_count } 枚が空です ({ $template_names })。
empty-cards-window-title = 空のカード
empty-cards-preserve-notes-checkbox = 有効なカードがないノートを残す
empty-cards-delete-button = 削除
empty-cards-not-found = 空のカードはありません。
empty-cards-deleted-count = カードを { $cards } 枚削除しました。
empty-cards-delete-empty-cards = 空のカードを削除
empty-cards-delete-empty-notes = カードがないノートを削除
empty-cards-deleting = 削除しています...
