preferences-automatically-sync-on-profile-openclose = プロファイルを開閉する際に自動的に同期する
preferences-backups = バックアップ
preferences-change-deck-depending-on-note-type = カード追加の時、ノートタイプによってデッキを選択
preferences-changes-will-take-effect-when-you = Ankiを再起動させると変更内容が反映されます。
preferences-hours-past-midnight = 時
preferences-language = 言語
preferences-interrupt-current-audio-when-answering = 質問の音声の再生を解答表示で停止
preferences-learn-ahead-limit = 習得学習の前倒し許容時間
preferences-mins = 分
preferences-network = ネットワーク
preferences-next-day-starts-at = 日付更新時刻
preferences-media-is-not-backed-up = 上記の機能ではメディア（画像／音声／動画）ファイルはバックアップされていません。データの安全のため、 Anki のフォルダのバックアップ（コピー）をご自身で定期的に作成してください。
preferences-on-next-sync-force-changes-in = 次回の同期は、一方向に変更を強制実行する
preferences-paste-clipboard-images-as-png = クリップボード画像をPNG形式で貼り付ける
preferences-paste-without-shift-key-strips-formatting = 貼り付けの際に書式を取り除く（書式を保持したい場合は Shiftキー＋貼り付け）
preferences-periodically-sync-media = 定期的にメディアを同期する
preferences-please-restart-anki-to-complete-language = Ankiを再起動した後、言語が変更されます。
preferences-preferences = 設定
preferences-scheduling = スケジュール
preferences-show-learning-cards-with-larger-steps = 習得中カードのステップを拡大する
preferences-show-next-review-time-above-answer = 次回の学習までの間隔を回答ボタンの上に表示
preferences-spacebar-rates-card = スペースキーまたはエンターキーでも回答
preferences-show-play-buttons-on-cards-with = 音声・動画を含むカードに再生ボタンを表示
preferences-show-remaining-card-count = 残りのカード枚数を表示
preferences-some-settings-will-take-effect-after = Anki を再起動した後に有効になる設定があります。
preferences-tab-synchronisation = 同期
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同期</b><br> 現在有効になっていません。有効にするにはメインウィンドウの同期ボタンを押してください。
preferences-synchronize-audio-and-images-too = 音声と画像も同期する
preferences-timebox-time-limit = タイムボックス（学習時間の目標・区切り）
preferences-user-interface-size = ユーザーインターフェースのサイズ
preferences-when-adding-default-to-current-deck = カード追加の時、現在のデッキを既定にする
preferences-you-can-restore-backups-via-fileswitch = バックアップの復元は、[ファイル] → [プロファイルを切り替える] → [バックアップを開く...] から行うことができます。
preferences-legacy-timezone-handling = 旧型のタイムゾーン処理 (バグあり、ただしAnkiDroid 2.14以前のバージョンでは必須)
preferences-default-search-text = デフォルトの検索文字列
preferences-default-search-text-example = 例：'deck:current '
preferences-theme = テーマ
preferences-theme-follow-system = システムに従う
preferences-theme-light = ライト
preferences-theme-dark = ダーク
preferences-v3-scheduler = V3スケジューラ―
preferences-ignore-accents-in-search = 検索する際にアクセント記号を無視する（検索速度低下）
preferences-backup-explanation = Anki は一定時間（分）ごとにコレクションのバックアップを作成しています。各期間（日／週／月）の代表として保管するバックアップ以外のバックアップは、ディスク領域を空けるために、作成から2日以上経過した後に削除していきます。
preferences-daily-backups = 各日代表のバックアップ保管数（何日分）
preferences-weekly-backups = 各週代表のバックアップ保管数（何週分）
preferences-monthly-backups = 各月代表のバックアップ保管数（何か月分）
preferences-minutes-between-backups = 自動バックアップの間隔（分）
preferences-reduce-motion = モーションを減らす
preferences-reduce-motion-tooltip = ユーザーインターフェースのさまざまなアニメーションやトランザクションを無効にします
preferences-custom-sync-url = セルフホスト同期サーバー
preferences-custom-sync-url-disclaimer = 上級ユーザー向け - 詳細はマニュアルをご確認ください
preferences-hide-top-bar-during-review = 学習画面でトップバーを非表示
preferences-hide-bottom-bar-during-review = 学習画面でボトムバーを非表示
preferences-always = 常に
preferences-full-screen-only = 全画面表示のみ
preferences-appearance = 表示
preferences-general = 一般
preferences-style = スタイル
preferences-review = 学習
preferences-answer-keys = 回答キー
preferences-distractions = 集中の妨げとなる場合の対策
preferences-minimalist-mode = ミニマリストモード
preferences-editing = 編集
preferences-browsing = 検索
preferences-default-deck = デフォルトデッキ
preferences-account = AnkiWebアカウント
preferences-note = 注意
preferences-scheduler = スケジューラー
preferences-user-interface = ユーザーインターフェース
preferences-import-export = インポート／エクスポート
preferences-network-timeout = ネットワークタイムアウト
preferences-reset-window-sizes = ウィンドウのサイズをリセット
preferences-reset-window-sizes-complete = ウィンドウのサイズと位置をリセットしました。
preferences-shortcut-placeholder = 他のショートカットに使用されていないキーを入力するか、空欄（ショートカットなし）にしてください。

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = 基本
preferences-reviewer = Reviewer
preferences-media = メディア
