preferences-automatically-sync-on-profile-openclose = プロファイルを開閉する際に自動的に同期する
preferences-backups = バックアップ
preferences-change-deck-depending-on-note-type = カード追加の時、ノートタイプによってデッキを選択
preferences-changes-will-take-effect-when-you = Ankiを再起動させると変更内容が反映されます。
preferences-hours-past-midnight = 時
preferences-language = 言語
preferences-interrupt-current-audio-when-answering = 解答時に音声を中断する
preferences-learn-ahead-limit = 習得学習の前倒しの限度
preferences-mins = 分
preferences-network = ネットワーク
preferences-next-day-starts-at = 日付更新時刻
preferences-on-next-sync-force-changes-in = 次回の同期は、一方向に変更を強制実行する
preferences-paste-clipboard-images-as-png = クリップボード画像をPNG形式で貼り付ける
preferences-paste-without-shift-key-strips-formatting = Shiftキーなしのペーストで書式を解除
preferences-periodically-sync-media = 定期的にメディアを同期する
preferences-please-restart-anki-to-complete-language = Ankiを再起動した後、言語が変更されます。
preferences-preferences = 設定
preferences-scheduling = スケジュール
preferences-show-learning-cards-with-larger-steps = 習得中カードのステップを拡大する
preferences-show-next-review-time-above-answer = 次回の復習時期を解答ボタンの上に表示する
preferences-show-play-buttons-on-cards-with = オーディオを含むカードに再生ボタンを表示する
preferences-some-settings-will-take-effect-after = Anki を再起動した後に有効になる設定があります。
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>同期</b><br> 現在有効になっていません。有効にするにはメインウィンドウの同期ボタンを押してください。
preferences-synchronize-audio-and-images-too = 音声と画像も同期する
preferences-timebox-time-limit = タイムボックスの時間枠
preferences-user-interface-size = ユーザーインターフェースのサイズ
preferences-when-adding-default-to-current-deck = カード追加の時、現在のデッキを既定にする
preferences-you-can-restore-backups-via-fileswitch = 「ファイル」→「プロファイル切替」でバックアップを復元することができます。
preferences-legacy-timezone-handling = 旧時間帯ハンドリング (バグあり、ただしAnkiDroid 2.14以前のバージョンでは必須)
preferences-default-search-text = ブラウザのデフォルト
preferences-default-search-text-example = 例：'deck:current '
preferences-theme = テーマ
preferences-theme-follow-system = システムに従う
preferences-theme-light = ライト
preferences-theme-dark = ダーク
preferences-v3-scheduler = V3スケジューラ―
preferences-ignore-accents-in-search = 検索する際にアクセント記号を無視する（検索速度低下）
preferences-backup-explanation = Ankiは定期的にあなたのコレクションをバックアップしています。２日以上経過したバックアップは、ディスクスペースを確保するために、順次削除していきます。
preferences-daily-backups = 毎日保存するバックアップの数:
preferences-weekly-backups = 毎週保存するバックアップの数:
preferences-monthly-backups = 毎月保存するバックアップの数:
preferences-minutes-between-backups = 自動バックアップの間隔（分）:
preferences-reduce-motion = モーションを減らす
preferences-reduce-motion-tooltip = ユーザーインターフェースのさまざまなアニメーションやトランザクションを無効にします
preferences-hide-top-bar-during-review = 学習画面でトップバーを非表示
preferences-hide-bottom-bar-during-review = 学習画面でボトムバーを非表示
preferences-appearance = 表示
preferences-general = 一般
preferences-minimalist-mode = ミニマリストモード
preferences-editing = 編集
preferences-user-interface = ユーザーインターフェース

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = 基本
