profiles-anki-could-not-read-your-profile = Anki はプロファイルデータを読み込めませんでした。ウィンドウのサイズと同期用ログイン情報はリセットされました。
profiles-anki-could-not-rename-your-profile = ディスク上のプロファイルフォルダー名を変更できなかったため、Anki はプロファイル名を変更できませんでした。Documents/Anki への書き込み権限があり、ほかのプログラムがプロファイルフォルダーを使用していないことを確認してから、もう一度試してください。
profiles-folder-already-exists = フォルダーはすでに存在します。
profiles-open = 開く
profiles-open-backup = バックアップを開く...
profiles-please-remove-the-folder-and = フォルダー “{ $val }” を削除してから、もう一度試してください。
profiles-profile-corrupt = プロファイルの破損
profiles-profiles = プロファイル
profiles-quit = 終了
profiles-user-1 = ユーザー 1
profiles-confirm-lang-choice = Anki の画面を { $lang } で表示しますか？
profiles-could-not-create-data-folder = Anki はデータフォルダーを作成できませんでした。マニュアルの “ファイルの場所” を参照し、保存先が読み取り専用になっていないことを確認してください。
profiles-prefs-corrupt-title = 環境設定の破損
profiles-prefs-file-is-corrupt = Anki の prefs21.db ファイルが破損していたため、再作成しました。複数のプロファイルを使用していた場合は、カードを復元するため、以前と同じ名前でプロファイルを追加し直してください。
profiles-profile-does-not-exist = 指定されたプロファイルは存在しません。
profiles-creating-backup = バックアップを作成しています...
profiles-backup-created = バックアップを作成しました。
profiles-backup-creation-failed = バックアップを作成できませんでした: { $reason }
profiles-backup-unchanged = 前回のバックアップ以降、変更はありません。
