actions-add = जोड़ें
actions-all-selected = सभी चुन लिया गया है
actions-any-selected = कोई भी चुना हुआ
actions-cancel = रद्द करें
actions-choose = चुनें
actions-close = बंद करें
actions-copy = प्रतिलिपि बनाएँ
actions-create-copy = नकल बनाएं
actions-custom-study = कस्टम अध्ययन
actions-decks = डेक्स
actions-delete = हटायें
actions-export = निर्यात करें
actions-filter = फ़िल्टर करें
actions-help = सहायता
actions-import = आयात करें
actions-manage = प्रबंधित करें...
actions-name = नाम:
actions-new = नया
actions-new-name = नया नाम:
actions-options = विकल्प
actions-options-for = { $val } के लिए विकल्प
actions-preview = पूर्व दर्शन
actions-rebuild = फिर से बनाएँ
actions-rename = पुन: नाम दें
actions-rename-deck = डेक का नाम बदलें
actions-rename-tag = टैग का नाम बदलें
actions-rename-with-parents = माता-पिता के साथ नाम बदलें
actions-remove-tag = टेग निकालें
actions-replay-audio = ऑडियो फिर से चलाएं
actions-reposition = स्थान बदलें
actions-save = सहेजें
actions-search = खोज करें
actions-select = चयन करें
actions-shortcut-key = शॉर्टकट कुंजी: { $val }
actions-suspend-card = काड रद्द करें
actions-set-due-date = नियत तिथि निर्धारित करें
actions-answer-card = उत्तर कार्ड
actions-build-filtered-deck = डेक बनाएँ
actions-add-notetype = नोट टाइप जोड़ें
actions-remove-notetype = नोट का प्रकार हटाएं
actions-update-notetype = नोट का प्रकार अद्यतन करें
actions-update-config = कॉन्फ़िगरेशन अपडेट करें
actions-card-info = कार्ड की जानकारी
actions-previous-card-info = पिछले कार्ड की जानकारी
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...

## Flags

actions-flag-number = { $number } झंडा
actions-flag-red = लाल
actions-flag-orange = संतरा
actions-flag-green = हरा
actions-flag-blue = नीला
actions-flag-pink = गुलाबी
actions-flag-turquoise = फ़िरोज़ा
actions-flag-purple = बैंगनी
actions-set-flag = झंडा सेट करें
