browsing-add-notes = नोट्स जोड़ें...
browsing-add-tags2 = टैगों को जोड़ें...
browsing-add-to-selected-notes = Add to Selected टैगों को जोड़ें...
browsing-remove-from-selected-notes = चयनित नोट्स से हटाएं
browsing-addon = ऐड ऑन

## obsolete; no need to translate

