actions-add = ଯୋଡ଼ନ୍ତୁ
actions-cancel = ବାତିଲ୍
actions-choose = ବାଛନ୍ତୁ
actions-close = ବନ୍ଦ କରନ୍ତୁ
actions-copy = ନକଲ କରନ୍ତୁ
actions-custom-study = ଇଚ୍ଛାରୂପିତ ଅଧ୍ୟୟନ
actions-decks = ଡେକଗୁଡ଼ିକ
actions-delete = ଅପସାରଣ କରନ୍ତୁ
actions-export = ରପ୍ତାନି
actions-filter = ଛାଣନ୍ତୁ
actions-help = ସହାୟତା
actions-import = ଆମଦାନୀ
actions-manage = ପରିଚାଳନା କରନ୍ତୁ...
actions-name = ନାମ:
actions-new = ନୂତନ
actions-new-name = ନୂତନ ନାମ:
actions-options = ବିକଳ୍ପଗୁଡ଼ିକ
actions-options-for = { $val } ପାଇଁ ବିକଳ୍ପଗୁଡ଼ିକ
actions-preview = ପୂର୍ବାବଲୋକନ
actions-rebuild = ପୁନଃନିର୍ମାଣ
actions-rename = ପୁନଃନାମକରଣ କରନ୍ତୁ
actions-rename-deck = ଡେକ୍ କୁ ପୁନଃ ନାମକରଣ କରନ୍ତୁ
actions-rename-tag = ଟ୍ୟାଗକୁ ପୁନଃ ନାମକରଣ କରନ୍ତୁ
actions-remove-tag = ଟ୍ୟାଗ୍ ଅପସାରଣ କରନ୍ତୁ
actions-replay-audio = ଅଡିଓ ପୁଣି ଚଲାନ୍ତୁ
actions-save = ସଞ୍ଚୟ
actions-search = ଖୋଜନ୍ତୁ
actions-shortcut-key = Shortcut key: { $val }
actions-suspend-card = କାର୍ଡ ନିଲମ୍ବିତ କରନ୍ତୁ
actions-forget = ଭୁଲିଯାଅ
actions-answer-card = ଉତ୍ତର କାର୍ଡ
actions-unbury-unsuspend = ସ୍ଥଗିତରୁ ଫେରାଇ ଆଣ/ଅନିଲମ୍ବିତ କରନ୍ତୁ
actions-add-deck = ଡେକ୍ ଯୋଡ଼ନ୍ତୁ
actions-add-note = ନୋଟ୍ ଯୋଡ଼ନ୍ତୁ
actions-update-tag = ଟ୍ୟାଗ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-note = ନୋଟ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-card = କାର୍ଡ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-deck = ଡେକ୍ ଅଦ୍ୟତନ କରନ୍ତୁ
actions-forget-card = କାର୍ଡ ଭୁଲିଯାଆନ୍ତୁ
actions-build-filtered-deck = ଡେକ୍ ନିର୍ମାଣ କରନ୍ତୁ
actions-add-notetype = ନୋଟ୍-ପ୍ରକାର ଯୋଡ଼ନ୍ତୁ
actions-remove-notetype = ନୋଟ୍-ପ୍ରକାର ଅପସାରଣ କରନ୍ତୁ
actions-update-notetype = ନୋଟ୍-ପ୍ରକାର ଅଦ୍ୟତନ କରନ୍ତୁ
actions-update-config = ବିନ୍ୟାସ ଅଦ୍ୟତନ କରନ୍ତୁ

## Flags

actions-flag-number = ପତାକା { $number }
actions-flag-red = ନାଲି
actions-flag-orange = କମଳା
actions-flag-green = ସବୁଜ
actions-flag-blue = ନୀଳ
actions-flag-pink = ଗୋଲାପୀ
actions-flag-turquoise = ଫୀରୋଜା
actions-flag-purple = ବାଇଗଣୀ
actions-set-flag = ପତାକା ନ୍ୟସ୍ତ କରନ୍ତୁ
