adding-add-shortcut-ctrlandenter = ଯୋଡ଼ନ୍ତୁ (ସର୍ଟକଟ୍: ctrl+enter)
adding-added = ଯୋଡ଼ାଗଲା
adding-close-and-lose-current-input = ବନ୍ଦ କରନ୍ତୁ ଏବଂ ସାମ୍ପ୍ରତିକ ଇନପୁଟ୍ ହରାନ୍ତୁ?
adding-edit = "{ $val }" ସମ୍ପାଦନ କରନ୍ତୁ
adding-history = ଇତିବୃତ୍ତି
adding-note-deleted = (ନୋଟ୍ ବିଲୋପ ହୋଇଛି)
adding-shortcut = ସର୍ଟକଟ୍: { $val }
adding-the-first-field-is-empty = ପ୍ରଥମ କ୍ଷେତ୍ର ଖାଲି ଅଛି।
adding-you-have-a-cloze-deletion-note = ଆପଣଙ୍କର ଏକ କ୍ଲୋଜ୍ ଡିଲିଶନ ନୋଟ୍ ପ୍ରକାର ଅଛି କିନ୍ତୁ କୌଣସି କ୍ଲୋଜ୍ ବିଲୋପ କରିନାହାଁନ୍ତି। ଅଗ୍ରଗତି କରିବେ?
