browsing-add-notes = ନୋଟଗୁଡ଼ିକୁ ଯୋଗ କରନ୍ତୁ...
browsing-add-tags = ଟ୍ୟାଗ୍ ଯୋଡ଼ନ୍ତୁ
browsing-add-tags2 = ଟ୍ୟାଗ୍ ଯୋଡ଼ନ୍ତୁ...
browsing-addon = ଆଡ୍-ଅନ୍
browsing-all-card-types = ସମସ୍ତ କାର୍ଡ ପ୍ରକାର
browsing-all-fields = ସମସ୍ତ କ୍ଷେତ୍ର
browsing-answer = ଉତ୍ତର
browsing-any-flag = ଯେକୌଣସି ପତାକା
browsing-browser-appearance = ବ୍ରାଉଜର୍ ଦୃଶ୍ୟ
browsing-browser-options = ବ୍ରାଉଜର୍ ବିକଳ୍ପଗୁଡ଼ିକ
browsing-buried = ସ୍ଥଗିତ ଅଛି
browsing-card = କାର୍ଡ
browsing-card-list = କାର୍ଡ ତାଲିକା
browsing-card-state = କାର୍ଡ ଅବସ୍ଥା
browsing-cards-cant-be-manually-moved-into = କାର୍ଡଗୁଡ଼ିକୁ ହସ୍ତକୃତ ଭାବରେ ଏକ ଛାଣକ ଡେକ୍ ରେ ସ୍ଥାନାନ୍ତରିତ କରାଯାଇପାରିବ ନାହିଁ।
browsing-cards-deleted =
    { $count ->
        [one] { $count }ଟିଏ କାର୍ଡ୍ ବିଲୋପ ହୋଇଛି।
       *[other] { $count }ଟି କାର୍ଡ୍ ବିଲୋପ ହୋଇଛି।
    }
browsing-change-deck = ଡେକ୍ ପରିବର୍ତ୍ତନ କରନ୍ତୁ
browsing-change-deck2 = ଡେକ୍ ପରିବର୍ତ୍ତନ...
browsing-change-note-type = ନୋଟ୍ ପ୍ରକାର ପରିବର୍ତ୍ତନ କରନ୍ତୁ
browsing-change-note-type2 = ନୋଟ୍ ପ୍ରକାର ପରିବର୍ତ୍ତନ...
browsing-change-to = { $val } କୁ ପରିବର୍ତ୍ତନ କରନ୍ତୁ:
browsing-clear-unused = ଅବ୍ୟବହୃତ ସଫା କରନ୍ତୁ
browsing-clear-unused-tags = ଅବ୍ୟବହୃତ ଟ୍ୟାଗଗୁଡ଼ିକ ସଫା କରନ୍ତୁ
browsing-confirm-saved-search-overwrite = { $name } ନାମ ସହିତ ଏକ ସଞ୍ଚିତ ସନ୍ଧାନ ପୂର୍ବରୁ ବିଦ୍ୟମାନ ଅଛି। ଆପଣ ଏହାକୁ ଓଭର୍ ରାଇଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?
browsing-created = ସୃଷ୍ଟି ହୋଇଛି
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = ସାମ୍ପ୍ରତିକ ଡ଼େକ୍
browsing-current-note-type = ସାମ୍ପ୍ରତିକ ନୋଟ୍ ପ୍ରକାର:
browsing-delete-notes = ନୋଟଗୁଡ଼ିକ ବିଲୋପ କରନ୍ତୁ
browsing-delete-tags = ଟ୍ୟାଗଗୁଡ଼ିକ ବିଲୋପ କରନ୍ତୁ
browsing-duplicate = ନକଲ
browsing-ease = ସହଜତା
browsing-end = ଶେଷ
browsing-enter-tags-to-add = ଯୋଡ଼ିବାକୁ ଟ୍ୟାଗଗୁଡ଼ିକ ପ୍ରବେଶ କରନ୍ତୁ:
browsing-enter-tags-to-delete = ବିଲୋପ କରିବାକୁ ଟ୍ୟାଗଗୁଡ଼ିକ ପ୍ରବେଶ କରନ୍ତୁ:
browsing-find = <b>ଖୋଜନ୍ତୁ</b>:
browsing-first-card = ପ୍ରଥମ କାର୍ଡ
browsing-flag = ପତାକା
browsing-home = ଘର
browsing-last-card = ଶେଷ କାର୍ଡ
browsing-move-cards = କାର୍ଡଗୁଡ଼ିକ ଘୁଞ୍ଚାନ୍ତୁ
browsing-nd-names = { $num }: { $name }
browsing-new = (ନୂତନ)
browsing-new-note-type = ନୂତନ ନୋଟ୍ ପ୍ରକାର:
browsing-note = ନୋଟ୍
browsing-nothing = କିଛି ନାହିଁ
browsing-please-give-your-filter-a-name = ଦୟାକରି ଆପଣଙ୍କର ଫିଲ୍ଟରକୁ ଗୋଟିଏ ନାମ ଦିଅନ୍ତୁ:
browsing-question = ପ୍ରଶ୍ନ
browsing-sidebar-expand = ବିସ୍ତାର କରନ୍ତୁ
browsing-sidebar-collapse = ସଂକୋଚନ କରନ୍ତୁ
browsing-today = ଆଜି
