browsing-add-notes = ନୋଟଗୁଡ଼ିକୁ ଯୋଗ କରନ୍ତୁ...
browsing-add-tags = ଟ୍ୟାଗ୍ ଯୋଡ଼ନ୍ତୁ
browsing-all-card-types = ସମସ୍ତ କାର୍ଡ ପ୍ରକାର
browsing-all-fields = ସମସ୍ତ କ୍ଷେତ୍ର
browsing-answer = ଉତ୍ତର
browsing-any-flag = ଯେକୌଣସି ପତାକା
browsing-browser-appearance = ବ୍ରାଉଜର୍ ଦୃଶ୍ୟ
browsing-browser-options = ବ୍ରାଉଜର୍ ବିକଳ୍ପଗୁଡ଼ିକ
browsing-buried = ସ୍ଥଗିତ ଅଛି
browsing-card = କାର୍ଡ
browsing-card-list = କାର୍ଡ ତାଲିକା
browsing-card-state = କାର୍ଡ ଅବସ୍ଥା
browsing-cards-cant-be-manually-moved-into = କାର୍ଡଗୁଡ଼ିକୁ ହସ୍ତକୃତ ଭାବରେ ଏକ ଛାଣକ ଡେକ୍ ରେ ସ୍ଥାନାନ୍ତରିତ କରାଯାଇପାରିବ ନାହିଁ।
browsing-change-deck = ଡେକ୍ ପରିବର୍ତ୍ତନ କରନ୍ତୁ
browsing-change-deck2 = ଡେକ୍ ପରିବର୍ତ୍ତନ...
browsing-change-note-type = ନୋଟ୍ ପ୍ରକାର ପରିବର୍ତ୍ତନ କରନ୍ତୁ
browsing-change-note-type2 = ନୋଟ୍ ପ୍ରକାର ପରିବର୍ତ୍ତନ...
browsing-clear-unused = ଅବ୍ୟବହୃତ ସଫା କରନ୍ତୁ
browsing-clear-unused-tags = ଅବ୍ୟବହୃତ ଟ୍ୟାଗଗୁଡ଼ିକ ସଫା କରନ୍ତୁ
browsing-created = ସୃଷ୍ଟି ହୋଇଛି
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = ସାମ୍ପ୍ରତିକ ଡ଼େକ୍
browsing-flag = ପତାକା
browsing-home = ଘର
browsing-note = ନୋଟ୍
browsing-please-give-your-filter-a-name = ଦୟାକରି ଆପଣଙ୍କର ଫିଲ୍ଟରକୁ ଗୋଟିଏ ନାମ ଦିଅନ୍ତୁ:
browsing-question = ପ୍ରଶ୍ନ
browsing-sidebar-expand = ବିସ୍ତାର କରନ୍ତୁ
browsing-sidebar-collapse = ସଂକୋଚନ କରନ୍ତୁ
browsing-today = ଆଜି
