card-stats-added = ଯୋଗ ହୋଇଛି
card-stats-first-review = ପ୍ରଥମ ସମୀକ୍ଷା
card-stats-latest-review = ସର୍ବଶେଷ ସମୀକ୍ଷା
card-stats-interval = ବ୍ୟବଧାନ
card-stats-ease = ସହଜ
card-stats-review-count = ସମୀକ୍ଷା
card-stats-lapse-count = ଲାପ୍ସ
card-stats-average-time = ହାରାହାରି ସମୟ
card-stats-total-time = ମୋଟ ସମୟ
card-stats-new-card-position = ସ୍ଥିତି
card-stats-card-template = କାର୍ଡ ପ୍ରକାର
card-stats-note-type = ଟିପ୍ପଣୀ ପ୍ରକାର
card-stats-deck-name = ଡେକ୍
card-stats-note-id = ଟିପ୍ପଣୀ ID
card-stats-card-id = କାର୍ଡ ID
card-stats-review-log-rating = ମୂଲ୍ୟାଙ୍କନ
card-stats-review-log-type = ପ୍ରକାର
card-stats-review-log-date = ତାରିଖ
card-stats-review-log-time-taken = ସମୟ
card-stats-review-log-type-learn = ଶିଖ
card-stats-review-log-type-review = ସମୀକ୍ଷା
card-stats-review-log-type-relearn = ପୁନର୍ବାର
card-stats-review-log-type-filtered = ଫିଲ୍ଟର୍ ହୋଇଛି
card-stats-review-log-type-manual = ମାନୁଆଲ୍
