custom-study-must-rename-deck = ଦୟାକରି ପ୍ରଥମେ ବିଦ୍ୟମାନ ଇଚ୍ଛାରୂପିତ ଅଧ୍ୟୟନ ଡେକ୍ ର ନାମ ପରିବର୍ତ୍ତନ କରନ୍ତୁ।
custom-study-all-cards-in-random-order-dont = ସମସ୍ତ କାର୍ଡ ଅନିୟମିତ କ୍ରମରେ (ପୁନଃନିର୍ଦ୍ଧାରଣ କରନ୍ତୁ ନାହିଁ)
custom-study-all-review-cards-in-random-order = ସମସ୍ତ ସମୀକ୍ଷା କାର୍ଡଗୁଡ଼ିକ ଅନିୟମିତ କ୍ରମରେ
custom-study-cards = ପତ୍ରଗୁଡ଼ିକ
custom-study-cards-from-the-deck = ଡେକ୍ ରୁ ପତ୍ରଗୁଡ଼ିକ
custom-study-choose-tags = ଟ୍ୟାଗ୍ ବାଛନ୍ତୁ
custom-study-custom-study-session = ଇଚ୍ଛାରୂପିତ ଅଧ୍ୟୟନ ଅଧିବେଶନ
custom-study-increase-todays-new-card-limit = ଆଜିର ନୂତନ କାର୍ଡ ସୀମା ବୃଦ୍ଧି କରନ୍ତୁ
custom-study-increase-todays-new-card-limit-by = ଏହା ଦ୍ୱାରା ଆଜିର ନୂତନ କାର୍ଡ ସୀମା ବୃଦ୍ଧି କରନ୍ତୁ
custom-study-increase-todays-review-card-limit = ଆଜିର କାର୍ଡ ସମୀକ୍ଷା ସୀମା ବୃଦ୍ଧି କରନ୍ତୁ
custom-study-increase-todays-review-limit-by = ଏହା ଦ୍ୱାରା ଆଜିର କାର୍ଡ ସମୀକ୍ଷା ସୀମା ବୃଦ୍ଧି କରନ୍ତୁ
custom-study-new-cards-in-deck-over-today = ଆଜିର ଦୈନିକ ସୀମା ଅନୁଯାୟୀ ଡେକ୍ ରେ ନୂତନ କାର୍ଡଗୁଡ଼ିକ: { $val }
custom-study-new-cards-only = କେବଳ ନୂତନ କାର୍ଡଗୁଡ଼ିକ
custom-study-no-cards-matched-the-criteria-you = ଆପଣ ପ୍ରଦାନ କରିଥିବା ମାନଦଣ୍ଡ ସହ କୌଣସି କାର୍ଡ ମେଳ ଖାଉ ନାହିଁ।
custom-study-ok = ଠିକ୍ ଅଛି
custom-study-preview-new-cards = ନୂତନ କାର୍ଡଗୁଡ଼ିକୁ ପୂର୍ବାବଲୋକନ କରନ୍ତୁ
custom-study-preview-new-cards-added-in-the = ଯୋଡ଼ା ଯାଇଥିବା ନୂତନ କାର୍ଡଗୁଡ଼ିକର ଶେଷରେ ପୂର୍ବାବଲୋକନ କରନ୍ତୁ
custom-study-require-one-or-more-of-these = ଏହି ଟ୍ୟାଗଗୁଡ଼ିକ ମଧ୍ୟରୁ ଗୋଟିଏ କିମ୍ବା ଅଧିକ ଆବଶ୍ୟକ:
custom-study-review-ahead = ପୂର୍ବରୁ ସମୀକ୍ଷା କରନ୍ତୁ
custom-study-review-ahead-by = ଏହି ଅବଧି ପୂର୍ବରୁ ସମୀକ୍ଷା କରନ୍ତୁ:
custom-study-review-cards-forgotten-in-last = ଶେଷରେ ଭୁଲିଯାଇଥିବା କାର୍ଡଗୁଡ଼ିକର ସମୀକ୍ଷା କରନ୍ତୁ
custom-study-review-forgotten-cards = ଭୁଲିଯାଇଥିବା କାର୍ଡଗୁଡ଼ିକୁ ସମୀକ୍ଷା କରନ୍ତୁ
custom-study-select = ଚୟନ କରନ୍ତୁ
custom-study-select-tags-to-exclude = ବାଦ୍ ଦେବା ପାଇଁ ଟ୍ୟାଗ୍ ଚୟନ କରନ୍ତୁ:
custom-study-study-by-card-state-or-tag = କାର୍ଡ ସ୍ଥିତି କିମ୍ବା ଟ୍ୟାଗ୍ ଦ୍ୱାରା ଅଧ୍ୟୟନ କରନ୍ତୁ
