decks-add-new-deck-ctrlandn = ନୂତନ ଡେକ୍ ଯୋଡ଼ନ୍ତୁ (Ctrl+N)
decks-build = ନିର୍ମାଣ କରନ୍ତୁ
decks-create-deck = ଡେକ୍ ସୃଷ୍ଟି କରନ୍ତୁ
decks-deck = ଡେକ୍
decks-decreasing-intervals = କମୁଥିବା ବ୍ୟବଧାନ
decks-delete-deck = ଡେକ୍ ବିଲୋପ କରନ୍ତୁ
decks-enable-second-filter = ଦ୍ୱିତୀୟ ଫିଲ୍ଟର୍ ସକ୍ଷମ କରନ୍ତୁ
decks-import-file = ଫାଇଲ୍ ଆମଦାନୀ କରନ୍ତୁ
decks-increasing-intervals = ବଢ଼ୁଥିବା ବ୍ୟବଧାନ
decks-latest-added-first = ସର୍ବଶେଷରେ ଯୋଡ଼ା ଯାଇଥିବା ପ୍ରଥମେ
decks-limit-to = ଏତିକିରେ ସୀମିତ ରଖ
decks-minutes = ମିନିଟ୍
decks-name-for-deck = ଡେକ୍ ପାଇଁ ନାମ:
decks-new-deck-name = ନୂତନ ଡେକ୍ ନାମ:
decks-no-deck = [ଡେକ୍ ନାହିଁ]
decks-random = ଅନିୟମିତ
decks-study = ଅଧ୍ୟୟନ
decks-study-deck = ଅଧ୍ୟୟନ ଡେକ୍
decks-unmovable-cards = ସବୁ ବହିଷ୍କୃତ କାର୍ଡ ଦେଖାନ୍ତୁ
