fields-add-field = କ୍ଷେତ୍ର ଯୋଡ଼ନ୍ତୁ
fields-delete-field-from = { $val }ରୁ କ୍ଷେତ୍ର ବିଲୋପ କରିବେ କି?
fields-editing-font = ସମ୍ପାଦନା ଫଣ୍ଟ
fields-field = କ୍ଷେତ୍ର:
fields-field-name = କ୍ଷେତ୍ର ନାମ:
fields-fields-for = { $val } ପାଇଁ କ୍ଷେତ୍ର
fields-font = ଫଣ୍ଟ:
fields-new-position-1 = ନୂତନ ସ୍ଥିତି (1...{ $val }):
fields-size = ଆକାର:
