preferences-backups = ବ୍ୟାକଅପ୍
preferences-backups2 = ବ୍ୟାକଅପଗୁଡ଼ିକ
preferences-backupsanki-will-create-a-backup-of = <html><head/><body><p><span style=" font-weight:600;">ବ୍ୟାକଅପଗୁଡ଼ିକ</span><br/>ପ୍ରତ୍ୟେକ ଥର ବନ୍ଦ ହେବାବେଳେ Anki ଆପଣଙ୍କ ସଂଗ୍ରହର ଏକ ବ୍ୟାକଅପ୍ ସୃଷ୍ଟି କରିବ।</p></body></html>
preferences-basic = ମୌଳିକ
preferences-change-deck-depending-on-note-type = ନୋଟ୍ ପ୍ରକାର ଉପରେ ନିର୍ଭର କରି ଡେକ୍ ପରିବର୍ତ୍ତନ କରନ୍ତୁ
preferences-changes-will-take-effect-when-you = ଆପଣ Anki ପୁନଃଆରମ୍ଭ କରିବା ସମୟରେ ପରିବର୍ତ୍ତନଗୁଡ଼ିକ କାର୍ଯ୍ୟକାରୀ ହେବ।
preferences-hours-past-midnight = ମଧ୍ୟରାତ୍ରିର ଏତିକି ଘଣ୍ଟା ପରେ
preferences-interface-language = ଇଣ୍ଟରଫେସ୍ ଭାଷା:
preferences-next-day-starts-at = ପରବର୍ତ୍ତୀ ଦିନ ଆରମ୍ଭ ହୁଏ
preferences-night-mode = ରାତ୍ରି ମୋଡ୍
preferences-on-next-sync-force-changes-in = ପରବର୍ତ୍ତୀ ସିଙ୍କ୍ ରେ, ଗୋଟିଏ ଦିଗରେ ପରିବର୍ତ୍ତନକୁ ବାଧ୍ୟ କରନ୍ତୁ
preferences-paste-clipboard-images-as-png = PNG ଭାବରେ କ୍ଲିପବୋର୍ଡ ପ୍ରତିଛବିଗୁଡ଼ିକୁ ଲଗାନ୍ତୁ
preferences-periodically-sync-media = ସମୟସମୟରେ ମିଡିଆକୁ ସିଙ୍କ୍ କରନ୍ତୁ
preferences-please-restart-anki-to-complete-language = ଭାଷା ପରିବର୍ତ୍ତନ ସମ୍ପୂର୍ଣ୍ଣ କରିବା ପାଇଁ ଦୟାକରି Anki ପୁନଃଆରମ୍ଭ କରନ୍ତୁ।
preferences-preferences = ଅଗ୍ରାଧିକାରସମୂହ
preferences-show-next-review-time-above-answer = ଉତ୍ତର ବଟନ୍ ଉପରେ ପରବର୍ତ୍ତୀ ସମୀକ୍ଷା ସମୟ ଦେଖାନ୍ତୁ
preferences-show-play-buttons-on-cards-with = ଅଡିଓ ଗଚ୍ଛିତ କାର୍ଡରେ ପ୍ଲେ ବଟନ୍ ଦେଖାନ୍ତୁ
preferences-timebox-time-limit = ଟାଇମ୍ ବକ୍ସ ସମୟ ସୀମା
preferences-user-interface-size = ଉପଭୋକ୍ତା ଇଣ୍ଟରଫେସ୍ ଆକାର
