studying-again = ପୁଣି
studying-all-buried-cards = ସମସ୍ତ ଥଗିତ ହୋଇଥିବା ପତ୍ର
studying-audio-5s = ଅଡ଼ିଓ -5ସେ
studying-audio-and5s = ଅଡ଼ିଓ +5ସେ
studying-buried-siblings = ସ୍ଥଗିତ ହୋଇଥିବା ଭାଇଭଉଣୀ
studying-bury = ସ୍ଥଗିତ ରଖନ୍ତୁ
studying-bury-card = ପତ୍ର ସ୍ଥଗିତ କରନ୍ତୁ
studying-bury-note = ନୋଟ୍ ସ୍ଥଗିତ କରନ୍ତୁ
studying-card-buried = ପତ୍ରଟିକୁ ସ୍ଥଗିତ କରି ଦିଆଗଲା
studying-card-suspended = ପତ୍ରଟିକୁ ନିଲମ୍ବିତ କରି ଦିଆଗଲା
studying-continue = ଜାରି ରଖନ୍ତୁ
studying-delete-note = ନୋଟ୍ ଅପସାରଣ କରନ୍ତୁ
studying-easy = ସହଜ
studying-edit = ସମ୍ପାଦନା
studying-empty = ଖାଲି
studying-finish = ସମାପ୍ତ
studying-flag-card = କାର୍ଡକୁ ଏକ ପତାକା ନ୍ୟସ୍ତ କରନ୍ତୁ
studying-good = ଭଲ
studying-hard = କଠିନ
studying-it-has-been-suspended = ଏହାକୁ ନିଲମ୍ବିତ ରଖାଯାଇଛି।
studying-mark-note = ନୋଟ ଚିନ୍ହିତ କରନ୍ତୁ
studying-more = ଅଧିକ
studying-no-cards-are-due-yet = ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପତ୍ର ବାକି ନାହିଁ।
studying-note-buried = ନୋଟଟିକୁ ସ୍ଥଗିତ କରି ଦିଆଗଲା
studying-note-suspended = ନୋଟଟିକୁ ନିଲମ୍ବିତ କରି ଦିଆଗଲା
studying-pause-audio = ଅଡ଼ିଓ ବିରତ କର
studying-please-run-toolsempty-cards = ଦୟାକରି ଉପକରଣଗୁଡ଼ିକ> ଖାଲି ପତ୍ରଗୁଡ଼ିକ ଚଲାନ୍ତୁ।
studying-show-answer = ଉତ୍ତର ଦେଖନ୍ତୁ
studying-study-now = ବର୍ତ୍ତମାନ ଅଧ୍ୟୟନ କରନ୍ତୁ
studying-suspend = ନିଲମ୍ବନ କରନ୍ତୁ
studying-suspend-note = ନୋଟ୍ ନିଲମ୍ବିତ କରନ୍ତୁ
studying-to-review = ସମୀକ୍ଷା କରିବାକୁ
studying-unbury = ସ୍ଥଗିତରୁ ଫେରାଇ ଆଣ
studying-what-would-you-like-to-unbury = ଆପଣ କ'ଣ ସ୍ଥଗିତରୁ ଫେରାଇ ଆଣିବାକୁ ଚାହାଁନ୍ତି?
studying-you-havent-recorded-your-voice-yet = ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ ନିଜ ସ୍ୱର ରେକର୍ଡ କରିନାହାଁନ୍ତି।
