importing-aborted = Anullat  { $val }
importing-added-duplicate-with-first-field = Un doblon es estat apondut amb coma primièr camp : { $val }
importing-allow-html-in-fields = Tolerar de HTML dins los camps
importing-anki-files-are-from-a-very = Los fichièrs .anki venon d'una version plan anciana d'Anki. Los podètz importar amb Anki 2.0 qu'es disponible sul siti web d'Anki.
importing-anki2-files-are-not-directly-importable = Los fichièrs .anki2 son pas importables directament. Mercé d'importar lo fichièr .apkg o .zip qu'avètz recebut en plaça.
importing-appeared-twice-in-file = Apareis en doble dins lo fichièr : { $val }
importing-change = Cambiar
importing-colon = Dos punts
importing-comma = Virgula
importing-ignored = <ignorat>
importing-rows-had-num1d-fields-expected-num2d = « %(row)s » aviá %(num1)d camps al luòc dels %(num2)d previstes
importing-semicolon = Punt-virgula
importing-supermemo-xml-export-xml = Supermemo exportat en XML (*.xml)
