studying-again = Tornamai
studying-bury = Enterrar
studying-bury-card = Enterrar la carta
studying-continue = Contunhar
studying-delete-note = Suprimir la nòta
studying-easy = Aisit
studying-edit = Editar
studying-empty = Void
studying-finish = Acabar
studying-good = Plan
studying-hard = Dur
studying-more = Mai
studying-space = Espaci
studying-suspend = Suspendre
