actions-add = Dodaj
actions-all-selected = Wszystkie wybrane
actions-any-selected = Jakiekolwiek wybrane
actions-blue-flag = Niebieska flaga
actions-cancel = Anuluj
actions-choose = Wybierz
actions-close = Zamknij
actions-copy = Kopiuj
actions-custom-study = Nauka własna
actions-decks = Talie
actions-delete = Usuń
actions-export = Eksportuj
actions-filter = Filtr
actions-green-flag = Zielona flaga
actions-help = Pomoc
actions-import = Importuj
actions-manage = Zarządzaj...
actions-name = Nazwa:
actions-new = Nowe
actions-new-name = Nowa nazwa :
actions-options = Opcje
actions-options-for = Opcje dla { $val }
actions-orange-flag = Pomarańczowa flaga
actions-preview = Podgląd
actions-rebuild = Przebuduj
actions-red-flag = Czerwona flaga
actions-rename = Zmień nazwę
actions-rename-deck = Zmień nazwę talii
actions-rename-tag = Zmień nazwę etykiety
actions-remove-tag = Usuń etykietę
actions-replay-audio = Odtwórz dźwięk
actions-reposition = Zmień pozycję
actions-save = Zapisz
actions-search = Szukaj
actions-select = Wybierz
actions-shortcut-key = Skrót klawiszowy: { $val }
actions-suspend-card = Zawieś kartę
actions-set-due-date = Ustaw termin
actions-forget = Zapomnij
