actions-add = Dodaj
actions-all-selected = Wszystkie wybrane
actions-any-selected = Jakiekolwiek wybrane
actions-cancel = Anuluj
actions-choose = Wybierz
actions-close = Zamknij
actions-copy = Kopiuj
actions-custom-study = Nauka własna
actions-decks = Talie
actions-delete = Usuń
actions-export = Eksportuj
actions-filter = Filtr
actions-help = Pomoc
actions-import = Importuj
actions-manage = Zarządzaj...
actions-name = Nazwa:
actions-new = Nowe
actions-new-name = Nowa nazwa :
actions-options = Opcje
actions-options-for = Opcje dla { $val }
actions-preview = Podgląd
actions-rebuild = Przebuduj
actions-rename = Zmień nazwę
actions-rename-deck = Zmień nazwę talii
actions-rename-tag = Zmień nazwę etykiety
actions-rename-with-parents = Zmiana nazwy wraz z rodzicami
actions-remove-tag = Usuń etykietę
actions-replay-audio = Odtwórz dźwięk
actions-reposition = Zmień pozycję
actions-save = Zapisz
actions-search = Szukaj
actions-select = Wybierz
actions-shortcut-key = Skrót klawiszowy: { $val }
actions-suspend-card = Zawieś kartę
actions-set-due-date = Ustaw termin
actions-forget = Zapomnij
actions-answer-card = Odpowiedź do karty
actions-unbury-unsuspend = Odkopanie/odwieszenie
actions-add-deck = Dodanie talii
actions-add-note = Dodanie notatki
actions-update-tag = Aktualizacja etykiety
actions-update-note = Aktualizacja notatki
actions-update-card = Aktualizacja karty
actions-update-deck = Aktualizacja talii
actions-forget-card = Zapomnienie karty
actions-build-filtered-deck = Zbuduj talię
actions-expand-collapse = Rozwinięcie/zwinięcie
actions-add-notetype = Dodanie typu notatki
actions-remove-notetype = Usunięcie typu notatki
actions-update-notetype = Aktualizacja typu notatki
actions-update-config = Aktualizacja konfiguracji
actions-card-info = Informacje o karcie

## Flags

actions-flag-number = Flaga { $number }
actions-flag-red = Czerwona
actions-flag-orange = Pomarańczowa
actions-flag-green = Zielona
actions-flag-blue = Niebieska
actions-flag-pink = Różowa
actions-flag-turquoise = Turkusowa
actions-flag-purple = Fioletowa
actions-set-flag = Ustaw flagę
