change-notetype-current = Aktualny
change-notetype-new = Nowy
change-notetype-nothing = (Nic)
change-notetype-collapse = Zwiń
change-notetype-expand = Rozwiń
change-notetype-will-discard-content = Zawartość zostanie usunięta z następujących kart:
change-notetype-will-discard-cards = Następujące karty zostaną usunięte:
change-notetype-fields = Pola
change-notetype-templates = Szablony
