editing-add-media = Dodaj pliki
editing-align-left = Wyrównaj do lewej
editing-align-right = Wyrównaj do prawej
editing-an-error-occurred-while-opening = Wystąpił błąd przy otwieraniu { $val }
editing-attach-picturesaudiovideo = Dołącz obraz/audio/wideo
editing-bold-text = Pogrubienie
editing-cards = Karty
editing-center = Wycentrowanie
editing-change-color = Zmień kolor
editing-cloze-deletion = Luka
editing-couldnt-record-audio-have-you-installed = Nie można nagrać dźwięku. Czy masz zainstalowany program "lame"?
editing-customize-card-templates = Dostosuj szablony kart
editing-customize-fields = Dostosuj pola
editing-cut = Wytnij
editing-edit-current = Edytuj aktualną
editing-edit-html = Edytuj HTML
editing-fields = Pola
editing-html-editor = Edytor HTML
editing-indent = Zwiększ wcięcie
editing-italic-text = Pochylenie
editing-jump-to-tags-with-ctrlandshiftandt = Przeskocz do etykiet z Ctrl+Shift+T
editing-justify = Wyjustowanie
editing-latex = LaTeX
editing-latex-equation = Równanie LaTeX
editing-latex-math-env = Środowisko matematyczne LaTeX
editing-mathjax-block = Blok MathJax
editing-mathjax-chemistry = Chemia MathJax
editing-mathjax-inline = Liniowy MathJax
editing-media = Pliki
editing-ordered-list = Lista uporządkowana
editing-outdent = Zmniejsz wcięcie
editing-paste = Wklej
editing-record-audio = Nagraj dźwięk
editing-remove-formatting = Usuń formatowanie
editing-set-text-color = Ustaw kolor tekstu
editing-set-text-highlight-color = Ustaw kolor wyróżnienia tekstu
editing-show-duplicates = Pokaż duplikaty
editing-subscript = Indeks dolny
editing-superscript = indeks górny
editing-tags = Etykiety
editing-to-make-a-cloze-deletion-on = Aby wprowadzić wypełnianie luk do istniejącej notatki, musisz zmienić jej typ na lukę poprzez Notatki>Zmień typ notatki
editing-underline-text = Podkreślenie
editing-unordered-list = Lista nieuporządkowana
editing-warning-cloze-deletions-will-not-work = Uwaga: wypełnianie luk nie będzie działać, jeśli nie ustawisz typu na górze na Luka.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Pogrubienie (Ctrl+B)
editing-italic-text-ctrlandi = Pochylenie (Ctrl+I)
editing-underline-text-ctrlandu = Podkreślenie (Ctrl+U)
editing-subscript-ctrland = Indeks dolny (Ctrl+=)
editing-superscript-ctrlandand = Indeks górny (Ctrl++)
editing-remove-formatting-ctrlandr = Usuń formatowanie (Ctrl+R)
editing-record-audio-f5 = Nagraj dźwięk (F5)
editing-attach-picturesaudiovideo-f3 = Załącz obraz/dźwięk/wideo (F3)
editing-cloze-deletion-ctrlandshiftandc = Luki (Ctrl+Shift+C)
editing-change-colour-f8 = Zmień kolor (F8)
editing-set-foreground-colour-f7 = Ustaw kolor czcionki (F7)
editing-customize-card-templates-ctrlandl = Dostosuj szablony kart (Ctrl+L)
editing-set-foreground-color = Ustaw kolor czcionki
