editing-add-media = Dodaj pliki
editing-an-error-occurred-while-opening = Wystąpił błąd przy otwieraniu { $val }
editing-attach-picturesaudiovideo-f3 = Załącz obraz/dźwięk/wideo (F3)
editing-bold-text-ctrlandb = Pogrubienie (Ctrl+B)
editing-cards = Karty
editing-change-colour-f8 = Zmień kolor (F8)
editing-cloze-deletion-ctrlandshiftandc = Luki (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Nie można nagrać dźwięku. Czy masz zainstalowany program "lame"?
editing-customize-card-templates-ctrlandl = Dostosuj szablony kart (Ctrl+L)
editing-customize-fields = Dostosuj pola
editing-cut = Wytnij
editing-edit-current = Edytuj aktualną
editing-edit-html = Edytuj HTML
editing-fields = Pola
editing-html-editor = Edytor HTML
editing-italic-text-ctrlandi = Pochylenie (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Przeskocz do etykiet z Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Równanie LaTeX
editing-latex-math-env = Środowisko matematyczne LaTeX
editing-mathjax-block = Blok MathJax
editing-mathjax-chemistry = Chemia MathJax
editing-mathjax-inline = Liniowy MathJax
editing-media = Pliki
editing-paste = Wklej
editing-record-audio-f5 = Nagraj dźwięk (F5)
editing-remove-formatting-ctrlandr = Usuń formatowanie (Ctrl+R)
editing-set-foreground-colour-f7 = Ustaw kolor czcionki (F7)
editing-show-duplicates = Pokaż duplikaty
editing-subscript-ctrland = Indeks dolny (Ctrl+=)
editing-superscript-ctrlandand = Indeks górny (Ctrl++)
editing-tags = Etykiety
editing-to-make-a-cloze-deletion-on = Aby wprowadzić wypełnianie luk do istniejącej notatki, musisz zmienić jej typ na lukę poprzez Notatki>Zmień typ notatki
editing-underline-text-ctrlandu = Podkreślenie (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Uwaga: wypełnianie luk nie będzie działać, jeśli nie ustawisz typu na górze na Luka.
