notetypes-front-field = Przód
notetypes-back-field = Tył
notetypes-add-reverse-field = Dodaj rewers
notetypes-text-field = Tekst
notetypes-basic-name = Podstawowy
notetypes-basic-reversed-name = Podstawowy (z odwrotną kartą)
notetypes-basic-optional-reversed-name = Podstawowy (z opcjonalną odwrotną kartą)
notetypes-cloze-name = Luka
notetypes-basic-type-answer-name = Podstawowy (wpisywanie odpowiedzi)
notetypes-card-2-name = Karta 2
notetypes-card-1-name = Karta 1
