preferences-automatically-sync-on-profile-openclose = Automatycznie synchronizuj przy otwarciu/zamknięciu profilu
preferences-backups = Kopie zapasowe
preferences-change-deck-depending-on-note-type = Zmień talię na podstawie typu notatki
preferences-changes-will-take-effect-when-you = Zmiany będą miały skutek kiedy ponownie uruchomisz Anki.
preferences-hours-past-midnight = godziny po północy
preferences-language = Język
preferences-interrupt-current-audio-when-answering = Przerywaj odtwarzany dźwięk podczas powtórki
preferences-learn-ahead-limit = Limit nauki z wyprzedzeniem
preferences-mins = minut
preferences-network = Sieć
preferences-next-day-starts-at = Nowy dzień zaczyna się
preferences-on-next-sync-force-changes-in = Przy następnej synchronizacji wymuś zmiany w jednym kierunku
preferences-paste-clipboard-images-as-png = Wklej zdjęcia ze schowka jako PNG
preferences-paste-without-shift-key-strips-formatting = Wklejanie bez klawisza Shift usuwa formatowanie
preferences-periodically-sync-media = Synchronizuj okresowo pliki
preferences-please-restart-anki-to-complete-language = Uruchom ponownie Anki, aby ukończyć zmianę języka.
preferences-preferences = Ustawienia
preferences-scheduling = Planowanie
preferences-show-learning-cards-with-larger-steps = Pokaż karty do nauczenia z dużym krokiem przed kartami powtórek
preferences-show-next-review-time-above-answer = Pokaż czas następnej powtórki nad przyciskami odpowiedzi
preferences-show-play-buttons-on-cards-with = Pokazuj przyciski odtwarzania na kartach z dźwiękiem
preferences-show-remaining-card-count = Pokaż liczbę pozostałych kart
preferences-some-settings-will-take-effect-after = Niektóre ustawienia zadziałają dopiero po ponownym uruchomieniu Anki.
preferences-tab-synchronisation = Synchronizacja
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronizacja</b><br> Aktualnie wyłączona; kliknij przycisk synchronizacji w oknie głównym, aby ją włączyć.
preferences-synchronize-audio-and-images-too = Synchronizuj również dźwięki i obrazy
preferences-timebox-time-limit = Limit czasowy na sesję
preferences-user-interface-size = Rozmiar interfejsu
preferences-when-adding-default-to-current-deck = Dodawaj domyślnie do aktualnej talii
preferences-you-can-restore-backups-via-fileswitch = Możesz przywrócić kopie zapasowe poprzez Plik>Przełącz profil.
preferences-legacy-timezone-handling = Przestarzała obsługa stref czasowych (posiadająca błędy, lecz wymagana do obsługi AnkiDroid <=  2.14)
preferences-default-search-text = Domyślny tekst wyszukiwania
preferences-default-search-text-example = np. "deck:current "
preferences-theme = Motyw
preferences-theme-follow-system = Używaj systemowego
preferences-theme-light = Jasny
preferences-theme-dark = Ciemny
preferences-v3-scheduler = Algorytm planowania V3
preferences-ignore-accents-in-search = Ignoruj znaki diakrytyczne przy wyszukiwaniu (spowalnia)
preferences-backup-explanation =
    Anki okresowo tworzy kopię zapasową kolekcji. Gdy kopie są starsze niż 2 dni,
    Anki będzie je usuwać, by zaoszczędzić miejsce na dysku.
preferences-daily-backups = Liczba kopii na dzień:
preferences-weekly-backups = Liczba kopii na tydzień:
preferences-monthly-backups = Liczba kopii na miesiąc:
preferences-minutes-between-backups = Co ile minut kopia zapasowa:
preferences-reduce-motion = Redukuj ruch
preferences-reduce-motion-tooltip = Wyłącza różne animacje i przejścia interfejsu użytkownika
preferences-hide-top-bar-during-review = Ukryj górną belkę podczas powtarzania
preferences-hide-bottom-bar-during-review = Ukryj dolną belkę podczas powtarzania
preferences-always = Zawsze
preferences-full-screen-only = Tylko pełen ekran
preferences-appearance = Wygląd
preferences-general = Ogólne
preferences-style = Styl
preferences-review = Powtórki
preferences-distractions = Rozpraszacze
preferences-minimalist-mode = Tryb minimalistyczny
preferences-editing = Edytowanie
preferences-browsing = Przeglądanie
preferences-default-deck = Domyślna talia
preferences-account = Konto AnkiWeb
preferences-note = Notatka
preferences-scheduler = Planowanie
preferences-user-interface = Interfejs użytkownika
preferences-import-export = Import/Eksport

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Ogólne
preferences-media = Pliki
