actions-add = إضافة
actions-all-selected = كل المحدد
actions-any-selected = أي من المحدد
actions-blue-flag = مؤشر أزرق
actions-cancel = إلغاء
actions-choose = اختيار
actions-close = إغلاق
actions-copy = نسخ
actions-custom-study = دراسة مخصصة
actions-decks = رزم
actions-delete = حذف
actions-export = تصدير
actions-filter = فلتر
actions-green-flag = مؤشر أخضر
actions-help = مساعدة
actions-import = استيراد
actions-manage = إدارة...
actions-name = اسم:
actions-new = جديدة
actions-new-name = الاسم الجديد:
actions-options = خيارات
actions-options-for = خيارات { $val }
actions-orange-flag = مؤشر برتقالي
actions-preview = معاينة
actions-rebuild = إعادة إنشاء
actions-red-flag = مؤشر أحمر
actions-rename = إعادة تسمية
actions-rename-deck = تغيير اسم الرزمة
actions-rename-tag = إعادة تسمية الوسم
actions-remove-tag = حذف الوسم
actions-replay-audio = إعادة تشغيل الصوت
actions-reposition = تغيير الموضع
actions-save = حفظ
actions-search = بحث
actions-select = تحديد
actions-shortcut-key = اختصار: { $val }
actions-suspend-card = تعليق البطاقة
actions-set-due-date = ضبط تاريخ الاستحقاق
actions-forget = نسيان
actions-answer-card = الإجابة عن بطاقة
actions-unbury-unsuspend = نكش/تفعيل
actions-add-deck = إضافة رزمة
actions-add-note = إضافة ملحوظة
actions-update-tag = تحديث وسم
actions-update-note = تحديث ملحوظة
actions-update-card = تحديث بطاقة
actions-update-deck = تحديث رزمة
actions-forget-card = نسيان بطاقة
actions-set-flag = وضع مؤشر
actions-build-filtered-deck = بناء رزمة
actions-expand-collapse = إسدال/طي
actions-add-notetype = إضافة نوع ملحوظة
actions-remove-notetype = حذف نوع ملحوظة
actions-update-notetype = تحديث نوع ملحوظة
actions-update-config = تحديث إعداد
