actions-add = إضافة
actions-blue-flag = مؤشر أزرق
actions-cancel = إلغاء
actions-choose = اختيار
actions-close = إغلاق
actions-copy = نسخ
actions-custom-study = دراسة مخصصة
actions-decks = رزم
actions-delete = حذف
actions-export = تصدير
actions-filter = فلتر
actions-green-flag = مؤشر أخضر
actions-help = مساعدة
actions-import = استيراد
actions-manage = إدارة...
actions-name = اسم:
actions-new = جديدة
actions-new-name = الاسم الجديد:
actions-options = خيارات
actions-options-for = خيارات { $val }
actions-orange-flag = مؤشر برتقالي
actions-preview = معاينة
actions-rebuild = إعادة إنشاء
actions-red-flag = مؤشر أحمر
actions-rename = إعادة تسمية
actions-rename-deck = تغيير اسم الرزمة
actions-replay-audio = إعادة تشغيل الصوت
actions-reposition = تغيير الموضع
actions-save = حفظ
actions-search = بحث
actions-shortcut-key = اختصار: { $val }
actions-suspend-card = تعليق البطاقة
