adding-add-shortcut-ctrlandenter = (ctrl+enter :اختصار) إضافة
adding-added = أُضيفت
adding-close-and-lose-current-input = هل تريد الإغلاق وفقدان المدخلات الحالية؟
adding-edit = تحرير "{ $val }"
adding-history = السجل
adding-note-deleted = (ملحوظة محذوفة)
adding-shortcut = اختصار: { $val }
adding-the-first-field-is-empty = الحقل الأول فارغ.
adding-you-have-a-cloze-deletion-note = أنت تستخدم نوع ملحوظات ملء الفراغات لكنك لم تصنع أي عبارة ملء فراغات. هل تريد الاستمرار؟
