card-stats-added = أُضيفت
card-stats-first-review = أول مراجعة
card-stats-latest-review = آخر مراجعة
card-stats-interval = الفاصل الزمني
card-stats-ease = سهولة
card-stats-review-count = مراجعات
card-stats-lapse-count = سقطات
card-stats-average-time = معدل الوقت
card-stats-total-time = الوقت الكلي
card-stats-new-card-position = الموضع
card-stats-card-template = نوع البطاقة
card-stats-note-type = نوع الملحوظة
card-stats-deck-name = رزمة
card-stats-note-id = مُعرّف الملحوظة
card-stats-card-id = مُعرف البطاقة
card-stats-review-log-rating = التقييم
card-stats-review-log-type = النوع
card-stats-review-log-date = التاريخ
card-stats-review-log-time-taken = الوقت
card-stats-review-log-type-learn = تعلّم
card-stats-review-log-type-review = مراجعة
card-stats-review-log-type-relearn = تعلّم مجددًا
card-stats-review-log-type-filtered = مفلتر
