card-stats-added = اُضيفت
card-stats-first-review = اول مراجعة
card-stats-ease = تسهيل
card-stats-review-count = مراجعات
card-stats-lapse-count = هفوات
card-stats-average-time = معدل الوقت
card-stats-total-time = الوقت الكلي
card-stats-card-template = نوع البطاقة
card-stats-deck-name = مجموعة
card-stats-card-id = مُعرف البطاقة
card-stats-review-log-type = النوع
card-stats-review-log-date = التاريخ
card-stats-review-log-type-review = مراجعة
