editing-add-media = إضافة وسائط
editing-align-left = محاذاة إلى اليسار
editing-align-right = محاذاة إلى اليمين
editing-an-error-occurred-while-opening = حدث خطأ عند فتح { $val }
editing-attach-picturesaudiovideo = ألحق صور/ملفات صوتية/فيديو
editing-bold-text = خط غامق
editing-cards = البطاقات
editing-center = محاذاة إلى الوسط
editing-change-color = تغيير اللون
editing-cloze-deletion = ملء فراغات
editing-couldnt-record-audio-have-you-installed = لا يمكن تسجيل الصوت. هل نصبّت 'lame'؟
editing-customize-card-templates = تخصيص قوالب البطاقات
editing-customize-fields = خصص الحقول
editing-cut = قص
editing-edit-current = تحرير البطاقة الحالية
editing-edit-html = تحرير HTML
editing-fields = الحقول
editing-html-editor = محرر HTML
editing-indent = زيادة الإزاحة
editing-italic-text = خط مائل
editing-jump-to-tags-with-ctrlandshiftandt = انتقل إلى الوسوم باستخدام Ctrl+Shift+T
editing-justify = محاذاة
editing-latex = LaTeX
editing-latex-equation = معادلة LaTeX
editing-latex-math-env = بيئة LaTeX الرياضية
editing-mathjax-block = كتلة MathJax
editing-mathjax-chemistry = MathJax كيمياء
editing-mathjax-inline = MathJax مضمَّن
editing-media = وسائط
editing-ordered-list = قائمة مرقمة
editing-outdent = خفض الإزاحة
editing-paste = لصق
editing-record-audio = تسجيل صوت
editing-remove-formatting = إزالة التنسيق
editing-set-text-color = ضبط لون النص
editing-set-text-highlight-color = ضبط لون التظليل
editing-show-duplicates = إظهار الملحوظات المكررة
editing-subscript = خط تحتي
editing-superscript = خط فوقي
editing-tags = وسوم
editing-to-make-a-cloze-deletion-on = لصنع عبارة ملء فراغات في ملحوظة موجودة، عليك تغيير نوعها إلى نوع ملء الفراغات أولًا، عبر 'ملحوظات>تغيير نوع الملحوظة'
editing-underline-text = خط تحت النص
editing-unordered-list = قائمة غير مرقمة
editing-warning-cloze-deletions-will-not-work = تحذير، عبارات ملء الفراغات لن تعمل حتى تغيّر النوع في الأعلى إلى نوع ملء الفراغات.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = خط غامق (Ctrl+B)
editing-italic-text-ctrlandi = خط مائل (Ctrl+I)
editing-underline-text-ctrlandu = ضع خطًا تحت النص (Ctrl+U)
editing-subscript-ctrland = رمز سفلي (Ctrl+=)
editing-superscript-ctrlandand = رمز علوي (Ctrl++)
editing-remove-formatting-ctrlandr = أزل التنسيق (Ctrl+R)
editing-record-audio-f5 = سجّل صوتًا (F5)
editing-attach-picturesaudiovideo-f3 = ألحق صور/ملفات صوتية/فيديو (F3)
editing-cloze-deletion-ctrlandshiftandc = عبارة ملء فراغات (Ctrl+Shift+C)
editing-change-colour-f8 = غيّر اللون (F8)
editing-set-foreground-colour-f7 = ضبط لون النص (F7)
editing-customize-card-templates-ctrlandl = خصص قوالب البطاقات (Ctrl+L)
editing-set-foreground-color = ضبط لون الخط
