importing-failed-debug-info = فشل الاستيراد. معلومات التصحيح:
importing-aborted = أُحبِط: { $val }
importing-added-duplicate-with-first-field = أضيفت ملحوظة حقلها الأول مكرر: { $val }
importing-allow-html-in-fields = السماح بـ HTML في الحقول
importing-anki-files-are-from-a-very = ملفات anki. تعود إلى إصدار قديم جدًا من أنكي. تستطيع استيرادها من خلال أنكي 2.0، متوفر على موقع أنكي على الإنترنت.
importing-anki2-files-are-not-directly-importable = ملفات anki2. غير متوافقة - الرجاء استيراد ملف apkg. أو zip. الذي تلقيته بدلًا من ذلك.
importing-appeared-twice-in-file = ظهر مرتين في الملف: { $val }
importing-by-default-anki-will-detect-the = يكتشف أنكي الرموز بين الحقول مثل التاب (tab)، والفاصلة، وما إلى ذلك افتراضيًا. إذا كان كشف أنكي عن هذه الرموز خاطئًا؛ تستطيع إدخالها هنا. استخدم t\ لتمثيل التاب.
importing-change = تعديل
importing-colon = نقطتان
importing-comma = فاصلة
importing-empty-first-field = الحقل الأول فارغ: { $val }
importing-field-mapping = توزيع الحقول
importing-field-of-file-is = الحقل رقم <b>{ $val }</b> من الملف هو:
importing-fields-separated-by = الحقول مفصولة بـ: { $val }
importing-file-version-unknown-trying-import-anyway = إصدار الملف غير معروف، سيُحاول الاستيراد على أي حال.
importing-first-field-matched = الحقل الأول مطابق: { $val }
importing-identical = مطابق
importing-ignore-field = تجاهل الحقل
importing-ignore-lines-where-first-field-matches = تجاهل السطور التي يطابق حقلها الأول ملحوظة موجودة
importing-ignored = <مهمل>
importing-import-even-if-existing-note-has = إضافة حتى لو كان لملحوظة موجودة مسبقًا الحقل الأول نفسه
importing-import-options = خيارات الاستيراد
importing-importing-complete = اكتمل الاستيراد.
importing-invalid-file-please-restore-from-backup = ملف غير صالح. الرجاء الاسترجاع من النسخ الاحتياطية.
importing-map-to = إيزاع إلى { $val }
importing-map-to-tags = إيزاع إلى الوسوم
importing-mapped-to = مُوزع إلى <b>{ $val }</b>
importing-mapped-to-tags = مُوزع إلى <b>وسوم</b>
importing-mnemosyne-20-deck-db = رزمة Mnemosyne 2.0 (*.db)
importing-multicharacter-separators-are-not-supported-please = الفواصل المكونة من أكثر من رمز غير مدعومة. الرجاء إدخال رمز واحد فقط.
importing-notes-added-from-file = عدد الملحوظات المضافة من الملف: { $val }
importing-notes-found-in-file = عدد الملحوظات الموجودة في الملف: { $val }
importing-notes-skipped-as-theyre-already-in = عدد الملحوظات المتخطاة لكونها موجودة في مجموعتك: { $val }
importing-notes-that-could-not-be-imported = الملحوظات التي لا يمكن استيرادها لأن نوع الملحوظة قد تغيّر: { $val }
importing-notes-updated-as-file-had-newer = عدد الملحوظات المحدثة لأن الملف له إصدار أحدث: { $val }
importing-packaged-anki-deckcollection-apkg-colpkg-zip = حزمة رزمة/مجموعة أنكي (*.apkg *.colpkg *.zip)
importing-pauker-18-lesson-paugz = درس Pauker 1.8 (*.pau.gz)
importing-rows-had-num1d-fields-expected-num2d = '%(row)s' له %(num1)d حقل، لكن المتوقع وجود %(num2)d حقل
importing-selected-file-was-not-in-utf8 = الملف المحدد ليس بصيغة UTF-8. الرجاء الرجوع إلى قسم الاستيراد في دليل الاستخدام.
importing-semicolon = فاصلة منقوطة
importing-skipped = مُتخطَّى
importing-supermemo-xml-export-xml = تصدير (xml.*) Supermemo XML
importing-tab = مفتاح Tab
importing-tag-modified-notes = أضف وسم إلى الملحوظات المعدلة:
importing-text-separated-by-tabs-or-semicolons = نص مفصول برموز جدولة أو فواصل منقوطة (*)
importing-the-first-field-of-the-note = يجب إيزاع الحقل الأول من نوع الملحوظة.
importing-the-provided-file-is-not-a = الملف المعطى ليس ملف .apkg صالحًا.
importing-this-file-does-not-appear-to = لا يبدو الملف ملف .apkg صالحًا. إذا كان الملف منزلَّا من أنكي ويب، من المحتمل أن التنزيل فشل. حاول مجددًا، وإذا استمرت المشكلة، حاول مجددًا باستخدام متصفح مختلف.
importing-this-will-delete-your-existing-collection = سيحذف هذا مجموعتك الحالية ويستبدلها بالبيانات في الملف الذي تستورده. هل أنت متأكد؟
importing-unable-to-import-from-a-readonly = يتعذر الاستيراد من ملف محمي ضد الكتابة.
importing-unknown-file-format = صيغة ملف غير معروفة.
importing-update-existing-notes-when-first-field = تحديث الملحوظات الموجودة عند تطابق الحقل الأول
importing-updated = تم التحديث
