preferences-automatically-sync-on-profile-openclose = مزامنة تلقائية عند فتح الملف الشخصي وإغلاقه
preferences-backups = نُسخ احتياطية
preferences-backups2 = نسخ احتياطية
preferences-backupsanki-will-create-a-backup-of = <html><head/><body dir="rtl"><p><span style=" font-weight:600;">النسخ الاحتياطي</span><br/>ينشئ أنكي نسخة احتياطية من مجموعتك كلما أُغلِق.</p></body></html>
preferences-basic = أساسي
preferences-change-deck-depending-on-note-type = تغيير الرزمة اعتمادًا على نوع الملحوظة
preferences-changes-will-take-effect-when-you = ستجري التغييرات عند إعادة تشغيل أنكي.
preferences-hours-past-midnight = ساعة بعد منتصف الليل
preferences-interface-language = لغة الواجهة:
preferences-interrupt-current-audio-when-answering = إيقاف التسجيل الصوتي الحالي عند الإجابة
preferences-keep = احتفظ بـ
preferences-learn-ahead-limit = حد التعلم المبكر
preferences-mins = دقيقة
preferences-network = الشبكة
preferences-next-day-starts-at = يبدأ اليوم التالي في
preferences-night-mode = الوضع الليلي
preferences-note-media-is-not-backed-up = ملحوظة: الوسائط غير منسوخة احتياطيًا. الرجاء نسخ مجلد أنكي الخاص بك احتياطيًا من وقت لآخر.
preferences-on-next-sync-force-changes-in = فرض التغييرات في جانب واحد عند المزامنة التالية
preferences-paste-clipboard-images-as-png = لصق الصور من الحافظة بصيغة PNG
preferences-paste-without-shift-key-strips-formatting = اللصق بدون الضغط على زر shift يزيل التنسيق
preferences-periodically-sync-media = مزامنة الوسائط من وقت لآخر
preferences-please-restart-anki-to-complete-language = أعد تشغيل أنكي لإكمال تغيير اللغة.
preferences-preferences = تفضيلات
preferences-scheduling = إعادة جدولة
preferences-show-learning-cards-with-larger-steps = عرض بطاقات التعلم ذات الخطوات الأكبر قبل المراجعات
preferences-show-next-review-time-above-answer = إظهار وقت المراجعة التالية فوق أزرار الإجابة
preferences-show-play-buttons-on-cards-with = إظهار أزرار التشغيل في البطاقات التي فيها تسجيلات صوتية
preferences-show-remaining-card-count-during-review = إظهار عدد البطاقات المتبقية أثناء المراجعة
preferences-some-settings-will-take-effect-after = ستُفعَّل بعض الإعدادات بعد إعادة تشغيل أنكي.
preferences-synchronisation = <b>مزامنة</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>مزامنة</b><br> ليست مفعلة حاليًا؛ اضغط زر المزامنة في النافذة الرئيسية للتفعيل.
preferences-synchronize-audio-and-images-too = مزامنة التسجيلات الصوتية والصور أيضًا
preferences-this-will-reset-any-cards-in = سيؤدي هذا إلى إعادة البطاقات في طور التعلم إلى بطاقات جديدة، ومسح الرزم المفلترة، وتغيير إصدار المجدول. هل تريد الاستمرار؟
preferences-timebox-time-limit = مهلة تقسيم المهام
preferences-user-interface-size = حجم واجهة المستخدم
preferences-when-adding-default-to-current-deck = معاملة الرزمة الحالية كرزمة افتراضية عند إضافة بطاقات
preferences-you-can-restore-backups-via-fileswitch = تستطيع استعادة النسخ الاحتياطية من خلال ملف>تبديل الملف الشخصي.
preferences-legacy-timezone-handling = طريقة المعالجة القديمة للمناطق الزمنية (فيها أخطاء، لكنها متطلبة لإصدارات أنكيدرويد من 2.14 وأقدم)
