profiles-anki-could-not-read-your-profile = لم يستطع أنكي قراءة بيانات ملفك الشخصي. أحجام النوافذ ومعلومات دخول المزامنة تم نسيانها.
profiles-anki-could-not-rename-your-profile = لم يستطع أنكي إعادة تسمية ملفك الشخصي لعدم استطاعته إعادة تسمية مجلد الملف الشخصي على القرص. تأكد من أن لديك الإذن بالكتابة إلى مجلد مستندات/أنكي وأنه لا توجد برامج أخرى تحاول الوصول إلى مجلدات ملفك الشخصي، ثم أعد المحاولة.
profiles-folder-already-exists = المجلد موجود مسبقًا.
profiles-open = فتح
profiles-open-backup = فتح نسخة احتياطية...
profiles-please-remove-the-folder-and = احذف المجلد { $val } ثم حاول مجددًا.
profiles-profile-corrupt = الملف الشخصي تالف
profiles-profiles = ملفات شخصية
profiles-quit = خروج
profiles-user-1 = مستخدم 1
