studying-again = مجددًا
studying-all-buried-cards = كل البطاقات المدفونة
studying-audio-5s = الصوت -5 ث
studying-audio-and5s = الصوت +5 ث
studying-buried-siblings = شقيقات مدفونة
studying-bury = دفن
studying-bury-card = دفن البطاقة
studying-bury-note = دفن الملحوظة
studying-card-buried = دُفِنت البطاقة.
studying-card-suspended = عُلِّقت البطاقة.
studying-card-was-a-leech = كانت البطاقة بطاقة مستعصية.
studying-cards-will-be-automatically-returned-to = ستعود البطاقات إلى رزمها الأصلية بعد أن تراجعها.
studying-continue = تابع
studying-delete-note = حذف الملحوظة
studying-deleting-this-deck-from-the-deck = .سيؤدي حذف هذه الرزمة من قائمة الرزم إلى عودة كل البطاقات المتبقية إلى رزمتها الأصلية
studying-easy = سهل
studying-edit = تحرير
studying-empty = إفراغ
studying-finish = إنهاء
studying-flag-card = تأشير البطاقة
studying-good = جيد
studying-hard = صعب
studying-it-has-been-suspended = عُلِّقت.
studying-manually-buried-cards = البطاقات المدفونة يدويًا
studying-mark-note = تعليم الملحوظة
studying-more = المزيد
studying-no-cards-are-due-yet = لا توجد بطاقات مستحقة بعد.
studying-note-buried = دُفِنت الملحوظة.
studying-note-suspended = عُلِّقت الملحوظة.
studying-pause-audio = إيقاف التسجيل الصوتي
studying-please-run-toolsempty-cards = استخدم أدوات>بحث عن بطاقات فارغة
studying-record-own-voice = تسجيل صوتك
studying-replay-own-voice = إعادة تشغيل صوتك
studying-show-answer = إظهار الجواب
studying-space = مفتاح المسافة
studying-study-now = ادرس الآن
studying-suspend = تعليق
studying-suspend-note = تعليق الملحوظة
studying-this-is-a-special-deck-for = هذه رزمة خاصة للدراسة خارج الجدول المعتاد.
studying-to-review = للمراجعة
studying-type-answer-unknown-field = أدخل الجواب: حقل غير معروف { $val }
studying-unbury = نكش
studying-what-would-you-like-to-unbury = ما الذي تريد نكشه؟
studying-you-havent-recorded-your-voice-yet = لم تسجّل صوتك بعد.
