change-notetype-current = Nuvarande
change-notetype-new = Ny
change-notetype-nothing = (Inget)
change-notetype-collapse = Minimera
change-notetype-expand = Expandera
change-notetype-will-discard-content = Innehållet på följande fält kommer raderas:
change-notetype-will-discard-cards = Följande kort kommer raderas:
change-notetype-fields = Fält
change-notetype-templates = Mallar
