notetypes-front-field = Framsida
notetypes-back-field = Baksida
notetypes-add-reverse-field = Lägg till Omvänt
notetypes-text-field = Text
notetypes-basic-name = Grundläggande
notetypes-basic-reversed-name = Bas (och omvänt kort)
notetypes-basic-optional-reversed-name = Bas (valbart omvänt kort)
notetypes-cloze-name = Lucktext
notetypes-basic-type-answer-name = Bas (skriv in svaret)
notetypes-card-2-name = Kort 2
notetypes-card-1-name = Kort 1
