preferences-automatically-sync-on-profile-openclose = Synka automatiskt när profil öppnas/stängs
preferences-backups = Säkerhetskopior
preferences-change-deck-depending-on-note-type = Ändra kortlek beroende på nottyp
preferences-changes-will-take-effect-when-you = Ändringar träder i kraft först när Anki startats om.
preferences-hours-past-midnight = timmar efter midnatt
preferences-language = Språk
preferences-interrupt-current-audio-when-answering = Pausa ljud medan svar skrivs in.
preferences-learn-ahead-limit = Gräns för inlärning i förväg
preferences-mins = min
preferences-network = Nätverk
preferences-next-day-starts-at = Nästa dag börjar
preferences-on-next-sync-force-changes-in = Vid nästa synkning, tvinga ändringar i en riktning
preferences-paste-clipboard-images-as-png = Klistra in bilder som PNG
preferences-paste-without-shift-key-strips-formatting = Inaktivera att shift-tangenten klistrar in utan formatering
preferences-periodically-sync-media = Synkronisera media regelbundet
preferences-please-restart-anki-to-complete-language = Starta om Anki för att slutföra ändringen av språk.
preferences-preferences = Inställningar
preferences-scheduling = Schemalägg igen
preferences-show-next-review-time-above-answer = Visa ny repetitionstid ovanför svarsknapparna
preferences-show-remaining-card-count = Visa antal återstående kort
preferences-some-settings-will-take-effect-after = Vissa inställningar blir aktiva först efter att du startat om Anki.
preferences-tab-synchronisation = Synkronisering
preferences-synchronize-audio-and-images-too = Synkronisera även ljud och bilder
preferences-timebox-time-limit = Tidsgräns för tidsfönster
preferences-when-adding-default-to-current-deck = När du lägger till, använd nuvarande kortlek som förval
preferences-default-search-text-example = t.ex. 'deck:current '
preferences-theme = Tema
preferences-theme-light = Ljust
preferences-theme-dark = Mörkt
preferences-always = Alltid
preferences-full-screen-only = Enbart fullskärmsläge
preferences-appearance = Utseende
preferences-general = Allmänt
preferences-account = AnkiWeb-konto
preferences-import-export = Importera/Exportera

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Grundläggande
preferences-media = Media
