actions-add = Қосу
actions-all-selected = Бөлшектенгеннің бәрі
actions-any-selected = Бөлшектенгеннің әр-бірі
actions-cancel = Болдырмау
actions-choose = Таңдау
actions-close = Жабу
actions-discard = Тастау
actions-copy = Көшіріп алу
actions-create-copy = Көшірме жасау
actions-custom-study = Жеке оқу
actions-decks = Колодалар
actions-decrement-value = Мәнді кеміту
actions-delete = Жою
actions-export = Әкету
actions-empty-cards = Бос карталар
actions-filter = Сүзгі
actions-help = Көмек
actions-increment-value = Мәнді өсірмелеу
actions-import = Әкелу
actions-manage = Басқару...
actions-name = Атау:
actions-new = Жаңа
actions-new-name = Жаңа атау:
actions-options = Баптаулар
actions-options-for = { $val } баптаулары
actions-preview = Көру
actions-rebuild = Қайта құру
actions-rename = Қайта атау
actions-rename-deck = Колоданы қайта атау
actions-rename-tag = Тамғаны қайта атау
actions-rename-with-parents = Аталықпен бірге қайта атау
actions-remove-tag = Тамғаны жою
actions-replay-audio = Дыбысты қайталау
actions-reposition = Жылжыту
actions-save = Сақтау
actions-search = Іздеу
actions-select = Бөлшектеу
actions-shortcut-key = Лақап пернесі: { $val }
actions-suspend-card = Картаны Кідірту
actions-set-due-date = Мерізім орнату
actions-answer-card = Жауап картасы
actions-unbury-unsuspend = Қайтару/Тірілту
actions-add-deck = Колода Қосу
actions-add-note = Жазба Қосу
actions-update-tag = Тамғаны жаңарту
actions-update-note = Жазбаны жаңарту
actions-update-card = Картаны жаңарту
actions-update-deck = Колоданы жаңарту
actions-forget-card = Картаны қалпына келтіру
actions-build-filtered-deck = Колода құру
actions-add-notetype = Жазба түрін қосу
actions-remove-notetype = Жазба түрін жою
actions-update-notetype = Жазба түрін жаңарту
actions-update-config = Конфигурацияны жаңарту
actions-card-info = Карта деректері
actions-previous-card-info = Алдыңғы картаның деректері
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-fullscreen-unsupported = Толық экран режимі сіздің бейне драйверіңізбен жұмыс істемейді. Баптаулар экранында басқа драйверге ауысып көріңіз.

## Flags

actions-flag-number = { $number } Белгі
actions-flag-red = Қызыл
actions-flag-orange = Жалқын
actions-flag-green = Жасыл
actions-flag-blue = Көк
actions-flag-pink = Қызғылт
actions-flag-turquoise = Перуза
actions-flag-purple = Күлгін
actions-set-flag = Белгілеу
actions-nothing-to-undo = Қайтаратын нәрсе жоқ
actions-nothing-to-redo = Қайта істейтін нәрсе жоқ
actions-auto-advance = Аутоілгерілу
actions-auto-advance-activated = Аутоілгерілу қосулы
actions-auto-advance-deactivated = Аутоілгерілу өшірулі
