card-stats-added = Қосылған
card-stats-first-review = Бірінші Шолу
card-stats-latest-review = Соңғы Шолу
card-stats-interval = Аралық
card-stats-ease = Жеңілдік
card-stats-review-count = Шолулар
card-stats-lapse-count = Ұмытшақтықтар
card-stats-average-time = Орташа Уақыт
card-stats-total-time = Жиынтық Уақыт
card-stats-new-card-position = Орын
card-stats-card-template = Карта Түрі
card-stats-note-type = Жазба Түрі
card-stats-deck-name = Колода
card-stats-preset = Белгіленім
card-stats-note-id = Жазба ID
card-stats-card-id = Карта ID
card-stats-review-log-rating = Баға
card-stats-review-log-type = түр
card-stats-review-log-date = Күн
card-stats-review-log-time-taken = Уақыт
card-stats-review-log-type-learn = Оқу
card-stats-review-log-type-review = Шолу
card-stats-review-log-type-relearn = Қайта Оқу
card-stats-review-log-type-filtered = Сүзілген
card-stats-review-log-type-manual = Нұсқаулық
card-stats-review-log-elapsed-time = Өткен Уақыт
card-stats-no-card = (Көрсететін карта жоқ.)
card-stats-custom-data = Бапталған Деректер
card-stats-fsrs-stability = Тұрақтылық
card-stats-fsrs-difficulty = Қиындық
card-stats-fsrs-retrievability = Еске түсірілімі
card-stats-fsrs-forgetting-curve-title = Ұмытылу қисығы
card-stats-fsrs-forgetting-curve-first-week = Бірінші Апта
card-stats-fsrs-forgetting-curve-first-month = Бірінші Ай
card-stats-fsrs-forgetting-curve-first-year = Бірінші Жыл
card-stats-fsrs-forgetting-curve-all-time = Толық Уақыт

## Window Titles

card-stats-current-card = Ағымдағы Карта ({ $context })
card-stats-previous-card = Алдыңғы Карта ({ $context })
