decks-add-new-deck-ctrlandn = Жаңа Колода Қосу (Ctrl+N)
decks-build = Құру
decks-cards-selected-by = карталарды таңдау:
decks-create-deck = Колода Жасау
decks_create_even_if_empty = Бос болса да колоданы жасау/жаңарту
decks-custom-steps-in-minutes = Жеке аралық (минут)
decks-deck = Колода
decks-decreasing-intervals = Азаятын аралықтар
decks-delete-deck = Колоданы Жою
decks-enable-second-filter = Екінші сүзгі қосу
decks-filter = Сүзгі:
decks-filter-2 = 2 Сүзгі
decks-get-shared = Бөлісу
decks-import-file = Файл Әкелу
decks-increasing-intervals = Артатын аралықтар
decks-latest-added-first = Соңғы қосылғын бірінші
decks-limit-to = Шектеу:
decks-minutes = минут
decks-most-lapses = Ең көп босау
decks-new-deck-name = Колоданың жаңа атауы:
decks-no-deck = [колода жоқ]
decks-oldest-seen-first = Алдымен ескілер көрінеді
decks-order-added = Қосу реті
decks-order-due = Мерізім реті
decks-please-select-something = Бірдіңе таңдаңыз.
decks-random = Кездейсоқ
decks-relative-overdueness = Салыстырмалы мерзімі өткендік
decks-repeat-failed-cards-after = Сәтсіз карталарды сосын қайталау
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = { $button } үшін іркілту
decks-reschedule-cards-based-on-my-answers = Колодадағы жауаптарым бойынша карталарды қайта жоспарлау
decks-study = Оқу
decks-study-deck = Колоданы Оқу
decks-filtered-deck-search-empty = Берілген іздеуге сәйкес карталар табылған жоқ. Кейбір карталар басқа сүзілген колодада немесе кідіртілген болуы себепті көрінбейді.
decks-unmovable-cards = Қамтылмаған карталарды көрсету
decks-learn-header = Оқу
# The count of cards waiting to be reviewed
decks-review-header = Бүгінге
