exporting-all-decks = Барлық Колода
exporting-anki-20-deck = Anki 2.0 Колодасы
exporting-anki-collection-package = Anki Жинақ Дестесі
exporting-anki-deck-package = Anki Колода Дестесі
exporting-cards-in-plain-text = Кәдімгі Мәтін Карталар
exporting-collection = жинақ
exporting-collection-exported = Жинақ әкетілді.
exporting-colpkg-too-new = Anki бағдарламасының соңғы нұсқасына жаңартыңыз, содан кейін .colpkg/.apkg файлын қайта әкеліңіз.
exporting-couldnt-save-file = Файлды сайтай алмады: { $val }
exporting-export = Әкету...
exporting-export-format = <b>Әкетілім пішімі</b>:
exporting-include = <b>Қамту</b>:
exporting-include-html-and-media-references = HTML және медиа сілтемелерін қамту
exporting-include-media = Медия қамту
exporting-include-scheduling-information = Жоспарлау деректерін қамту
exporting-include-deck-configs = Колода баптауларын қамту
exporting-include-tags = Тамғаларды қамту
exporting-support-older-anki-versions = Ескі Anki нұсқаларын қолдау (баяу/үлкен файлдар)
exporting-notes-in-plain-text = Кәдімгі Мәтін Жазбалар
exporting-selected-notes = Бөлшектенген Жазбалар
exporting-card-exported = { $count } карта әкетілді.
exporting-exported-media-file = { $count } медиа файлы әкетілді
exporting-note-exported = { $count } жазба әкетілді.
exporting-exporting-file = Файл әкетілуде...
exporting-processed-media-files = { $count } медиа файлы өзгертілді
exporting-include-deck = Колода атауын қамту
exporting-include-notetype = Жазба түрі атауын қамту
exporting-include-guid = жеке сәйкестендіргішті қамту
