preferences-automatically-sync-on-profile-openclose = Профиль ашылғанда/жабылғанда автоматты үйлестіру
preferences-backups = Сақтық көшірмелер
preferences-change-deck-depending-on-note-type = Жазба түріне қарай колоданы ауыстыру
preferences-changes-will-take-effect-when-you = Өзгерістер Anki-ді қайта қосқанда іске асады.
preferences-hours-past-midnight = сағат
preferences-language = Тіл
preferences-interrupt-current-audio-when-answering = Жауап бергенде аудионы кідірту
preferences-learn-ahead-limit = Асып оқу шектеуі
preferences-mins = минут
preferences-network = Үйлестіру
preferences-next-day-starts-at = Келесі күннің басталуы
preferences-media-is-not-backed-up = Медиа файлдары сақтық көшірмеге қосылмаған. Қауіпсіздік үшін Anki қалтасының мерзімді сақтық көшірмесін жасаңыз.
preferences-on-next-sync-force-changes-in = Келесі үйлестіруде өзгерістерді бір бағытта мәжбүрлеп үйлестіру.
preferences-paste-clipboard-images-as-png = Буферден көшірілген суреттерді PNG форматында қою.
preferences-paste-without-shift-key-strips-formatting = Shift пернесісіз қою мәтіннің пімімдеуін жояды.
preferences-generate-latex-images-automatically = LaTeX кескіндерін жасау (қауіпсіздік қатері)
preferences-latex-generation-disabled = LaTeX кескіндерін жасау баптауларда өшірілген.
preferences-periodically-sync-media = Медиа файлдарын мерізімді түрде үйлестіру
preferences-please-restart-anki-to-complete-language = Тіл өзгерісін аяқтау үшін Anki бағдарламасын қайта іске қосыңыз.
preferences-preferences = Баптаулар
preferences-scheduling = Жоспарлау
preferences-show-learning-cards-with-larger-steps = Шолу жасаудан бұрын қадамы үлкен карталарды көрсету
preferences-show-next-review-time-above-answer = Келесі шолу уақытын жауап беру түймелерінің үстінде көрсету
preferences-spacebar-rates-card = Бос орын пернесі (я enter) де картаға жауап береді
preferences-show-play-buttons-on-cards-with = Аудиолы карталарда ойнату түймесін көрсету
preferences-show-remaining-card-count = Қалған карта санын көрсету
preferences-some-settings-will-take-effect-after = Кейбір баптаулар Anki-ді қайта іске қосқаннан кейін іске асады.
preferences-tab-synchronisation = Үйлестіру
preferences-synchronize-audio-and-images-too = Аудио мен кескіндерді де үйлестіру
preferences-login-successful-sync-now = Кіру сәтті аяқталды. Баптауларды сақтап, қазір үйлестіру?
preferences-timebox-time-limit = Уақытты шектеу лимиті
preferences-user-interface-size = Интерфейс өлшемі
preferences-when-adding-default-to-current-deck = Қосу кезінде осы колоданы әдепкі ету
preferences-default-search-text = Әдепкі іздеу мәтіні
preferences-default-search-text-example = мыс. «deck:current»
preferences-theme = Тақырып
preferences-theme-follow-system = Жүйеге сүйену
preferences-theme-light = Ашық
preferences-theme-dark = Қою
preferences-v3-scheduler = V3 жоспарлаушысы
preferences-always = Әрдайым
preferences-full-screen-only = Тек толық экран
preferences-appearance = Көрініс
preferences-general = Жалпы
preferences-style = Стиль
preferences-review = Шолу
preferences-answer-keys = Жауап кілттері
preferences-distractions = Араласулар
preferences-minimalist-mode = Минималист режимі
preferences-editing = Өңдеу
preferences-browsing = Қарау
preferences-default-deck = Әдепкі колода
preferences-account = AnkiWeb тіркелгісі
preferences-note = Жазба
preferences-scheduler = Жопарлаушы
preferences-user-interface = Интерфейс
preferences-import-export = Әкелім/әкетілім

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Қарапайым
preferences-reviewer = Шолу
preferences-media = Медиа
preferences-not-logged-in = NO NEED TO TRANSLATE
