actions-add = افزودن
actions-all-selected = همۀ انتخاب شده‌ها
actions-any-selected = هر انتخاب‌شده
actions-cancel = لغو
actions-choose = انتخاب
actions-close = بستن
actions-discard = صرف‌نظر کردن
actions-copy = کپی
actions-create-copy = ایجاد رونوشت
actions-custom-study = مطالعۀ سفارشی
actions-decks = دسته‌ها
actions-decrement-value = کاستن
actions-delete = حذف
actions-export = خروجی‌گرفتن
actions-filter = فیلتر
actions-help = راهنما
actions-increment-value = افزایش
actions-import = وارد کردن
actions-manage = مدیریت…
actions-name = نام:
actions-new = جدید
actions-new-name = نام جدید:
actions-options = تنظیمات
actions-options-for = تنظیمات { $val }
actions-preview = پیش‌نمایش
actions-rebuild = بازسازی
actions-rename = تغییر نام
actions-rename-deck = تغییر نام دسته
actions-rename-tag = تغییر نام برچسب
actions-rename-with-parents = تغییر نام گروهی
actions-remove-tag = حذف برچسب
actions-replay-audio = بازپخش صوت
actions-reposition = جابه‌جا کردن
actions-save = ذخیره
actions-search = جست‌و‌جو
actions-select = برگزیدن
actions-shortcut-key = کلید میان‌بُر: { $val }
actions-suspend-card = تعلیق کارت
actions-set-due-date = تعیین زمان مرور
actions-answer-card = پاسخ به کارت
actions-unbury-unsuspend = لغو دفن/تعلیق
actions-add-deck = افزودن دسته
actions-add-note = افزودن یادداشت
actions-update-tag = به‌روز‌رسانی برچسب
actions-update-note = به‌روز‌رسانی یادداشت
actions-update-card = به‌روز‌رسانی کارت
actions-update-deck = به‌روز‌رسانی دسته
actions-forget-card = فراموش‌کردن کارت
actions-build-filtered-deck = ایجاد دسته
actions-add-notetype = افزودن نوع یادداشت
actions-remove-notetype = حذف نوع یادداشت
actions-update-notetype = به‌روزرسانی نوع یادداشت
actions-update-config = به‌روزرسانی کانفیگ
actions-card-info = اطلاعات کارت
actions-previous-card-info = اطلاعات کارت پیشین
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }…
actions-fullscreen-unsupported = درایور ویدئوی شما از حالت تمام‌صحفه پشتیبانی نمی‌کند. برای فعال‌سازی این قابلیت، از بخش تنظیمات، گزینۀ دیگری را انتخاب کنید.

## Flags

actions-flag-number = نشانه { $number }
actions-flag-red = قرمز
actions-flag-orange = نارنجی
actions-flag-green = سبز
actions-flag-blue = آبی
actions-flag-pink = صورتی
actions-flag-turquoise = فیروزه‌ای
actions-flag-purple = ارغوانی
actions-set-flag = نشانه‌گذاری
actions-nothing-to-undo = لغو ممکن نیست
actions-nothing-to-redo = تکرار ممکن نیست
actions-auto-advance = پیشروی خودکار
actions-auto-advance-activated = پیشروی خودکار: روشن
actions-auto-advance-deactivated = پیشروی خودکار: خاموش
