actions-add = افزودن
actions-all-selected = همۀ انتخاب شده‌ها
actions-any-selected = هر انتخاب‌شده
actions-cancel = لغو
actions-choose = انتخاب
actions-close = بستن
actions-discard = صرف‌نظر کردن
actions-copy = کپی
actions-create-copy = ایجاد رونوشت
actions-custom-study = مطالعۀ سفارشی
actions-decks = دسته‌ها
actions-decrement-value = کاستن
actions-delete = حذف
actions-export = خروجی‌گرفتن
actions-filter = فیلتر
actions-help = راهنما
actions-increment-value = افزایش
actions-import = وارد کردن
actions-manage = مدیریت…
actions-name = نام:
actions-new = جدید
actions-new-name = نام جدید:
actions-options = تنظیمات
actions-options-for = تنظیمات { $val }
actions-preview = پیش‌نمایش
actions-rebuild = بازسازی
actions-rename = تغییر نام
actions-rename-deck = تغییر نام دسته
actions-rename-tag = تغییر نام برچسب
actions-rename-with-parents = تغییر نام گروهی
actions-remove-tag = حذف برچسب
actions-replay-audio = بازپخش صوت
actions-reposition = جابه‌جا کردن
actions-save = ذخیره
actions-select = انتخاب
actions-shortcut-key = کلید میانبر: { $val }
actions-suspend-card = معلق کردن کارت
actions-set-due-date = انتخاب موعد مرور
actions-answer-card = پاسخ دادن به کارت
actions-unbury-unsuspend = لغو دفن/تعلیق
actions-add-deck = افزودن دسته
actions-add-note = افزودن یادداشت
actions-update-tag = به‌روز رسانی برچسب
actions-update-note = به‌روز رسانی یادداشت
actions-update-card = به‌روز رسانی کارت
actions-update-deck = به‌روز رسانی دسته
actions-forget-card = فراموش کردن کارت
actions-build-filtered-deck = ایجاد دسته
actions-add-notetype = افزودن نوع یادداشت
actions-remove-notetype = حذف نوع یادداشت
actions-update-notetype = به‌روز رسانی نوع یادداشت
actions-update-config = به‌روز رسانی کانفیگ
actions-card-info = مشخصات کارت
actions-previous-card-info = اطلاعات کارت قبلی
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }…
actions-fullscreen-unsupported = حالت تمام صفحه در درایور ویدئوی شما پشتیبانی نمیشود. از صفحهٔ ویژگی‌ها تلاش کنید از یکی دیگر استفاده کنید.

## Flags

actions-flag-number = نشان { $number }
actions-flag-red = قرمز
actions-flag-orange = نارنجی
actions-flag-green = سبز
actions-flag-blue = آبی
actions-flag-pink = صورتی
actions-flag-turquoise = فیروزه‌ای
actions-flag-purple = ارغوانی
actions-set-flag = تنظیم نشان
actions-nothing-to-undo = عملی برای لغو وجود ندارد
actions-nothing-to-redo = عملی برای برگرداندن وجود ندارد
actions-auto-advance = پیشروی خودکار
