browsing-add-notes = افزودن یادداشت...
browsing-add-tags = افزودن برچسب
browsing-add-tags2 = افزودن برچسب...
browsing-added-today = امروز اضافه شده
browsing-addon = افزونه
browsing-again-today = دوباره امروز
browsing-all-card-types = همۀ انواع کارت
browsing-all-fields = تمام فیلدها
browsing-answer = پاسخ
browsing-any-cards-mapped-to-nothing-will = هر کارت نشانه‌گذاری شده به هیچ چیز حذف خواهد شد. اگر یک یادداشت بدون کارت باقی بماند حذف خواهد شد. آیا از انجام این عمل اطمینان دارد؟
browsing-any-flag = هر نشان
browsing-browser-appearance = نمایش مرورگر
browsing-browser-options = اختیارات مرورگر
browsing-buried = دفن شده
browsing-card = کارت
browsing-card-list = فهرست کارت‌ها
browsing-card-state = وضعیت کارت
browsing-cards-cant-be-manually-moved-into = کارت‌ها بصورت دستی قابل انتقال به یک دسته فیلتر شده نیستند.
browsing-change-deck = تغییر دسته
browsing-change-deck2 = تغییر دسته…
browsing-change-note-type = تغییر نوع یادداشت
browsing-change-note-type2 = تغییر نوع یادداشت...
browsing-change-to = تغییر دادن { $val } به:
browsing-clear-unused = پاک کردن استفاده نشده
browsing-clear-unused-tags = پاک کردن برچسب‌های استفاده نشده
browsing-created = ایجادشده
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = دستۀ فعلی
browsing-current-note-type = نوع یادداشت فعلی:
browsing-delete-notes = حذف یادداشت
browsing-delete-tags = حذف برچسب‌ها
browsing-duplicate = تکراری
browsing-ease = سهولت
browsing-end = پایان
browsing-enter-tags-to-add = برچسب‌ها را برای افزودن وارد کنید:
browsing-enter-tags-to-delete = برچسب‌ها را بری حذف کردن وارد کنید:
browsing-filter = فیلتر...
browsing-filtered = (فیلترشده)
browsing-find = <b>یافتن</b>:
browsing-find-and-replace = یافتن و جایگزین کردن
browsing-find-duplicates = یافتن تکراری‌ها
browsing-first-card = اولین کارت
browsing-flag = نشان
browsing-font = <b>فونت</b>:
browsing-font-size = <b>سایز فونت</b>:
browsing-found-as-across-bs = پیدا شده{ $part } سرتاسر { $whole }.
browsing-home = خانه
browsing-ignore-case = نادیده گرفتن مورد
browsing-in = <b>در</b>:
browsing-interval = بازه زمانی
browsing-last-card = آخرین کارت
browsing-learning = (یادگیری)
browsing-line-size = <b>اندازه خطوط</b>:
browsing-manage-note-types = مدیریت نوع یادداشت...
browsing-move-cards = انتقال کارت‌ها
browsing-move-cards-to-deck = انتقال کارت‌ها به دسته:
browsing-nd-names = { $num }:{ $name }
browsing-new = (جدید)
browsing-new-note-type = نوع کارت جدید:
browsing-no-flag = بدون نشان
browsing-note = یادداشت
browsing-notes-tagged = یادداشت‌ها برچسب‌گذاری شدند.
browsing-nothing = هیچ‌چیز
browsing-only-new-cards-can-be-repositioned = فقط کارت‌های جدید قابلیت تغییر موقعیت را دارند.
browsing-optional-filter = فیلتر اختیاری:
browsing-override-back-template = بازنویسی قالب پشت کارت :
browsing-override-font = لغو فونت :
browsing-override-front-template = بازنویسی قالب روی کارت:
browsing-place-at-end-of-new-card = در انتهای صف کار‌تهای جدید قرار بده
browsing-place-in-review-queue-with-interval = در آخر صف کارتهای مرور قرار بگیرد با بازه زمانی بین:
browsing-please-give-your-filter-a-name = لطفاً فایل خود را نامگذاری کنید:
browsing-please-select-cards-from-only-one = لطفاً کارت‌ها را فقط از یک نوع یادداشت انتخاب کنید.
browsing-preview-selected-card = پیش‌نمایش کارت‌های انتخاب شده ({ $val })
browsing-question = پرسش
browsing-queue-bottom = انتهای صف: { $val }
browsing-queue-top = بالای صف: { $val }
browsing-randomize-order = مخلوط کردن چیدمان
browsing-remove-current-filter = پاک کردن فیلتر کنونی...
browsing-remove-from-your-saved-searches = پاک کردن { $val } از جستجوهای ذخیره شدۀ شما؟
browsing-remove-tags = پاک کردن برچسب‌ها...
browsing-replace-with = <b>جایگزینی با</b>:
browsing-reposition = تغییر موقعیت ...
browsing-reposition-new-cards = تغییر موقعیت کارت‌های جدید
browsing-reschedule = زمان‌بندی کردن مجدد
browsing-save-current-filter = ذخیرۀ فیلتر کنونی...
browsing-search-in = جستجو در:
browsing-search-within-formatting-slow = جستجو در قالب (کند)
browsing-shift-position-of-existing-cards = موقعیت کارتهای موجود را تغییر دهید
browsing-sidebar = نوار کناری
browsing-sort-field = فیلد دسته‌بندی
browsing-sorting-on-this-column-is-not = مرتب سازی بر اساس این ستون پشتیبانی نشده است. لطفا یکی دیگر را انتخاب کنید.
browsing-start-position = موقعیت شروع:
browsing-step = گام:
browsing-studied-today = امروز مطالعه شده
browsing-suspended = معلق شده
browsing-tag-duplicates = برچسب‌گذاری تکراری‌ها
browsing-target-field = فیلد هدف:
browsing-today = امروز
browsing-toggle-mark = تغییر وضعیت علامت
browsing-toggle-suspend = تغییر وضعیت تعلیق
browsing-treat-input-as-regular-expression = تلقی ورودی به عنوان یک بیان با قاعده
browsing-type-here-to-search = <جهت جستجو اینجا تایپ کنید; برای نمایش دسته فعلی اینتر را فشار دهید>
browsing-whole-collection = تمام مجموعه
browsing-you-must-have-at-least-one = حداقل باید یک ستون داشته باشید.
browsing-group =
    { $count ->
       *[other] { $count } گروه
    }
browsing-note-count =
    { $count ->
       *[other] { $count } یادداشت
    }
browsing-note-deleted =
    { $count ->
       *[other] { $count } کارت حذف شد.
    }
browsing-window-title = جستجو (تعداد { $selected } از { $total } کارت انتخاب شده‌اند)
