card-stats-added = اضافه‌شده
card-stats-first-review = نخستین مرور
card-stats-latest-review = آخرین مرور
card-stats-interval = بازه زمانی
card-stats-ease = سهولت
card-stats-review-count = مرورها
card-stats-lapse-count = دورهای سپری شده
card-stats-average-time = میانگین زمان
card-stats-total-time = زمان کل
card-stats-new-card-position = موقعیت
card-stats-card-template = نوع کارت
card-stats-note-type = نوع یادداشت
card-stats-deck-name = دسته
card-stats-card-id = شماره کارت
