editing-add-media = افزودن رسانه
editing-an-error-occurred-while-opening = یک خطا هنگام باز کردن رخ داده است { $val }
editing-attach-picturesaudiovideo-f3 = پیوست کردن عکس/صدا/فیلم (F3)
editing-bold-text-ctrlandb = متن بولد (Ctrl+B)
editing-cards = کارت‌ها
editing-change-colour-f8 = تغییر رنگ (F8)
editing-cloze-deletion-ctrlandshiftandc = ایجاد جاخالی (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = ضبط صدا ممکن نیست. آیا ‘lame’ را نصب کرده‌اید؟
editing-customize-card-templates-ctrlandl = ویرایش قالب‌های کارت (Ctrl+L)
editing-customize-fields = شخصی‌سازی فیلدها
editing-cut = برش
editing-edit-current = ویرایش فعلی
editing-edit-html = ویرایش HTML
editing-fields = فیلدها
editing-html-editor = ویرایشگر HTML
editing-italic-text-ctrlandi = متن کج (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = رفتن به برچسب‌ها ‫با کنترل+شیفت+T
editing-latex = LaTeX
editing-latex-equation = معادله LaTeX
editing-latex-math-env = محیط ریاضی LaTeX.
editing-mathjax-block = بلوک MathJax
editing-mathjax-chemistry = فرمول شیمی MathJax
editing-mathjax-inline = ‫MathJax درون خطی
editing-media = رسانه
editing-paste = جاگذاری
editing-record-audio-f5 = ضبط صدا (F5)
editing-remove-formatting-ctrlandr = پارک کردن تزئین (Ctrl+R)
editing-set-foreground-colour-f7 = تنظیم رنگ پیش‌زمینه (F7)
editing-show-duplicates = نمایش تکراریها
editing-subscript-ctrland = زیرنویس (=+Ctrl)
editing-superscript-ctrlandand = بالانویس (++Ctrl)
editing-tags = برچسب‌ها
editing-to-make-a-cloze-deletion-on = برای ایجاد جاخالی روی یادداشت موجود، اول باید نوع یادداشت را از مسیر 'یادداشت‌ها>تغییر نوع یادداشت' تغییر دهید
editing-underline-text-ctrlandu = خط کشیدن زیر متن (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = اخطار، جای خالی تا وقتی که شما نوع را از بالا به جای خالی تغییر ندهید بطور صحیح کار نخواهد کرد.
