profiles-anki-could-not-read-your-profile = آنکی قادر به خواند اطلاعات پروفایل شما نبود. اندازۀ پنجره و اطلاعات همگام‌سازی اکانت فراموش شده‌اند.
profiles-anki-could-not-rename-your-profile = آنکی به دلیل ناتوانی در نامگذاری مجدد پوشۀ پروفایل شما روی هارد درایو، قادر به نامگذاری مجدد پروفایل شما نیست. لطفاً از اینکه اجازۀ ویرایش مسیر Documents/Anki را دارید و هیچ نرم‌افزار دیگری در حال استفاده از پوشۀ پروفایل شما نیست اطمینان حاصل کرده و مجدداً تلاش کنید.
profiles-folder-already-exists = پوشه از قبل وجود دارد.
profiles-open = باز کردن
profiles-open-backup = باز کردن پشتیبان…
profiles-please-remove-the-folder-and = لطفاً پوشۀ { $val } را حذف کرده و دوباره امتحان کنید.
profiles-profile-corrupt = پروفایل خراب است
profiles-profiles = پروفایل‌ها
profiles-quit = خروج
profiles-user-1 = کاربر 1
