actions-add = Magdagdag
actions-all-selected = Napili lahat
actions-any-selected = Kahit ano ang napili
actions-cancel = Kanselahin
actions-choose = Piliin
actions-close = Isara
actions-copy = Kopyahin
actions-create-copy = Gumawa ng kopya
actions-custom-study = Sadyang Pag-aaral
actions-decks = Mga Deck
actions-decrement-value = Halaga ng pagbabawas
actions-delete = I-delete
actions-export = I-export
actions-filter = I-filter
actions-help = Humingi ng tulong
actions-increment-value = Halaga ng pagdagdag
actions-import = I-import
actions-manage = Asikasuhin...
actions-name = Pangalan:
actions-new = Gumawa ng bago
actions-new-name = Bagong pangalan:
actions-options = Mga Opsiyon
actions-options-for = Mga Opsiyon para sa
actions-preview = Tingnan
actions-rebuild = Muling itayo
actions-rename = Baguhin ang pangalan
actions-rename-deck = Baguhin ang pangalan ng Deck
actions-rename-tag = Baguhin ang pangalan ng Tag
actions-rename-with-parents = Baguhin ang pangalan pati ng Magulang
actions-remove-tag = Tanggalin ang Tag
actions-replay-audio = Patugtugin ulit
actions-reposition = Baguhin ang puwesto
actions-save = I-save
actions-search = Maghanap
actions-select = Pumili
actions-shortcut-key = Pipindutin para sa shortcut:
actions-suspend-card = Tigilin ang card
actions-set-due-date = Itakda kung kailan ulit lilitaw
actions-answer-card = Sagutin ang card
actions-unbury-unsuspend = Ituloy ang card
actions-add-deck = Magdagdag ng Deck
actions-add-note = Magdagdag ng Note
actions-update-tag = I-update ang Tag
actions-update-note = I-update ang Note
actions-update-card = I-update ang Card
actions-update-deck = I-update ang Deck
actions-forget-card = Limutin ang Card
actions-build-filtered-deck = Itayo ang Deck
actions-add-notetype = Magdagdag ng Notetype
actions-remove-notetype = Tanggalin ang Notetype
actions-update-notetype = I-update ang Notetype
actions-update-config = I-update ang Config
actions-card-info = Impormasyon ng Card
actions-previous-card-info = Impormasyon ng nakaraang card
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = ...
actions-currently-unsupported = Ang kilos na ito ay kasalukuyang hindi sinusuportahan sa sistema mo.

## Flags

actions-flag-number = Flag
actions-flag-red = Pula
actions-flag-orange = Kahel
actions-flag-green = Berde
actions-flag-blue = Asul
actions-flag-pink = Rosas
actions-flag-turquoise = Turkesa
actions-flag-purple = Lila
actions-set-flag = Mag-set ng Flag
