actions-add = Adicionar
actions-all-selected = Todos selecionados
actions-blue-flag = Marcador Azul
actions-cancel = Cancelar
actions-choose = Escolher
actions-close = Fechar
actions-copy = Copiar
actions-custom-study = Estudo Personalizado
actions-decks = Baralhos
actions-delete = Excluir
actions-export = Exportar
actions-filter = Filtro
actions-green-flag = Marcador Verde
actions-help = Ajuda
actions-import = Importar
actions-manage = Gerenciar...
actions-name = Nome:
actions-new = Novos
actions-new-name = Novo nome:
actions-options = Opções
actions-options-for = Opções para { $val }
actions-orange-flag = Marcador Laranja
actions-preview = Pré-visualização
actions-rebuild = Recriar
actions-red-flag = Marcador Vermelho
actions-rename = Renomear
actions-rename-deck = Renomear Baralho
actions-replay-audio = Repetir Áudio
actions-reposition = Reposicionar
actions-save = Salvar
actions-search = Procurar
actions-shortcut-key = Tecla de Atalho: { $val }
actions-suspend-card = Suspender Cartão
