actions-add = Adicionar
actions-all-selected = Todos selecionados
actions-any-selected = Qualquer selecionado
actions-cancel = Cancelar
actions-choose = Escolher
actions-close = Fechar
actions-copy = Copiar
actions-custom-study = Estudo Personalizado
actions-decks = Baralhos
actions-delete = Excluir
actions-export = Exportar
actions-filter = Filtro
actions-help = Ajuda
actions-import = Importar
actions-manage = Gerenciar...
actions-name = Nome:
actions-new = Novos
actions-new-name = Novo nome:
actions-options = Opções
actions-options-for = Opções para { $val }
actions-preview = Pré-visualização
actions-rebuild = Recriar
actions-rename = Renomear
actions-rename-deck = Renomear Baralho
actions-rename-tag = Renomear Etiqueta
actions-rename-with-parents = Renomear com Parentes
actions-remove-tag = Remover Tag
actions-replay-audio = Repetir Áudio
actions-reposition = Reposicionar
actions-save = Salvar
actions-search = Procurar
actions-select = Selecionar
actions-shortcut-key = Tecla de Atalho: { $val }
actions-suspend-card = Suspender Carta
actions-set-due-date = Definir Data de Revisão
actions-forget = Esquecerﾠ
actions-answer-card = Responder Carta
actions-unbury-unsuspend = Remover Ocultação/Suspensão
actions-add-deck = Adicionar Baralho
actions-add-note = Adicionar Nota
actions-update-tag = Atualizar Tag
actions-update-note = Atualizar Nota
actions-update-card = Atualizar Carta
actions-update-deck = Atualizar baralho
actions-forget-card = Esquecer Carta
actions-build-filtered-deck = Criar Baralho
actions-expand-collapse = Expandir/Recolher
actions-add-notetype = Adicionar Tipo de Notaﾠ
actions-remove-notetype = Remover Tipo de Nota
actions-update-notetype = Atualizar Tipo de Notaﾠ
actions-update-config = Atualizar Configurações
actions-card-info = Informação da Carta
actions-previous-card-info = Informação da Carta Anterior

## Flags

actions-flag-number = Bandeira { $number }
actions-flag-red = Vermelho
actions-flag-orange = Laranja
actions-flag-green = Verde
actions-flag-blue = Azul
actions-flag-pink = Rosa
actions-flag-turquoise = Turquesa
actions-flag-purple = Roxo
actions-set-flag = Definir Bandeira
