adding-add-shortcut-ctrlandenter = Adicionar (atalho: Ctrl+Enter)
adding-added = Adicionado
adding-discard-current-input = Descartar entrada atual?
adding-keep-editing = Continuar Editando
adding-edit = Editar "{ $val }"
adding-history = Histórico
adding-note-deleted = (Nota deletada)
adding-shortcut = Atalho: { $val }
adding-the-first-field-is-empty = O primeiro campo está vazio.
adding-you-have-a-cloze-deletion-note = Você tem uma nota do tipo omissão de palavras, mas não fez nenhuma omissão. Continuar?
adding-cloze-outside-cloze-notetype = Omissões podem apenas ser usadas no tipo de nota "Omissão de palavras".
adding-cloze-outside-cloze-field = Omissões podem apenas ser usadas no campos que usam o filtro 'cloze:'. Normalmente o primeiro campo.
