browsing-add-notes = Adicionar Notas...
browsing-add-tags = Adicionar etiquetas
browsing-add-tags2 = Adicionar Etiquetas...
browsing-added-today = Adicionado hoje
browsing-addon = Extensão
browsing-again-today = Repetir Hoje
browsing-all-card-types = Todos os Tipos de Cartões
browsing-all-fields = Todos os Campos
browsing-answer = Resposta
browsing-any-cards-mapped-to-nothing-will = Todos os cartões em branco serão excluídos. Se uma nota não tiver um cartão referente, será descartada. Você tem certeza que quer continuar?
browsing-any-flag = Qualquer emblema
browsing-browser-appearance = Aparência do Painel
browsing-browser-options = Opções do Painel de Cartões
browsing-buried = Enterrado
browsing-card = Cartão
browsing-card-list = Lista de Cartões
browsing-card-state = Estado do Cartão
browsing-cards-cant-be-manually-moved-into = Os cartões não podem ser movidos manualmente dentro de um baralho filtrado.
browsing-change-deck = Mudar Baralho
browsing-change-deck2 = Mudar Baralho...
browsing-change-note-type = Mudar Tipo de Nota
browsing-change-note-type2 = Mudar Tipo de Nota...
browsing-change-to = Mudar { $val } para:
browsing-clear-unused = Limpar Não-usado
browsing-clear-unused-tags = Limpar Etiquetas Não-usadas
browsing-created = Criado
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = Baralho Atual
browsing-current-note-type = Tipo de nota atual:
browsing-delete-notes = Excluir Notas
browsing-delete-tags = Apagar Etiquetas
browsing-duplicate = duplicata
browsing-ease = Dificuldade
browsing-end = Fim
browsing-enter-tags-to-add = Digite as etiquetas a adicionar:
browsing-enter-tags-to-delete = Digite as etiquetas a apagar:
browsing-filter = Filtrar...
browsing-filtered = (filtrado)
browsing-find = <b>Localizar</b>:
browsing-find-and-replace = Localizar e substituir
browsing-find-duplicates = Encontrar Duplicatas
browsing-first-card = Primeiro Cartão
browsing-flag = Marcador
browsing-font = <b>Fonte</b>:
browsing-font-size = <b>Tamanho da Fonte</b>:
browsing-found-as-across-bs = Encontrar %(a)s através de %(b)s.
browsing-home = Início
browsing-ignore-case = Ignorar maiúsculas / minúsculas
browsing-in = <b>Em</b>:
browsing-interval = Intervalo
browsing-last-card = Último Cartão
browsing-learning = (estudando)
browsing-line-size = <b>Tamanho da Linha</b>:
browsing-manage-note-types = Gerenciar Tipos de Notas...
browsing-move-cards = Mover Cartões
browsing-move-cards-to-deck = Mover cartões para o baralho:
browsing-nd-names = %(n)d: %(name)s
browsing-new = (novo)
browsing-new-note-type = Novo tipo de nota:
browsing-no-flag = Sem Marcador
browsing-note = Nota
browsing-notes-tagged = Notas marcadas.
browsing-nothing = Nada
browsing-only-new-cards-can-be-repositioned = Somente os cartões novos podem ser reposicionados.
browsing-optional-filter = Flitro Opcional
browsing-override-back-template = Substituir modelo do verso:
browsing-override-font = Substituir frente:
browsing-override-front-template = Substituir modelo da frente:
browsing-place-at-end-of-new-card = Colocar no fim da fila de novos cartões.
browsing-place-in-review-queue-with-interval = Colocar na fila de revisão com intervalo entre:
browsing-please-give-your-filter-a-name = Por favor, dê um nome ao seu filtro:
browsing-please-select-cards-from-only-one = Por favor, escolhar cartões de somente um tipo de nota.
browsing-preview-selected-card = Pré-vizualizar os cartão selecionado ({ $val }).
browsing-question = Pergunta
browsing-queue-bottom = Último da fila: { $val }
browsing-queue-top = Primeiro da fila: { $val }
browsing-randomize-order = Ordem aleatória
browsing-remove-current-filter = Remover Filtro Atual...
browsing-remove-from-your-saved-searches = Remover { $val } de suas pesquisas salvas?
browsing-remove-tags = Remover Etiquetas...
browsing-replace-with = <b>Substituir Por</b>:
browsing-reposition = Reposicionar...
browsing-reposition-new-cards = Reposicionar Novos Cartões
browsing-reschedule = Reagendar
browsing-save-current-filter = Salvar Filtro Atual...
browsing-search-in = Procurar em:
browsing-search-within-formatting-slow = Procurar com formatação (lento)
browsing-shift-position-of-existing-cards = Alterar posição dos cartões existentes
browsing-sidebar = Barra Lateral
browsing-sort-field = Classificar Campo
browsing-sorting-on-this-column-is-not = Não é possível classificar esta coluna. Por favor, escolha outra.
browsing-start-position = Posição inicial:
browsing-step = Passo:
browsing-studied-today = Estudados Hoje
browsing-suspended = Suspenso
browsing-tag-duplicates = Etiquetas Duplicadas
browsing-target-field = Campo alvo:
browsing-today = Hoje
browsing-toggle-mark = Marcar/Desmarcar
browsing-toggle-suspend = Suspender (sim/não)
browsing-treat-input-as-regular-expression = Tratar texto como expressão regular
browsing-type-here-to-search = <digite aqui para pesquisar; tecle enter para mostrar o baralho atual>
browsing-whole-collection = Coleção inteira
browsing-you-must-have-at-least-one = É preciso ter ao menos uma coluna.
