custom-study-must-rename-deck = Por favor, primeiro renomeie o já existente baralho Estudo Personalizado.
custom-study-all-cards-in-random-order-dont = Todos os cartões em ordem aleatória (não reagendar)
custom-study-all-review-cards-in-random-order = Todos os cartões estudados em ordem aleatória
custom-study-cards = cartões
custom-study-cards-from-the-deck = cartões do baralho
custom-study-choose-tags = Escolha etiquetas.
custom-study-custom-study-session = Sessão de Estudo Personalizado
custom-study-due-cards-only = Apenas cartões devidos.
custom-study-increase-todays-new-card-limit = Aumentar o limite de cartões novos por hoje
custom-study-increase-todays-new-card-limit-by = Aumentar o limite de cartões novos de hoje em
custom-study-increase-todays-review-card-limit = Aumentar o limite de cartões a revisar hoje
custom-study-increase-todays-review-limit-by = Aumentar o limite de cartões a revisar hoje em
custom-study-new-cards-in-deck-over-today = Novos cartões no baralho acima do limite de hoje: { $val }
custom-study-new-cards-only = Somente cartões novos.
custom-study-no-cards-matched-the-criteria-you = Nenhum cartão atende aos seus critérios.
custom-study-ok = Aceitar
custom-study-preview-new-cards = Visualizar cartões novos
custom-study-preview-new-cards-added-in-the = Visualizar cartões novos criados por último
custom-study-require-one-or-more-of-these = Deve ter pelo menos uma dessas etiquetas:
custom-study-review-ahead = Antecipar a revisão
custom-study-review-ahead-by = Antecipar a revisão dos próximos
custom-study-review-cards-forgotten-in-last = Revisar os cartões esquecidos nos últimos
custom-study-review-forgotten-cards = Revisar os cartões esquecidos
custom-study-reviews-due-in-deck-over-today = Limite de revisões pendentes no baralho, por hoje: { $val }
custom-study-select = Selecionar
custom-study-select-tags-to-exclude = Excluir cartões com as etiquetas:
custom-study-selective-study = Estudo Seletivo
custom-study-study-by-card-state-or-tag = Estudando pelo status do cartão ou etiqueta
