custom-study-must-rename-deck = Por favor, primeiro renomeie o já existente baralho Estudo Personalizado.
custom-study-all-cards-in-random-order-dont = Todos as cartas em ordem aleatória (não reagendar)
custom-study-all-review-cards-in-random-order = Todos as cartas estudadas em ordem aleatória
custom-study-cards = cartas
custom-study-cards-from-the-deck = cartas do baralho
custom-study-choose-tags = Escolha etiquetas.
custom-study-custom-study-session = Sessão de Estudo Personalizado
custom-study-due-cards-only = Apenas cartas a revisar.
custom-study-increase-todays-new-card-limit = Aumentar o limite de novas cartas por hoje
custom-study-increase-todays-new-card-limit-by = Aumentar o limite de novas cartas de hoje em
custom-study-increase-todays-review-card-limit = Aumentar o limite de cartas a revisar hoje
custom-study-increase-todays-review-limit-by = Aumentar o limite de cartões a revisar hoje em
custom-study-new-cards-in-deck-over-today = Novas cartas no baralho acima do limite de hoje: { $val }
custom-study-new-cards-only = Somente cartas novas.
custom-study-no-cards-matched-the-criteria-you = Nenhuma carta atende aos seus critérios.
custom-study-ok = Aceitar
custom-study-preview-new-cards = Visualizar novas cartas
custom-study-preview-new-cards-added-in-the = Visualizar novas cartas criadas por último
custom-study-require-one-or-more-of-these = Deve ter pelo menos uma dessas etiquetas:
custom-study-review-ahead = Antecipar a revisão
custom-study-review-ahead-by = Antecipar a revisão dos próximos
custom-study-review-cards-forgotten-in-last = Revisar as cartas esquecidas por último
custom-study-review-forgotten-cards = Revisar as cartas esquecidas
custom-study-reviews-due-in-deck-over-today = Limite de revisões pendentes no baralho, por hoje: { $val }
custom-study-select = Selecionar
custom-study-select-tags-to-exclude = Excluir cartões com as etiquetas:
custom-study-selective-study = Estudo Seletivo
custom-study-study-by-card-state-or-tag = Estudar pelo estado da carta ou etiqueta
