decks-add-new-deck-ctrlandn = Criar Novo Baralho (Ctrl+N)
decks-are-you-sure-you-wish-to = Você tem certeza que deseja excluir { $val }?
decks-build = Criar
decks-cards-selected-by = cartões selecionados por
decks-create-deck = Criar Baralho
decks-custom-steps-in-minutes = Etapas personalizadas (em minutos)
decks-deck = Baralho
decks-decreasing-intervals = Mais distantes a estudar/revisar
decks-delete-deck = Excluir Baralho
decks-enable-second-filter = Habilite o segundo filtro
decks-filter = Filtro:
decks-filter-2 = Filtro 2
decks-get-shared = Obter Compartilhado
decks-import-file = Importar Arquivo
decks-increasing-intervals = Mais próximos a estudar/revisar
decks-latest-added-first = Criados há menos tempo
decks-limit-to = Limitar a
decks-minutes = minutos
decks-most-lapses = Mais falhas
decks-name-for-deck = Nome do baralho:
decks-new-deck-name = Novo nome do baralho:
decks-no-deck = [sem baralho]
decks-oldest-seen-first = Mais antiga data do primeiro estudo
decks-order-added = Criados há mais tempo
decks-order-due = Revisões mais próximas
decks-please-select-something = Por favor, selecione algo.
decks-random = Aleatório
decks-relative-overdueness = Atrasos relativos
decks-repeat-failed-cards-after = Repita os cartões com falha depois
decks-reschedule-cards-based-on-my-answers = Reagendar cartões baseado nas minhas respostas neste baralho
decks-study = Estudar
decks-study-deck = Estudar Baralho
decks-the-provided-search-did-not-match = A pesquisa não encontrou nenhum cartão. Gostaria de alterá-la?
