editing-add-media = Adicionar Mídia
editing-an-error-occurred-while-opening = Ocorreu um erro ao abrir { $val }
editing-attach-picturesaudiovideo-f3 = Anexar imagens/áudio/vídeo (F3)
editing-bold-text-ctrlandb = Texto em Negrito (Ctrl+B)
editing-cards = Cartões
editing-change-colour-f8 = Mudar cor (F8)
editing-cloze-deletion-ctrlandshiftandc = Omissão de palavras (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Não foi possível efetuar a gravação de áudio. Você já tentou instalar o pacote "lame" da sua distribuição?
editing-customize-card-templates-ctrlandl = Personalizar modelos de cartão (Ctrl + L)
editing-customize-fields = Personalizar Campos
editing-cut = Recortar
editing-edit-current = Editar Atual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-html-editor = Editor HTML
editing-italic-text-ctrlandi = Texto em Itálico (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Ir para etiquetas com Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Equação LaTeX
editing-latex-math-env = Matemática LaTeX
editing-mathjax-block = bloco MathJax
editing-mathjax-chemistry = Utilizar formato de entrada MathJax para equações químicas
editing-mathjax-inline = MathJax em linha
editing-media = Mídia
editing-paste = Colar
editing-record-audio-f5 = Gravar áudio (F5)
editing-remove-formatting-ctrlandr = Remover Formatação (Ctrl+R)
editing-set-foreground-colour-f7 = Definir cor de primeiro plano (F7)
editing-show-duplicates = Mostrar Duplicatas
editing-subscript-ctrland = Subscrito (Ctrl+=)
editing-superscript-ctrlandand = Superscrito (Ctrl++)
editing-tags = Etiquetas
editing-to-make-a-cloze-deletion-on = Para omitir palavras em uma nota existente, você precisa mudá-la para o tipo Omissão de Palavras primeiro, em 'Editar>Mudar Tipo de Nota'
editing-underline-text-ctrlandu = Texto Sublinhado (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Atenção, omissões de palavras não funcionarão até que você mude o tipo na parte superior para Omissão de Palavras.
