editing-actual-size = Alternar tamanho real
editing-add-media = Adicionar Mídia
editing-align-left = Alinhar à esquerda
editing-align-right = Alinhar à direita
editing-an-error-occurred-while-opening = Ocorreu um erro ao abrir { $val }
editing-attach-picturesaudiovideo = Anexar imagens/áudio/vídeo
editing-bold-text = Texto em negrito
editing-cards = Cartões
editing-center = Centro
editing-change-color = Mudar a cor
editing-cloze-deletion = Omissão de palavras
editing-couldnt-record-audio-have-you-installed = Não foi possível efetuar a gravação de áudio. Você já tentou instalar o pacote "lame" da sua distribuição?
editing-customize-card-templates = Personalizar Modelos de Cartão
editing-customize-fields = Personalizar Campos
editing-cut = Recortar
editing-edit-current = Editar Atual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-float-left = Flutuante à esquerda
editing-float-right = Flutuante à direita
editing-float-none = Não flutuante
editing-indent = Aumentar a identação
editing-italic-text = Texto em itálico
editing-jump-to-tags-with-ctrlandshiftandt = Ir para etiquetas com Ctrl+Shift+T
editing-justify = Justificar
editing-latex = LaTeX
editing-latex-equation = Equação LaTeX
editing-latex-math-env = Matemática LaTeX
editing-mathjax-block = bloco MathJax
editing-mathjax-chemistry = Utilizar formato de entrada MathJax para equações químicas
editing-mathjax-inline = MathJax em linha
editing-mathjax-placeholder = Pressione { $accept } para aceitar, { $newline } para nova linha.
editing-media = Mídia
editing-ordered-list = Lista ordenada
editing-outdent = Diminuir a identação
editing-paste = Colar
editing-record-audio = Gravar áudio
editing-remove-formatting = Remover formatação
editing-set-text-color = Escolher cor de fonte
editing-set-text-highlight-color = Definir cor de destaque de texto
editing-show-duplicates = Mostrar Duplicatas
editing-subscript = Subscrito
editing-superscript = Sobrescrito
editing-tags = Etiquetas
editing-to-make-a-cloze-deletion-on = Para omitir palavras em uma nota existente, você precisa mudá-la para o tipo Omissão de Palavras primeiro, em 'Editar>Mudar Tipo de Nota'
editing-toggle-html-editor = Alternar para Editor de HTML
editing-toggle-sticky = Alternar cola
editing-toggle-visual-editor = Alternar para Editor Visual
editing-underline-text = Sublinhar texto
editing-unordered-list = Lista não-ordenada
editing-warning-cloze-deletions-will-not-work = Atenção, omissões de palavras não funcionarão até que você mude o tipo na parte superior para Omissão de Palavras.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
