notetypes-front-field = Frente
notetypes-back-field = Verso
notetypes-add-reverse-field = Adicionar Invertido
notetypes-text-field = Texto
notetypes-basic-name = Básico
notetypes-basic-reversed-name = Básico (e cartão invertido)
notetypes-basic-optional-reversed-name = Básico (cartão invertido opcional)
notetypes-cloze-name = Omissão de Palavras
notetypes-basic-type-answer-name = Básico (digite a resposta)
notetypes-card-2-name = Cartão 2
notetypes-card-1-name = Cartão 1
