preferences-automatically-sync-on-profile-openclose = Sincronizar automaticamente ao abrir/fechar perfil de usuário
preferences-backups = Cópias de segurança
preferences-backups2 = cópias de segurança
preferences-backupsanki-will-create-a-backup-of = <b>Cópias de segurança</b><br>O Anki criará uma cópia de segurança da sua coleção cada vez que ela for fechada ou sincronizada.
preferences-basic = Básico
preferences-change-deck-depending-on-note-type = Mudar baralho dependendo do tipo de nota
preferences-changes-will-take-effect-when-you = As alterações serão aplicadas depois que você reiniciar o Anki.
preferences-hours-past-midnight = horas além da meia-noite
preferences-interface-language = Idioma da interface:
preferences-interrupt-current-audio-when-answering = Interromper o áudio atual ao responder
preferences-keep = Manter
preferences-learn-ahead-limit = Aprender além do limite
preferences-mins = minutos
preferences-network = Rede
preferences-next-day-starts-at = Novo dia começa às
preferences-night-mode = Modo noturno
preferences-note-media-is-not-backed-up = Nota: A mídia não tem cópia de segurança. Por favor, copie periodicamente sua pasta Anki por segurança.
preferences-on-next-sync-force-changes-in = Na próxima sincronização, obrigar mudanças em uma direção.
preferences-paste-clipboard-images-as-png = Colar imagens da área de transferência como PNG
preferences-paste-without-shift-key-strips-formatting = Colar sem o botão shift desfaz a formatação
preferences-periodically-sync-media = Sincronizar mídia periodicamente
preferences-please-restart-anki-to-complete-language = Por favor, reinicie o Anki para completar a mudação de idioma.
preferences-preferences = Preferências
preferences-scheduling = Agendamento
preferences-show-learning-cards-with-larger-steps = Exibir os cartões de aprendizagem com intervalos maiores antes de efetuar novas revisões
preferences-show-next-review-time-above-answer = Mostrar tempo da próxima revisão acima dos botões de resposta
preferences-show-play-buttons-on-cards-with = Mostrar botões de reprodução nos cartões com áudio
preferences-show-remaining-card-count-during-review = Mostrar contador de cartões restantes durante a revisão
preferences-some-settings-will-take-effect-after = Algumas configurações só surtirão efeito quando você reiniciar o Anki
preferences-synchronisation = <b>Sincronização</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronização</b><br> Desabilitado; clique no botão de sincronização na janela principal para ativá-la.
preferences-synchronize-audio-and-images-too = Sincronizar áudios e imagens também
preferences-this-will-reset-any-cards-in = Esta ação irá apagar todos os cartões de aprendizado dos baralhos selecionados e consequentemente alterar a versão do agendador. Deseja continuar mesmo assim?
preferences-timebox-time-limit = Tempo limite
preferences-user-interface-size = Tamanho da interface do usuário
preferences-when-adding-default-to-current-deck = Ao criar, o padrão é o baralho atual
preferences-you-can-restore-backups-via-fileswitch = Você pode restaurar as cópias de seguranças em Arquivo>Mudar perfil.
