profiles-anki-could-not-read-your-profile = O Anki não pôde ler seus dados de perfil. Os tamanhos das janelas e seus detalhes de login de sincronização foram esquecidos.
profiles-anki-could-not-rename-your-profile = O Anki não poderia alterar o nome do perfil porque não poderia alterar o nome da pasta de perfil no disco. Por favor, verifique se você possuir a permissão de escrita ao Arquivos/Anki e outros programas não estiver acessando as pastas de perfil, em seguida, tente novamente.
profiles-folder-already-exists = A pasta já existe.
profiles-open = Abrir
profiles-open-backup = Abrir cópia de segurança...
profiles-please-remove-the-folder-and = Por favor. remova a pasta { $val } e tente novamente.
profiles-profile-corrupt = Perfil Corrompido
profiles-profiles = Usuários
profiles-quit = Sair
profiles-user-1 = Usuário 1
