notetypes-front-field = Հարց
notetypes-back-field = Պատասխան
notetypes-add-reverse-field = Ավելացնել հետադարձում
notetypes-text-field = Գրվածք
notetypes-basic-name = Հիմնական
notetypes-basic-reversed-name = Հիմնական (+ հետադարձ քարտերը)
notetypes-basic-optional-reversed-name = Հիմնական (հետադարձը ըստ ընտրության)
notetypes-cloze-name = Բացթողումներ
notetypes-basic-type-answer-name = Հիմնական (մուտքագրեք պատասխանը)
notetypes-card-2-name = Քարտ 2
notetypes-card-1-name = Քարտ 1
