actions-add = צולייגן
actions-all-selected = אַלע אויסגעקליבענע
actions-any-selected = וואָסער אויסגעקליבענע
actions-cancel = אַנולירן
actions-choose = קלײַבן
actions-close = פֿאַרמאַכן
actions-discard = אָפּוואַרפֿן
actions-copy = קאָפּירן
actions-create-copy = שאַפֿן אָפּשריפֿט
actions-custom-study = אײַנ׳חזר׳ן צוגעפּאַסט
actions-decks = טעשלעך
actions-decrement-value = ווייניקער
actions-delete = אָפּמעקן
actions-export = אַרויספֿירן
actions-filter = פֿילטרירן
actions-help = הילף
actions-increment-value = אַ שטאַפּל ווייניקער
actions-import = אַרײַנפֿירן
actions-manage = אָנפֿירן
actions-name = נאָמען:
actions-new = נײַ
actions-new-name = נײַער נאָמען:
actions-options = ברירות
actions-options-for = ברירות אויף
actions-preview = זען אין פֿאָרויס
actions-rebuild = איבערבויען
actions-rename = געבן אַן אַנדער נאָמען
actions-rename-deck = געבן טעשל אַן אַנדער נאָמען
actions-rename-tag = געבן צעטל אַן אַנדער נאָמען
actions-rename-with-parents = געבן אַן אַנדער נאָמען, אויך מיט מוטערס
actions-remove-tag = צונעמען צעטל
actions-replay-audio = איבערשפּילן
actions-reposition = איבערשטעלן
actions-save = אויפֿהיטן
actions-search = זוכן
actions-select = אויסקלײַבן
actions-shortcut-key = גיכקנעפּל:
actions-suspend-card = אָפּשטעלן קאַרטל
actions-set-due-date = שטעלן טערמין
actions-answer-card = ענטפֿער קאַרטל
actions-unbury-unsuspend = אויפֿגראָבן
actions-add-deck = שאַפֿן טעשל
actions-add-note = שאַפֿן נאָטיץ
actions-update-tag = דערהײַנטיקן צעטל
actions-update-note = דערהײַנטיקן נאָטיץ
actions-update-card = דערהײַנטיקן קאַרטל
actions-update-deck = דער הײַנטיקן טעשל
actions-forget-card = פֿאַרגעסן קאַרטל
actions-build-filtered-deck = בויען טעשל
actions-add-notetype = שאַפֿן נאָטיצגרופּע
actions-remove-notetype = צונעמען נאָטיצגרופּע
actions-update-notetype = דערהײַנטיקן נאָטיצגרופּע
actions-update-config = דערהײַנטיקן אויסשטעל
actions-card-info = קאַרטל פּרטים
actions-previous-card-info = פֿריִערדיקע קאַרטל פּרטים
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = …
actions-fullscreen-unsupported = פֿול-עקראַן-מאָדוס אַרבעט נישט מיט דײַן ווידעאָראָד. פּרוביר איבערצובײַטן אין אַן אַנדער דורך די אויסוואַל-עקראַן.

## Flags

actions-flag-number = אַרויסהייבן
actions-flag-red = רויט
actions-flag-orange = אָראַנזש
actions-flag-green = גרין
actions-flag-blue = בלאָ
actions-flag-pink = ראָזע
actions-flag-turquoise = טורקיזן
actions-flag-purple = פּערפּל
actions-set-flag = צולייגן סימן
actions-nothing-to-undo = גאָרנישט צו אַנולירן
actions-nothing-to-redo = גאָרנישט צו איבערמאַכן
actions-auto-advance = אויטאָ-פֿאָראויסגיין
actions-auto-advance-activated = אויטאָ-פֿאָראויסגיין אַקטיווירט
actions-auto-advance-deactivated = אויטאָ-פֿאָראויסגיין בטל געוואָרן
