actions-add = צולייגן
actions-all-selected = אַלע אויסגעקליבענע
actions-any-selected = וואָסער אויסגעקליבענע
actions-cancel = בטל מאַכן
actions-choose = קלײַבן
actions-close = פֿאַרמאַכן
actions-copy = קאָפּירן
actions-create-copy = שאַפֿן אַן אָפּשריפֿט
actions-custom-study = לערנען זיך צוגעפּאַסט
actions-decks = טעשלעך
actions-decrement-value = ווייניקער
actions-delete = אויסמעקן
actions-export = אַרויספֿירן
actions-filter = פֿילטרירן
actions-help = הילף
actions-increment-value = אינקרעמענט ציפֿער
actions-import = אַרײַנפֿירן
actions-manage = אָנפֿירן
actions-name = נאָמען:
actions-new = נײַ
actions-new-name = נײַער נאָמען:
actions-options = ברירות
actions-options-for = ברירות אויף
actions-preview = זען אין פֿאָרויס
actions-rebuild = איבערבויען
actions-rename = געבן אַן אַנדער נאָמען
actions-rename-deck = געבן טעשל אַן אַנדער נאָמען
actions-rename-tag = געבן צעטל אַן אַנדער נאָמען
actions-remove-tag = צונעמען צעטל
actions-replay-audio = איבערשפּילן
actions-reposition = איבערשטעלן
actions-save = אויפֿהיטן
actions-search = זוכן
actions-select = אויסקלײַבן
actions-shortcut-key = גיכוועג קלאַוויש:
actions-suspend-card = אָפּהאַלטן קאַרטל
actions-set-due-date = שטעלן טערמין
actions-answer-card = ענטפֿער קאַרטל

## Flags

