adding-add-shortcut-ctrlandenter = שאַפֿן (גיכקנעפּל: ctrl+enter)
adding-added = געשאַפֿן
adding-close-and-lose-current-input = צומאַכן און פֿאַרלירן איציקע אַרײַנוואַרג?
adding-edit = בײַטן "{ $val }"
adding-history = פֿריִער
adding-note-deleted = (נאָטיץ אָפּגעמעקט)
adding-shortcut = גיכקנעפּל: { $val }
adding-the-first-field-is-empty = ערשטע פֿעלד איז ליידיק.
adding-you-have-a-cloze-deletion-note = האָסט אַ ׳קלאָז׳ מין נאָטיץ, אָבער האָסט נישט קיין ׳קלאָז׳ אָפּמעקונג געטאָן. זײַן ממשיך?
adding-cloze-outside-cloze-notetype = ׳קלאָז׳ אָפּמעקונג קען מע טאָן נאָר מיט ׳קלאָז׳ מינים נאָטיצן.
adding-cloze-outside-cloze-field = ׳קלאָז׳ אָפּמעקונג קען מע טאָן נאָר מיט פֿעלדער וואָס ניצן דעם ׳קלאָז׳ פֿילטער. בדרך-כּלל איז עס דאָס ערטשע פֿעלד.
