browsing-add-notes = שאַפֿן נאָטיצן…
browsing-add-tags2 = צולייגן צעטלעך…
browsing-add-to-selected-notes = צולייגן אויף אויסגעקליבענע נאָטיצן
browsing-remove-from-selected-notes = צונעמען פֿון אויסגעקליבענע נאָטיצן
browsing-all-fields = אַלע פֿעלדער
browsing-answer = ענטפֿער
browsing-any-flag = וואָסער קאָליר
browsing-average-ease = גרינגקייט דורכשניטלעך
browsing-average-interval = צווישנצײַט דורכשניטלעך
browsing-browser-appearance = אָנבליק פֿון בלעטערער
browsing-browser-options = בלעטערער ברירות
browsing-buried = אָפּגעהאַלטן
browsing-card = קאַרטל
browsing-cards = קאַרטלעך
browsing-card-list = קאַרטלעך-רשימה
browsing-cards-cant-be-manually-moved-into = מע טאָר נישט בידים איבערטראָגן קאַרטלעך אין אַ פֿילטרירטן טעשל.
browsing-cards-deleted =
    { $count ->
        [one] { $count } קאַרטל אָפּגעמעקט געוואָרן.
       *[other] { $count } קאַרטלעך אָפּגעמעקט געוואָרן.
    }
browsing-change-deck = איבערבײַטן טעשל
browsing-change-deck2 = איבערבײַטן טעשל…
browsing-change-note-type = איבערבײַטן מין נאָטיץ
browsing-change-note-type2 = איבערבײַטן מין נאָטיץ…
browsing-change-notetype = איבערבײַטן מין נאָטיץ
browsing-clear-unused-tags = אָפּרייניקן נישט-געניצטע צעטלען
browsing-confirm-saved-search-overwrite = אַן אויפֿגעהיטנער דורכזוך בײַם נאָמען { $name } איז שוין פֿאַראַן. ווילסט אים פֿאַרבײַטן?
browsing-created = געשאַפֿן
browsing-current-deck = איציקע טעשל
browsing-current-note-type = איצטיקע מין נאָטיץ:
browsing-delete-notes = אָפּמעקן נאָטיצן
browsing-duplicate = דופּליקירן
browsing-ease = גרינגקייט
browsing-enter-tags-to-add = שטעל אַרײַן צעטלען צוצולייגן:
browsing-enter-tags-to-delete = שטעל אַרײַן צעטלען צוצונעמען:
browsing-filtered = (פֿילטרירט)
browsing-find = <b>זוכן</b>:
browsing-find-and-replace = זוכן און פֿאַרבײַטן
browsing-find-duplicates = זוכן דופּליקאַטן
browsing-first-card = ערשטע קאַרטל
browsing-flag = קאָלירן
browsing-font = <b>שריפֿט<b/>:
browsing-font-size = <b>שריפֿטגרייס</b>:
browsing-found-as-across-bs = { $part } געפֿינען צווישן { $whole }.
browsing-in = <b>אין</b>:
browsing-interval = צווישנצײַט
browsing-last-card = לעצטע קאַרטל
browsing-learning = (לערנענדיק זיך)
browsing-line-size = <b>גרייס פֿון שורה</b>:
browsing-manage-note-types = אָנפֿירן מיט מינים נאָטיצן
browsing-move-cards = איבעררוקן קאַרטלעך
browsing-move-cards-to-deck = איבעררוקן קאַרטלעך אין טעשל:
browsing-new = (נײַ)
browsing-new-note-type = נײַער מין נאָטיץ:
browsing-no-flag = אָן קיין קאָליר
browsing-no-selection = קיין קאַרטלעך/נאָטיצן אויסגעקליבן.
browsing-note = נאָטיץ
browsing-notes = נאָטיצן
browsing-optional-filter = ברירה-פֿילטער:
browsing-override-back-template = אַנולירן מוסטער-הינטן:
browsing-override-font = אַנולירן שריפֿט:
browsing-override-front-template = אַנולירן מוסטער-פֿאָרנט:
browsing-please-give-your-filter-a-name = שטעלט אויף אײַער פֿילטער אַ נאָמען:
browsing-preview-selected-card = זען אויסגעקליבענע קאַרטל אין פֿאָרויס ({ $val })
browsing-question = פֿראַגע
browsing-randomize-order = ראַנדאָמיזירן סדר
browsing-remove-tags = צונעמען צעטלען…
browsing-replace-with = <b>פֿאַרבײַטן אין</b>:
browsing-reposition = איבערשטעלן…
browsing-reposition-new-cards = איבערשטעלן נײַע קאַרטלעך
browsing-search-bar-hint = זוכן קאַרטלעך/נאָטיצן (וואָרטיר אויס טעקסט, נערנאָך קוועשטן ״Enter״)
browsing-search-in = זוכן צווישן:
browsing-search-within-formatting-slow = זוכן צווישן פֿאָרמאַטירונג (פּאַמעלעך)
browsing-selected-notes-only = נאָר אויסגעקליבענע נאָטיצן
browsing-shift-position-of-existing-cards = איבעררוקן פּאָזיציע פֿון איצטיקע קאַרטלעך
browsing-sidebar = זײַט-קעסטעלע
browsing-sidebar-filter = זײַט-קעסטעלע פֿילטער
browsing-sort-field = סאָרטיר-פֿעלד
browsing-sorting-on-this-column-is-not = סאָרטירן אין דער קאָלאָנקע ווערט נישט מעגלעך. קלײַבט אויס אַן אַנדערע.
browsing-start-position = אָנהייב-פּאָסיציע:
browsing-suspended = אָפּגעשטעלט

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

