decks-add-new-deck-ctrlandn = צושטעלן נײַ טעשל (Ctrl+N)
decks-build = בויען
decks-cards-selected-by = קאַרטלעך אויסגעקליבן פֿון
decks-create-deck = שאַפֿן טעשל
decks-custom-steps-in-minutes = צוגעפּאַסטע שטאַפּלען (אין מינוטן)
decks-deck = טעשל
decks-decreasing-intervals = פֿאַרקלענערנדיקע שטאַפּלען
decks-delete-deck = אָפּמעקן טעשל
decks-enable-second-filter = דערמעגלעכן צווייטן פֿילטער
decks-filter = פֿילטרירן:
decks-filter-2 = פֿילטער 2
decks-get-shared = נעמען שותּפֿישע
decks-import-file = אַרײַנפֿירן טעקע
decks-increasing-intervals = פֿאַרגרעסערנדיקע שטאַפּלען
decks-latest-added-first = קודם לעצטע צוגעלייגטע
decks-limit-to = באַגרעניצן אויף
decks-minutes = מינוטן
decks-most-lapses = מערסטע אויסגליטשן
decks-new-deck-name = נאָמען פֿון נײַ טעשל:
decks-no-deck = [קיין טעשל]
decks-oldest-seen-first = קודם עלטסטער געזען
decks-order-added = סדר פֿון שאַפֿונג
decks-order-due = סדר פֿון טערמין
decks-please-select-something = זײַט מוחל, קלײַבט עפּעס אויס.
decks-random = צופֿעליק
