decks-add-new-deck-ctrlandn = צושטעלן נײַ טעשל (Ctrl+N)
decks-build = בויען
decks-cards-selected-by = קאַרטלעך אויסגעקליבן פֿון
decks-create-deck = שאַפֿן טעשל
decks_create_even_if_empty = שאַפֿן/דערהײַנטיקן דאָס טעשל, אַפֿילו ווען ליידיק
decks-custom-steps-in-minutes = צוגעפּאַסטע שטאַפּלען (אין מינוטן)
decks-deck = טעשל
decks-decreasing-intervals = פֿאַרקלענערנדיקע שטאַפּלען
decks-delete-deck = אָפּמעקן טעשל
decks-enable-second-filter = דערמעגלעכן צווייטן פֿילטער
decks-filter = פֿילטרירן:
decks-filter-2 = פֿילטער 2
decks-get-shared = נעמען שותּפֿישע
decks-import-file = אַרײַנפֿירן טעקע
decks-increasing-intervals = פֿאַרגרעסערנדיקע שטאַפּלען
decks-latest-added-first = קודם לעצטע צוגעלייגטע
decks-limit-to = באַגרעניצן אויף
decks-minutes = מינוטן
decks-most-lapses = מערסטע אויסגליטשן
decks-new-deck-name = נאָמען פֿון נײַ טעשל:
decks-no-deck = [קיין טעשל]
decks-oldest-seen-first = קודם עלטסטער געזען
decks-order-added = סדר פֿון שאַפֿונג
decks-order-due = סדר פֿון טערמין
decks-please-select-something = זײַט מוחל, קלײַבט עפּעס אויס.
decks-random = צופֿעליק
decks-relative-overdueness = רעלאַטיוו אָפּלייגעניש
decks-repeat-failed-cards-after = איבער׳חזר׳ן דורכגעפֿאַלן קאַרטלעך נאָך
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = אָפּלייגן אויף { $button }
decks-reschedule-cards-based-on-my-answers = בײַטן באַשטימטע צײַט פֿון קאַרטלעך לויט מײַנע ענטפֿער אין דעם טעשל
decks-study = אײַנ׳חזר׳ן
decks-study-deck = אײַנ׳חזר׳ן טעשל
decks-filtered-deck-search-empty = קיין קאַרטל האָט זיך נישט געפּאַסט צו דער געגעבנער דורכזוך. ס׳קען זײַן, אַז טייל קאַרטלעך זענען אַרויסגעלאָזט פֿון חשבון, ווײַל זיי זענען אין אַן אַנדער פֿילטרירטן טעשל, אָדער זענען אָפּגעשטעלט געוואָרן.
decks-unmovable-cards = באַווײַזן אויסגעשליסטע קאַרטלעך
decks-learn-header = לערנען
# The count of cards waiting to be reviewed
decks-review-header = טערמיניק
decks-zero-minutes-hint = (0 = צוריקלייגן קאַרטל אינעם עיקר-טעשל)
