exporting-all-decks = אַלע טעשלעך
exporting-anki-20-deck = אַנקי 2.0 קעשל
exporting-anki-collection-package = אַנקי זאַמלונג-פּעקל
exporting-anki-deck-package = אַנקי טעשל-פּעקל
exporting-cards-in-plain-text = קאַרטלעך אין סתּם טעקסט
exporting-collection = זאַמלונג
exporting-collection-exported = זאַמלונג אַרויסגעפֿירט.
exporting-colpkg-too-new = זײַט אַזוי גוט, דערהײַנטיקט ביזן נײַסטן נוסח פֿון אַנקי. דערנאָך, פֿירט ווידער אַרײַן די טעקע .colpkg/.apkg.
exporting-couldnt-save-file = מ׳האָט נישט געקענט אויפֿהיטן די טעקע: { $val }
exporting-export = אַרויספֿירן…
exporting-export-format = <b>אַרויספֿיר-פֿאָרמאַט</b>:
exporting-include = <b>אַרײַננעמען</b>:
exporting-include-html-and-media-references = אַרײַננעמען HTML און מעדיע אָפּשיקן
exporting-include-media = אַרײַננעמען מעדיע
exporting-include-scheduling-information = אַרײַננעמען צײַטפּלאַן-ידיעות
exporting-include-deck-configs = אַרײַנננעמען טעשל מוסטערן
exporting-include-tags = אַרײַננעמען צעטלעך
exporting-support-older-anki-versions = באַדינען עלטערע נוסחאָות פֿון אַנקי (פּאַמעלעכעך/גרעסער טעקעס)
exporting-notes-in-plain-text = נאָטיצן אין סתּם טעקסט
exporting-selected-notes = אויסגעקליבענע נאָטיצן
