preferences-automatically-sync-on-profile-openclose = סינכראָנירן אויטאָמאַטיש בעתן עפֿענען/צומאַכן פּראָפֿיל
preferences-backups = רעזערוו-קאָפּיעס
preferences-change-deck-depending-on-note-type = בײַטן טעשל לויט נאָטיצגרופּע
preferences-changes-will-take-effect-when-you = בײַטן וועלן ווערן גילטיק בײַם צולאָדן ANKI אויף ס׳נײַ
preferences-hours-past-midnight = שעהען נאָך האַלבע נאַכט
preferences-language = שפּראַך
preferences-interrupt-current-audio-when-answering = איבעררײַסן גייי‎ִקע קלאַנג בעתן ענטפֿערן
preferences-learn-ahead-limit = גרענעץ פֿון זיך לערנען אין פֿאָראויס
preferences-mins = מינוטן
preferences-network = סיכראָניזירן
preferences-next-day-starts-at = דער אַנדער טאָג הייבט זיך אָן
preferences-media-is-not-backed-up = מ׳האָט קיין רעזערוו-קאָפּיע פֿון מעדיע נישט געמאַכט. מאַך פּעריאָדיש אַ רעזערוו-קאָפּיע פֿון די ANKI פּאַפּקע אויף יעדן פֿאַל.
preferences-on-next-sync-force-changes-in = אויפֿן קומעדיקן סינכראָניזירן, צווינגן בײַטן אין איין ריכטונג
preferences-paste-clipboard-images-as-png = אַרײַנקלעפּן בילדער פֿון קלעמברעטל ווי PNG
preferences-paste-without-shift-key-strips-formatting = קלעפּ אָן ״שיפֿט״ קנעפּל נעמט צו די צורה
preferences-generate-latex-images-automatically = אַרויסגעבן LaTeX בילדער (זיכערהייט סכּנה)
preferences-latex-generation-disabled = אַרויסגעבן LaTeX בילדער איז נישט-געניצט געהאַכט אין די פּרעפֿערענצן
preferences-periodically-sync-media = סינכראָניזירן מעדיע פּעריאָדיש
preferences-please-restart-anki-to-complete-language = כּדי צו באַווירן שפּראַכבײַט, לאָד צו ANKI אויף ס׳נײַ.
preferences-preferences = פּרעפֿערענצן
preferences-scheduling = פּלאַנירונג
preferences-show-next-review-time-above-answer = אַרויסווײַזן קומעדיקע אויס׳חזר׳ן-צײַט אויבן פֿון ענטפֿער-קנעפּלעך
preferences-spacebar-rates-card = שפּײַצער (אָדער אַרײַנ-קלאַוויש) ענטפֿערט אויך דאָס קאַרטל
preferences-show-play-buttons-on-cards-with = אַרויסווײַזן ׳שפּילן׳ קנעפּלעך אויף קאַרטלעך וואָס מיט אוידיאָ
preferences-show-remaining-card-count = ווײַזן חשבון פֿון געבליבענע קאַרטלעך
preferences-some-settings-will-take-effect-after = טייל פֿיקסירונגען וועלן ווערן גילטיק בײַם צולאָדן ANKI אויף ס׳נײַ.
preferences-tab-synchronisation = סינכראָניזאַציע
preferences-synchronize-audio-and-images-too = סינכראָניזירן אוידיאָ און אויך בילדער
preferences-not-logged-in = יעצט נישט אַרײַנלאָגירט אין AnkiWeb.
preferences-login-successful-sync-now = דאָס אַרײַנלאָגירן איז מצליח געווען. אויפֿהיטן פּרעפֿערענצטן און סינכראָניזירן שוין?
preferences-timebox-time-limit = צײַט-גרענעץ פֿון צײַטקעסטל
preferences-user-interface-size = גרייס פֿון ניצער-צווישנבינד
preferences-when-adding-default-to-current-deck = צושטעלן אין יעצטיקן טעשל דורך פֿעליקייט
preferences-you-can-restore-backups-via-fileswitch = מע קען אויפֿריכטן רעזערוו-קאָפּיעס בײַ טעקע ('File') > איבערבײַטן פּראָפֿיל
preferences-default-search-text = עצם זוכטעקסט
preferences-default-search-text-example = למשל, 'deck:current' ("טעשל: גײיִק")
preferences-theme = פֿאַרב-צורה
preferences-theme-follow-system = לויט דער סיסטעם
preferences-theme-light = ליכטיק
preferences-theme-dark = טונקל
preferences-v3-scheduler = V3 פּלאַנירער
preferences-ignore-accents-in-search = פֿאַרקוקן דיאַקריטלעך בײַם פֿאַרזוכן (פּאַמעלעכער)
preferences-backup-explanation = פּעריאָדיש מאַכט ANKI אַ רעזערוו-קאָפּיע פֿון דײַן זאַמלונג. נאָך רעזערוו-קאָפּיעס ווערן אַלט מער פֿון 2 טעג, ANKI וועט אָנהייבן צוצונעמען טייל כּדי אָפּפֿרײַען אָרט אויפֿן דיסק.
preferences-daily-backups = טעגלעכע רעזערוו-קאָפּיעס וועס צו האַלטן:
preferences-weekly-backups = וואָכיקע רעזערוו-קאָפּיעס וועס צו האַלטן:
preferences-monthly-backups = חודשלעכע רעזערוו-קאָפּיעס וועס צו האַלטן:
preferences-minutes-between-backups = מינוטן צווישן אויטאָמאַטישע רעזערוו-קאָפּיעס
preferences-reduce-motion = פֿאַרקלענערן באַוועג
preferences-reduce-motion-tooltip = מאַכן אומניצלעך עטלעכע אַנימאַציעס און איבערגאַנגען פֿונעם ניצער-צווישנבינד.
preferences-hide-top-bar-during-review = באַהאַלטן אויבנבאַלקן בעתן איבער׳חזר׳ן
preferences-hide-bottom-bar-during-review = באַהאַלטן אונטנבאַלקן בעתן איבער׳חזר׳ן
preferences-always = תּמיד
preferences-full-screen-only = נאָר פֿולער-עקראַן
preferences-appearance = אויסזען
preferences-general = אַלגעמיין
preferences-style = שטייגער
preferences-review = איבער׳חזר׳ן
preferences-answer-keys = ענטפֿער-קנעפּלעך
preferences-minimalist-mode = מינימאַליסטישער-מאָדוס
preferences-minimalist-mode-tooltip = פֿאַרדריקן און פֿאַרפּשוטערן דעם ניצער-צווישנבינד
preferences-editing = רעדאַקטירן
preferences-browsing = בלעטערן
preferences-default-deck = עצם-טעשל
preferences-account = AnkiWeb קאָנטע
preferences-note = נאָטיץ
preferences-scheduler = פּלאַנירער
preferences-user-interface = ניצער-צווישנבינד
preferences-import-export = פֿירן אַרײַן/אַרויס
preferences-reset-window-sizes = אײַנשטעלן פֿענצטער גרײסן אויף ס׳נײַ
preferences-reset-window-sizes-complete = פֿענצטער גרייסן און פּלעצער זענען אײַנגעשטעלט געוואָרן אויף ס׳נײַ.
preferences-shortcut-placeholder = אַרײַנשרײַבן אַ נישט-געניצט גיך-קנעפּל, אָדער לאָז ליידיק כּדי צו מאַכן אומניצלעך.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = עיקרדיק
preferences-reviewer = רעצענזענט
preferences-media = מעדיע
