exporting-all-decks = Všetky balíčky
exporting-anki-20-deck = Balíček Anki 2.0
exporting-anki-collection-package = Balíček Anki kolekce
exporting-anki-deck-package = Balíček Anki
exporting-cards-in-plain-text = Karty ako obyčajný text
exporting-collection = zbierka
exporting-collection-exported = Zbierka exportovaná.
exporting-couldnt-save-file = Nemôžem uložiť súbor: { $val }
exporting-export = Exportovať...
exporting-export-format = <b>Formát exportu</b>:
exporting-include = <b>Zahrnúť</b>:
exporting-include-html-and-media-references = Zahrnúť HTML a odkazy na médiá
exporting-include-media = Zahrnúť médiá
exporting-include-scheduling-information = Zahrnúť informácie o plánovaní
exporting-include-tags = Zahrnúť štítky
exporting-notes-in-plain-text = Poznámky ako jednoduchý text
exporting-selected-notes = Vybrané poznámky
