actions-add = Aggiungi
actions-blue-flag = Contrassegno blu
actions-cancel = Annulla
actions-choose = Scegli
actions-close = Chiudi
actions-copy = Copia
actions-custom-study = Studio personalizzato
actions-decks = Mazzi
actions-delete = Elimina
actions-export = Esporta
actions-filter = Filtro
actions-green-flag = Contrassegno verde
actions-help = Aiuto
actions-import = Importa
actions-manage = Gestisci...
actions-name = Nome:
actions-new = Nuove
actions-new-name = Nuovo nome:
actions-options = Opzioni
actions-options-for = Opzioni per { $val }
actions-orange-flag = Contrassegno arancione
actions-preview = Anteprima
actions-rebuild = Ricrea
actions-red-flag = Contrassegno rosso
actions-rename = Rinomina
actions-rename-deck = Rinomina il mazzo
actions-rename-tag = Rinomina tag
actions-remove-tag = Rimuovi tag
actions-replay-audio = Riproduci di nuovo l'audio
actions-reposition = Riposiziona
actions-save = Salva
actions-search = Cerca
actions-select = Seleziona
actions-shortcut-key = Tasto di scorciatoia: { $val }
actions-suspend-card = Sospendi la carta
actions-set-due-date = Imposta la data di scadenza
