decks-add-new-deck-ctrlandn = Aggiungi un nuovo mazzo (Ctrl+N)
decks-are-you-sure-you-wish-to = Sei sicuro di voler eliminare { $val }?
decks-build = Crea
decks-cards-selected-by = carte selezionate per
decks-create-deck = Crea mazzo
decks-custom-steps-in-minutes = Passi personalizzati (in minuti)
decks-deck = Mazzo
decks-decreasing-intervals = Intervalli decrescenti
decks-delete-deck = Elimina il mazzo
decks-enable-second-filter = Abilita secondo filtro
decks-filter = Filtro:
decks-filter-2 = Filtro 2
decks-get-shared = Ottieni mazzi condivisi
decks-import-file = Importa file
decks-increasing-intervals = Intervalli crescenti
decks-latest-added-first = Dapprima aggiunte più recentemente
decks-limit-to = Limita a
decks-minutes = minuti
decks-most-lapses = Maggior numero di errori
decks-name-for-deck = Nome per il mazzo:
decks-new-deck-name = Nome del nuovo mazzo:
decks-no-deck = [nessun mazzo]
decks-oldest-seen-first = Più vecchie visualizzate per prime
decks-order-added = Ordine di aggiunta
decks-order-due = Ordine di scadenza
decks-please-select-something = Per piacere, seleziona qualcosa.
decks-random = Casuale
decks-relative-overdueness = Ritardo relativo
decks-repeat-failed-cards-after = Ripeti carte fallite dopo
decks-reschedule-cards-based-on-my-answers = Ripianifica le carte considerando le mie risposte in questo mazzo
decks-study = Studia
decks-study-deck = Studia il mazzo
decks-the-provided-search-did-not-match = La ricerca non ha fornito nessun risultato. Vuoi modificare i criteri di ricerca?
