editing-actual-size = Attiva/disattiva dimensione effettiva
editing-add-media = Aggiungi media
editing-align-left = Allinea a sinistra
editing-align-right = Allinea a destra
editing-an-error-occurred-while-opening = Si è verificato un errore durante l'apertura di { $val }
editing-attach-picturesaudiovideo = Allega immagini/audio/video
editing-bold-text = Grassetto
editing-cards = Carte
editing-center = Centro
editing-change-color = Cambia colore
editing-cloze-deletion = Cancellazione cloze
editing-couldnt-record-audio-have-you-installed = La registrazione audio non è stata possibile. Hai installato 'lame'?
editing-customize-card-templates = Personalizza i modelli delle carte
editing-customize-fields = Personalizza i campi
editing-cut = Taglia
editing-edit-current = Modifica corrente
editing-edit-html = Modifica HTML
editing-fields = Campi
editing-float-left = Fluttua a sinistra
editing-float-right = Fluttua a destra
editing-float-none = Non fluttuare
editing-indent = Aumenta l'indentazione
editing-italic-text = Corsivo
editing-jump-to-tags-with-ctrlandshiftandt = Salta a etichette con Ctrl+Shift+T
editing-justify = Giustificato
editing-latex = LaTeX
editing-latex-equation = Equazione LaTeX
editing-latex-math-env = Ambiente LaTeX math
editing-mathjax-block = Blocco MathJax
editing-mathjax-chemistry = MathJax chimica
editing-mathjax-inline = MathJax in linea
editing-mathjax-placeholder = Premi { $accept } per accettare, { $newline } per una nuova riga.
editing-media = File multimediale
editing-ordered-list = Lista ordinata
editing-outdent = Riduci indentazione
editing-paste = Incolla
editing-record-audio = Registra audio
editing-remove-formatting = Rimuovi formattazione
editing-set-text-color = Imposta il colore del testo
editing-set-text-highlight-color = Imposta il colore di evidenziazione
editing-show-duplicates = Mostra i duplicati
editing-subscript = Pedice
editing-superscript = Apice
editing-tags = Etichette
editing-to-make-a-cloze-deletion-on = Per inserire una cancellazione cloze in una nota esistente, devi prima cambiarla in una nota di tipo cloze, attraverso Modifica>Cambia tipo di nota
editing-toggle-html-editor = Attiva/Disattiva l'editor HTML
editing-toggle-sticky = Attiva/Disattiva adesività
editing-toggle-visual-editor = Attiva/Disattiva editor visuale
editing-underline-text = Sottolinea testo
editing-unordered-list = Lista non ordinata
editing-warning-cloze-deletions-will-not-work = Attenzione, le cancellazioni cloze non funzioneranno fino a quando non cambierai in "Cloze" il tipo in alto.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor HTML
