exporting-all-decks = Tutti i mazzi
exporting-anki-20-deck = Mazzo di Anki 2.0
exporting-anki-collection-package = Pacchetto di collezioni Anki
exporting-anki-deck-package = Pacchetto Mazzi Anki
exporting-cards-in-plain-text = Carte in Testo Semplice
exporting-collection = collezione
exporting-collection-exported = Collezione esportata
exporting-couldnt-save-file = Non è stato possibile salvare il file: { $val }
exporting-export = Esporta...
exporting-export-format = <b>Formato di esportazione</b>:
exporting-include = <b>Includi</b>:
exporting-include-html-and-media-references = Includi HTML e riferimenti multimediali
exporting-include-media = Includi file multimediali
exporting-include-scheduling-information = Includi informazioni pianificazione
exporting-include-tags = Includi etichette
exporting-notes-in-plain-text = Note in testo semplice
exporting-selected-notes = Note selezionate
