preferences-automatically-sync-on-profile-openclose = Sincronizza automaticamente all'apertura/chiusura del profilo
preferences-backups = Backup
preferences-backups2 = backup
preferences-backupsanki-will-create-a-backup-of = <b>Backup</b><br>Anki creerà un backup della tua collezione ogni volta che viene chiuso o sincronizzato.
preferences-basic = Basilare
preferences-change-deck-depending-on-note-type = Cambia mazzo a dipendenza del tipo di nota
preferences-changes-will-take-effect-when-you = I cambiamenti avranno effetto dopo il riavvio di Anki.
preferences-hours-past-midnight = ore dopo mezzanotte
preferences-interface-language = Lingua dell'interfaccia:
preferences-interrupt-current-audio-when-answering = Interrompi l'audio mentre rispondi
preferences-keep = Conserva
preferences-learn-ahead-limit = Impara oltre il limite
preferences-mins = min
preferences-network = Rete
preferences-next-day-starts-at = Il giorno successivo inizia
preferences-night-mode = Modalità notturna
preferences-note-media-is-not-backed-up = Nota: Non viene effettuato un backup dei file multimediali. Per sicurezza effettua un backup periodico della cartella di Anki.
preferences-on-next-sync-force-changes-in = Alla prossima sincronizzazione, forza i cambiamenti in una direzione
preferences-paste-clipboard-images-as-png = Incolla immagini dagli appunti come png
preferences-paste-without-shift-key-strips-formatting = Incolla senza formattazione
preferences-periodically-sync-media = Sincronizza file multimediali periodicamente
preferences-please-restart-anki-to-complete-language = Riavvia Anki per completare il cambiamento di lingua.
preferences-preferences = Preferenze
preferences-scheduling = Ripianifica
preferences-show-learning-cards-with-larger-steps = Mostra le carte in apprendimento con grandi passi prima delle ripetizioni
preferences-show-next-review-time-above-answer = Mostra la prossima scadenza sopra i pulsanti di risposta
preferences-show-play-buttons-on-cards-with = Mostra i pulsanti di riproduzione sulle carte con l'audio
preferences-show-remaining-card-count-during-review = Mostra il contatore delle carte rimanenti durante le ripetizioni
preferences-some-settings-will-take-effect-after = Alcune opzioni avranno effetto solo dopo il riavvio di Anki.
preferences-synchronisation = <b>Sincronizzazione</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronizzazione</b><br> Non abilitata correntemente; clicca il pulsante di sincronizzazione nella finestra principale per abilitarla.
preferences-synchronize-audio-and-images-too = Sincronizza anche l'audio e le immagini
preferences-timebox-time-limit = Limite di tempo per sessione
preferences-user-interface-size = Misura dell'interfaccia utente
preferences-when-adding-default-to-current-deck = Aggiungi le note nuove al mazzo corrente
preferences-you-can-restore-backups-via-fileswitch = Ripristina i backup attraverso File>Cambia Profilo.
preferences-legacy-timezone-handling = Vecchio sistema di gestione dei fusi orari (pieno di bug, ma richiesto da AnkiDroid <= 2.14)
preferences-default-search-text = Testo di ricerca di default
preferences-default-search-text-example = es. 'deck:current'
preferences-theme-label = Tema: { $theme }
preferences-theme-follow-system = Seguire il sistema
preferences-theme-light = Chiaro
preferences-theme-dark = Scuro
preferences-v3-scheduler = Pianificatore V3
