profiles-anki-could-not-read-your-profile = Anki non ha potuto leggere i dati del tuo profilo. Le impostazioni non sono state riprese.
profiles-anki-could-not-rename-your-profile = Anki non ha potuto rinominare il profilo perché non è riuscito a rinominare la cartella del profilo sul disco. Assicurati di avere il permesso di scrittura in Documenti/Anki e che nessun altro programma stia accedendo alle cartelle del profilo, quindi riprova.
profiles-folder-already-exists = La cartella esiste già.
profiles-open = Apri
profiles-open-backup = Apri backup...
profiles-please-remove-the-folder-and = Rimuovi la cartella { $val } e riprova.
profiles-profile-corrupt = Profilo corrotto
profiles-profiles = Profili
profiles-quit = Esci
profiles-user-1 = Utente 1
