actions-add = قوش
actions-all-selected = ھەممىسى تاللاندى
actions-any-selected = خالىغان تاللانغىنى
actions-cancel = ۋاز كەچ
actions-choose = تاللا
actions-close = ياپ
actions-discard = تاشلىۋەت
actions-copy = كۆچۈر
actions-create-copy = كۆچۈرۈلمىسىنى قۇر
actions-custom-study = ئىختىيارى ئۆگىنىش
actions-decks = دەستە
actions-decrement-value = كېمەيگۈچى قىممەت
actions-delete = ئۆچۈر
actions-export = چىقار
actions-filter = سۈزگۈچ
actions-help = ياردەم
actions-increment-value = ئۆسكۈچى قىممەت
actions-import = ئەكىر
actions-manage = باشقۇر…
actions-name = ئات:
actions-new = يېڭى
actions-new-name = يېڭى ئات:
actions-options = تاللانما
actions-options-for = { $val } نىڭ تاللانمىسى
actions-preview = ئالدىن كۆزەت
actions-rebuild = قايتا قۇر
actions-rename = ئات ئۆزگەرت
actions-rename-deck = دەستە ئاتىنى ئۆزگەرت
actions-rename-tag = بەلگە ئاتىنى ئۆزگەرت
actions-rename-with-parents = ئانا ئاتىنى ئۆزگەرت
actions-remove-tag = بەلگە چىقىرىۋەت
actions-replay-audio = ئاۋازنى قايتىلا
actions-reposition = قايتا تەرتىپلە
actions-save = ساقلا
actions-search = ئىزدە
actions-select = تاللا
actions-shortcut-key = قىسقا يول كۇنۇپكىسى: { $val }
actions-suspend-card = كارتىنى كېچىكتۈر
actions-set-due-date = مۆھلەت چېسلا تەڭشىكى
actions-answer-card = جاۋاب كارتا
actions-unbury-unsuspend = يوشۇرما/كېچىكتۈرمە
actions-add-deck = دەستە قوش
actions-add-note = ئىزاھات قوش
actions-update-tag = بەلگە يېڭىلا
actions-update-note = ئىزاھات يېڭىلا
actions-update-card = كارتا يېڭىلا
actions-update-deck = دەستە يېڭىلا
actions-forget-card = كارتىنى ئەسلىگە قايتۇر
actions-build-filtered-deck = دەستە قۇر
actions-add-notetype = ئىزاھات تۈرى قوش
actions-remove-notetype = ئىزاھات تۈرىنى چىقىرىۋەت
actions-update-notetype = ئىزاھات تۈرىنى يېڭىلا
actions-update-config = سەپلىمە يېڭىلا
actions-card-info = كارتا ئۇچۇرى
actions-previous-card-info = ئالدىنقى كارتا ئۇچۇرى
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }…
actions-fullscreen-unsupported = پۈتۈن ئېكران ھالىتى كۆرسىتىش كارتىڭىزنىڭ قوزغاتقۇچ پىروگراممىسىنى قوللىمايدۇ. مايىللىق ئېكرانىدىن باشقا بىرىنى تاللاپ سىناڭ.

## Flags

actions-flag-number = بايراق { $number }
actions-flag-red = قىزىل
actions-flag-orange = قىزغۇچ سېرىق
actions-flag-green = يېشىل
actions-flag-blue = كۆك
actions-flag-pink = ھالرەڭ
actions-flag-turquoise = توق يېشىل
actions-flag-purple = بىنەپشە
actions-set-flag = بايراق تەڭشەك
actions-nothing-to-undo = يېنىۋالىدىغان مەشغۇلات يوق
actions-nothing-to-redo = قايتىلايدىغان مەشغۇلات يوق
actions-auto-advance = ئۆزلۈكىدىن كۆرسەت
actions-auto-advance-activated = ئۆزلۈكىدىن كۆرسىتىش قوزغىتىلدى
actions-auto-advance-deactivated = ئۆزلۈكىدىن كۆرسىتىش چەكلەندى
