change-notetype-current = نۆۋەتتىكى
change-notetype-new = يېڭى
change-notetype-nothing = (يوق)
change-notetype-collapse = يىغ
change-notetype-expand = ياي
change-notetype-will-discard-content = تۆۋەندىكى بۆلەكنىڭ مەزمۇنىنى تاشلىۋېتىدۇ:
change-notetype-will-discard-cards = تۆۋەندىكى كارتىنى چىقىرىۋېتىدۇ:
change-notetype-fields = بۆلەك
change-notetype-templates = قېلىپ
