preferences-automatically-sync-on-profile-openclose = سەپلىمە ھۆججەتنى ئۆزلۈكىدىن قەدەمداشلاشنى ئاچ/ياپ
preferences-backups = زاپاس
preferences-change-deck-depending-on-note-type = كارتا قوشقاندا كارتا تۈرىگە ئاساسەن دەستە تاللىنىدۇ
preferences-changes-will-take-effect-when-you = ئۆزگىرىش Anki قايتا قوزغالغاندا ئاندىن ئۈنۈمىنى كۆرسىتىدۇ.
preferences-hours-past-midnight = سائەت
preferences-language = تىل
preferences-interrupt-current-audio-when-answering = كارتىغا جاۋاب بېرىۋاتقاندا نۆۋەتتىكى ئۈن قويۇشنى توختىتىدۇ
preferences-learn-ahead-limit = ئالدىن ئۆگىنىش چېكى
preferences-mins = مىنۇت
preferences-network = قەدەمداشلاۋاتىدۇ
preferences-next-day-starts-at = ئەتە باشلايدىغان ۋاقىت
preferences-media-is-not-backed-up = ۋاسىتە زاپاسلانمايدۇ. بىخەتەرلىك ئۈچۈن Anki قىسقۇچنى قەرەللىك زاپاسلاڭ.
preferences-on-next-sync-force-changes-in = كېيىنكى قېتىم قەدەمداشلىغاندا، مەجبۇرىي بىر يۆنىلىشتە ئۆزگەرتىدۇ
preferences-paste-clipboard-images-as-png = چاپلاش تاختىسىدىكى سۈرەتنى PNG پىچىمىدا چاپلايدۇ
preferences-paste-without-shift-key-strips-formatting = ئەگەر چاپلىغاندا shift كۇنۇپكىسى بېسىلمىسا تېكىست پىچىمىنى تازىلايدۇ
preferences-generate-latex-images-automatically = LaTeX سۈرىتى ھاسىللايدۇ (بىخەتەرلىك خەتىرى بار)
preferences-latex-generation-disabled = LaTeX سۈرەت ھاسىللاش مايىللىقتا چەكلەنگەن.
preferences-periodically-sync-media = ۋاسىتە ھۆججەتنى قەرەللىك قەدەمداشلايدۇ
preferences-please-restart-anki-to-complete-language = تىل ئالماشتۇرۇشنى تاماملاشتا Anki نى قايتا قوزغىتىڭ.
preferences-preferences = مايىللىق
preferences-scheduling = كۈنتەرتىپكە تىزىۋاتىدۇ
preferences-always = ھەمىشە
preferences-full-screen-only = پۈتۈن ئېكرانلا
preferences-appearance = كۆرۈنۈش
preferences-general = ئادەتتىكى
preferences-style = ئۇسلۇب
preferences-review = تەكرار
preferences-answer-keys = جاۋاب كۇنۇپكا
preferences-minimalist-mode = ئىخچام ھالىتى
preferences-minimalist-mode-tooltip = ئارايۈزنى تېخىمۇ ئىخچام/ئاددىيلاشتۇرىدۇ
preferences-editing = تەھرىرلەش
preferences-browsing = كۆز يۈگۈرتۈش
preferences-default-deck = كۆڭۈلدىكى دەستە
preferences-account = AnkiWeb ھېساباتى
preferences-note = ئىزاھات
preferences-scheduler = كۈنتەرتىپلىگۈچ
preferences-user-interface = ئىشلەتكۈچى ئارايۈزى
preferences-import-export = ئەكىر/چىقار
preferences-network-timeout = تور ۋاقىت ھالقىش
preferences-reset-window-sizes = كۆزنەك چوڭلۇقىنى ئەسلىگە قايتۇر
preferences-reset-window-sizes-complete = كۆزنەك چوڭلۇقى ۋە ئورنى ئەسلىگە قايتۇرۇلدى.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

