actions-add = הוספה
actions-all-selected = כל אלו שנבחרו
actions-any-selected = כל אחד שנבחר
actions-cancel = ביטול
actions-choose = בחירה
actions-close = סגירה
actions-discard = סגור מבלי לשמור
actions-copy = העתקה
actions-create-copy = יצירת עותק
actions-custom-study = לימוד מותאם
actions-decks = חפיסות
actions-decrement-value = הפחתת ערך
actions-delete = מחיקה
actions-export = ייצוא
actions-empty-cards = כרטיסים ריקים
actions-filter = מסנן
actions-help = עזרה
actions-increment-value = הגדלת ערך
actions-import = ייבוא
actions-manage = ניהול…
actions-name = שם:
actions-new = חדשים
actions-new-name = שם חדש:
actions-options = אפשרויות
actions-options-for = אפשרויות עבור { $val }
actions-preview = תצוגה מקדימה
actions-rebuild = בנייה מחדש
actions-rename = שינוי שם
actions-rename-deck = שינוי שם חפיסה
actions-rename-tag = שינוי שם תגית
actions-rename-with-parents = שנה שם עם חפיסות אב
actions-remove-tag = הסרת תגית
actions-replay-audio = נגן אודיו מחדש
actions-reposition = שנה מיקום
actions-save = שמירה
actions-search = חיפוש
actions-select = בחירה
actions-shortcut-key = מקש קיצור: { $val }
actions-suspend-card = השהה כרטיס
actions-set-due-date = הגדרת תאריך יעד
actions-answer-card = ענה על כרטיס
actions-unbury-unsuspend = הוצא מהטמנה/השהיה
actions-add-deck = הוספת חפיסה
actions-add-note = הוסף רשומה
actions-update-tag = עדכון תגית
actions-update-note = עדכן רשומה
actions-update-card = עדכון קלף
actions-update-deck = עדכן חפיסה
actions-forget-card = שכח כרטיס (איפוס תזמונים)
actions-build-filtered-deck = בנה חפיסה
actions-add-notetype = הוסף סוג רשומה
actions-remove-notetype = הסר סוג רשומה
actions-update-notetype = עדכן סוג רשומה
actions-update-config = עדכן הגדרה
actions-card-info = מידע כרטיס
actions-previous-card-info = מידע כרטיס קודם
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-fullscreen-unsupported = מצב מסך מלא אינו נתמך עבור דרייבר הווידאו שלך. נסה לעבור לדרייבר אחר בחלון ההעדפות.

## Flags

actions-flag-number = דגל#{ $number }
actions-flag-red = אדום
actions-flag-orange = כתום
actions-flag-green = ירוק
actions-flag-blue = כחול
actions-flag-pink = ורוד
actions-flag-turquoise = טורקיז
actions-flag-purple = סגול
actions-set-flag = הצבת דגל
actions-nothing-to-undo = אין מה לבטל
actions-nothing-to-redo = אין מה לעשות מחדש
actions-auto-advance = התקדמות אוטומטית
actions-auto-advance-activated = התקדמות אוטומטית מופעלת
actions-auto-advance-deactivated = התקדמות אוטומטית מושבתת
