actions-add = הוספה
actions-all-selected = כל אלו שנבחרו
actions-any-selected = כל אחד שנבחר
actions-cancel = ביטול
actions-choose = בחר
actions-close = סגירה
actions-copy = העתק
actions-custom-study = לימוד מותאם
actions-decks = חפיסות
actions-delete = מחק
actions-export = ייצוא
actions-filter = סנן
actions-help = עזרה
actions-import = ייבוא
actions-manage = נהל...
actions-name = שם:
actions-new = חדשים
actions-new-name = שם חדש:
actions-options = אפשרויות
actions-options-for = אפשריות ל-{ $val }
actions-preview = תצוגה מקדימה
actions-rebuild = בנה מחדש
actions-rename = שנה שם
actions-rename-deck = שנה שם חפיסה
actions-rename-tag = שנה תגית
actions-remove-tag = הסר תגית
actions-replay-audio = נגן אודיו מחדש
actions-reposition = שנה מיקום
actions-save = שמור
actions-search = חיפוש
actions-select = בחירה
actions-shortcut-key = מקש קיצור: { $val }
actions-suspend-card = השהה כרטיס
actions-set-due-date = הגדר תאריך יעד
actions-forget = שכח
actions-answer-card = ענה על כרטיס
actions-unbury-unsuspend = הוצא מהטמנה/השהיה
actions-add-deck = הוסף חפיסה
actions-add-note = הוסף רשומה
actions-update-tag = עדכן תגית
actions-update-note = עדכן רשומה
actions-update-card = עדכן כרטיס
actions-update-deck = עדכן חפיסה
actions-forget-card = שכח כרטיס
actions-build-filtered-deck = בנה חפיסה
actions-expand-collapse = הרחב/כווץ
actions-add-notetype = הוסף סוג רשומה
actions-remove-notetype = הסר סוג רשומה
actions-update-notetype = עדכן סוג רשומה
actions-update-config = עדכן הגדרה
actions-card-info = מידע כרטיס

## Flags

