actions-add = הוספה
actions-all-selected = כל אלו שנבחרו
actions-any-selected = כל אחד שנבחר
actions-blue-flag = דגל כחול
actions-cancel = ביטול
actions-choose = בחר
actions-close = סגירה
actions-copy = העתק
actions-custom-study = לימוד מותאם
actions-decks = חפיסות
actions-delete = מחק
actions-export = ייצוא
actions-filter = סנן
actions-green-flag = דגל ירוק
actions-help = עזרה
actions-import = ייבוא
actions-manage = נהל...
actions-name = שם:
actions-new = חדשים
actions-new-name = שם חדש:
actions-options = אפשרויות
actions-options-for = אפשריות ל-{ $val }
actions-orange-flag = דגל כתום
actions-preview = תצוגה מקדימה
actions-rebuild = בנה מחדש
actions-red-flag = דגל אדום
actions-rename = שנה שם
actions-rename-deck = שנה שם חפיסה
actions-rename-tag = שנה תגית
actions-remove-tag = הסר תגית
actions-replay-audio = נגן אודיו מחדש
actions-reposition = שנה מיקום
actions-save = שמור
actions-search = חיפוש
actions-select = בחירה
actions-shortcut-key = מקש קיצור: { $val }
actions-suspend-card = השהה כרטיס
actions-set-due-date = הגדר תאריך יעד
actions-forget = שכח
