card-stats-added = נוספו
card-stats-first-review = סקירה ראשונה
card-stats-latest-review = סקירה אחרונה
card-stats-interval = מרווח-זמן
card-stats-ease = קלות
card-stats-review-count = סקירות
card-stats-lapse-count = שגיאות
card-stats-average-time = זמן ממוצע
card-stats-total-time = זמן כולל
card-stats-new-card-position = מיקום
card-stats-card-template = סוג כרטיס
card-stats-note-type = סוג הערה
card-stats-deck-name = חפיסה
card-stats-note-id = מזהה הערה
card-stats-card-id = מזהה כרטיס
card-stats-review-log-rating = ניקוד
card-stats-review-log-type = סוג
card-stats-review-log-date = תאריך
card-stats-review-log-time-taken = שעה
card-stats-review-log-type-learn = לימוד
card-stats-review-log-type-review = סקירה
card-stats-review-log-type-relearn = ‏‏לימוד חוזר
card-stats-review-log-type-filtered = מסונן
