card-stats-added = נוספו
card-stats-first-review = חזרה ראשונה
card-stats-latest-review = חזרה אחרונה
card-stats-interval = מרווח-זמן
card-stats-ease = קלות
card-stats-review-count = חזרות
card-stats-lapse-count = שגיאות
card-stats-average-time = זמן ממוצע
card-stats-total-time = זמן כולל
card-stats-new-card-position = מיקום
card-stats-card-template = סוג כרטיסייה
card-stats-note-type = סוג הערה
card-stats-deck-name = חפיסה
card-stats-note-id = ID הערה
card-stats-card-id = ID כרטיסייה
card-stats-review-log-rating = ניקוד
card-stats-review-log-type = סוג
card-stats-review-log-date = תאריך
card-stats-review-log-time-taken = שעה
card-stats-review-log-type-learn = למד
card-stats-review-log-type-review = סקירה
card-stats-review-log-type-relearn = למד מחדש
card-stats-review-log-type-filtered = מסונן
