decks-add-new-deck-ctrlandn = הוסף חפיסה חדשה (Ctrl+N)
decks-build = בנה
decks-cards-selected-by = כרטיסים נבחרים לפי
decks-create-deck = צור חפיסה
decks_create_even_if_empty = צור/עדכן את החפיסה הזו גם אם היא ריקה
decks-custom-steps-in-minutes = צעדים מותאמים אישית (דקות)
decks-deck = חפיסה
decks-decreasing-intervals = הפחתת מרווחי זמן
decks-delete-deck = מחק חפיסה
decks-enable-second-filter = אפשר פילטר שני
decks-filter = סינון:
decks-filter-2 = סנן 2
decks-get-shared = קבל שיתופים
decks-import-file = ייבא קובץ
decks-increasing-intervals = הגדלת מרווחי זמן
decks-latest-added-first = נוספו לאחרונה
decks-limit-to = הגבל ל־
decks-minutes = דקות
decks-most-lapses = השגיאות הרבות ביותר
decks-new-deck-name = שם חפיסה חדש:
decks-no-deck = [אין חפיסות]
decks-oldest-seen-first = הישנים ביותר
decks-order-added = סדר ההוספה
decks-order-due = תאריך יעד
decks-please-select-something = נא בחר משהו.
decks-random = אקראי
decks-relative-overdueness = איחור יחסי
decks-repeat-failed-cards-after = חזור על הכרטיסיות שנכשלו לאחר
# e.g. "Delay for Again", "Delay for Hard", "Delay for Good"
decks-delay-for-button = מרווח עבור { $button }
decks-reschedule-cards-based-on-my-answers = תזמן כרטיסים מחדש על בסיס התשובות שלי בחפיסה זו.
decks-study = למד
decks-study-deck = למד חפיסה
decks-filtered-deck-search-empty = אין כרטיסים שתואמים לחיפוש המבוקש. יתכן שחלק מהכרטיסים לא נכללו בחיפוש משום שהם בחפיסה מסוננת אחרת, או שהם מושהים.
decks-unmovable-cards = הצג בדפדוף את כל הכרטיסים שאינם תואמים להגדרה
decks-learn-header = לימוד
# The count of cards waiting to be reviewed
decks-review-header = מתוזמנים
decks-zero-minutes-hint = (0 = החזרת כרטיס לחפיסה המקורית)
