editing-add-media = הוסף מדיה
editing-an-error-occurred-while-opening = שגיאה התרחשה בזמן פתיחת { $val }
editing-attach-picturesaudiovideo-f3 = צרף תמונה\אודיו\ווידאו (F3)
editing-bold-text-ctrlandb = טקסט מודגש (Ctrl+B)
editing-cards = כרטיסים
editing-change-colour-f8 = שנה צבע (F8)
editing-cloze-deletion-ctrlandshiftandc = השלם את החסר (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = הקלטת אודיו נכשלה. האם התקנת 'lame'?
editing-customize-card-templates-ctrlandl = התאם-אישית תבניות של כרטיסים (Ctrl+L)
editing-customize-fields = התאם-אישית שדות
editing-cut = גזור
editing-edit-current = ערוך נוכחי
editing-edit-html = ערוך HTML
editing-fields = שדות
editing-html-editor = עורך HTML
editing-italic-text-ctrlandi = טקסט נטוי (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = עבור לתגיות עם Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = משוואת LaTeX
editing-latex-math-env = סביבת מתמטיקה באמצעות LaTeX
editing-mathjax-block = בלוק MathJax
editing-mathjax-chemistry = כימיה באמצעות MathJax
editing-mathjax-inline = MathJax כחלק משורה
editing-media = מדיה
editing-paste = הדבק
editing-record-audio-f5 = הקלט אודיו (F5)
editing-remove-formatting-ctrlandr = הסר עיצוב (Ctrl+R)
editing-set-foreground-colour-f7 = הגדר צבע חזית (F7)
editing-show-duplicates = הצג כפילויות
editing-subscript-ctrland = כתב תחתון (Ctrl+=)
editing-superscript-ctrlandand = כתב עליון (Ctrl++)
editing-tags = תגיות
editing-to-make-a-cloze-deletion-on = ליצור השלם את החסר ברשומה קיימת, תצטרך לשנות את סוג הרשומה להשלם את החסר, דרך 'רשומות>שנה סוג רשומה'
editing-underline-text-ctrlandu = סמן טקסט בקו תחתון (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = אזהרה, השלם את החסר לא יעבוד עד שתשנה את הסוג למעלה להשלם את החסר.
