editing-actual-size = שנה גודל
editing-add-media = הוסף מדיה
editing-align-left = יישור לשמאל
editing-align-right = יישור לימין
editing-an-error-occurred-while-opening = שגיאה התרחשה בזמן פתיחת { $val }
editing-attach-picturesaudiovideo = צרף תמונות/שמע/וידאו
editing-bold-text = טקסט מודגש
editing-cards = כרטיסים
editing-center = מרכז
editing-change-color = שינוי צבע
editing-cloze-deletion = השלם את החסר
editing-couldnt-record-audio-have-you-installed = הקלטת אודיו נכשלה. האם התקנת 'lame'?
editing-customize-card-templates = שנה תבניות כרטיס
editing-customize-fields = התאם אישית שדות
editing-cut = גזור
editing-edit-current = ערוך נוכחי
editing-edit-html = ערוך HTML
editing-fields = שדות
editing-float-left = הצמד לשמאל
editing-float-right = הצמד לימין
editing-float-none = ללא הצמדה
editing-html-editor = עורך HTML
editing-indent = הגדל הזחה
editing-italic-text = טקסט נטוי
editing-jump-to-tags-with-ctrlandshiftandt = עבור לתגיות עם Ctrl+Shift+T
editing-justify = יישור לשני הצדדים
editing-latex = LaTeX
editing-latex-equation = משוואת LaTeX
editing-latex-math-env = סביבת מתמטיקה באמצעות LaTeX
editing-mathjax-block = בלוק MathJax
editing-mathjax-chemistry = כימיה באמצעות MathJax
editing-mathjax-inline = MathJax כחלק משורה
editing-media = מדיה
editing-ordered-list = רשימה (מספרים)
editing-outdent = הקטן הזחה
editing-paste = הדבק
editing-record-audio = הקלט שמע
editing-remove-formatting = הסר עיצוב
editing-set-text-color = צבע טקסט
editing-set-text-highlight-color = צבע רקע לטקסט
editing-show-duplicates = הצג כפילויות
editing-subscript = כתב תחתי
editing-superscript = ‏‏כתב עילי
editing-tags = תגיות
editing-to-make-a-cloze-deletion-on = ליצור השלם את החסר ברשומה קיימת, תצטרך לשנות את סוג הרשומה להשלם את החסר, דרך 'רשומות>שנה סוג רשומה'
editing-toggle-sticky = שמור שדה לשאלה הבאה
editing-underline-text = קו תחתון
editing-unordered-list = רשימה (נקודות)
editing-warning-cloze-deletions-will-not-work = אזהרה, השלם את החסר לא יעבוד עד שתשנה את הסוג למעלה להשלם את החסר.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = טקסט מודגש (Ctrl+B)
editing-italic-text-ctrlandi = טקסט נטוי (Ctrl+I)
editing-underline-text-ctrlandu = סמן טקסט בקו תחתון (Ctrl+U)
editing-subscript-ctrland = כתב תחתון (Ctrl+=)
editing-superscript-ctrlandand = כתב עליון (Ctrl++)
editing-remove-formatting-ctrlandr = הסר עיצוב (Ctrl+R)
editing-record-audio-f5 = הקלט אודיו (F5)
editing-attach-picturesaudiovideo-f3 = צרף תמונה\אודיו\ווידאו (F3)
editing-cloze-deletion-ctrlandshiftandc = השלם את החסר (Ctrl+Shift+C)
editing-change-colour-f8 = שנה צבע (F8)
editing-set-foreground-colour-f7 = הגדר צבע חזית (F7)
editing-customize-card-templates-ctrlandl = התאם אישית תבניות של כרטיסים (Ctrl+L)
editing-set-foreground-color = קבע צבע חזית
