exporting-all-decks = כל החפיסות
exporting-anki-20-deck = חפיסת Anki 2.0
exporting-anki-collection-package = חבילת מאגר Anki
exporting-anki-deck-package = חבילת חפיסת Anki
exporting-cards-in-plain-text = כרטיסים בטקסט פשוט
exporting-collection = אוסף
exporting-collection-exported = התבצע ייצוא האוסף.
exporting-couldnt-save-file = שמירת קובץ נכשלה: { $val }
exporting-export = ייצוא...
exporting-export-format = <b>תבנית ייצוא</b>:
exporting-include = <b>כולל</b>:
exporting-include-html-and-media-references = כלול HTML והפניות מדיה
exporting-include-media = כלול מדיה
exporting-include-scheduling-information = כלול מידע על מועדים קבועים מראש
exporting-include-tags = כלול תגיות
exporting-notes-in-plain-text = רשומות בטקסט רגיל
exporting-selected-notes = רשומות נבחרות
