card-templates-card-type = Тип карата:
card-templates-front-template = Шаблон лица
card-templates-back-template = Шаблон наличја
card-templates-template-styling = Стил
card-templates-front-preview = Пример лица
card-templates-back-preview = Преглед наличја
card-templates-preview-box = Преглед
card-templates-sample-cloze = Ево га {"{{c1::"}пример{"}}"} попуњавања пропуштеног.
card-templates-anki-couldnt-find-the-line-between = Anki није пронашао линију између питања и одговора. Да бисте заменили њихова места, уредите шаблон ручно.
card-templates-at-least-one-card-type-is = Мора да постоји бар један тип карте.
card-templates-card = Карта { $val }
card-templates-card-types = Типови карата
card-templates-card-types-for = Типови карата за { $val }
card-templates-cloze = Пропусти
card-templates-delete-the-as-card-type-and = Избриши '%(a)s' тип карте и њен %(b)s?
card-templates-enter-deck-to-place-new = Задајте шпил за смештање нових карата { $val }, или оставите поље празно:
card-templates-enter-new-card-position-1 = Унесите нову позицију карте (1...{ $val }):
card-templates-flip = Преврни
card-templates-form = Образац
card-templates-off =  искљ.
card-templates-on =  укљ.
