adding-add-shortcut-ctrlandenter = Dodaj (prečac: ctrl+enter)
adding-added = Dodano
adding-discard-current-input = Odbaciti trenutni unos?
adding-keep-editing = Nastavi uređivati
adding-edit = Uredi "{ $val }"
adding-history = Povijest
adding-note-deleted = (Bilješka izbrisana)
adding-shortcut = Prečac: { $val }
adding-the-first-field-is-empty = Prvo polje je prazno.
