fields-add-field = Dodaj polje
fields-delete-field-from = Obrisati polje iz { $val }?
fields-field = Polje:
fields-field-name = Ime polja:
fields-description = Opis
fields-description-placeholder = Tekst koji se prikazuje unutar polja kad je prazno
fields-fields-for = Polja za { $val }
fields-font = Font:
fields-new-position-1 = Novi položaj (1...{ $val }):
fields-notes-require-at-least-one-field = Bilješka zahtijeva barem jedno polje.
fields-reverse-text-direction-rtl = Obrnuti smjer teksta (s desna)
fields-size = Veličina:
fields-sort-by-this-field-in-the = Sortiraj prema ovom polju u pregledniku
fields-that-field-name-is-already-used = Taj naziv za polje je već u uporabi.
fields-name-first-letter-not-valid = Naziv polja ne bi trebao počinjati s #, ^ ili /.
fields-name-invalid-letter = Ime polja ne bi trebalo sadržavati :, ", { "{" } ili { "}" }.
fields-field-is-required = Ovo je obvezno polje, ne može ga se obrisati.
