studying-again = Ponovno
studying-bury = Zakopaj
studying-bury-note = Zakopaj bilješku
studying-card-was-a-leech = Karta je bila pijavica.
studying-delete-note = Obriši bilješku
studying-easy = Lagano
studying-edit = Uredi
studying-empty = Prazno
studying-good = Dobro
studying-hard = Teško
studying-it-has-been-suspended = Suspendirana je.
studying-more = Više
studying-note-buried = Bilješka je zakopana.
studying-note-suspended = Bilješka suspendirana.
studying-record-own-voice = Snimi vlastiti glas
studying-replay-own-voice = Reproducirajte vlastiti glas
studying-show-answer = Prikaži odgovor
studying-space = Razmak
studying-study-now = Uči sad
studying-suspend = Suspendiraj
studying-suspend-note = Suspendiraj bilješku
studying-to-review = Za ponavljanje
studying-you-havent-recorded-your-voice-yet = Još niste snimili svoj glas.
