decks-add-new-deck-ctrlandn = Criar Novo Baralho (Ctrl+N)
decks-build = Criar
decks-cards-selected-by = fichas seleccionadas por
decks-create-deck = Criar Baralho
decks_create_even_if_empty = Criar/Actualizar o baralho, mesmo que este esteja vazio
decks-custom-steps-in-minutes = Intervalos personalizados (em minutos)
decks-deck = Baralho
decks-decreasing-intervals = Mais distantes a estudar/revisar
decks-delete-deck = Eliminar baralho
decks-enable-second-filter = Activar segundo filtro
decks-filter = Filtro:
decks-filter-2 = Filtro 2
decks-get-shared = Obter partilha
decks-import-file = Importar ficheiro
decks-increasing-intervals = Mais próximos a estudar/rever
decks-latest-added-first = Criados há menos tempo
decks-limit-to = Limitar a
decks-minutes = minutos
decks-most-lapses = Mais respostas erradas
decks-new-deck-name = Novo nome do baralho:
decks-no-deck = [sem baralho]
decks-oldest-seen-first = Mais antiga data do primeiro estudo
decks-order-added = Criados há mais tempo
decks-order-due = Revisões mais próximas
decks-please-select-something = Por favor, selecione algo.
decks-random = Aleatório
decks-relative-overdueness = Atrasos relativos
decks-reschedule-cards-based-on-my-answers = Re-agendar fichas com base nas minhas respostas neste baralho
decks-study = Estudar
decks-study-deck = Estudar Baralho
decks-learn-header = Aprender
# The count of cards waiting to be reviewed
decks-review-header = A rever
