actions-add = Ajouter
actions-blue-flag = Marqueur bleu
actions-cancel = Annuler
actions-choose = Choisir
actions-close = Fermer
actions-copy = Copier
actions-custom-study = Révisions particulières
actions-decks = Paquets
actions-delete = Supprimer
actions-export = Exporter
actions-filter = Filtrer
actions-green-flag = Marqueur vert
actions-help = Aide
actions-import = Importer
actions-manage = Gérer...
actions-name = Nom :
actions-new = Inédites
actions-new-name = Nouveau nom :
actions-options = Options
actions-options-for = Options pour { $val }
actions-orange-flag = Marqueur orange
actions-preview = Aperçu
actions-rebuild = Reconstruire
actions-red-flag = Marqueur rouge
actions-rename = Renommer
actions-rename-deck = Renommer le paquet
actions-replay-audio = Rejouer le son
actions-reposition = Repositionner
actions-save = Enregistrer
actions-search = Chercher
actions-shortcut-key = Raccourci : { $val }
actions-suspend-card = Suspendre la carte
actions-set-due-date = Définir une date d'échéance
