actions-add = Ajouter
actions-all-selected = Tous les sélectionnés
actions-any-selected = Toute sélection
actions-blue-flag = Marqueur bleu
actions-cancel = Annuler
actions-choose = Choisir
actions-close = Fermer
actions-copy = Copier
actions-custom-study = Révisions particulières
actions-decks = Paquets
actions-delete = Supprimer
actions-export = Exporter
actions-filter = Filtrer
actions-green-flag = Marqueur vert
actions-help = Aide
actions-import = Importer
actions-manage = Gérer...
actions-name = Nom :
actions-new = Inédites
actions-new-name = Nouveau nom :
actions-options = Options
actions-options-for = Options pour { $val }
actions-orange-flag = Marqueur orange
actions-preview = Aperçu
actions-rebuild = Reconstruire
actions-red-flag = Marqueur rouge
actions-rename = Renommer
actions-rename-deck = Renommer le paquet
actions-rename-tag = Renommer le tag
actions-remove-tag = Enlever le tag
actions-replay-audio = Rejouer le son
actions-reposition = Repositionner
actions-save = Enregistrer
actions-search = Chercher
actions-select = Sélectionner
actions-shortcut-key = Raccourci : { $val }
actions-suspend-card = Suspendre la carte
actions-set-due-date = Définir une date d'échéance
actions-forget = Oublier
actions-answer-card = Réponse
actions-unbury-unsuspend = Déterrer/Enlever la suspension
actions-add-deck = Ajouter un paquet
actions-add-note = Ajouter une note
actions-update-tag = Modifier le tag
actions-update-note = Modifier la note
actions-update-card = Modifier la carte
actions-update-deck = Modifier le paquet
actions-forget-card = Oublier la carte
actions-set-flag = Définir le marqueur
actions-build-filtered-deck = Construire le paquet
actions-expand-collapse = Développer/Réduire
actions-add-notetype = Ajouter un type de note
actions-remove-notetype = Enlever le type de note
actions-update-notetype = Modifier le type de note
actions-update-config = Modifier la configuration
actions-card-info = Info carte
