card-stats-added = Ajouté
card-stats-first-review = Première révision
card-stats-latest-review = Dernière révision
card-stats-interval = Intervalle
card-stats-ease = Facilité
card-stats-review-count = Révisions
card-stats-lapse-count = Echecs
card-stats-average-time = Durée moyenne
card-stats-total-time = Durée totale
card-stats-new-card-position = Position
card-stats-card-template = Type de carte
card-stats-note-type = Type de note
card-stats-deck-name = Paquet
card-stats-note-id = Identifiant note
card-stats-card-id = Identifiant carte
