custom-study-must-rename-deck = Veuillez d'abord renommer le paquet de révision personnalisé existant.
custom-study-all-cards-in-random-order-dont = Toutes les cartes dans un ordre aléatoire (ne pas replanifier)
custom-study-all-review-cards-in-random-order = Toutes les cartes à revoir dans un ordre aléatoire
custom-study-cards = carte(s)
custom-study-cards-from-the-deck = Les cartes du paquets
custom-study-choose-tags = Choisir les marqueurs
custom-study-custom-study-session = Séance de révisions particulières
custom-study-due-cards-only = Seulement les cartes dues
custom-study-increase-todays-new-card-limit = Accroître le quota de cartes inédites
custom-study-increase-todays-new-card-limit-by = Accroître le quota de cartes inédites de
custom-study-increase-todays-review-card-limit = Accroître le quota de cartes à revoir
custom-study-increase-todays-review-limit-by = Accroître le quota de cartes à revoir de
custom-study-new-cards-in-deck-over-today = Le nombre de nouvelles cartes dans le paquet dépasse la limite pour aujourd’hui : { $val }
custom-study-new-cards-only = Seulement les nouvelles cartes
custom-study-no-cards-matched-the-criteria-you = Aucune carte ne remplit les critères demandés.
custom-study-ok = Valider
custom-study-preview-new-cards = Aperçu des cartes inédites
custom-study-preview-new-cards-added-in-the = Voir les cartes inédites ajoutées ces derniers
custom-study-require-one-or-more-of-these = Il faut au moins l’un de ces marqueurs :
custom-study-review-ahead = Avancer la révision
custom-study-review-ahead-by = Avancer la révision de
custom-study-review-cards-forgotten-in-last = Revoir les cartes oubliées la dernière fois
custom-study-review-forgotten-cards = Revoir les cartes oubliées
custom-study-reviews-due-in-deck-over-today = Révisions requises par le paquet au delà de la limite d’aujourd’hui : { $val }
custom-study-select = Sélection
custom-study-select-tags-to-exclude = Ôter par les marqueurs :
custom-study-selective-study = Révision sélective
custom-study-study-by-card-state-or-tag = Étude par carte ou par étiquette
