editing-add-media = Ajouter des médias
editing-align-left = Aligner à gauche
editing-align-right = Aligner à droite
editing-an-error-occurred-while-opening = Une erreur est survenue lors de l’ouverture de { $val }
editing-attach-picturesaudiovideo = Joindre des images/fichiers audios/vidéos
editing-bold-text = Texte en gras
editing-cards = Cartes
editing-center = Centre
editing-change-color = Changer de couleur
editing-cloze-deletion = Texte à trous
editing-couldnt-record-audio-have-you-installed = Impossible d’enregistrer le son. Avez-vous installé 'lame' ?
editing-customize-card-templates = Personnaliser les modèles de carte
editing-customize-fields = Personnaliser les champs
editing-cut = Couper
editing-edit-current = Modifier la carte en cours
editing-edit-html = Modifier le HTML
editing-fields = Champs
editing-indent = Augmenter l'indentation
editing-italic-text = Italique
editing-jump-to-tags-with-ctrlandshiftandt = Aller aux tags avec Ctrl+Shift+T
editing-justify = Justifié
editing-latex = LaTeX
editing-latex-equation = Équation LaTeX
editing-latex-math-env = Env. math. LaTeX
editing-mathjax-block = Bloc de MathJax
editing-mathjax-chemistry = MathJax chimie
editing-mathjax-inline = MathJax en ligne
editing-mathjax-placeholder = Appuyez sur { $accept } pour accepter, { $newline } pour une nouvelle ligne.
editing-media = Médias
editing-ordered-list = Liste ordonée
editing-outdent = Diminuer l'indentation
editing-paste = Coller
editing-record-audio = Enregistrer l'audio
editing-remove-formatting = Supprimer le formatage
editing-set-text-color = Définir la couleur du texte
editing-set-text-highlight-color = Définir la couleur de la surbrillance du texte
editing-show-duplicates = Afficher les doublons
editing-subscript = Indice
editing-superscript = Exposant
editing-tags = Tags
editing-to-make-a-cloze-deletion-on = Pour faire d’une carte déjà existante, un texte à trous, il faut passer par « Édition > Modifier le type de la note » et choisir « Texte à trous ».
editing-underline-text = Souligné
editing-unordered-list = Liste non ordonnée
editing-warning-cloze-deletions-will-not-work = Attention, le texte à trous ne fonctionnera pas tant que vous ne changez pas le type de carte en « Texte à trous » (en haut de la fenêtre).

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Vue en langage hypertexte
