editing-add-media = Ajouter des médias
editing-an-error-occurred-while-opening = Une erreur est survenue lors de l’ouverture de { $val }
editing-attach-picturesaudiovideo-f3 = Joindre des images/fichiers audios/vidéos (F3)
editing-bold-text-ctrlandb = Gras (Ctrl-B)
editing-cards = Cartes
editing-change-colour-f8 = Changer de couleur (F8)
editing-cloze-deletion-ctrlandshiftandc = Texte à trous (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Impossible d’enregistrer le son. Avez-vous installé 'lame' ?
editing-customize-card-templates-ctrlandl = Personnaliser les modèles de carte (Ctrl+L)
editing-customize-fields = Personnaliser les champs
editing-cut = Couper
editing-edit-current = Modifier la carte en cours
editing-edit-html = Modifier le HTML
editing-fields = Champs
editing-html-editor = Vue en langage hypertexte
editing-italic-text-ctrlandi = Texte italique (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Aller aux mots-clés avec Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Équation LaTeX
editing-latex-math-env = Env. math. LaTeX
editing-mathjax-block = Bloc de MathJax
editing-mathjax-chemistry = MathJax chimie
editing-mathjax-inline = MathJax en ligne
editing-media = Médias
editing-paste = Coller
editing-record-audio-f5 = Enregistrer un son (F5)
editing-remove-formatting-ctrlandr = Supprimer le formatage (Ctrl-R)
editing-set-foreground-colour-f7 = Choisir une couleur (F7)
editing-show-duplicates = Afficher les doublons
editing-subscript-ctrland = Indice  (Ctrl+=)
editing-superscript-ctrlandand = Exposant (Ctrl++)
editing-tags = Marqueurs
editing-to-make-a-cloze-deletion-on = Pour faire d’une carte déjà existante, un texte à trous, il faut passer par « Édition > Modifier le type de la note » et choisir « Texte à trous ».
editing-underline-text-ctrlandu = Souligné (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Attention, le texte à trous ne fonctionnera pas tant que vous ne changez pas le type de carte en « Texte à trous » (en haut de la fenêtre).
