editing-add-media = Ajouter des médias
editing-align-left = Aligner à gauche
editing-align-right = Aligner à droite
editing-an-error-occurred-while-opening = Une erreur est survenue lors de l’ouverture de { $val }
editing-attach-picturesaudiovideo = Joindre des images/fichiers audios/vidéos
editing-bold-text = Texte en gras
editing-cards = Cartes
editing-center = Centre
editing-change-color = Changer de couleur
editing-cloze-deletion = Texte à trous
editing-couldnt-record-audio-have-you-installed = Impossible d’enregistrer le son. Avez-vous installé 'lame' ?
editing-customize-card-templates = Personnaliser les modèles de carte
editing-customize-fields = Personnaliser les champs
editing-cut = Couper
editing-edit-current = Modifier la carte en cours
editing-edit-html = Modifier le HTML
editing-fields = Champs
editing-html-editor = Vue en langage hypertexte
editing-indent = Augmenter l'indentation
editing-italic-text = Italique
editing-jump-to-tags-with-ctrlandshiftandt = Aller aux tags avec Ctrl+Shift+T
editing-justify = Justifié
editing-latex = LaTeX
editing-latex-equation = Équation LaTeX
editing-latex-math-env = Env. math. LaTeX
editing-mathjax-block = Bloc de MathJax
editing-mathjax-chemistry = MathJax chimie
editing-mathjax-inline = MathJax en ligne
editing-media = Médias
editing-ordered-list = Liste ordonée
editing-outdent = Diminuer l'indentation
editing-paste = Coller
editing-record-audio = Enregistrer l'audio
editing-remove-formatting = Supprimer le formatage
editing-set-foreground-color = Choisir une couleur
editing-show-duplicates = Afficher les doublons
editing-subscript = Indice
editing-superscript = Exposant
editing-tags = Tags
editing-to-make-a-cloze-deletion-on = Pour faire d’une carte déjà existante, un texte à trous, il faut passer par « Édition > Modifier le type de la note » et choisir « Texte à trous ».
editing-underline-text = Souligné
editing-unordered-list = Liste non ordonnée
editing-warning-cloze-deletions-will-not-work = Attention, le texte à trous ne fonctionnera pas tant que vous ne changez pas le type de carte en « Texte à trous » (en haut de la fenêtre).

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Gras (Ctrl-B)
editing-italic-text-ctrlandi = Texte italique (Ctrl+I)
editing-underline-text-ctrlandu = Souligné (Ctrl+U)
editing-subscript-ctrland = Indice  (Ctrl+=)
editing-superscript-ctrlandand = Exposant (Ctrl++)
editing-remove-formatting-ctrlandr = Supprimer le formatage (Ctrl-R)
editing-record-audio-f5 = Enregistrer un son (F5)
editing-attach-picturesaudiovideo-f3 = Joindre des images/fichiers audios/vidéos (F3)
editing-cloze-deletion-ctrlandshiftandc = Texte à trous (Ctrl+Shift+C)
editing-change-colour-f8 = Changer de couleur (F8)
editing-set-foreground-colour-f7 = Choisir une couleur (F7)
editing-customize-card-templates-ctrlandl = Personnaliser les modèles de carte (Ctrl+L)
