exporting-all-decks = Tous les paquets
exporting-anki-20-deck = Paquet ANKI 2.0
exporting-anki-collection-package = Collection des paquets Anki
exporting-anki-deck-package = Tas de paquets ANKI
exporting-cards-in-plain-text = Cartes avec texte en clair
exporting-collection = collection
exporting-collection-exported = Collection exportée.
exporting-couldnt-save-file = Le fichier { $val } n’a pas pu être sauvegardé.
exporting-export = Exporter...
exporting-export-format = <b>Format d’exportation</b> :
exporting-include = <b>Inclure</b> :
exporting-include-html-and-media-references = Inclure des références HTML et médiatiques
exporting-include-media = Inclure les médias
exporting-include-scheduling-information = Inclure les données de planification
exporting-include-tags = Inclure les marqueurs
exporting-notes-in-plain-text = Notes en texte
exporting-selected-notes = Notes selectionnées
