preferences-automatically-sync-on-profile-openclose = Synchroniser automatiquement à l’ouverture et à la fermeture
preferences-backups = Sauvegardes
preferences-backups2 = sauvegardes
preferences-backupsanki-will-create-a-backup-of = <b>Sauvegardes</b><br>Anki va créer une sauvegarde de votre collection à chaque fois qu’il est fermé ou synchronisé.
preferences-basic = Basique
preferences-change-deck-depending-on-note-type = Changer le paquet selon le type de note
preferences-changes-will-take-effect-when-you = Les modifications prendront effet au redémarrage d'Anki.
preferences-hours-past-midnight = heure(s) après minuit
preferences-interface-language = Langue de l’interface
preferences-interrupt-current-audio-when-answering = Interrompre l’audio en cours de lecture lors de la réponse
preferences-keep = Conserver
preferences-learn-ahead-limit = Réviser en avance de
preferences-mins = minute(s)
preferences-network = Réseau
preferences-next-day-starts-at = Le jour suivant démarre à
preferences-night-mode = Mode nuit
preferences-note-media-is-not-backed-up = Information : les médias ne sont pas restaurés. Il serait sage de sauvegarder régulièrement votre dossier Anki.
preferences-on-next-sync-force-changes-in = À la prochaine synchronisation, forcer les changements dans une direction.
preferences-paste-clipboard-images-as-png = Coller les images du presse-papier en PNG.
preferences-paste-without-shift-key-strips-formatting = Coller sans maintenir la touche Maj retire le formatage
preferences-periodically-sync-media = Synchroniser périodiquement les médias
preferences-please-restart-anki-to-complete-language = S’il vous plait, redémarrez Anki pour finaliser le changement de langue.
preferences-preferences = Préférences
preferences-scheduling = Replanifier
preferences-show-learning-cards-with-larger-steps = Montrer les cartes en cours d’apprentissage avec de plus grand pas avant de les revoir
preferences-show-next-review-time-above-answer = Afficher la date de la prochaine révision au dessus des boutons
preferences-show-play-buttons-on-cards-with = Afficher les boutons de lecture sur les cartes avec de l’audio
preferences-show-remaining-card-count-during-review = Afficher le nombre de cartes restantes durant la révision
preferences-some-settings-will-take-effect-after = Certains réglages ne s’appliqueront qu’après le redémarrage d’Anki.
preferences-synchronisation = <b>Synchronisation</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synchronisation</b><br> Désactivée pour le moment ; pour l’activer cliquez sur le bouton de synchronisation dans la fenêtre principale.
preferences-synchronize-audio-and-images-too = Synchroniser l’audio et les images également
preferences-this-will-reset-any-cards-in = Ceci réinitialisera toutes les cartes et cours d’apprentissage, supprimera les paquets filtrés et changera la version du planificateur. Voulez-vous continuer ?
preferences-timebox-time-limit = Montrer la progression toutes les
preferences-user-interface-size = Taille de l’interface
preferences-when-adding-default-to-current-deck = Ajouter par défaut au paquet courant
preferences-you-can-restore-backups-via-fileswitch = Vous pouvez restaurer les sauvegardes en passant par Fichier > Changer de compte.
preferences-legacy-timezone-handling = Ancienne gestion des fuseaux horaires (bugué, mais nécessaire pour AnkiDroid <= 2.14)
