profiles-anki-could-not-read-your-profile = Anki n’a pas pu lire les données de votre profil. Les tailles des fenêtres et les informations de connexion à la synchronisation ont été oubliées.
profiles-anki-could-not-rename-your-profile = Anki n’a pas pu renommer votre profil car il n’a pas réussi à renommer le dossier profil sur le disque. Veuillez vous assurer que vous avez bien la permission d’écrire dans Documents/Anki et qu’aucune autre application n’est en train d’accéder à vos dossiers profils, puis réessayez.
profiles-folder-already-exists = Le dossier existe déjà.
profiles-open = Ouvrir
profiles-open-backup = Ouvrir la sauvegarde...
profiles-please-remove-the-folder-and = Veuillez enlever le dossier { $val } et réessayer.
profiles-profile-corrupt = Profil corrompu
profiles-profiles = Comptes
profiles-quit = Quitter
profiles-user-1 = Utilisateur 1
