studying-again = À revoir
studying-all-buried-cards = Toutes les cartes enfouies
studying-audio-5s = Audio -5s
studying-audio-and5s = Audio +5s
studying-buried-siblings = Enfouir les cartes connexes
studying-bury = Enfouir
studying-bury-card = Enfouir la carte
studying-bury-note = Enfouir la note
studying-card-buried = Carte enfouie.
studying-card-suspended = Carte exclue.
studying-card-was-a-leech = Cette carte est pénible.
studying-cards-will-be-automatically-returned-to = Les cartes reviendront à leurs paquets d’origine après révision.
studying-continue = Continuer
studying-delete-note = Supprimer la note
studying-deleting-this-deck-from-the-deck = En supprimant le paquet de la liste des paquets, ses cartes reviendront à leur paquet d’origine.
studying-easy = Facile
studying-edit = Modifier
studying-empty = Vide
studying-finish = Terminer
studying-flag-card = Marqueur de carte
studying-good = Correct
studying-hard = Difficile
studying-it-has-been-suspended = La carte a été suspendue.
studying-manually-buried-cards = Cartes enfouies manuellement
studying-mark-note = Marquez la note
studying-more = Autres choix
studying-no-cards-are-due-yet = Aucune carte n’est arrivée à échéance pour le moment.
studying-note-buried = Note enterrée.
studying-note-suspended = Note suspendue.
studying-pause-audio = Pause audio
studying-please-run-toolsempty-cards = Merci d’utiliser le menu Outils > Cartes vides
studying-record-own-voice = S’enregistrer
studying-replay-own-voice = Se réécouter
studying-show-answer = Afficher la réponse
studying-space = Espace
studying-study-now = Étudier maintenant
studying-suspend = Suspendre
studying-suspend-note = Suspendre la note
studying-this-is-a-special-deck-for = Ce paquet permet de réviser indépendamment de la planification d’Anki.
studying-to-review = À réviser
studying-type-answer-unknown-field = Champ inconnu { $val }
studying-unbury = Exhumer
studying-what-would-you-like-to-unbury = Que voudriez-vous déterrer ?
studying-you-havent-recorded-your-voice-yet = Vous ne vous êtes pas encore enregistré.
