actions-add = Добавить
actions-all-selected = Все выбранные
actions-any-selected = Любое из выбранного
actions-cancel = Отменить
actions-choose = Выбрать
actions-close = Закрыть
actions-copy = Копировать
actions-custom-study = Учить ещё
actions-decks = Колоды
actions-delete = Удалить
actions-export = Экспортировать
actions-filter = Фильтр
actions-help = Справка
actions-import = Импортировать
actions-manage = Управлять...
actions-name = Имя:
actions-new = Новое
actions-new-name = Новое имя:
actions-options = Настройки
actions-options-for = Настройки для { $val }
actions-preview = Просмотреть
actions-rebuild = Обновить
actions-rename = Переименовать
actions-rename-deck = Переименовать колоду
actions-rename-tag = Переименовать метку
actions-remove-tag = Удалить метку
actions-replay-audio = Воспроизвести снова
actions-reposition = Переместить
actions-save = Сохранить
actions-search = Поиск
actions-select = Выбрать
actions-shortcut-key = Горячая клавиша: { $val }
actions-suspend-card = Исключить карточку
actions-set-due-date = Задать срок
actions-forget = Отложить
actions-answer-card = Карточка ответа
actions-unbury-unsuspend = Вернуть/Включить
actions-add-deck = Добавить колоду
actions-add-note = Добавить запись
actions-update-tag = Обновить метку
actions-update-note = Обновить запись
actions-update-card = Обновить карточку
actions-update-deck = Обновить колоду
actions-forget-card = Отложить карточку
actions-build-filtered-deck = Создать колоду
actions-expand-collapse = Развернуть/Свернуть
actions-add-notetype = Добавить тип записи
actions-remove-notetype = Удалить тип записи
actions-update-notetype = Обновить тип записи
actions-update-config = Обновить конфигурацию
actions-card-info = Сведения о карточке

## Flags

actions-flag-number = Флажок { $number }
actions-flag-red = Красный
actions-flag-orange = Оранжевый
actions-flag-green = Зеленый
actions-flag-blue = Синий
actions-flag-pink = Розовый
actions-flag-turquoise = Бирюзовый
actions-flag-purple = Фиолетовый
actions-set-flag = Установить флажок
