actions-add = Добавить
actions-blue-flag = Синий флаг
actions-cancel = Отменить
actions-choose = Выбрать
actions-close = Закрыть
actions-copy = Копировать
actions-custom-study = Учить ещё
actions-decks = Колоды
actions-delete = Удалить
actions-export = Экспортировать
actions-filter = Фильтр
actions-green-flag = Зелёный флаг
actions-help = Справка
actions-import = Импортировать
actions-manage = Управлять...
actions-name = Имя поля:
actions-new = Новые
actions-new-name = Новое имя:
actions-options = Настройки
actions-options-for = Конфигурация { $val }
actions-orange-flag = Оранжевый флаг
actions-preview = Предпросмотр
actions-rebuild = Перестроить
actions-red-flag = Красный флаг
actions-rename = Переименовать
actions-rename-deck = Переименовать колоду
actions-replay-audio = Повторное воспроизведение аудио
actions-reposition = Переместить
actions-save = Сохранить
actions-search = Поиск
actions-shortcut-key = Горячая клавиша: { $val }
actions-suspend-card = Исключить карточку
