card-stats-added = Добавлено
card-stats-first-review = Просмотрена впервые
card-stats-latest-review = Последнее повторение
card-stats-interval = Интервал
card-stats-ease = Лёгкость
card-stats-review-count = Повторена
card-stats-lapse-count = Забыта
card-stats-average-time = Среднее время
card-stats-total-time = Общее время
card-stats-new-card-position = Позиция
card-stats-card-template = Тип карточки
card-stats-note-type = Тип записи
card-stats-deck-name = Колода
card-stats-note-id = ID записи
card-stats-card-id = Идентификатор карточки
card-stats-review-log-rating = Оценка
card-stats-review-log-type = Тип
card-stats-review-log-date = Дата
card-stats-review-log-time-taken = Время
card-stats-review-log-type-learn = Изучаемые
card-stats-review-log-type-review = Повторяемые
card-stats-review-log-type-relearn = Переучиваемые
card-stats-review-log-type-filtered = Отфильтрованые
card-stats-review-log-type-manual = Ручной
