custom-study-must-rename-deck = Пожалуйста, сперва переименуйте существующую колоду Пользовательского изучения.
custom-study-all-cards-in-random-order-dont = Все карточки в случайном порядке (без перепланирования)
custom-study-all-review-cards-in-random-order = Все повторяемые карточки в случайном порядке
custom-study-cards = карточки
custom-study-cards-from-the-deck = карточки из колоды
custom-study-choose-tags = Выбрать метки
custom-study-custom-study-session = Учить ещё
custom-study-due-cards-only = Только карточки к просмотру
custom-study-increase-todays-new-card-limit = Добавить новых на сегодня
custom-study-increase-todays-new-card-limit-by = Увеличить лимит новых на
custom-study-increase-todays-review-card-limit = Добавить повторяемых на сегодня
custom-study-increase-todays-review-limit-by = Увеличить лимит повторениемых на
custom-study-new-cards-in-deck-over-today = Новые карточки в колоде сверх лимита: { $val }
custom-study-new-cards-only = Только новые карточки
custom-study-no-cards-matched-the-criteria-you = Нет карточек, подходящих под запрос.
custom-study-ok = ОК
custom-study-preview-new-cards = Предпросмотр новых карточек
custom-study-preview-new-cards-added-in-the = Предпросмотр новых карточек, добавленных за последние
custom-study-require-one-or-more-of-these = Требуется одна или несколько из этих меток:
custom-study-review-ahead = Просмотреть вперед (вне дневного лимита)
custom-study-review-ahead-by = Просмотреть вперед на
custom-study-review-cards-forgotten-in-last = Пересмотреть карточки, забытые в прошлом
custom-study-review-forgotten-cards = Повторить забытые карточки
custom-study-reviews-due-in-deck-over-today = Просмотреть в колоде повторяемые карточки сверх дневного лимита: { $val }
custom-study-select = Выбрать
custom-study-select-tags-to-exclude = Выберите исключаемые метки:
custom-study-selective-study = Выборочное обучение
custom-study-study-by-card-state-or-tag = Учить по состоянию карточки или по метке
