editing-add-media = Добавить медиафайл
editing-an-error-occurred-while-opening = При открытии { $val } возникла ошибка
editing-attach-picturesaudiovideo-f3 = Прикрепить изображение, аудио, видео (F3)
editing-bold-text-ctrlandb = Полужирный текст (Ctrl+B)
editing-cards = Карточки
editing-change-colour-f8 = Изменить цвет (F8)
editing-cloze-deletion-ctrlandshiftandc = Задание с пропусками (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = Не получается записать звук. У вас установлен "lame"?
editing-customize-card-templates-ctrlandl = Изменить шаблоны карточек (Ctrl+L)
editing-customize-fields = Изменить поля
editing-cut = Вырезать
editing-edit-current = Править текущую
editing-edit-html = Править HTML
editing-fields = Поля
editing-html-editor = Редактор HTML
editing-italic-text-ctrlandi = Курсив (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Перейти к меткам (Ctrl+Shift+T)
editing-latex = LaTeX
editing-latex-equation = Формула LaTeX
editing-latex-math-env = Окружение LaTeX
editing-mathjax-block = MathJax с выключкой
editing-mathjax-chemistry = MathJax для химии
editing-mathjax-inline = MathJax в строке
editing-media = Медиафайлы
editing-paste = Вставить
editing-record-audio-f5 = Запись аудио (F5)
editing-remove-formatting-ctrlandr = Удалить форматирование (Ctrl+R)
editing-set-foreground-colour-f7 = Повторить последний использованный цвет шрифта (F7)
editing-show-duplicates = Показать повторы
editing-subscript-ctrland = Нижний индекс (Ctrl+=)
editing-superscript-ctrlandand = Верхний индекс (Ctrl++)
editing-tags = Метки
editing-to-make-a-cloze-deletion-on = Чтобы добавить заполнение пропусков к существующей записи, вы прежде должны изменить её тип на «Задание с пропусками», выбрав 'Записи>Поменять тип записи'.
editing-underline-text-ctrlandu = Подчеркнуть текст (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Предупреждение. Заполнение пропусков не будет работать, пока вы не смените тип на «Пропуски» выше.
