editing-actual-size = Переключить размер
editing-add-media = Добавить медиафайл
editing-align-left = Выровнять по левому краю
editing-align-right = Выровнять по правому краю
editing-an-error-occurred-while-opening = При открытии { $val } возникла ошибка
editing-attach-picturesaudiovideo = Прикрепить изображение/аудиофайл/видеофайл
editing-bold-text = Жирный шрифт
editing-cards = Карточки
editing-center = Центр
editing-change-color = Изменить цвет
editing-cloze-deletion = Заполнить пропуск
editing-couldnt-record-audio-have-you-installed = Не получается записать звук. У вас установлен "lame"?
editing-customize-card-templates = Настроить шаблоны карточек
editing-customize-fields = Настроить поля
editing-cut = Вырезать
editing-edit-current = Редактировать
editing-edit-html = Править HTML
editing-fields = Поля
editing-float-left = Слева
editing-float-right = Справа
editing-float-none = Выключить обтекание
editing-html-editor = Редактор HTML
editing-indent = Увеличить отступ
editing-italic-text = Курсив
editing-jump-to-tags-with-ctrlandshiftandt = Перейти к меткам (Ctrl+Shift+T)
editing-justify = Выровнять
editing-latex = LaTeX
editing-latex-equation = Формула LaTeX
editing-latex-math-env = Окружение LaTeX
editing-mathjax-block = MathJax с выключкой
editing-mathjax-chemistry = MathJax для химии
editing-mathjax-inline = MathJax в строке
editing-media = Медиафайлы
editing-ordered-list = Упорядоченный список
editing-outdent = Сократить отступ
editing-paste = Вставить
editing-record-audio = Записать аудиофайл
editing-remove-formatting = Удалить форматирование
editing-set-text-color = Выбрать цвет текста
editing-set-text-highlight-color = Выбрать цвет выделения
editing-show-duplicates = Показать повторы
editing-subscript = Подстрочный знак
editing-superscript = Надстрочный знак
editing-tags = Метки
editing-to-make-a-cloze-deletion-on = Чтобы добавить заполнение пропусков к существующей записи, необходимо сначала изменить её тип на «Задание с пропусками», выбрав Записи>Поменять тип записи.
editing-toggle-sticky = Сохранять значение
editing-underline-text = Подчеркивание
editing-unordered-list = Неупорядоченный список
editing-warning-cloze-deletions-will-not-work = Внимание! Заполнение пропусков не будет работать, пока вы не измените тип карточки на «Пропуски».

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-bold-text-ctrlandb = Жирный шрифт (Ctrl+B)
editing-italic-text-ctrlandi = Курсив (Ctrl+I)
editing-underline-text-ctrlandu = Подчеркнуть текст (Ctrl+U)
editing-subscript-ctrland = Нижний индекс (Ctrl+=)
editing-superscript-ctrlandand = Верхний индекс (Ctrl++)
editing-remove-formatting-ctrlandr = Удалить форматирование (Ctrl+R)
editing-record-audio-f5 = Запись аудио (F5)
editing-attach-picturesaudiovideo-f3 = Прикрепить изображение, аудио, видео (F3)
editing-cloze-deletion-ctrlandshiftandc = Задание с пропусками (Ctrl+Shift+C)
editing-change-colour-f8 = Изменить цвет (F8)
editing-set-foreground-colour-f7 = Повторить последний использованный цвет шрифта (F7)
editing-customize-card-templates-ctrlandl = Настроить шаблоны карточек (Ctrl+L)
editing-set-foreground-color = Установить цвет переднего плана
