fields-add-field = Добавить поле
fields-delete-field-from = Удалить поле из { $val }?
fields-editing-font = Шрифт в редакторе
fields-field = Поле:
fields-field-name = Имя поля:
fields-fields-for = Поля для { $val }
fields-font = Шрифт:
fields-new-position-1 = Новая позиция (1…{ $val }):
fields-notes-require-at-least-one-field = В записи должно быть хотя бы одно поле.
fields-remember-last-input-when-adding = Помнить последние введённые данные
fields-reverse-text-direction-rtl = Направление текста справа-налево
fields-size = Размер:
fields-sort-by-this-field-in-the = Сортировать список по этому полю
fields-that-field-name-is-already-used = Заданное имя уже используется
