notetypes-front-field = Лицевая сторона
notetypes-back-field = Обратная сторона
notetypes-add-reverse-field = Добавить обратную
notetypes-text-field = Текст
notetypes-basic-name = Основная
notetypes-basic-reversed-name = Основная (с обратной карточкой)
notetypes-basic-optional-reversed-name = Основная (обратная по выбору)
notetypes-cloze-name = Задание с пропусками
notetypes-basic-type-answer-name = Основная (с вводом ответа)
notetypes-card-2-name = Карточка 2
notetypes-card-1-name = Карточка 1
