preferences-automatically-sync-on-profile-openclose = Автоматически синхронизировать при смене профиля
preferences-backups = Резервные копии
preferences-backups2 = резервных копий
preferences-backupsanki-will-create-a-backup-of = <b>Резервные копии</b><br>Anki делает резервную копию коллекции при закрытии и синхронизации.
preferences-basic = Основная
preferences-change-deck-depending-on-note-type = Выбрать колоду по типу записи
preferences-changes-will-take-effect-when-you = Изменения вступят в силу при перезапуске Anki.
preferences-hours-past-midnight = ч. после полуночи
preferences-interface-language = Язык интерфейса:
preferences-interrupt-current-audio-when-answering = Прерывать аудио при ответе
preferences-keep = Хранить
preferences-learn-ahead-limit = Лимит опережения
preferences-mins = мин.
preferences-network = Сеть
preferences-next-day-starts-at = Начало следующего дня
preferences-night-mode = Ночной режим
preferences-note-media-is-not-backed-up = Примечание: медиафайлы не резервируются. Делайте резервные копии своей папки Anki.
preferences-on-next-sync-force-changes-in = При следующей синхронизации перезаписать в одном направлении
preferences-paste-clipboard-images-as-png = Вставлять изображения из буфера как PNG
preferences-paste-without-shift-key-strips-formatting = Вставка без клавиши Shift убирает форматирование
preferences-periodically-sync-media = Периодически синхронизировать медиаданные
preferences-please-restart-anki-to-complete-language = Перезагрузите Anki, чтобы переключить язык.
preferences-preferences = Настройки
preferences-scheduling = Расписание
preferences-show-learning-cards-with-larger-steps = Показывать изучаемые карточки с большими шагами до повторяемых
preferences-show-next-review-time-above-answer = Показывать время повторения над кнопками ответа
preferences-show-play-buttons-on-cards-with = Показывать кнопки управления на карточках с аудио
preferences-show-remaining-card-count-during-review = Показывать число оставшихся карточек
preferences-some-settings-will-take-effect-after = Некоторые параметры вступят в силу только после перезапуска Anki.
preferences-synchronisation = <b>Сихронизация</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронизация</b><br> Выключена. Чтобы включить её, щёлкните кнопку в главном окне.
preferences-synchronize-audio-and-images-too = Синхронизировать аудио и изображения
preferences-timebox-time-limit = Лимит ограничения времени
preferences-user-interface-size = Размер интерфейса
preferences-when-adding-default-to-current-deck = Добавлять в текущую колоду
preferences-you-can-restore-backups-via-fileswitch = Вы можете восстановить резервную копию через «Файл» — «Сменить профиль».
preferences-legacy-timezone-handling = Устаревшая обработка часовых поясов (с ошибками, но требуется для AnkiDroid <= 2.14)
preferences-default-search-text = Текст поиска по умолчанию
preferences-default-search-text-example = например, 'deck:current ' для выбора текущей колоды
preferences-theme-label = Тема: { $theme }
preferences-theme-follow-system = Как в системе
preferences-theme-light = Светлая
preferences-theme-dark = Тёмная
preferences-v3-scheduler = Планировщик V3
preferences-ignore-accents-in-search = Игнорировать диакритические знаки при поиске (медленнее)
preferences-backup-explanation =
    Anki периодически создает резервную копию ваших коллекций при выходе. После двух дней,
    Anki начнет удалять некоторые из них для освобождения дискового пространства.
preferences-daily-backups = Оставлять резервных копий ежедневно:
preferences-weekly-backups = Оставлять резервных копий еженедельно:
preferences-monthly-backups = Оставлять резервных копий ежемесячно:
preferences-minutes-between-backups = Интервал между автоматическими копиями:
