preferences-automatically-sync-on-profile-openclose = Автоматически синхронизировать при открытии и закрытии профиля
preferences-backups = Резервные копии
preferences-backups2 = резервных копий
preferences-backupsanki-will-create-a-backup-of = <b>Резервные копии</b><br>Anki делает резервную копию коллекции при закрытии и синхронизации.
preferences-basic = Основная
preferences-change-deck-depending-on-note-type = Изменить колоду в зависимости от типа записи
preferences-changes-will-take-effect-when-you = Изменения вступят в силу при перезапуске Anki.
preferences-hours-past-midnight = ч. после полуночи
preferences-interface-language = Язык интерфейса:
preferences-interrupt-current-audio-when-answering = Прерывать аудио при ответе
preferences-keep = Хранить
preferences-learn-ahead-limit = Лимит опережения
preferences-mins = мин.
preferences-network = Сеть
preferences-next-day-starts-at = Начало следующего дня
preferences-night-mode = Ночной режим
preferences-note-media-is-not-backed-up = Примечание: медиафайлы не резервируются. Делайте резервные копии своей папки Anki.
preferences-on-next-sync-force-changes-in = При следующей синхронизации перезаписать в одном направлении
preferences-paste-clipboard-images-as-png = Вставлять изображения из буфера как PNG
preferences-paste-without-shift-key-strips-formatting = Вставка без клавиши Shift убирает форматирование
preferences-periodically-sync-media = Периодические синхронизировать медиаданные
preferences-please-restart-anki-to-complete-language = Перезагрузите Anki для завершения смены языка.
preferences-preferences = Настройки
preferences-scheduling = Расписание
preferences-show-learning-cards-with-larger-steps = Показывать изучаемые карточки с большими интервалами до повторяемых
preferences-show-next-review-time-above-answer = Показывать время следующего повторения над кнопками ответа
preferences-show-play-buttons-on-cards-with = Показывать кнопки управления на карточках с аудио
preferences-show-remaining-card-count-during-review = Показывать при просмотре число оставшихся карточек
preferences-some-settings-will-take-effect-after = Некоторые параметры вступят в силу только после перезапуска Anki.
preferences-synchronisation = <b>Сихронизация</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Синхронизация</b><br> Выключена. Чтобы включить её, щёлкните кнопку в главном окне.
preferences-synchronize-audio-and-images-too = Синхронизировать аудио и изображения
preferences-this-will-reset-any-cards-in = Будут сброшены все изучаемые карточки, очищены фильтрованные колоды и изменена версия планировщика. Продолжить?
preferences-timebox-time-limit = Лимит ограничения времени
preferences-user-interface-size = Размер интерфейса
preferences-when-adding-default-to-current-deck = По умолчанию помещать создаваемое в текущую колоду
preferences-you-can-restore-backups-via-fileswitch = Вы можете восстановить резервную копию через «Файл» — «Сменить профиль».
preferences-legacy-timezone-handling = Устаревшая обработка часовых поясов (с ошибками, но требуется для AnkiDroid <= 2.14)
preferences-default-search-text = Текст поиска по умолчанию
preferences-default-search-text-example = например, 'колода:текущая '
