actions-add = Erantsi
actions-cancel = Utzi
actions-choose = Aukeratu
actions-close = Irten
actions-copy = Kopiatu
actions-create-copy = Sortu kopia
actions-custom-study = Ikasketa itxuratuta
actions-decks = Karta-sortak
actions-delete = Ezabatu
actions-export = Esportatu
actions-filter = Iragazia
actions-help = Laguntza
actions-import = Inportatu
actions-manage = Kudeatu...
actions-name = Izena:
actions-new = Berria
actions-new-name = Izen berria:
actions-options = Aukerak
actions-options-for = { $val }-(r)en aukerak
actions-preview = Aurrebista
actions-rebuild = Berreraiki
actions-rename = Berrizendatu
actions-rename-deck = Sorta berrizendatu
actions-rename-tag = Berrizendatu etiketa
actions-remove-tag = Kendu etiketa
actions-replay-audio = Grabaketa berriro jarri
actions-reposition = Berreposizionatu
actions-save = Gorde
actions-search = Bilatu
actions-select = Hautatu
actions-shortcut-key = Tekla bizkor: { $val }
actions-suspend-card = Karta eten
actions-answer-card = Erantzun txartela
actions-add-deck = Gehitu sorta
actions-add-note = Gehitu oharra
actions-update-tag = Eguneratu etiketa
actions-update-note = Eguneratu oharra
actions-update-card = Eguneratu txartela
actions-update-deck = Eguneratu sorta
actions-forget-card = Ahaztu txartela
actions-build-filtered-deck = Sortu sorta
actions-card-info = Txartelaren informazioa
actions-previous-card-info = Aurreko txartelaren informazioa

## Flags

actions-flag-red = Gorria
actions-flag-orange = Laranja
actions-flag-green = Berdea
actions-flag-blue = Urdina
actions-flag-pink = Arrosa
actions-flag-turquoise = Turkesa
actions-flag-purple = Morea
