browsing-add-tags = Erantsi etiketak
browsing-add-tags2 = Etiketak erantsi...
browsing-added-today = Gaur erantsita
browsing-again-today = Gaur berriro
browsing-all-fields = Eremu guztiak
browsing-answer = Erantzuna
browsing-any-cards-mapped-to-nothing-will = Ezertara mapatu gabeko kartak ezabatu egingo dira. Ohar bati ez bazaizkio kartak gelditzen, galdu egingo da. Ziur zaude jarraitu nahi duzula?
browsing-browser-appearance = Nabigatzailearen Itxura
browsing-browser-options = Arakatzailearen aukerak
browsing-card = Karta
browsing-card-list = Karta zerrenda
browsing-card-state = Karta egoera
browsing-cards-cant-be-manually-moved-into = Kartak sorta iragazitako batera ezin mugi daitezke  eskuz
browsing-change-deck = Aldatu karta-sorta
browsing-change-note-type = Aldatu ohar-mota
browsing-change-note-type2 = Aldatu ohar-mota...
browsing-change-to = Aldatu { $val } :
browsing-created = Sortuta
browsing-current-deck = Uneko karta-sorta
browsing-current-note-type = Uneko ohar-mota
browsing-delete-notes = Ezabatu oharrak
browsing-delete-tags = Ezabatu etiketak
browsing-duplicate = bikoiztua
browsing-ease = Erraztasun
browsing-end = Bukatu
browsing-enter-tags-to-add = Etiketak sartu eransteko
browsing-enter-tags-to-delete = Sartu ezabatzeko etiketak
browsing-filter = Iragazki...
browsing-filtered = (hiragazita)
browsing-find = <b>Bilatu</b>:
browsing-find-and-replace = Bilatu eta ordeztu
browsing-find-duplicates = Bilatu bikoiztuak
browsing-first-card = Lehengo karta
browsing-font = <b>Letra-tipoa</b>:
browsing-font-size = <b>Letra-tipoaren neurria</b>:
browsing-found-as-across-bs = %(b)s -en zehar %(a)s aurkituta
browsing-home = Direktorio Pertsonala
browsing-ignore-case = Ezikusi maius./minus.
browsing-in = <b>Hemen</b>:
browsing-interval = Denbora-tartea
browsing-last-card = Karta azkena
browsing-learning = (ikasten)
browsing-line-size = <b>Lerroaren neurria</b>:
browsing-manage-note-types = ohar motakoak kudeatu...
browsing-move-cards = Txartelak lekuz aldatu
browsing-move-cards-to-deck = sortara kartak mugitu :
browsing-new = (berria)
browsing-new-note-type = Ohar mota berria:
browsing-note = Oharra
browsing-notes-tagged = ohar etiketatuak
browsing-nothing = Ezer ez
browsing-only-new-cards-can-be-repositioned = bakarrik karta berriak berriz koka daitezke
browsing-override-back-template = atzealdeko eredu ordeztu
browsing-override-font = letra tipoa ordeztu
browsing-override-front-template = aurkiko eredua ordeztu
browsing-place-at-end-of-new-card = karta berri ilarako bukaeran ipini
browsing-place-in-review-queue-with-interval = Errepasatzea itxaroten jarri, tarte horrekin :
browsing-please-select-cards-from-only-one = Mesedez, mota bakar bateko kartak aukera itzazu
browsing-preview-selected-card = Karta aukeratutak ({ $val }) aurreikusi
browsing-question = Galdera
browsing-queue-bottom = Ilarako bukaera : { $val }
browsing-queue-top = Ilarako hasiera : { $val }
browsing-randomize-order = ausazko hurrenkera
browsing-replace-with = <b>Ordezkatu honekin</b>:
browsing-reposition = Berreposizionatu
browsing-reposition-new-cards = Karta berriak berreposizionatu
browsing-reschedule = Berreplanifikatu
browsing-search-within-formatting-slow = formatuaz bilatzen (astitsu)
browsing-shift-position-of-existing-cards = existitzen diren karten kokapena aldatu
browsing-sort-field = Eremuaren arabera sailkatu
browsing-sorting-on-this-column-is-not = Zutabe honetan ordena ez dezake. Mesedez beste bat aukera.
browsing-start-position = Abiapuntu
browsing-step = Urratsa:
browsing-studied-today = Gaur ikasitakoak
browsing-suspended = Etenda
browsing-tag-duplicates = Bizkoitutak etiketatu
browsing-target-field = Jomuga izanda eremua:
browsing-today = Gaur
browsing-treat-input-as-regular-expression = Sarrera adierazpen erregular batentzat hartu
browsing-type-here-to-search = <idatzi hemen bilatzeko; sakatu sartu uneko bilduma erakusteko>
browsing-whole-collection = Bilduma osoa
browsing-you-must-have-at-least-one = Gutxienez zutabe bat izan behar duzu.
