card-stats-added = Erantsita
card-stats-first-review = Lehen berrikuspena
card-stats-latest-review = Azken berrikuspena
card-stats-interval = Denbora-tartea
card-stats-ease = Erraztasun
card-stats-review-count = Berrikuspenak
card-stats-lapse-count = Hutsegiteak
card-stats-average-time = Batez besteko denbora
card-stats-total-time = Denbora guztira
card-stats-new-card-position = Kokapena
card-stats-card-template = Karta mota
card-stats-note-type = Ohar-mota
card-stats-deck-name = Sorta
card-stats-note-id = ohar identifikadorea
card-stats-card-id = Kartaren ID
card-stats-review-log-rating = ebaluazioa
card-stats-review-log-type = Mota
card-stats-review-log-date = Data
card-stats-review-log-time-taken = Denbora
card-stats-review-log-type-learn = Ikasi
card-stats-review-log-type-review = Berrikusi
card-stats-review-log-type-relearn = Berrikasi
card-stats-review-log-type-filtered = Iragazia
card-stats-review-log-type-rescheduled = Atzeratuta
