change-notetype-current = Unekoa
change-notetype-new = Berria
change-notetype-nothing = (Ezer ez)
change-notetype-collapse = Tolestu
change-notetype-expand = Zabaldu
change-notetype-will-discard-content = Eremu hauetako edukia baztertuko da:
change-notetype-will-discard-cards = Txartel hauek kenduko dira:
change-notetype-fields = Eremuak
change-notetype-templates = Txantiloiak
