editing-add-media = Erantsi euskarria
editing-an-error-occurred-while-opening = errore bat gertatu zen { $val } ikeritzean
editing-attach-picturesaudiovideo-f3 = Erantsi argazkiak/audio/bideo (F3)
editing-bold-text-ctrlandb = Letra lodi (Ktrl+B)
editing-cards = Kartak
editing-change-colour-f8 = Kolore aldatu (F8)
editing-cut = Ebaki
editing-edit-current = Editatu azkena
editing-edit-html = HTML editatu
editing-fields = Eremuak
editing-html-editor = HTML editorea
editing-italic-text-ctrlandi = Etzan letra (Ktrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Krtl+Shift+T etiketetara joateko
editing-latex-equation = LaTeX ekuazioa
editing-latex-math-env = Latex Math  ingurunea
editing-media = Euskarria
editing-paste = Itsatsi
editing-record-audio-f5 = Audio grabatu (F5)
editing-remove-formatting-ctrlandr = Formatu ezabatu (Ktrl+R)
editing-show-duplicates = bizkoitutak erakutsi
editing-subscript-ctrland = Azpiindize (Ktrl+=)
editing-superscript-ctrlandand = Goi-idize (Ktrl++)
editing-tags = Etiketak
editing-to-make-a-cloze-deletion-on = Hustuneak betetzea existitzen den ohar batean egiteko, lehenik bere tipo aldatu behar duzu, Editatu>Aldatu ohar-mota-en bidez.
editing-underline-text-ctrlandu = Azpimarratu (Ktrl+U)
editing-warning-cloze-deletions-will-not-work = Kontuz, zuloekin testua ez baldin baduzu bihurrarazten karta mota,  zuloekin testua ez da ongi funtzionatuko
