exporting-all-decks = Bilduma guztiak
exporting-anki-20-deck = Anki 2.0 Bilduma
exporting-anki-deck-package = Anki Bilduma paketea
exporting-cards-in-plain-text = Kartak in testu xumea
exporting-collection = bilduma
exporting-couldnt-save-file = Ezin izan da fitxategia gorde: { $val }
exporting-export = Esportatu...
exporting-export-format = <b>Esportatzeko formatua</b>:
exporting-include = <b>Erantsi</b>:
exporting-include-media = Sartu euskarria
exporting-include-scheduling-information = Sartu antolaketako informazioa
exporting-include-tags = Sartu etiketak
exporting-notes-in-plain-text = Oharrak testu arruntean
