notetypes-front-field = Voorkant
notetypes-back-field = Achterkant
notetypes-add-reverse-field = Omgekeerde toevoegen
notetypes-text-field = Tekst
notetypes-basic-name = Basis
notetypes-basic-reversed-name = Basis (en omgekeerde kaart)
notetypes-basic-optional-reversed-name = Basis (omgekeerde kaart optioneel)
notetypes-basic-type-answer-name = Basisch (typ het antwoord in)
notetypes-card-2-name = Kaart 2
notetypes-card-1-name = Kaart 1
