adding-add-shortcut-ctrlandenter = Pievienot (īsceļš: ctrl+enter)
adding-added = Pievienots
adding-discard-current-input = Vai dzēst pašreizējo ievadi?
adding-keep-editing = Turpināt rediģēšanu
adding-edit = Rediģēt „{ $val }”
adding-history = Vēsture
adding-note-deleted = (Piezīme dzēsta)
adding-shortcut = Īsceļš: { $val }
adding-the-first-field-is-empty = Pirmais lauks ir tukšs.
adding-you-have-a-cloze-deletion-note = Jums ir cloze piezīmes veids, bet neesat veicis nekādu cloze dzēšanu. Vai turpināt?
adding-cloze-outside-cloze-notetype = Cloze dzēšanu var izmantot tikai cloze piezīmju veidiem.
adding-cloze-outside-cloze-field = Cloze dzēšanu var izmantot tikai tajos laukos, kuros tiek izmantots „cloze:” filtrs. Parasti tas ir pirmais lauks.
