adding-add-shortcut-ctrlandenter = Pievienuot (īsceļš: ctrl+enter)
adding-added = Pievienuots
adding-close-and-lose-current-input = Aizvērt un zaudēt pašreizējo ievadi?
adding-edit = Rediģēt «{ $val }»
adding-history = Vēsture
adding-note-deleted = (Piezīme dzēsta)
adding-shortcut = Īsceļš: { $val }
adding-the-first-field-is-empty = Pirmais lauks ir tukšs.
adding-you-have-a-cloze-deletion-note = Jums ir cloze piezīmes tips, bet neesat veicis nekādu cloze dzēšanu. Vai turpināt?
adding-cloze-outside-cloze-notetype = Cloze dzēšanu var izmantot tikai cloze piezīmju tipiem.
adding-cloze-outside-cloze-field = Cloze dzēšanu var izmantot tikai tajos laukos, kuros tiek izmantots «cloze:» filtrs. Parasti tas ir pirmais lauks.
