browsing-add-notes = Pievienuot piezīmes...
browsing-add-tags2 = Pievienuot birkas...
browsing-add-to-selected-notes = Pievienuot atlasītajām piezīmēm
browsing-remove-from-selected-notes = Nuoņemt nuo atlasītajām piezīmēm
browsing-addon = Papildinājums
browsing-all-fields = Visi lauciņi
browsing-answer = Atbilde
browsing-any-flag = Jebkurš karuogs
browsing-average-ease = Vidējais vieglums
browsing-average-interval = Vidējais intervāls
browsing-browser-appearance = Pārlūka izskats
browsing-browser-options = Izlūka opcijas
browsing-buried = Aprakts
browsing-card = Karte
browsing-cards = Kartes
browsing-card-list = Karšu saraksts
browsing-cards-cant-be-manually-moved-into = Kartes nevar manuāli tikt pārvietuotas filtrētā kavā.
browsing-cards-deleted =
    { $count ->
        [zero] { $count } kartes dzēstas.
        [one] { $count } karte dzēsta.
       *[other] { $count } kartes dzēstas.
    }
browsing-change-deck = Mainīt kavu
browsing-change-deck2 = Mainīt kavu...
browsing-change-note-type = Mainīt piezīmes veidu
browsing-change-note-type2 = Mainīt piezīmes veidu...
browsing-change-notetype = Mainīt piezīmes veidu
browsing-clear-unused-tags = Dzēst neizmantuotas birkas
browsing-confirm-saved-search-overwrite = Saglabātā meklēšana ar nosaukumu «{ $name }» jau pastāv. Vai vēlaties to pārrakstīt?
browsing-created = Izveiduots
browsing-current-deck = Pašreizējā kava
browsing-current-note-type = Pašreizējais piezīmes veids:
browsing-delete-notes = Dzēstās piezīmes
browsing-duplicate = dublēt
browsing-ease = Vieglums
browsing-enter-tags-to-add = Ievietuot pievienuojamās birkas:
browsing-enter-tags-to-delete = Ievietuojiet dzēšamās birkas:
browsing-filtered = (filtrēts)
browsing-find = <b>Meklēt</b>:
browsing-find-and-replace = Meklēt un aizstāt
browsing-find-duplicates = Atrast duplikātus
browsing-first-card = Pirmā karte
browsing-flag = Karuogs
browsing-font = <b>Fonts</b>:
browsing-font-size = <b>Fonta izmērs</b>:
browsing-found-as-across-bs = Atrasts { $part } pāri { $whole }.
browsing-ignore-case = Ignorēt gadījumu
browsing-in = <b>Iekšā</b>:
browsing-interval = Intervāls
browsing-last-card = Pēdējā karte
browsing-learning = (mācuos)
browsing-line-size = <b>Līnijas izmērs</b>:
browsing-manage-note-types = Pārvaldīt piezīmju veidus
browsing-move-cards = Pārvietuot kartes
browsing-move-cards-to-deck = Pārvietuot uz citu kavu:
browsing-new = (jauns)
browsing-new-note-type = Atjaunuot ar pašreizējuo meklēšanu
browsing-no-flag = Nav karuoga
browsing-no-selection = Nav ne karuoga ne piezīmes atlasītas.
browsing-note = Piezīme
browsing-notes = Piezīmes
browsing-optional-filter = Papildus filtri:
browsing-override-back-template = Pārraktīt aizmugures veidni:
browsing-override-font = Pārrakstīt fontu:
browsing-override-front-template = Pārrakstīt prekšas veidni:
browsing-please-give-your-filter-a-name = Nuosauc savu filtru:
browsing-preview-selected-card = Priekšskatīt atlasītuo karti ({ $val })
browsing-question = Jautājums
browsing-queue-bottom = Rindas apakša: { $val }
browsing-queue-top = Rindas augša: { $val }
browsing-randomize-order = Secību pēc nejaušības
browsing-remove-tags = Nuoņemt birkas...
browsing-replace-with = <b>Aizvietuot ar</b>:
browsing-reposition = Pārvietuot...
browsing-reposition-new-cards = Pārvietuot jaunās kartes
browsing-reschedule = Pārplānuot
browsing-search-bar-hint = Meklēt kartes/piezīmes (ierakstīet tekstu, tad spiediet uz Enter)
browsing-search-in = Meklējiet iekš:
browsing-search-within-formatting-slow = Meklēšana formatēšanas ietvaros (lēni)
browsing-selected-notes-only = Tikai atlasītās piezīmes
browsing-shift-position-of-existing-cards = Pārvietuot jau pastāvuošuo karšu pozīciju
browsing-sidebar = Sānjuosla
browsing-sidebar-filter = Sānjuostas filtrs
browsing-sort-field = Šķiruot lauciņu
browsing-sorting-on-this-column-is-not = Šīs kolonnas šķirošana netiek atbalstīta. Lūdzu, izvēlieties citu.
browsing-start-position = Sākuma pozīcija:
browsing-step = Suolis:
browsing-suspended = Apturētie(ās)
browsing-tag-duplicates = Birku duplikāti
browsing-tag-rename-warning-empty = Nevar pārdēvēt birku kurai nav piezīmju.
browsing-target-field = Mērķa lauciņš:
browsing-toggle-bury = Sākt aprakšanu
browsing-toggle-showing-cards-notes = Sākt kartes/piezīmes
browsing-toggle-mark = Sākt atzīmēšanu
browsing-toggle-suspend = Sākt apturēšanu
browsing-treat-input-as-regular-expression = Uzskatīt ievadi kā parastu izsteksmi
browsing-update-saved-search = Atjaunuot ar pašreizējuo meklēšanu

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

