card-stats-added = Pievienots
card-stats-first-review = Pirmais pārskats
card-stats-latest-review = Pēdējais pārskats
card-stats-interval = Intervāls
card-stats-ease = Vienkāršība
card-stats-review-count = Pārskati
card-stats-lapse-count = Apļl
card-stats-average-time = Vidējais laiks
card-stats-total-time = Kopējais laiks
card-stats-new-card-position = Pozīcija
card-stats-card-template = Kārts veids
card-stats-note-type = Piezīmes veids
card-stats-deck-name = Kava
card-stats-preset = Iepriekš iestatītais
card-stats-note-id = Piezīmes identifikators
card-stats-card-id = Kārts identifikators
card-stats-review-log-rating = Vērtējums
card-stats-review-log-type = Veids
card-stats-review-log-date = Datums
card-stats-review-log-time-taken = Laiks
card-stats-review-log-type-learn = Mācīties
card-stats-review-log-type-review = Pārskatīt
card-stats-review-log-type-relearn = Mācīties no jauna
card-stats-review-log-type-filtered = Filtrētie
card-stats-review-log-type-manual = Manuāli
card-stats-review-log-type-rescheduled = Pārplānotie
card-stats-review-log-elapsed-time = Pagājušais laiks
card-stats-no-card = (Nav kāršu kuras parādīt)
card-stats-custom-data = Pielāgotie dati
card-stats-fsrs-stability = Stabilitāte
card-stats-fsrs-difficulty = Grūtības pakāpe
card-stats-fsrs-retrievability = Atgūstamība
card-stats-fsrs-forgetting-curve-title = Aizmiršanas līkme
card-stats-fsrs-forgetting-curve-first-week = Pirmā nedēļa
card-stats-fsrs-forgetting-curve-first-month = Pirmais mēnesis
card-stats-fsrs-forgetting-curve-first-year = Pirmais gads
card-stats-fsrs-forgetting-curve-all-time = Viss laiks

## Window Titles

card-stats-current-card = Pašreizējā kārts ({ $context })
card-stats-previous-card = Iepriekšējā kārts ({ $context })
