studying-again = Atkal
studying-continue = Turpināt
studying-easy = Viegli
studying-edit = Rediģēt
studying-finish = Pabeigt
studying-good = Labi
studying-hard = Grūti
studying-more = Vairāk
studying-question-time-elapsed = Jautājuma laiks beidzies
studying-answer-time-elapsed = Atbildes laiks beidzies
