actions-add = Πρόσθηκη
actions-cancel = Ακύρωση
actions-choose = Επιλογή
actions-close = Κλείσιμο
actions-copy = Αντιγραφή
actions-custom-study = Προσαρμογή μελέτης
actions-decks = Τράπουλες
actions-delete = Διαγραφή
actions-export = Εξαγωγή
actions-filter = Φιλτράρισμα
actions-help = Βοήθεια
actions-import = Εισαγωγή
actions-name = Όνομα:
actions-new = Νέο
actions-new-name = Νέο όνομα:
actions-options = Επιλογές
actions-options-for = Επιλογές για { $val }
actions-search = Αναζήτηση
actions-suspend-card = Αναστολή κάρτας
