adding-add-shortcut-ctrlandenter = Προσθήκη (συντόμευση: ctrl+enter)
adding-added = Προστέθηκε
adding-close-and-lose-current-input = Κλείσιμο με απώλεια αλλαγών;
adding-edit = Επεξεργασία "{ $val }"
adding-history = Ιστορικό
adding-note-deleted = (Η σημείωση διαγράφηκε)
adding-shortcut = Συντόμευση: { $val }
adding-the-first-field-is-empty = Το πρώτο πεδίο είναι κενό.
adding-you-have-a-cloze-deletion-note = Ο τύπος σημείωσης είναι συμπλήρωση κενού, αλλά δεν έχετε βάλει κενά. Συνέχεια;
