card-stats-added = Προστέθηκε
card-stats-latest-review = Τελευταία Αναθεώρηση
card-stats-interval = Διάστημα ανανέωσης
card-stats-ease = Ευκολία
card-stats-review-count = Επιθεωρήσεις
card-stats-average-time = Μέσος χρόνος
card-stats-total-time = Συνολικός χρόνος
card-stats-new-card-position = Τοποθεσία
card-stats-card-template = Τύπος κάρτας
card-stats-note-type = Τύπος σημείωσης
card-stats-deck-name = Τράπουλα
