change-notetype-current = Τρέχων
change-notetype-new = Νέος
change-notetype-nothing = (Τίποτα)
change-notetype-collapse = Σύμπτυξη
change-notetype-expand = Ανάπτυξη
change-notetype-will-discard-content = Το  περιεχόμενο των παρακάτω πεδίων θα απορριφθεί:
change-notetype-will-discard-cards = Θα αφαιρέσει τις ακόλουθες κάρτες:
change-notetype-fields = Πεδία
change-notetype-templates = Πρότυπα
