database-check-corrupt = Η συλλογή είναι κατεστραμμένη. Παρακαλούμε δείτε το manual.
database-check-rebuilt = Η βάση δεδομένων ξαναδημιουργήθηκε και βελτιώθηκε.

## Progress info

database-check-checking-integrity = Έλεγχος συλλογής...
database-check-checking-cards = Έλεγχος καρτών...
database-check-checking-notes = Έλεγχος σημειώσεων...
database-check-checking-history = Έλεγχος ιστορικού...
database-check-title = Έλεγχος βάσης δεδομένων
