decks-add-new-deck-ctrlandn = Προσθήκη νέας τράπουλας (Ctrl+N)
decks-build = Χτίσιμο
decks-cards-selected-by = κάρτες επελεγμένες από
decks-create-deck = Δημιουργία τράπουλας
decks_create_even_if_empty = Δημιουργία/ενημέρωση αυτής της τράπουλας ακόμα και αν είναι κενή
decks-deck = Τράπουλα
decks-decreasing-intervals = Φθίνοντα διαστήματα
decks-delete-deck = Διαγραφή Τράπουλας
decks-enable-second-filter = Ενεργοποίηση δεύτερου φίλτρου
decks-filter = Φιλτράρισμα:
decks-filter-2 = Φίλτρο 2
decks-import-file = Εισαγωγή Αρχείου
decks-increasing-intervals = Αυξανόμενα διαστήματα
decks-minutes = λεπτά
decks-new-deck-name = Νέο όνομα τράπουλας
decks-random = Τυχαία
decks-study = Μελέτη
decks-study-deck = Μελέτη τράπουλας
decks-learn-header = Μάθετε
# The count of cards waiting to be reviewed
decks-review-header = Λόγω
