decks-add-new-deck-ctrlandn = Προσθήκη νέας τράπουλας (Ctrl+N)
decks-build = Χτίσιμο
decks-cards-selected-by = κάρτες επελεγμένες κατά
decks-create-deck = Δημιουργία τράπουλας
decks_create_even_if_empty = Δημιουργία/ενημέρωση αυτής της τράπουλας ακόμα και αν είναι κενή
decks-custom-steps-in-minutes = Εξατομικευμένα βήματα (σε λεπτά)
decks-deck = Τράπουλα
decks-decreasing-intervals = Φθίνοντα διαστήματα
decks-delete-deck = Διαγραφή Τράπουλας
decks-enable-second-filter = Ενεργοποίηση δεύτερου φίλτρου
decks-filter = Φιλτράρισμα:
decks-filter-2 = Φίλτρο 2
decks-get-shared = Λήψη κοινόχρηστων
decks-import-file = Εισαγωγή Αρχείου
decks-increasing-intervals = Αύξοντα διαστήματα
decks-limit-to = Περιορισμός σε
decks-minutes = λεπτά
decks-most-lapses = Περισσότερα ολισθήματα
decks-new-deck-name = Νέο όνομα τράπουλας
decks-no-deck = [καμία τράπουλα]
decks-oldest-seen-first = Παλαιότερες εμφανίζονται πρώτα
decks-please-select-something = Παρακαλούμε επιλέξτε κάτι.
decks-random = Τυχαία
decks-reschedule-cards-based-on-my-answers = Επαναπρογραμματισμός καρτών βάσει των απαντήσεων μου σε αυτή την τράπουλα
decks-study = Μελέτη
decks-study-deck = Μελέτη τράπουλας
decks-filtered-deck-search-empty = Καμία κάρτα δεν ταιριάζει στην αναζήτησή σας. Μερικές κάρτες μπορεί να αποκλείστηκαν επειδή είναι σε μια φιλτραρισμένη τράπουλα ή σε αναστολή.
decks-unmovable-cards = Εμφάνιση εξαιρούμενων καρτών
decks-learn-header = Μάθετε
# The count of cards waiting to be reviewed
decks-review-header = Προς επανάληψη
