editing-actual-size = Πραγματικό μέγεθος
editing-add-media = Προσθήκη πολυμέσων
editing-align-left = Στοίχιση αριστερά
editing-align-right = Στοίχιση δεξιά
editing-an-error-occurred-while-opening = Προέκυψε σφάλμα κατά το άνοιγμα του/της  { $val }
editing-attach-picturesaudiovideo = Επισύναψη εικόνων/ήχου/βίντεο
editing-cards = Κάρτες
editing-center = Κέντρο
editing-change-color = Αλλαγή χρώματος
editing-cloze-deletion = Συμπλήρωση κενού (νέα κάρτα)
editing-cloze-deletion-repeat = Συμπλήρωση κενού (ίδια κάρτα)
editing-couldnt-record-audio-have-you-installed = Αδύνατη η εγγραφή ήχου. Έχετε εγκαταστήσει το 'lame';
editing-customize-card-templates = Προσαρμογή προτύπων κάρτας
editing-customize-fields = Προσαρμογή πεδίων
editing-cut = Αποκοπή
editing-double-click-image = διπλό κλικ στην εικόνα
editing-double-click-to-expand = διπλό κλικ για επέκταση
editing-double-click-to-collapse = διπλό κλικ για σύμπτυξη
editing-edit-current = Επεξεργασία τρέχοντος
editing-edit-html = Επεξεργασία HTML
editing-fields = Πεδία
editing-indent = Αύξηση εσοχής
editing-jump-to-tags-with-ctrlandshiftandt = Μεταπήδηση σε ετικέτες με Ctrl+Shift+T
editing-latex = Latex
editing-latex-equation = Εξίσωση LaTeX
editing-latex-math-env = LaTeX math env.
editing-mathjax-chemistry = MathJax χημεία
editing-mathjax-placeholder = Πατήστε { $accept } για αποδοχή, { $newline } για νέα γραμμή.
editing-media = Πολυμέσα
editing-ordered-list = Ταξινομημένη λίστα
editing-outdent = Μείωση εσοχής
editing-paste = Επικόλληση
editing-record-audio = Εγγραφή ήχου
editing-remove-formatting = Αφαίρεση μορφοποίησης
editing-restore-original-size = Επαναφορά αρχικού μεγέθους
editing-select-remove-formatting = Επιλογή μορφοποίησης προς αφαίρεση
editing-show-duplicates = Προβολή διπλότυπων
editing-subscript = Δείκτης
editing-superscript = Εκθέτης
editing-tags = Ετικέτες
editing-tags-add = Προσθήκη ετικέτας
editing-tags-copy = Αντιγραφή ετικετών
editing-tags-remove = Αφαίρεση ετικετών
editing-tags-select-all = Επιλογή όλων των ετικετών
editing-text-color = Χρώμα κειμένου
editing-text-highlight-color = Χρώμα υπογράμμισης κειμένου
editing-toggle-html-editor = Ενεργοποίηση επεξεργασίας HTML
editing-expand = Επέκταση
editing-collapse = Σύμπτυξη
editing-expand-field = Επέκταση πεδίου
editing-collapse-field = Σύμπτυξη πεδίου
editing-underline-text = Υπογράμμιση κειμένου
editing-unordered-list = Αταξινόμητη λίστα
editing-warning-cloze-deletions-will-not-work = Προσοχή! Η συμπλήρωση κενού λειτουργεί μόνο όταν επιλεχθεί πάνω ως τύπος σημείωσης.
editing-mathjax-preview = Προεπισκόπηση MathJax
editing-shrink-images = Συρρίκνωση εικόνων
editing-close-html-tags = Αυτόματο κλείσιμο ετικετών HTML
editing-from-clipboard = Από το πρόχειρο
editing-alignment = Στοίχιση
editing-equations = Εξισώσεις
editing-no-image-found-on-clipboard = Δεν βρέθηκε εικόνα στο πρόχειρο.
editing-image-occlusion-mode = Λειτουργία επικάλυψης εικόνας
editing-image-occlusion-zoom-out = Σμίκρυνση
editing-image-occlusion-zoom-in = Μεγέθυνση
editing-image-occlusion-zoom-reset = Επαναφορά ζουμ
editing-image-occlusion-toggle-translucent = Ενεργοποίηση διαφάνειας
editing-image-occlusion-delete = Διαγραφή
editing-image-occlusion-duplicate = Διπλασιασμός
editing-image-occlusion-select-all = Επιλογή όλων
editing-image-occlusion-alignment = Στοίχιση
editing-image-occlusion-align-left = Στοίχιση αριστερά
editing-image-occlusion-align-right = Στοίχιση δεξιά
editing-image-occlusion-align-top = Στοίχιση πάνω
editing-image-occlusion-align-bottom = Στοίχιση κάτω
editing-image-occlusion-select-tool = Επιλογή
editing-image-occlusion-zoom-tool = Ζουμ
editing-image-occlusion-rectangle-tool = Ορθογώνιο παραλληλόγραμμο
editing-image-occlusion-ellipse-tool = Έλλειψη
editing-image-occlusion-polygon-tool = Πολύγωνο
editing-image-occlusion-text-tool = Κείμενο
editing-image-occlusion-reset = Επαναφορά επικάλυψης εικόνας
editing-image-occlusion-confirm-reset = Είστε σίγουροι ότι θέλετε να επαναφέρετε αυτή την επικάλυψη εικόνας;

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Επεξεργαστής HTML
