fields-add-field = Προσθήκη πεδίου
fields-delete-field-from = Διαγραφή πεδίου από  { $val };
fields-editing-font = Επεξεργασία Γραμματοσειράς
fields-field = Πεδίο:
fields-field-name = Όνομα πεδίου:
fields-description = Περιγραφή
fields-fields-for = Πεδία για { $val }
fields-font = Γραμματοσειρά
fields-size = Μέγεθος:
fields-that-field-name-is-already-used = Αυτό το όνομα αρχείου έχει ήδη χρησιμοποιηθεί.
fields-name-first-letter-not-valid = Το όνομα πεδίου δεν πρέπει να αρχίζει με #, ^ ή /.
fields-name-invalid-letter = Το όνομα πεδίου δεν πρέπει να περιέχει :, ", { "{" } ή { "}" }.
fields-field-is-required = Αυτό είναι ένα απαιτούμενο πεδίο και δεν μπορεί να διαγραφεί.
