importing-failed = Αποτυχία εισαγωγής
importing-added-duplicate-with-first-field = Προστέθηκε διπλοεγγραφή με το πρώτο πεδίο:{ $val }
importing-allow-html-in-fields = Επιτρέψτε HTML στα πεδία
importing-appeared-twice-in-file = Εμφανίζεται δις στο αρχείο: { $val }
importing-change = Αλλαγή
importing-colon = Άνω κάτω τελεία
importing-comma = Κόμμα
importing-field-of-file-is = Πεδίο <b>{ $val }</b> αυτού του αρχείου:
importing-fields-separated-by = Πεδία χωρισμένα με:{ $val }
importing-ignored = <αγνοήθηκε>
importing-import-options = Επιλογές εισαγωγής
importing-map-to = Χάρτης στο { $val }
importing-map-to-tags = Χάρτης σε Ετικέτες
importing-mapped-to = σε αντιστοιχία προς <b>{ $val }</b>
importing-mapped-to-tags = σε αντιστοιχία προς  <b>Ετικέτες</b>
importing-rows-had-num1d-fields-expected-num2d = '%(row)s' είχε %(num1)d πεδία, αναμένωντας %(num2)d
importing-semicolon = Άνω τελεία
importing-supermemo-xml-export-xml = εξαγωγή Supermemo XML (*.xml)
