preferences-automatically-sync-on-profile-openclose = Αυτόματος συγχρονισμός του προφίλ στο άνοιγμα/κλείσιμο
preferences-backups = Αντίγραφα Ασφαλείας
preferences-change-deck-depending-on-note-type = Αλλαγή τράπουλας ανάλογα με τον τύπο σημείωσης
preferences-changes-will-take-effect-when-you = Οι αλλαγές θα εφαρμοστούν όταν κάνετε επανεκκίνηση του Anki.
preferences-hours-past-midnight = ώρες μετά τα μεσάνυχτα
preferences-language = Γλώσσα
preferences-interrupt-current-audio-when-answering = Διακοπή ήχου κατά τη διάρκεια απάντησης
preferences-mins = λεπτά
preferences-network = Δίκτυο
preferences-next-day-starts-at = Η επόμενη μέρα αρχίζει στις
preferences-media-is-not-backed-up = Τα πολυμέσα δεν έχουν αντιγραφεί. Παρακαλούμε δημιουργείτε ένα περιοδικό αντίγραφο ασφαλείας του φακέλου σας Anki για να είστε ασφαλής.
preferences-on-next-sync-force-changes-in = Στον επόμενο συγχρονισμός, εξαναγκάστε τις αλλαγές προς μια κατεύθυνση
preferences-paste-clipboard-images-as-png = Επικόλληση εικόνων από το πρόχειρο ως PNG
preferences-paste-without-shift-key-strips-formatting = Η επικόλληση χωρίς shift αφαιρεί την μορφοποίηση
preferences-periodically-sync-media = Περιοδικός συγχρονισμός πολυμέσων
preferences-please-restart-anki-to-complete-language = Παρακαλώ επανεκκινήστε το Anki για την ολοκλήρωση της αλλαγής γλώσσας.
preferences-preferences = Προτιμήσεις
preferences-scheduling = Προγραμματισμός
preferences-show-learning-cards-with-larger-steps = Εμφάνιση καρτών προς μελέτη με μεγαλύτερα βήματα πριν τις επαναλήψεις
preferences-show-next-review-time-above-answer = Εμφάνιση χρόνου επόμενης επανάληψης πάνω από τα κουμπιά απάντησης
preferences-show-remaining-card-count = Εμφάνιση αριθμού εναπομείναντων καρτών
preferences-some-settings-will-take-effect-after = Μερικές αλλαγές θα εφαρμοστούν μετά την επανεκκίνηση του Anki.
preferences-tab-synchronisation = Συγχρονισμός
preferences-synchronizationnot-currently-enabled-click-the-sync = <
preferences-synchronize-audio-and-images-too = Συγχρονισμός ήχου και εικόνων επίσης
preferences-user-interface-size = Μέγεθος διεπαφής χρήστη
preferences-when-adding-default-to-current-deck = Προσθήκη στην τρέχουσα τράπουλα ως προεπιλογή
preferences-you-can-restore-backups-via-fileswitch = Μπορείτε να αποκαταστήσετε αντίγραφα μέσω Αρχείο > Αλλαγή Προφίλ
preferences-default-search-text = Προεπιλεγμένο κείμενο αναζήτησης
preferences-theme = Θέμα
preferences-theme-follow-system = Σύστημα
preferences-v3-scheduler = Προγραμματιστής V3
preferences-backup-explanation = Το Anki δημιουργεί περιοδικά αντίγραφα ασφαλείας της συλλογής σας. Όταν τα αντίγραφα είναι παλαιότερα των 2 ημερών, το Anki αρχίζει να αφαιρεί ορισμένα από αυτά για την απελευθέρωση χώρου στο δίσκο.
preferences-daily-backups = Διατήρηση καθημερινών αντιγράφων ασφαλείας:
preferences-weekly-backups = Διατήρηση εβδομαδιαίων αντιγράφων ασφαλείας:
preferences-monthly-backups = Διατήρηση μηνιαίων αντιγράφων ασφαλείας:
preferences-minutes-between-backups = Λεπτά μεταξύ των αυτόματων αντιγράφων ασφαλείας:
preferences-reduce-motion = Μείωση κίνησης
preferences-custom-sync-url-disclaimer = Για προχωρημένους χρήστες - παρακαλούμε δείτε το εγχειρίδιο
preferences-hide-top-bar-during-review = Απόκρυψη της άνω μπάρας κατά τη διάρκεια των επαναλήψεων
preferences-hide-bottom-bar-during-review = Απόκρυψη της κάτω μπάρας κατά τη διάρκεια των επαναλήψεων
preferences-always = Πάντα
preferences-full-screen-only = Μόνο σε πλήρη οθόνη
preferences-appearance = Εμφάνιση
preferences-general = Γενικά
preferences-style = Στυλ
preferences-review = Επαναλήψεις
preferences-answer-keys = Πλήκτρα απάντησης
preferences-editing = Επεξεργασία
preferences-browsing = Περιήγηση
preferences-default-deck = Προεπιλεγμένη τράπουλα
preferences-account = Λογαριασμός AnkiWeb
preferences-note = Σημείωση
preferences-scheduler = Προγραμματιστής
preferences-user-interface = Διεπαφή χρήστη
preferences-import-export = Εισαγωγή/Εξαγωγή
preferences-reset-window-sizes = Επαναφορά μεγέθους παραθύρων
preferences-reset-window-sizes-complete = Το μέγεθος των παραθύρων και οι τοποθεσίες έχουν επαναρυθμιστεί.
preferences-shortcut-placeholder = Εισάγετε ένα μη χρησιμοποιούμενο πλήκτρο συντόμευσης ή αφήστε κενό για απενεργοποίηση.

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Βασικό
preferences-media = Πολυμέσα
