preferences-automatically-sync-on-profile-openclose = Αυτόματος συγχρονισμός του προφίλ στο άνοιγμα/κλείσιμο
preferences-backups = Αντίγραφα Ασφαλείας
preferences-change-deck-depending-on-note-type = Αλλαγή τράπουλας ανάλογα με τον τύπο σημείωσης
preferences-changes-will-take-effect-when-you = Οι αλλαγές θα εφαρμοστούν όταν κάνετε επανεκκίνηση του Anki.
preferences-hours-past-midnight = ώρες μετά τα μεσάνυχτα
preferences-language = Γλώσσα
preferences-mins = λεπτά
preferences-network = Δίκτυο
preferences-next-day-starts-at = Η επόμενη μέρα αρχίζει στις
preferences-on-next-sync-force-changes-in = Στον επόμενο συγχρονισμός, εξαναγκάστε τις αλλαγές προς μια κατεύθυνση
preferences-paste-clipboard-images-as-png = Επικόλληση εικόνων από το πρόχειρο ως PNG
preferences-paste-without-shift-key-strips-formatting = Η επικόλληση χωρίς shift αφαιρεί την μορφοποίηση
preferences-periodically-sync-media = Περιοδικός συγχρονισμός πολυμέσων
preferences-please-restart-anki-to-complete-language = Παρακαλώ επανεκκινήστε το Anki για την ολοκλήρωση της αλλαγής γλώσσας.
preferences-preferences = Προτιμήσεις
preferences-scheduling = Προγραμματισμός
preferences-show-remaining-card-count = Εμφάνιση αριθμού εναπομείναντων καρτών
preferences-some-settings-will-take-effect-after = Μερικές αλλαγές θα εφαρμοστούν μετά την επανεκκίνηση του Anki.
preferences-tab-synchronisation = Συγχρονισμός
preferences-synchronizationnot-currently-enabled-click-the-sync = <
preferences-synchronize-audio-and-images-too = Συγχρονισμός ήχου και εικόνων επίσης
preferences-user-interface-size = Μέγεθος διεπαφής χρήστη
preferences-you-can-restore-backups-via-fileswitch = Μπορείτε να αποκαταστήσετε αντίγραφα μέσω Αρχείο > Αλλαγή Προφίλ
preferences-default-search-text = Προεπιλεγμένο κείμενο αναζήτησης
preferences-theme-follow-system = Σύστημα
preferences-v3-scheduler = Προγραμματιστής V3
preferences-daily-backups = Διατήρηση καθημερινών αντιγράφων:
preferences-weekly-backups = Διατήρηση εβδομαδιαίων αντιγράφων:
preferences-monthly-backups = Διατήρηση μηνιαίων αντιγράφων:
preferences-minutes-between-backups = Λεπτά μεταξύ των αυτόματων αντιγράφων:
preferences-reduce-motion = Μείωση κίνησης
preferences-custom-sync-url-disclaimer = Για προχωρημένους χρήστες - παρακαλούμε δείτε το εγχειρίδιο
preferences-hide-top-bar-during-review = Απόκρυψη της άνω μπάρας κατά τη διάρκεια των επαναλήψεων
preferences-hide-bottom-bar-during-review = Απόκρυψη της κάτω μπάρας κατά τη διάρκεια των επαναλήψεων
preferences-always = Πάντα
preferences-full-screen-only = Μόνο σε πλήρη οθόνη
preferences-appearance = Εμφάνιση
preferences-general = Γενικά
preferences-style = Στυλ
preferences-editing = Επεξεργασία
preferences-browsing = Περιήγηση
preferences-default-deck = Προεπιλεγμένη τράπουλα
preferences-account = Λογαριασμός AnkiWeb
preferences-user-interface = Διεπαφή χρήστη
preferences-import-export = Εισαγωγή/Εξαγωγή

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

preferences-basic = Βασικό
preferences-media = Πολυμέσα
