studying-again = Ξανά
studying-bury = Μπέρι
studying-bury-note = Σημείωση μπέρι
studying-card-suspended = Αναστολή κάρτας.
studying-cards-will-be-automatically-returned-to = Οι κάρτες θα επιστραφούν αυτόματα στις αρχικές τους τράπουλες αφού τις επιθεωρήσεις.
studying-delete-note = Διαγραφή Σημείωσης
studying-easy = Εύκολο
studying-edit = Επεξεργασία
studying-empty = Κενό
studying-good = Καλώς
studying-hard = Δύσκολο
studying-more = Περισσότερα
studying-show-answer = Προβολή απάντησης
studying-study-now = Μελέτησε τώρα
studying-suspend = Αναστολή
studying-suspend-note = Αναστολή σημείωσης
studying-you-havent-recorded-your-voice-yet = Δεν έχετε ηχογραφήσει τη φωνή σας ακόμα
