actions-add = Añadir
actions-blue-flag = Marca azul
actions-cancel = Cancelar
actions-choose = Seleccionar
actions-close = Cerrar
actions-copy = Copiar
actions-custom-study = Estudio personalizado
actions-decks = Mazos
actions-delete = Eliminar
actions-export = Exportar
actions-filter = Filtrar
actions-green-flag = Marca verde
actions-help = Ayuda
actions-import = Importar
actions-manage = Gestionar…
actions-name = Nombre
actions-new = Nuevas
actions-new-name = Nombre nuevo:
actions-options = Opciones
actions-options-for = Opciones para { $val }
actions-orange-flag = Marca Naranja
actions-preview = Previsualizar
actions-rebuild = Reconstruir
actions-red-flag = Marca roja
actions-rename = Renombrar
actions-rename-deck = Renombrar mazo
actions-replay-audio = Reproducir sonido
actions-reposition = Reposición
actions-save = Guardar
actions-search = Buscar
actions-shortcut-key = Tecla de atajo: { $val }
actions-suspend-card = Suspender tarjeta
actions-set-due-date = Establecer fecha de vencimiento
