actions-add = Añadir
actions-all-selected = Todo seleccionado
actions-cancel = Cancelar
actions-choose = Seleccionar
actions-close = Cerrar
actions-copy = Copiar
actions-create-copy = Crear copia
actions-custom-study = Estudio personalizado
actions-decks = Mazos
actions-delete = Eliminar
actions-export = Exportar
actions-filter = Filtrar
actions-help = Ayuda
actions-import = Importar
actions-manage = Gestionar…
actions-name = Nombre
actions-new = Nuevas
actions-new-name = Nombre nuevo:
actions-options = Opciones
actions-options-for = Opciones para { $val }
actions-preview = Previsualizar
actions-rebuild = Reconstruir
actions-rename = Renombrar
actions-rename-deck = Renombrar mazo
actions-rename-tag = Renombrar etiqueta
actions-rename-with-parents = Renombrar con los Parientes
actions-remove-tag = Remover etiqueta
actions-replay-audio = Reproducir sonido
actions-reposition = Reposición
actions-save = Guardar
actions-search = Buscar
actions-select = Seleccione
actions-shortcut-key = Tecla de atajo: { $val }
actions-suspend-card = Suspender tarjeta
actions-set-due-date = Establecer fecha de vencimiento
actions-answer-card = Contestar tarjeta
actions-unbury-unsuspend = Desenterrar/Dessuspender
actions-add-deck = Añadir mazo
actions-add-note = Añadir nota
actions-update-tag = Actualizar etiqueta
actions-update-note = Actualizar Nota
actions-update-card = Actualizar Tarjeta
actions-update-deck = Actualizar Mazo
actions-card-info = Información de la tarjeta

## Flags

