adding-add-shortcut-ctrlandenter = Añadir (atajo: ctrl+enter)
adding-added = Añadidas
adding-close-and-lose-current-input = ¿Cerrar y perder la información actual?
adding-edit = Editar "{ $val }"
adding-history = Historia
adding-note-deleted = (Nota borrada)
adding-shortcut = Atajo: { $val }
adding-the-first-field-is-empty = El primer campo está vacío.
adding-you-have-a-cloze-deletion-note = Tienes un tipo de nota de huecos pero no has insertado ningún hueco. ¿Quieres continuar?
