change-notetype-current = Actual
change-notetype-new = Nuevo
change-notetype-nothing = (Nada)
change-notetype-collapse = Colapsar
change-notetype-expand = Expandir
change-notetype-will-discard-content = Se descartará contenido en los siguientes campos:
change-notetype-will-discard-cards = Eliminará las siguientes tarjetas:
change-notetype-fields = Campos
change-notetype-templates = Plantillas
