editing-add-media = Añadir archivos multimedia
editing-an-error-occurred-while-opening = Ocurrió un error al abrir { $val }
editing-attach-picturesaudiovideo-f3 = Adjuntar imágenes/audio/video (F3)
editing-bold-text-ctrlandb = Texto en negrita (Ctrl+B)
editing-cards = Tarjetas
editing-change-colour-f8 = Cambiar de color (F8)
editing-cloze-deletion-ctrlandshiftandc = Pregunta anidada (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = No se pudo grabar el audio. Tienes instalado "lame"?
editing-customize-card-templates-ctrlandl = Personalizar plantillas de tarjetas (Ctrl+L)
editing-customize-fields = Personalizar campos
editing-cut = Cortar
editing-edit-current = Editar actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-html-editor = Editor HTML
editing-italic-text-ctrlandi = Texto en cursiva (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Saltar a etiquetas con Ctrl+Mayús+T
editing-latex = LaTeX
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-mathjax-block = Bloque de MathJacx
editing-mathjax-chemistry = Química MathJax
editing-mathjax-inline = MathJacx en línea
editing-media = Multimedia
editing-paste = Pegar
editing-record-audio-f5 = Grabar audio (F5)
editing-remove-formatting-ctrlandr = Eliminar formato (Ctrl+R)
editing-set-foreground-colour-f7 = Establecer color de primer plano (F7)
editing-show-duplicates = Mostrar duplicados
editing-subscript-ctrland = Subíndice (Ctrl+=)
editing-superscript-ctrlandand = Superíndice (Ctrl++)
editing-tags = Etiquetas
editing-to-make-a-cloze-deletion-on = Para crear preguntas anidadas en una nota existente, primero debe cambiarla a un tipo de nota de Respuesta Anidada, mediante 'Editar>Cambiar tipo de nota'.
editing-underline-text-ctrlandu = Subrayar texto (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = Cuidado, los huecos no funcionarán a menos que cambies el tipo de nota a Huecos.
