exporting-all-decks = Todos los mazos
exporting-anki-20-deck = Mazo Anki 2.0
exporting-anki-collection-package = Paquete de colección de Anki
exporting-anki-deck-package = Paquete de mazos Anki
exporting-cards-in-plain-text = Tarjetas en texto plano
exporting-collection = colección
exporting-collection-exported = Colección exportada
exporting-couldnt-save-file = No se ha podido guardar el archivo: { $val }
exporting-export = Exportar...
exporting-export-format = <b>Formato de export.</b>:
exporting-include = <b>Incluir</b>:
exporting-include-html-and-media-references = Incluir referencias a HTML y archivos multimedia
exporting-include-media = Incluir archivos multimedia
exporting-include-scheduling-information = Incluir información de programación
exporting-include-tags = Incluir etiquetas
exporting-notes-in-plain-text = Notas en texto plano
exporting-selected-notes = Notas Seleccionadas
