notetypes-front-field = Anverso
notetypes-back-field = Reverso
notetypes-add-reverse-field = Añadir reverso
notetypes-text-field = Texto
notetypes-basic-name = Básico
notetypes-basic-reversed-name = Básico (y tarjeta invertida)
notetypes-basic-optional-reversed-name = Básico (tarjeta invertida opcional)
notetypes-cloze-name = Hueco
notetypes-basic-type-answer-name = Básico (teclear la respuesta)
notetypes-card-2-name = Tarjeta 2
notetypes-card-1-name = Tarjeta 1
