preferences-automatically-sync-on-profile-openclose = Sincronizar automáticamente al abrir/cerrar el perfil
preferences-backups = Copias de seguridad
preferences-backups2 = copias de respaldo
preferences-backupsanki-will-create-a-backup-of = <b>Copias de seguridad</b><br>Anki creará una copia de seguridad de tu colección cada vez que sea cerrada o sincronizada.
preferences-basic = Básico
preferences-change-deck-depending-on-note-type = Cambiar mazo en función del tipo de nota
preferences-changes-will-take-effect-when-you = Los cambios se aplicarán cuando reinicies Anki.
preferences-hours-past-midnight = horas pasada la medianoche
preferences-interface-language = Idioma de la interfaz:
preferences-interrupt-current-audio-when-answering = Interrumpir el audio actual al responder
preferences-keep = Conservar
preferences-learn-ahead-limit = Límite del estudio por adelantado
preferences-mins = mins
preferences-network = Red
preferences-next-day-starts-at = El siguiente día empieza a las
preferences-night-mode = Modo nocturno
preferences-note-media-is-not-backed-up = Nota: no se hacen copias de seguridad de los archivos multimedia. Por favor, haz copias de seguridad de tu carpeta de Anki periódicamente para asegurarla.
preferences-on-next-sync-force-changes-in = Forzar cambios en una dirección en la próxima sincronización
preferences-paste-clipboard-images-as-png = Pegar imágenes del portapapeles como PNG
preferences-paste-without-shift-key-strips-formatting = Pegar sin la tecla Mayús elimina el formato
preferences-periodically-sync-media = Sincronizar archivos multimedia periódicamente
preferences-please-restart-anki-to-complete-language = Por favor, reinicia Anki para completar el cambio de idioma.
preferences-preferences = Preferencias
preferences-scheduling = Programación
preferences-show-learning-cards-with-larger-steps = Mostrar las tarjetas en aprendizaje con pasos mayores antes de los repasos
preferences-show-next-review-time-above-answer = Mostrar intervalo de próximo repaso encima de los botones de respuesta
preferences-show-play-buttons-on-cards-with = Mostrar botones de reproducción en tarjetas con audio
preferences-show-remaining-card-count-during-review = Mostrar el número de tarjetas restantes durante el repaso
preferences-some-settings-will-take-effect-after = Algunos ajustes tendrán efecto después de reiniciar Anki.
preferences-synchronisation = <b>Sincronización</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronización</b><br> Actualmente no está activada; haz clic en el botón de sincronizar en la pantalla principal para activarla.
preferences-synchronize-audio-and-images-too = Sincronizar también los sonidos y las imágenes
preferences-timebox-time-limit = Límite de sesión de estudio
preferences-user-interface-size = Tamaño de interfaz de usuario
preferences-when-adding-default-to-current-deck = Al añadir, hacerlo en el mazo actual de manera predeterminada
preferences-you-can-restore-backups-via-fileswitch = Puedes restaurar copias de seguridad con Archivo>Cambiar perfil.
preferences-theme-label = Tema: { $theme }
preferences-theme-follow-system = Seguir el sistema
preferences-theme-light = Claro
preferences-theme-dark = Oscuro
preferences-ignore-accents-in-search = Ignorar acentos en la búsqueda (más lento)
preferences-daily-backups = Copias de seguridad diarias para mantener:
preferences-weekly-backups = Copias de seguridad semanales para mantener:
preferences-monthly-backups = Número de copias de seguridad mensuales a mantener:
