studying-again = Otra vez
studying-all-buried-cards = Totas las tarjetas enterradas
studying-audio-5s = Audio -5s
studying-audio-and5s = Audio +5s
studying-buried-siblings = Enterrar tarjetas relacionadas
studying-bury = Enterrar
studying-bury-card = Enterrar tarjeta
studying-bury-note = Enterrar nota
studying-card-buried = Tarjeta ocultada.
studying-card-suspended = Tarjeta suspendida.
studying-card-was-a-leech = La tarjeta era una sanguijuela.
studying-cards-will-be-automatically-returned-to = Las tarjetas se devolverán automáticamente a sus mazos originales una vez las hayas repasado.
studying-continue = Siguiente
studying-delete-note = Eliminar nota
studying-deleting-this-deck-from-the-deck = Al eliminar este mazo de la lista de mazos se devolverán todas las tarjetas restantes a su mazo original.
studying-easy = Fácil
studying-edit = Editar
studying-empty = Vacío
studying-finish = Finalizar
studying-flag-card = Marcar tarjeta
studying-good = Bien
studying-hard = Difícil
studying-it-has-been-suspended = Ha sido suspendida.
studying-manually-buried-cards = Tarjetas enterradas manualmente
studying-mark-note = Marcar nota
studying-more = Más
studying-no-cards-are-due-yet = Aún no hay tarjetas programadas.
studying-note-buried = La nota se ha enterrado.
studying-note-suspended = La nota se ha suspendido.
studying-pause-audio = Pausar audio
studying-please-run-toolsempty-cards = Por favor, ejecuta Herramientas>Tarjetas vacías
studying-record-own-voice = Grabar mi propia voz
studying-replay-own-voice = Reproducir mi propia voz
studying-show-answer = Mostrar respuesta
studying-space = Espacio
studying-study-now = Comenzar a estudiar
studying-suspend = Suspender
studying-suspend-note = Suspender nota
studying-this-is-a-special-deck-for = Este es un mazo especial para estudiar fuera del horario normal.
studying-to-review = A repasar
studying-type-answer-unknown-field = Escribir respuesta: campo desconocido { $val }
studying-unbury = Desenterrar
studying-what-would-you-like-to-unbury = ¿Qué deseas desenterrar?
studying-you-havent-recorded-your-voice-yet = Aún no has grabado tu voz.
