editing-actual-size = Alternar tamaño real
editing-add-media = Engadir ficheiros multimedia
editing-align-left = Aliñar á esquerda
editing-align-right = Aliñar á dereita
editing-an-error-occurred-while-opening = produciuse un erro ao abrir { $val }
editing-attach-picturesaudiovideo = Anexar imaxes/audio/vídeo
editing-bold-text = Aplicar letra grosa
editing-cards = Tarxetas
editing-center = Centrar
editing-change-color = Cambiar a cor
editing-copy-image = Copiar imaxe
editing-customize-fields = Personalizar campos
editing-cut = Cortar
editing-edit-current = Editar a actual
editing-edit-html = Editar HTML
editing-fields = Campos
editing-italic-text = Aplicar cursiva
editing-jump-to-tags-with-ctrlandshiftandt = Ir ás etiquetas con Ctrl+Maiús+T
editing-justify = Xustificar
editing-latex = LaTeX
editing-latex-equation = Ecuación LaTeX
editing-latex-math-env = Entorno matemático LaTeX
editing-media = Recursos multimedia
editing-open-image = Abrir imaxe
editing-show-in-folder = Amosar en cartafol
editing-paste = Pegar
editing-show-duplicates = Amosar os duplicados
editing-tags = Etiquetas
editing-tags-add = Engadir etiqueta
editing-tags-copy = Copiar etiquetas
editing-tags-remove = Eliminar etiquetas
editing-tags-select-all = Seleccionar tódalas etiquetas
editing-text-color = Cor do texto
editing-to-make-a-cloze-deletion-on = Para crear ocos nunha nota existente, primeiro debe cambiala a un tipo de nota de ocos, mediante Editar > Cambiar o tipo de nota.
editing-toggle-html-editor = Alternar o editor HTML
editing-toggle-visual-editor = Alternar o editor visual
editing-expand = Estender
editing-warning-cloze-deletions-will-not-work = Aviso: os ocos non funcionarán a non ser que cambie o tipo de nota a Ocos.

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = Editor de HTML
