studying-again = De novo
studying-all-buried-cards = Tódalas tarxetas soterradas
studying-bury = Descartar
studying-bury-card = Soterrar carta
studying-bury-note = Descartar a nota
studying-card-buried = Carta soterrada.
studying-card-suspended = Tarxeta suspendida.
studying-card-was-a-leech = A tarxeta era unha samesuga
studying-cards-will-be-automatically-returned-to = As tarxetas devolveranse automaticamente aos seus feixes orixinais unha vez as teña repasado.
studying-continue = Continuar
studying-delete-note = Eliminar a nota
studying-deleting-this-deck-from-the-deck = Ao eliminar este feixe da lista de feixes devolveranse todas as tarxetas restantes ao seu feixe orixinal.
studying-easy = Fácil
studying-edit = Editar
studying-empty = Baleira
studying-finish = Terminar
studying-good = Ben
studying-hard = Difícil
studying-it-has-been-suspended = Foi suspendida.
studying-more = Máis
studying-no-cards-are-due-yet = Non hai tarxetas obrigadas
studying-note-buried = Nota descartada
studying-note-suspended = A nota foi suspendida.
studying-please-run-toolsempty-cards = Execute Ferramentas >Tarxetas baleiras
studying-record-own-voice = Gravar a súa propia voz
studying-replay-own-voice = Reproducir a súa propia voz
studying-show-answer = Amosar a resposta
studying-space = Espazo
studying-study-now = Estudar agora
studying-suspend = Suspender
studying-suspend-note = Suspender nota
studying-this-is-a-special-deck-for = Este é un feixe especial para estudar fora do horario normal.
studying-to-review = Para repasar
studying-type-answer-unknown-field = Tipo de resposta: campo descoñecido { $val }
studying-unbury = Reincorporar
studying-you-havent-recorded-your-voice-yet = Aínda non gravou a súa voz.
