actions-add = Tilføj
actions-cancel = Afbryd
actions-choose = Vælg
actions-close = Luk
actions-copy = Kopier
actions-custom-study = Brugerdefineret studie
actions-decks = Alle kortsæt
actions-delete = Slet
actions-export = Eksportér
actions-filter = Filtrér
actions-help = Hjælp
actions-import = Importér
actions-name = Navn:
actions-new = Nye
actions-new-name = Nyt navn:
actions-options = Indstillinger
actions-options-for = Muligheder for { $val }
actions-preview = Forhåndsvisning
actions-rebuild = Genopbyg
actions-rename = Omdøb
actions-rename-deck = Omdøg kortsæt
actions-replay-audio = Genafspil lyd
actions-reposition = Repositioner
actions-search = Søg
actions-shortcut-key = Genvej: { $val }
actions-suspend-card = Suspender kort
