card-stats-added = Tilføjet
card-stats-first-review = Første genopfriskning
card-stats-latest-review = Seneste genopfriskning
card-stats-ease = Sværhedsgrad
card-stats-review-count = Genopfriskninger
card-stats-lapse-count = Udfald
card-stats-average-time = Gennemsnitstid
card-stats-total-time = Tid i alt
card-stats-card-template = Korttype
card-stats-note-type = Notattype
card-stats-deck-name = Kortsæt
card-stats-note-id = Note-ID
card-stats-card-id = Kort-ID
card-stats-review-log-rating = Bedømmelse
card-stats-review-log-date = Dato
card-stats-review-log-time-taken = Tid
card-stats-review-log-type-learn = Lær
card-stats-review-log-type-review = Gennemgang
card-stats-review-log-type-relearn = Genlær
card-stats-review-log-type-filtered = Filtreret
card-stats-review-log-type-rescheduled = Nyt tidspunkt
