card-templates-front-template = Skabelon for forside
card-templates-back-template = Skabelon for bagside
card-templates-template-styling = Stil
card-templates-front-preview = Forhåndsvisning af forside
card-templates-back-preview = Forhåndsvisning af bagside
card-templates-preview-box = Forhåndsvisning
card-templates-sample-cloze = Dette er en {"{{c1::"}sample{"}}"} cloze-sletning.
card-templates-anki-couldnt-find-the-line-between = Anki fandt ikke linjen mellem spørgsmålet og svaret. Tilpas venligst skabelonen manuelt for at bytte om på spørgsmålet og svaret.
card-templates-at-least-one-card-type-is = Der kræves mindst én korttype.
card-templates-card = Kort { $val }
card-templates-card-types = Korttyper
card-templates-card-types-for = Korttyper til { $val }
card-templates-delete-the-as-card-type-and = Slet korttypen '%(a)s' og dets %(b)s?
card-templates-enter-deck-to-place-new = Indtast kortsæt at placere nye { $val } kort i, eller efterlad blank:
card-templates-enter-new-card-position-1 = Indtast ny kortposition (1...{ $val }):
card-templates-flip = Vend
card-templates-form = Formular
card-templates-off =  (slået fra)
card-templates-on =  (slået til)
