custom-study-cards = kort
custom-study-cards-from-the-deck = kort fra kortsættet
custom-study-choose-tags = Vælg mærker
custom-study-custom-study-session = Brugerdefineret studielektion
custom-study-due-cards-only = Vis kun kort med overskredet tidsfrist
custom-study-increase-todays-new-card-limit = Forøg dagens begrænsning for nye kort
custom-study-increase-todays-new-card-limit-by = Forøg dagens begrænsning for nye kort med
custom-study-increase-todays-review-card-limit = Forøg grænsen for dagens kort-genopfriskninger
custom-study-increase-todays-review-limit-by = Forøg dagens grænse for genopfriskning af kort med
custom-study-new-cards-only = Kun nye kort
custom-study-no-cards-matched-the-criteria-you = Ingen kort som passede til de kriterier du angav.
custom-study-ok = O.k.
custom-study-preview-new-cards = Forhåndsvis nye kort
custom-study-preview-new-cards-added-in-the = Forhåndsvis nye kort tilføjet i den sidste
custom-study-require-one-or-more-of-these = Påkræv én eller flere af disse mærker:
custom-study-review-ahead = Genopfrisk før planlagt
custom-study-review-ahead-by = Genopfrisk før planlagt med
custom-study-review-cards-forgotten-in-last = Genopfrisk kort som er glemt i seneste
custom-study-review-forgotten-cards = Genopfrisk glemte kort
custom-study-select = Vælg
custom-study-select-tags-to-exclude = Vælg mærker som skal udelades:
custom-study-selective-study = Selektivt studie
custom-study-study-by-card-state-or-tag = Studér kortene efter kortenes tilstand eller mærke
