decks-add-new-deck-ctrlandn = Tilføj nyt kortsæt (Ctrl+N)
decks-are-you-sure-you-wish-to = Er du sikker på at du vil slette { $val }?
decks-build = Byg
decks-cards-selected-by = kort udvalgt af
decks-create-deck = Opret kortsæt
decks-deck = Kortsæt
decks-decreasing-intervals = Aftagende intervaller
decks-delete-deck = Slet kortsæt
decks-get-shared = Hent delte
decks-import-file = Importer fil
decks-increasing-intervals = Intervallerne øges
decks-latest-added-first = Seneste tilføjes først
decks-limit-to = Begræns til
decks-minutes = minutter
decks-most-lapses = Flest omgange
decks-name-for-deck = Navn på kortsæt:
decks-new-deck-name = Nyt kortsætnavn:
decks-no-deck = [intet kortsæt]
decks-oldest-seen-first = Ældste set først
decks-order-added = Tilføjede rækkefølge
decks-order-due = Fristorden
decks-please-select-something = Vælg venligst et eller andet.
decks-random = Tilfældig
decks-relative-overdueness = Relativ overskridelse
decks-reschedule-cards-based-on-my-answers = Planlæg kort påny baseret på mine svar i denne kortsæt
decks-study = Studér
decks-study-deck = Studér kortsæt
decks-the-provided-search-did-not-match = Den foretagne søgning gav ingen match med kort. Ønsker du at tilpasse den?
