editing-add-media = Tilføj medie
editing-an-error-occurred-while-opening = Der opstod en fejl under åbning af { $val }
editing-cards = Kort
editing-cut = Klip
editing-edit-current = Rediger nuværende
editing-edit-html = Rediger HTML
editing-fields = Felter
editing-jump-to-tags-with-ctrlandshiftandt = Spring til mærker med Ctrl+Skift+T
editing-latex-equation = LaTeX-ligning
editing-latex-math-env = Matematik-miljø for LaTeX
editing-media = Medie
editing-paste = Indsæt
editing-show-duplicates = Vis dubletter
editing-tags = Mærker
editing-to-make-a-cloze-deletion-on = For at lave en cloze-sletning på en eksisterende note, så skal du først ændre den til en cloze-type, via Redigér>Skift notetype.
editing-warning-cloze-deletions-will-not-work = Advarsel, cloze-sletninger vil ikke fungere før du skifter typen i toppen til Cloze.
