exporting-all-decks = Alle kortsæt
exporting-anki-20-deck = Anki 2.0 Kortsæt
exporting-anki-deck-package = Anki kortsæt-pakke
exporting-cards-in-plain-text = Kort som ren tekst
exporting-collection = samling
exporting-couldnt-save-file = Kunne ikke gemme filen: { $val }
exporting-export = Eksportér
exporting-export-format = <b>Eksportformat</b>:
exporting-include = <b>Inkludér</b>:
exporting-include-media = Inkluder medie
exporting-include-scheduling-information = Inkluder planlægningsinformation
exporting-include-tags = Inkluder etiketter
exporting-notes-in-plain-text = Notat i ren tekst
