fields-add-field = Tilføj felt
fields-delete-field-from = Slet felt fra { $val }?
fields-editing-font = Redigerende font
fields-field = Felt:
fields-field-name = Feltnavn:
fields-fields-for = Felter for { $val }
fields-font = Skrift:
fields-new-position-1 = Ny position (1...{ $val }):
fields-notes-require-at-least-one-field = Noter kræver mindst ét felt.
fields-remember-last-input-when-adding = Husk sidste indtastning når der tilføjes
fields-reverse-text-direction-rtl = Modsat tekstretning (RTL)
fields-size = Størrelse:
fields-sort-by-this-field-in-the = Sorter efter dette felt i browseren
fields-that-field-name-is-already-used = Det feltnavn er allerede brugt.
