importing-failed = Import mislykkedes.
importing-failed-debug-info = Import fejlede: fejlinformation:
importing-aborted = Afbrød: { $val }
importing-added-duplicate-with-first-field = Tilføjede dublet med første felt: { $val }
importing-allow-html-in-fields = Tillad HTML i felterne
importing-appeared-twice-in-file = Forekommer 2 gange i filen: { $val }
importing-by-default-anki-will-detect-the = Som standard vil Anki opfange tegnet mellem felter, så som en tabulator, et komma eller lign. Hvis Anki opfanger tegnet forkert, kan du indtaste det her. Brug \t til at repræsentere tabulator.
importing-change = Ændre
importing-colon = Kolon
importing-comma = Komma
importing-empty-first-field = Tome første felt: { $val }
importing-field-mapping = Feltopmærkning
importing-field-of-file-is = Felt <b>{ $val }</b> i fil er:
importing-fields-separated-by = Felter separeret af: { $val }
importing-first-field-matched = Første felt matchede: { $val }
importing-ignore-field = Ignorér felt
importing-ignore-lines-where-first-field-matches = Ignorér linjer hvor første felt matcher eksisterende note
importing-ignored = <ignoreres>
importing-import-even-if-existing-note-has = Importér selv om eksisterende note har samme første-felt
importing-import-options = Import muligheder
importing-importing-complete = Import er fuldført.
importing-invalid-file-please-restore-from-backup = Filen er ugyldig. Gendan den fra en sikkerhedskopi.
importing-map-to = Mappe til { $val }
importing-map-to-tags = Knyt til Tags
importing-mapped-to = afbilledet til <b>{ $val }</b>
importing-mapped-to-tags = afbilledet til <b>Mærker</b>
importing-mnemosyne-20-deck-db = Mnemosyne 2.0 kortsæt (*.db)
importing-pauker-18-lesson-paugz = Pauker 1.8-lektion (*.pau.gz)
importing-rows-had-num1d-fields-expected-num2d = '%(row)s' havde %(num1)d felter, forventede %(num2)d
importing-selected-file-was-not-in-utf8 = Den valgte vil var ikke i formatet UTF-8. Læs venligst manualens importsektion .
importing-semicolon = Semikolon
importing-supermemo-xml-export-xml = Supermemo XML-eksport (*.xml)
importing-text-separated-by-tabs-or-semicolons = Tekst separerede af tabulatorstop eller semikolon(*)
importing-the-first-field-of-the-note = Det første felt af denne notetype skal være afbildet.
importing-the-provided-file-is-not-a = Den leverede fil er ikke en gyldig .apkg-fil.
importing-this-file-does-not-appear-to = Dette ligner ikke en gyldig .apkg-fil. Hvis du får denne fejl fra en fil, der er hentet fra AnkiWeb, så mislykkedes hentningen sandsynligvis. Forsøg venligst igen, og hvis problemet fortsat er tilstede, så kan du forsøge igen med en anden browser.
importing-this-will-delete-your-existing-collection = Dette vil slette din eksisterende samling og erstatte den med dataene i filen du importerer. Er du sikker?
importing-unable-to-import-from-a-readonly = Kan ikke importere fra en skrivebeskyttet fil.
importing-unknown-file-format = Ukendt filformat
importing-update-existing-notes-when-first-field = Opdatér eksisterende noter når første felt matches
