notetypes-front-field = Forside
notetypes-back-field = Bagside
notetypes-add-reverse-field = Tilføj baglæns
notetypes-text-field = Tekst
notetypes-basic-name = Grundlæggende
notetypes-basic-reversed-name = Grundlæggende (og kort baglæns)
notetypes-basic-optional-reversed-name = Grundlæggende (valgfrit med kort  baglæns)
notetypes-card-2-name = Kort 2
notetypes-card-1-name = Kort 1
notetypes-add = Tilføj: { $val }
notetypes-add-note-type = Tilføj notetype
notetypes-cards = Kort...
notetypes-clone = Klon: { $val }
notetypes-copy = { $val } kopi
notetypes-delete-this-note-type-and-all = Slet denne note-type og alle dens kort?
notetypes-delete-this-unused-note-type = Slet denne ubrugte notetype?
notetypes-fields = Felter...
notetypes-footer = Sidefod
notetypes-header = Overskrift
notetypes-note-types = Notetyper
notetypes-options = Indstillinger...
notetypes-please-add-another-note-type-first = Tilføj venligst en anden note-type først.
