notetypes-front-field = Forside
notetypes-back-field = Bagside
notetypes-add-reverse-field = Tilføj baglæns
notetypes-text-field = Tekst
notetypes-basic-name = Grundlæggende
notetypes-basic-reversed-name = Grundlæggende (og kort baglæns)
notetypes-basic-optional-reversed-name = Grundlæggende (valgfrit med kort  baglæns)
notetypes-card-2-name = Kort 2
notetypes-card-1-name = Kort 1
