preferences-automatically-sync-on-profile-openclose = Synkronisér automatisk når profil åbnes/lukkes
preferences-backups = Sikkerhedskopier
preferences-backups2 = Sikkerhedskopier
preferences-backupsanki-will-create-a-backup-of = <b>Sikkerhedskopier</b><br>Anki vil oprette en sikkerhedskopi af din samling, hver gang programmet lukkes eller der synkroniseres.
preferences-basic = Grundlæggende
preferences-change-deck-depending-on-note-type = Skift kortsæt afhængigt af notetype
preferences-hours-past-midnight = timer efter midnat
preferences-interface-language = Grænsefladesprog:
preferences-keep = Behold
preferences-learn-ahead-limit = Lær foran grænse
preferences-mins = min
preferences-network = Netværk
preferences-next-day-starts-at = Næste dag start ved
preferences-note-media-is-not-backed-up = Bemærk: Medie er ikke sikkerhedskopieret. Etablér venligst en periodisk sikkerhedskopi af din Anki-mappe for at sikre dig.
preferences-on-next-sync-force-changes-in = Gennemtving ensretning af ændringer ved næste synkronisering.
preferences-paste-clipboard-images-as-png = Indsæt billeder fra udklipsholder som PNG
preferences-preferences = Opsætning
preferences-scheduling = Skemalæg igen
preferences-show-next-review-time-above-answer = Vis næste genopfriskningstid over svarknapperne
preferences-show-remaining-card-count-during-review = Vis tilbageværende kortantal under genopfriskning
preferences-some-settings-will-take-effect-after = Nogle ændringer træder først i kraft efter du har genstartet Anki.
preferences-synchronisation = <b>Synkronisering</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Synkronisering</b><br> Er ikke indstillet; klik på knappen til synkronisering i hovedvinduet for at aktivere.
preferences-synchronize-audio-and-images-too = Synkroniser lyd og billeder også
preferences-timebox-time-limit = Tidsboksgrænse
preferences-when-adding-default-to-current-deck = Når der tilføjes, så anvend nuværende kortsæt som standard
