studying-again = Igen
studying-bury = Begrav
studying-bury-card = Begrav kort
studying-bury-note = Begrav notat
studying-card-buried = Kort er begravet
studying-card-suspended = Kort er suspenderet.
studying-card-was-a-leech = Kortet var en igle.
studying-cards-will-be-automatically-returned-to = Kort flyttes automatisk tilbage til deres oprindelige kortsæt, når du gennemgår dem.
studying-continue = Fortsæt
studying-delete-note = Slet notat
studying-deleting-this-deck-from-the-deck = Sletning af dette kortsæt fra listen, vil returnere alle tilbageværende kort til deres oprindelige kortsæt.
studying-easy = Let
studying-edit = Redigér
studying-empty = Tom
studying-finish = Færdiggør
studying-good = Godt
studying-hard = Hård
studying-it-has-been-suspended = Det er blevet suspenderet.
studying-more = Mere
studying-no-cards-are-due-yet = Der er ingen kort med udløben tidsfrist
studying-note-buried = Noten er begravet.
studying-note-suspended = Note er suspenderet.
studying-please-run-toolsempty-cards = Kør venligst Værktøjer>Tomme kort
studying-record-own-voice = Optag egen stemme
studying-replay-own-voice = Afspil egen stemme
studying-show-answer = Vis svar
studying-space = Mellemrum
studying-study-now = Gennemgå nu
studying-suspend = Suspendér
studying-suspend-note = Suspender notat
studying-this-is-a-special-deck-for = Dette er et specielt kortsæt til studier uden for den normale tidsplan.
studying-to-review = Til genopfriskning
studying-type-answer-unknown-field = Skriv svar: ukendt felt { $val }
studying-unbury = Grav frem igen
studying-you-havent-recorded-your-voice-yet = Du har endnu ikke optaget din stemme endnu.
