actions-add = 추가
actions-all-selected = 선택된 전체
actions-any-selected = 선택된 아무거나
actions-cancel = 취소
actions-choose = 선택
actions-close = 닫기
actions-copy = 복사하기
actions-create-copy = 사본 만들기
actions-custom-study = 맞춤 공부
actions-decks = 뭉치
actions-delete = 삭제
actions-export = 내보내기
actions-filter = 필터
actions-help = 도움말
actions-import = 가져오기
actions-manage = 관리...
actions-name = 이름:
actions-new = 새 카드
actions-new-name = 새 이름:
actions-options = 옵션
actions-options-for = { $val }의 옵션
actions-preview = 미리 보기
actions-rebuild = 다시 모으기
actions-rename = 이름 변경
actions-rename-deck = 뭉치 이름 변경
actions-rename-tag = 태그 이름 변경
actions-remove-tag = 태그 삭제
actions-replay-audio = 오디오 재생
actions-reposition = 위치 변경
actions-save = 저장하기
actions-search = 찾기
actions-select = 선택
actions-shortcut-key = 단축키: { $val }
actions-suspend-card = 카드 일시중단
actions-set-due-date = 마감 날짜 설정
actions-unbury-unsuspend = 덮기/일시중단 취소
actions-add-deck = 뭉치 추가
actions-add-note = 노트 추가
actions-update-tag = 태그 업데이트
actions-update-note = 노트 업데이트
actions-update-card = 카드 업데이트
actions-update-deck = 뭉치 업데이트
actions-forget-card = 초기화
actions-add-notetype = 노트 유형 추가
actions-remove-notetype = 노트 유형 삭제
actions-update-notetype = 노트 유형 업데이트
actions-card-info = 카드 정보
actions-previous-card-info = 이전 카드 정보

## Flags

actions-flag-number = 플래그 { $number }
actions-set-flag = 플래그 설정
