actions-add = 추가
actions-blue-flag = 파란색 표시
actions-cancel = 취소
actions-choose = 선택
actions-close = 닫기
actions-copy = 복사하기
actions-custom-study = 맞춤 공부
actions-decks = 뭉치
actions-delete = 삭제
actions-export = 내보내기
actions-filter = 여과
actions-green-flag = 녹색 표시
actions-help = 도움말
actions-import = 가져오기
actions-manage = 관리...
actions-name = 이름:
actions-new = 새 카드
actions-new-name = 새 이름:
actions-options = 옵션
actions-options-for = { $val }의 옵션
actions-orange-flag = 오렌지색 깃발
actions-preview = 미리 보기
actions-rebuild = 다시 모으기
actions-red-flag = 빨간색 표시
actions-rename = 이름 변경
actions-rename-deck = 뭉치 이름 변경
actions-replay-audio = 오디오 재생
actions-reposition = 위치 변경
actions-save = 저장하기
actions-search = 찾기
actions-shortcut-key = 단축키: { $val }
actions-suspend-card = 카드 보류
