browsing-add-notes = 노트 추가...
browsing-add-tags = 태그 추가
browsing-add-tags2 = 태그 추가...
browsing-added-today = 오늘 추가
browsing-addon = 확장 프로그램
browsing-again-today = 오늘 다시
browsing-all-card-types = 모든 카드 유형
browsing-all-fields = 모든 필드
browsing-answer = 답
browsing-any-cards-mapped-to-nothing-will = 어디에도 배정되지 않은 카드는 모두 삭제됩니다. 카드가 존재하지 않는 노트는 사라집니다. 계속 진행하겠습니까?
browsing-any-flag = 모든 표시
browsing-browser-appearance = 탐색기에서 표시할 때
browsing-browser-options = 탐색기 옵션
browsing-buried = 덮음
browsing-card = 카드
browsing-card-list = 카드 목록
browsing-card-state = 카드 상태
browsing-cards-cant-be-manually-moved-into = 여과된 뭉치에 카드를 수동으로 옮겨 넣을 수 없습니다.
browsing-change-deck = 뭉치 바꾸기
browsing-change-deck2 = 뭉치 바꾸기...
browsing-change-note-type = 노트 유형 바꾸기
browsing-change-note-type2 = 노트 유형 바꾸기...
browsing-change-to = '{ $val }'에서:
browsing-clear-unused = 사용되지 않은 것을 지우기
browsing-clear-unused-tags = 사용되지 않은 태그들 지우기
browsing-created = 생성
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = 현재 뭉치
browsing-current-note-type = 현재 노트 유형:
browsing-delete-notes = 노트 삭제
browsing-delete-tags = 태그 삭제
browsing-duplicate = 복제
browsing-ease = 수월함
browsing-end = 끝
browsing-enter-tags-to-add = 추가할 태그를 입력하세요:
browsing-enter-tags-to-delete = 삭제할 태그를 입력하세요:
browsing-filter = 필터...
browsing-filtered = (여과됨)
browsing-find = <b>찾을 말</b>:
browsing-find-and-replace = 바꾸기
browsing-find-duplicates = 중복된 항목 찾기
browsing-first-card = 첫째 카드
browsing-flag = 표시
browsing-font = <b>글꼴</b>:
browsing-font-size = <b>글꼴 크기</b>:
browsing-found-as-across-bs = %(a)s을 %(b)s에 걸쳐 찾았습니다.
browsing-home = 홈
browsing-ignore-case = 대소문자 무시
browsing-in = <b>대상</b>:
browsing-interval = 간격
browsing-last-card = 마지막 카드
browsing-learning = (익히는 중)
browsing-line-size = <b>줄 간격</b>:
browsing-manage-note-types = 노트 유형 관리...
browsing-move-cards = 카드 이동
browsing-move-cards-to-deck = 카드를 뭉치로 이동:
browsing-nd-names = %(n)d: %(name)s
browsing-new = (새 카드)
browsing-new-note-type = 새 노트 유형:
browsing-no-flag = 표시 없음
browsing-note = 노트
browsing-notes-tagged = 노트에 태그 설정됨.
browsing-nothing = 배정 안 함
browsing-only-new-cards-can-be-repositioned = 위치 수정은 새 카드만 가능합니다.
browsing-optional-filter = 필터 선택
browsing-override-back-template = 뒷면 서식 교체:
browsing-override-font = 글꼴 교체:
browsing-override-front-template = 앞면 서식 교체:
browsing-place-at-end-of-new-card = 새 카드 대기열의 끝으로 보내기
browsing-place-in-review-queue-with-interval = 다음 범위 안의 복습 주기를 유지한 채로 복습 대기열에 넣기:
browsing-please-give-your-filter-a-name = 이 필터에 이름을 지으세요:
browsing-please-select-cards-from-only-one = 하나의 노트 유형에 속한 카드만 선택하세요.
browsing-preview-selected-card = 선택된 카드 미리 보기 ({ $val })
browsing-question = 질문
browsing-queue-bottom = 대기열의 끝: { $val }
browsing-queue-top = 대기열의 시작: { $val }
browsing-randomize-order = 무작위 순서
browsing-remove-current-filter = 현재 사용하는 필터 지우기
browsing-remove-from-your-saved-searches = 저장된 검색에서 { $val }를 제거하시겠습니까?
browsing-remove-tags = 태그 지우기
browsing-replace-with = <b>바꿀 말</b>:
browsing-reposition = 위치 변경...
browsing-reposition-new-cards = 새 카드 위치 변경
browsing-reschedule = 일정 재조정
browsing-save-current-filter = 지금 사용한 필터를 저장...
browsing-search-in = 찾을 범위:
browsing-search-within-formatting-slow = 꾸밈 정보 안까지 찾기 (느림)
browsing-shift-position-of-existing-cards = 기존 카드의 위치 이동
browsing-sidebar = 가장자리 창
browsing-sort-field = 정렬 필드
browsing-sorting-on-this-column-is-not = 이 세로열을 기준으로 정렬할 수 없습니다. 다른 열을 선택하세요.
browsing-start-position = 시작 위치:
browsing-step = 단계:
browsing-studied-today = 오늘 공부
browsing-suspended = 보류됨
browsing-tag-duplicates = 중복된 태그
browsing-target-field = 목표 필드:
browsing-today = 오늘
browsing-toggle-mark = Mark(*) 하기
browsing-toggle-suspend = 보류하기
browsing-treat-input-as-regular-expression = 정규식으로 취급
browsing-type-here-to-search = <찾을 내용을 이 곳에 입력하세요. 이대로 엔터 키를 누르면 현재 뭉치를 표시합니다.>
browsing-whole-collection = 모음집 전체
browsing-you-must-have-at-least-one = 적어도 세로열 하나는 반드시 필요합니다.
