card-templates-changes-will-affect-notes = 변경한 내용은 이 카드 유형이 적용된 { $count }개의 노트에 반영됩니다.
card-templates-card-type = 카드 유형:
card-templates-front-template = 앞면 서식
card-templates-back-template = 뒷면 서식
card-templates-template-styling = 스타일
card-templates-front-preview = 앞면 미리보기
card-templates-back-preview = 뒷면 미리보기
card-templates-preview-box = 미리 보기
card-templates-sample-cloze = 이것은 빈칸 뚫기 { "{{c1::" }예시{ "}}" }입니다.
card-templates-night-mode = 야간 모드
card-templates-preview-settings = 옵션
card-templates-changes-saved = 변경 사항이 저장됨.
card-templates-add-card-type = 카드 형 추가...
card-templates-anki-couldnt-find-the-line-between = 질문과 답을 구분하는 선을 찾을 수 없습니다. 서식을 수동으로 수정해서 질문과 답을 바꾸세요.
card-templates-at-least-one-card-type-is = 최소한 하나의 카드 유형이 필요합니다.
card-templates-browser-appearance = 탐색기 모양...
card-templates-card = 카드 { $val }
card-templates-card-types = 카드 유형
card-templates-card-types-for = { $val }의 카드 유형
card-templates-cloze = 빈칸 뚫기 { $val }
card-templates-deck-override = 덱 전체 적용
card-templates-delete-the-as-card-type-and = '%(a)s'카드 유형과 함께, %(b)s카드를 삭제하시겠습니까?
card-templates-enter-deck-to-place-new = { $val }의 새로운 카드를 넣을 뭉치를 입력하거나, 빈 칸으로 남겨 두세요:
card-templates-enter-new-card-position-1 = 새 카드 위치를 입력하세요 (1...{ $val }):
card-templates-flip = 뒤집기
card-templates-form = 양식
card-templates-off =  (꺼짐)
card-templates-on =  (켜짐)
card-templates-remove-card-type = 카드 유형 삭제...
card-templates-rename-card-type = 카드 유형 이름 변경
card-templates-reposition-card-type = 카드 유형 위치 변경...
