decks-add-new-deck-ctrlandn = 새 뭉치 추가 (Ctrl+N)
decks-are-you-sure-you-wish-to = { $val } 뭉치를 삭제하시겠습니까?
decks-build = 모으기
decks-cards-selected-by = 카드, 선택 기준
decks-create-deck = 뭉치 만들기
decks-custom-steps-in-minutes = 맞춤 복습 주기(분 단위)
decks-deck = 뭉치
decks-decreasing-intervals = 복습 주기가 긴 것부터
decks-delete-deck = 뭉치 삭제
decks-enable-second-filter = 두 번째 필터 허용
decks-filter = 여과:
decks-filter-2 = 필터 2
decks-get-shared = 공유 뭉치 다운로드
decks-import-file = 파일 가져오기
decks-increasing-intervals = 복습 주기가 짧은 것부터
decks-latest-added-first = 나중에 추가한 것부터
decks-limit-to = 개수 제한
decks-minutes = 분
decks-most-lapses = 많이 틀린 순서대로
decks-name-for-deck = 뭉치 이름:
decks-new-deck-name = 새 뭉치 이름:
decks-no-deck = [뭉치 없음]
decks-oldest-seen-first = 처음 공부한 지 오래된 것부터
decks-order-added = 추가한 순서대로
decks-order-due = 만기 순서대로
decks-please-select-something = 무언가 선택하세요.
decks-random = 무작위로
decks-relative-overdueness = 늦은 정도의 상대값
decks-repeat-failed-cards-after = 학습 실패한 카드를 다음에 반복하기
decks-reschedule-cards-based-on-my-answers = 이 뭉치에서 선택한 답 버튼에 기반하여 카드 일정 조정
decks-study = 공부
decks-study-deck = 공부할 뭉치
decks-the-provided-search-did-not-match = 제시한 검색어에 해당하는 카드가 없습니다. 검색어를 수정하겠습니까?
