editing-add-media = 미디어 넣기
editing-an-error-occurred-while-opening = { $val }를 여는동안 에러가 발생하였습니다.
editing-attach-picturesaudiovideo-f3 = 사진/오디오/비디오 추가(F3)
editing-bold-text-ctrlandb = 볼드체(Ctrl +B)
editing-cards = 카드
editing-change-colour-f8 = 색깔 바꾸기(F8)
editing-cloze-deletion-ctrlandshiftandc = 빈칸 뚫기 (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = 오디오를 녹음할 수 없음. 'lame'을 설치하겠습니까?
editing-customize-card-templates-ctrlandl = 카드 탬플릿 맞춤 설정
editing-customize-fields = 필드 맞춤 설정
editing-cut = 잘라내기
editing-edit-current = 현재 카드 편집
editing-edit-html = HTML 편집
editing-fields = 필드
editing-html-editor = HTML 편집기
editing-italic-text-ctrlandi = 기울임꼴 (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Ctrl+Shift+T를 눌러 태그로 이동
editing-latex = LaTeX
editing-mathjax-block = MathJax 공간
editing-mathjax-chemistry = MathJax 화학
editing-mathjax-inline = MathJax 인라인
editing-media = 미디어
editing-paste = 붙여넣기
editing-record-audio-f5 = 소리 녹음하기 (F5)
editing-remove-formatting-ctrlandr = 포맷 지우기
editing-set-foreground-colour-f7 = 외향 색 설명하기
editing-show-duplicates = 중복된 항목 보기
editing-subscript-ctrland = 아래 첨자 (Ctrl+=)
editing-superscript-ctrlandand = 위 첨자 (Ctrl++)
editing-tags = 태그
editing-to-make-a-cloze-deletion-on = 이미 존재하는 노트에 빈칸 뚫기를 만들려면, 편집>노트 유형 바꾸기를 통해서 빈칸(cloze) 유형으로 먼저 바꾸어야 합니다.
editing-underline-text-ctrlandu = 밑줄 (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = 빈칸 뚫기는 화면 위쪽에서 유형을 빈칸(Cloze)으로 선택해야만 동작합니다.
