notetypes-front-field = 앞면
notetypes-back-field = 뒷면
notetypes-add-reverse-field = 반대 방향 추가
notetypes-text-field = 내용
notetypes-basic-name = 기본
notetypes-basic-reversed-name = 기본 (역방향 카드 포함)
notetypes-basic-optional-reversed-name = 기본 (선택적 역방향 카드)
notetypes-basic-type-answer-name = 기본 (답 입력)
notetypes-card-2-name = 카드 2
notetypes-card-1-name = 카드 1
