preferences-anki-21-scheduler-beta = Anki 2.1 스케쥴러 (베타)
preferences-automatically-sync-on-profile-openclose = 프로필을 열고 닫을 때 자동 동기화
preferences-backups = 백업
preferences-backups2 = 개
preferences-backupsanki-will-create-a-backup-of = <b>백업</b><br>Anki는 사용자의 모음집을 종료하거나 동기화할 때마다 백업을 만듭니다.
preferences-basic = 기본
preferences-change-deck-depending-on-note-type = 노트 유형에 따라 뭉치 바꾸기
preferences-changes-will-take-effect-when-you = 변경 사항은 앙키를 재시작한 뒤 적용됩니다.
preferences-hardware-acceleration-faster-may-cause-display = 하드웨어 가속(더 빠르지만 디스플레이 이슈가 발생할 수 있음)
preferences-hours-past-midnight = 시간 뒤
preferences-interface-language = 인터페이스 언어:
preferences-interrupt-current-audio-when-answering = 응답 할 때 현재 오디오 재생 중단
preferences-keep = 보관할 백업
preferences-learn-ahead-limit = 앞당겨 공부하기 제한
preferences-mins = 분
preferences-network = 네트워크
preferences-next-day-starts-at = 하루가 시작하는 시각은 자정으로부터
preferences-night-mode = 야간 모드
preferences-note-media-is-not-backed-up = 주의: 미디어는 백업되지 않습니다. 만약을 대비해 주기적으로 Anki 폴더를 백업하세요.
preferences-on-next-sync-force-changes-in = 다음 동기화 때, 한 방향으로만 변경 사항 적용하기
preferences-paste-clipboard-images-as-png = 클립보드에 있는 이미지를 PNG 형식으로 붙여넣기
preferences-please-restart-anki-to-complete-language = 바뀐 언어 설정을 적용하려면 Anki를 재시작해 주세요.
preferences-preferences = 환경 설정
preferences-scheduling = 일정 재조정
preferences-show-learning-cards-with-larger-steps = 복습하지 않은 긴 복습 주기의 배운 카드 보기
preferences-show-next-review-time-above-answer = 답 버튼 위에 다음 복습 시점 표시
preferences-show-play-buttons-on-cards-with = 카드에 오디오와 함께 재생 버튼 보이기
preferences-show-remaining-card-count-during-review = 남은 카드 개수를 복습 화면에 표시
preferences-some-settings-will-take-effect-after = 일부 사항은 Anki를 다시 시작한 뒤 적용됩니다.
preferences-synchronisation = <b>동기화</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>동기화</b><br> 현재 사용하지 않고 있습니다. 프로그램 기본 창에서 동기화 버튼을 눌러서 활성화하세요.
preferences-synchronize-audio-and-images-too = 오디오와 이미지 동기화
preferences-this-will-reset-any-cards-in = 이는 학습 중인 모든 카드를 초기화하고, 필터링한 덱을 지우고, 일정조절기의 버전을 바꿉니다. 진행할까요?
preferences-timebox-time-limit = 시간 제한
preferences-when-adding-default-to-current-deck = 카드를 추가할 때, 현재 뭉치에 넣음
preferences-you-can-restore-backups-via-fileswitch = 파일>프로필 전환을 통해 백업을 복구할 수 있습니다.
