scheduling-answer-button-time-seconds = { $amount }초
scheduling-answer-button-time-minutes = { $amount }분
scheduling-answer-button-time-hours = { $amount }시간
scheduling-answer-button-time-days = { $amount }일
scheduling-answer-button-time-months = { $amount }달
scheduling-answer-button-time-years = { $amount }년
scheduling-time-span-seconds = { $amount }초
scheduling-time-span-minutes = { $amount }분
scheduling-time-span-hours = { $amount }시간
scheduling-time-span-days = { $amount }일
scheduling-time-span-months = { $amount }개월
scheduling-time-span-years = { $amount }년
scheduling-congratulations-finished = 축하합니다! 현재까지 이 뭉치에서 만기된 모든 카드를 공부했습니다.
