-time-span-seconds = snidu li {$seconds}
-time-span-minutes = mentu li {$minutes}
-time-span-hours = cacra li {$hours}
-time-span-days = djedi li {$days}
-time-span-months = masti li {$months}
-time-span-years = nanca li {$years}
