profiles-anki-could-not-read-your-profile = Anki kunne ikke lese profildata. Vindustørrelser og innloggingsopplysninger for synkronisering har blitt glemt.
profiles-folder-already-exists = Mappen eksisterer allerede.
profiles-open = Åpne
profiles-open-backup = Åpne sikkerhetskopi...
profiles-please-remove-the-folder-and = Fjern denne mappen: { $val } og prøv deretter på nytt.
profiles-profile-corrupt = Profilen er ødelagt
profiles-profiles = Profiler
profiles-quit = Avslutt
profiles-user-1 = Bruker 1
profiles-confirm-lang-choice = Ønsker du å vise Ankis grensesnitt i språket { $lang }?
profiles-could-not-create-data-folder = Anki kunne ikke opprette sin datamappe. Se delen om "Filplasseringer" i bruksanvisningen og vær sikker på at plasseringen ikke er skrivebeskyttet.
profiles-prefs-corrupt-title = Preferanser er ødelagt
profiles-prefs-file-is-corrupt = Ankis prefs21.db-fil var ødelagt og har blitt opprettet på nytt. Om du brukte flere profiler, må du legge dem tilbake med de samme navnene for å gjenopprette kortene dine.
profiles-profile-does-not-exist = Den etterspurte profilen finnes ikke.
profiles-creating-backup = Oppretter en sikkerhetskopi...
profiles-backup-created = Sikkerhetskopi opprettet.
profiles-backup-creation-failed = En feil oppstod ved opprettelsen av sikkerhetskopi: { $reason }
profiles-backup-unchanged = Ingen endringer foretatt siden forrige sikkerhetskopi.
