browsing-add-notes = Adde notas
browsing-add-tags = Adde indicia
browsing-add-tags2 = Add indicia...
browsing-added-today = Hodie additum esse
browsing-again-today = Hodie rursus
browsing-all-card-types = Omnes generes cartae
browsing-all-fields = Omnes tabulae
browsing-answer = Responsum
browsing-find = <b>Reperi</b>:
browsing-font = <b>Forma litterae</b>:
browsing-font-size = <b>Magnitudo formae litterae</b>:
browsing-line-size = <b>Longitudo lineae</b>:
browsing-new = (novum)
browsing-replace-with = <b>Substitue ab </b>:
