database-check-corrupt = Файл калекцыі пашкоджаны. Аднавіце яго з аўтаматычнай рэзервовай копіі.
database-check-rebuilt = База даных перасобрана і аптымізавана.

## Progress info

database-check-checking-integrity = Праверка калекцыі...
database-check-rebuilding = Перазборка...
database-check-checking-cards = Праверка картак...
database-check-checking-notes = Праверка нататак...
database-check-checking-history = Праверка гісторыі...
database-check-title = Праверыць базу даных
