decks-add-new-deck-ctrlandn = Дадаць новую калоду (Ctrl+N)
decks-build = Сабраць
decks-create-deck = Стварыць калоду
decks-custom-steps-in-minutes = Наладжвальныя крокі (у хвілінах)
decks-deck = Калода
decks-decreasing-intervals = Інтэрвалы з памяншэннем
decks-delete-deck = Выдаліць калоду
decks-enable-second-filter = Уключыць другі фільтр
decks-filter = Фільтр:
decks-filter-2 = Фільтр 2
decks-import-file = Імпартаваць файл
decks-limit-to = Абмежаваць да
decks-minutes = хвілін
decks-most-lapses = Найбольш недаглядаў
decks-new-deck-name = Новая назва калоды:
decks-no-deck = [няма калоды]
decks-order-added = У парадку дадавання
decks-please-select-something = Выберыце нешта.
decks-random = Выпадковы
decks-study = Вучыць
decks-study-deck = Вучыць калоду
