preferences-automatically-sync-on-profile-openclose = Аўтаматычна сінхранізаваць пры адкрыцці/закрыцці профілю
preferences-backups = Рэзервовыя копіі
preferences-basic = Асноўнае
preferences-change-deck-depending-on-note-type = Змяніць калоду ў залежнасці ад тыпу нататкі
preferences-changes-will-take-effect-when-you = Змены набудуць моц, калі вы перазапусціце Anki.
preferences-interface-language = Мова інтэрфейсу:
preferences-interrupt-current-audio-when-answering = Перарываць аўдыя падчас адказу
preferences-mins = хв.
preferences-network = Сетка
preferences-next-day-starts-at = Наступны дзень пачынаецца а
preferences-on-next-sync-force-changes-in = Пры наступнай сінхранізацыі прымусіць да зменаў у адным кірунку
preferences-paste-clipboard-images-as-png = Устаўляць відарысы з буферу абмену як PNG
preferences-paste-without-shift-key-strips-formatting = Устаўка без клавішы Shift пазбаўляе фарматавання
preferences-periodically-sync-media = Перыядычна сінхранізаваць медыя
preferences-please-restart-anki-to-complete-language = Перазапусціце Anki, каб завяршыць змену мовы.
preferences-preferences = Параметры
preferences-scheduling = Планаванне
preferences-synchronisation = <b>Сінхранізацыя</b>
preferences-synchronize-audio-and-images-too = Сінхранізаваць таксама аўдыя і відарысы
preferences-user-interface-size = Памер інтэрфейсу
preferences-when-adding-default-to-current-deck = Перадвызначана дадаваць да бягучай калоды
preferences-you-can-restore-backups-via-fileswitch = Вы можаце аднавіць рэзервовую копію праз «Файл > Пераключыць профіль».
preferences-default-search-text = Тэкст пошуку па змаўчанні
preferences-default-search-text-example = напр. «deck:current »
preferences-theme-label = Тэма: { $theme }
preferences-theme-follow-system = Прытрымлівацца сістэмнай
preferences-theme-light = Светлая
preferences-theme-dark = Цёмная
preferences-v3-scheduler = Планіроўшчык V3
