profiles-folder-already-exists = Папка ужо існуе.
profiles-open = Адкрыць
profiles-open-backup = Адкрыць рэзервовую копію...
profiles-please-remove-the-folder-and = Выдаліце папку { $val } і паспрабуйце зноў.
profiles-profile-corrupt = Профіль пашкоджаны
profiles-profiles = Профілі
profiles-quit = Выйсці
profiles-user-1 = Карыстальнік 1
profiles-confirm-lang-choice = Вы ўпэўнены, што хочаце пераключыць адлюстраванне інтэрфейсу Anki на { $lang }?
profiles-could-not-create-data-folder = Anki не змагла стварыць папку сваіх даных. Праглядзіце секцыю «Размяшчэнне файла» у дапаможніку і пераканайцеся, што размяшчэнне не «толькі для чытання».
profiles-prefs-corrupt-title = Параметры пашкоджаны
profiles-prefs-file-is-corrupt = Файл Anki prefs21.db быў пашкоджаны і створаны нанава. Калі вы выкарыстоўвалі некалькі профіляў, дадайце іх назад з тымі ж назвамі, каб аднавіць вашы карткі.
profiles-profile-does-not-exist = Запытаны профіль не існуе.
profiles-creating-backup = Стварэнне рэзервовай копіі...
profiles-backup-created = Рэзервовая копія створана.
profiles-backup-creation-failed = Не ўдалося стварыць рэзервовую копію: { $reason }
profiles-backup-unchanged = Няма змен з апошняй рэзервовай копіі.
