profiles-folder-already-exists = Папка ужо існуе.
profiles-open = Адкрыць
profiles-open-backup = Адкрыць рэзервовую копію...
profiles-please-remove-the-folder-and = Выдаліце папку { $val } і паспрабуйце зноў.
profiles-profile-corrupt = Профіль пашкоджаны
profiles-profiles = Профілі
profiles-quit = Выйсці
profiles-user-1 = Карыстальнік 1
profiles-confirm-lang-choice = Вы ўпэўнены, што хочаце пераключыць адлюстраванне інтэрфейсу Anki на { $lang }?
profiles-prefs-corrupt-title = Параметры пашкоджаны
profiles-profile-does-not-exist = Запытаны профіль не існуе.
