studying-again = Зноў
studying-all-buried-cards = Усе адкладзеныя карткі
studying-audio-5s = Аўдыя -5 с
studying-audio-and5s = Аўдыя +5 с
studying-buried-siblings = Адкладзеныя сястрынскія
studying-bury = Адкласці
studying-bury-card = Адкласці картку
studying-bury-note = Адкласці нататку
studying-card-suspended = Картка прыпынена.
studying-continue = Працягнуць
studying-delete-note = Выдаліць нататку
studying-easy = Лёгка
studying-edit = Рэдагаваць
studying-empty = Ачысціць
studying-finish = Скончыць
studying-flag-card = Дадаць сцяжок да карткі
studying-good = Добра
studying-hard = Цяжка
studying-it-has-been-suspended = Была прыпынена.
studying-manually-buried-cards = Адкладзеныя ўручную карткі
studying-mark-note = Пазначыць нататку
studying-more = Больш
studying-no-cards-are-due-yet = Няма картак на сёння.
studying-note-suspended = Нататка прыпынена.
studying-pause-audio = Прыпыніць аўдыя
studying-show-answer = Паказаць адказ
studying-space = Прабел
studying-study-now = Вучыць зараз
studying-suspend = Прыпыніць
studying-suspend-note = Прыпыніць нататку
studying-to-review = Да перагляду
studying-type-answer-unknown-field = Увядзіце адказ: невядомае поле { $val }
studying-unbury = Вярнуць
studying-what-would-you-like-to-unbury = Што вы хочаце вярнуць?
