studying-easy = Лёгка
studying-edit = Рэдагаваць
studying-good = Добра
studying-hard = Цяжка
studying-it-has-been-suspended = Была прыпынена.
studying-manually-buried-cards = Адкладзеныя ўручную карткі
studying-more = Больш
studying-space = Прабел
studying-unbury = Вярнуць
studying-what-would-you-like-to-unbury = Што вы хочаце вярнуць?
