adding-add-shortcut-ctrlandenter = เพิ่ม (คีย์ลัด: ctrl+enter)
adding-added = เพิ่มแล้ว
adding-discard-current-input = ทิ้งข้อมูลที่กรอกไว้?
adding-keep-editing = แก้ไขต่อ
adding-edit = แก้ไข "{ $val }"
adding-history = ประวัติ
adding-note-deleted = (โน้ตถูกลบแล้ว)
adding-shortcut = ทางลัด: { $val }
adding-the-first-field-is-empty = ช่องข้อมูลแรกว่างเปล่า
