browsing-add-notes = เพิ่มโน้ต...
browsing-add-tags2 = เพิ่มแท็ก...
browsing-all-fields = ช่องข้อมูลทั้งหมด
browsing-answer = คำตอบ
browsing-average-interval = ระยะเวลาเฉลี่ย
browsing-card = การ์ด
browsing-cards = การ์ด
browsing-card-list = รายการการ์ด
browsing-cards-deleted = การ์ด { $count } ใบถูกลบแล้ว
browsing-cards-deleted-with-deckname = การ์ด { $count } ใบถูกลบจาก { $deck_name } แล้ว
browsing-change-deck = เปลี่ยนสำรับ
browsing-change-deck2 = เปลี่ยนสำรับ...
browsing-change-note-type = เปลี่ยนประเภทโน้ต
# Action in a context menu (right mouse-click on a card type)
browsing-change-note-type2 = เปลี่ยนประเภทโน้ต...
browsing-change-notetype = เปลี่ยนประเภทโน้ต
browsing-clear-unused-tags = ลบแท็กที่ไม่ได้ใช้
browsing-created = สร้างเมื่อ
browsing-current-deck = สำรับปัจจุบัน
browsing-current-note-type = ประเภทโน้ตปัจจุบัน:
browsing-delete-notes = ลบโน้ต
browsing-duplicate = ซ้ำ
browsing-enter-tags-to-add = ใส่แท็กที่จะเพิ่ม:
browsing-enter-tags-to-delete = ใส่แท็กที่จะลบ:
browsing-find = <b>ค้นหา</b>:
browsing-find-and-replace = ค้นหาและแทนที่
browsing-find-duplicates = ค้นหาโน้ตซ้ำ
browsing-first-card = การ์ดใบแรก
browsing-flag = ธง
browsing-interval = ช่วงเวลา
browsing-last-card = การ์ดใบสุดท้าย
browsing-learning = (กำลังเรียน)
browsing-line-size = <b>ขนาดบรรทัด</b>:
browsing-manage-note-types = จัดการประเภทโน้ต
browsing-move-cards = ย้ายการ์ด
browsing-move-cards-to-deck = ย้ายการ์ดไปที่สำรับ:
browsing-new = (ใหม่)
browsing-new-note-type = ประเภทโน้ตใหม่:
browsing-no-flag = ไม่มีธง
browsing-no-selection = ไม่มีการ์ดหรือโน้ตที่ถูกเลือกอยู่
browsing-note = โน้ต
browsing-notes = โน้ต
browsing-please-give-your-filter-a-name = กรุณาตั้งชื่อตัวกรอง:
browsing-question = คำถาม
browsing-randomize-order = สุ่มลำดับ
browsing-remove-tags = นำแท็กออก...
browsing-replace-with = <b>แทนที่ด้วย</b>:
browsing-reposition = เปลี่ยนตำแหน่ง...
browsing-search-bar-hint = ค้นหาการ์ด/โน้ต (พิมพ์ข้อความ แล้วกด Enter)
browsing-search-in = ค้นหาใน:
browsing-select-deck = เลือกสำรับ
browsing-selected-notes-only = โน้ตที่เลือกเท่านั้น
browsing-suspended = ถูกแขวนแล้ว
browsing-group = { $count } กลุ่ม
browsing-note-count = { $count } โน้ต
browsing-sidebar-expand = ขยาย
browsing-sidebar-collapse = ย่อ
browsing-sidebar-decks = สำรับ
browsing-sidebar-tags = แท็ก
browsing-sidebar-notetypes = ประเภทโน้ต
browsing-sidebar-save-current-search = บันทึกการค้นหาปัจจุบัน
browsing-sidebar-card-state = สถานะการ์ด
browsing-sidebar-flags = ธง
browsing-today = วันนี้
browsing-studied-today = เรียนแล้ว
browsing-added-today = เพิ่มแล้ว
browsing-again-today = อีกครั้ง
browsing-edited-today = แก้ไขแล้ว
browsing-sidebar-first-review = ทบทวนครั้งแรก
browsing-row-deleted = (ลบแล้ว)
browsing-removed-unused-tags-count = ลบแท็กที่ไม่ได้ใช้ { $count } แท็กแล้ว
browsing-reparented-decks = เปลี่ยนชื่อสำรับ { $count } ชุดแล้ว
browsing-sidebar-card-state-review = บทวิจารณ์

## NO NEED TO TRANSLATE. This text is no longer used by Anki, and will be removed in the future.

