## Progress info

database-check-checking-cards = ตรวจสอบการ์ด...
database-check-checking-notes = ตรวจสอบโน้ต...
database-check-checking-history = ตรวจสอบประวัติ...
database-check-title = ตรวจสอบฐานข้อมูล
