actions-add = Dodaj
actions-cancel = Prekliči
actions-choose = Izberi
actions-close = Zapri
actions-copy = Kopiraj
actions-custom-study = Študij po meri
actions-decks = Zbirke kartic
actions-delete = Izbriši
actions-export = Izvoz
actions-help = Pomoč
actions-import = Uvoz
actions-name = Ime:
actions-new = Novo
actions-new-name = Novo ime:
actions-options = Možnosti
actions-options-for = Možnosti za { $val }
actions-rebuild = Ponovno zgradi
actions-rename = Preimenuj
actions-rename-deck = Preimenuj paket
actions-replay-audio = Znova predvajaj zvok
actions-reposition = Prestavi
actions-search = Iskanje
actions-shortcut-key = Bližnjica: { $val }
actions-suspend-card = Odloži kartico
