browsing-add-tags = Dodaj oznake
browsing-added-today = Dodano danes
browsing-again-today = Ponovno danes
browsing-all-fields = Vsa polja
browsing-any-cards-mapped-to-nothing-will = Vse kartice, ki niso povezane, bodo izbrisane. Če zapisek ne vsebuje nobene kartice več, bo izbrisan. Želite vseeno nadaljevati?
browsing-browser-options = Možnosti brskalnika
browsing-card = Kartica
browsing-card-list = Seznam kartic
browsing-cards-cant-be-manually-moved-into = Kartic ni možno ročno dodati v filtriran paket.
browsing-change-deck = Spremeni zbirko kartic
browsing-change-note-type = Spremeni tip zapiska
browsing-change-note-type2 = Spremeni tip zapiska...
browsing-change-to = Spremeni { $val } v:
browsing-created = Ustvarjeno
browsing-current-deck = Trenutna zbirka kartic
browsing-current-note-type = Trenutni tip zapiska:
browsing-delete-notes = Izbriši zapiske
browsing-delete-tags = Izbriši oznake
browsing-end = Konec
browsing-enter-tags-to-add = Vnesite oznake za dodajanje:
browsing-enter-tags-to-delete = Vnesite oznake za brisanje:
browsing-filtered = (filtrirano)
browsing-find = <b>Poišči</b>:
browsing-find-and-replace = Najdi in zamenjaj
browsing-find-duplicates = Poišči dvojnike
browsing-first-card = Prva kartica
browsing-font = <b>Pisava</b>:
browsing-font-size = <b>Velikost pisave</b>:
browsing-found-as-across-bs = Najdenih %(a)s čez %(b)s.
browsing-home = Domov
browsing-ignore-case = Velikost črk ni pomembna
browsing-in = <b>V</b>
browsing-last-card = Zadnja kartica
browsing-learning = (v fazi učenja)
browsing-line-size = <b>Velikost črte</b>
browsing-move-cards = Premakni kartice
browsing-move-cards-to-deck = Premakni kartice v zbirko:
browsing-new = (nova)
browsing-new-note-type = Nov tip zapiska:
browsing-note = Zapisek
browsing-nothing = Nič
browsing-only-new-cards-can-be-repositioned = Prerazporedite lahko samo nove kartice.
browsing-place-at-end-of-new-card = Prestavi na konec čakalne vrste kartic
browsing-place-in-review-queue-with-interval = Prestavi v čakalno vrsto za pregled z intervalom med:
browsing-please-select-cards-from-only-one = Izberite kartice samo enega tipa zapiskov.
browsing-queue-bottom = Dno čakalne vrste: { $val }
browsing-queue-top = Vrh čakalne vrste: { $val }
browsing-randomize-order = Naključno uredi
browsing-replace-with = <b>Zamenjaj z</b>:
browsing-reposition = Prestavi...
browsing-reposition-new-cards = Prestavi nove kartice
browsing-reschedule = Določi nov razpored
browsing-search-within-formatting-slow = Išči v oblikovanju (počasno)
browsing-shift-position-of-existing-cards = Zamakni položaj obstoječih kartic.
browsing-sort-field = Polje za urejanje
browsing-sorting-on-this-column-is-not = Urejanje po tem stolpcu ni podprto. Izberite drug stolpec.
browsing-start-position = Začetni položaj:
browsing-step = Korak:
browsing-studied-today = Naučene danes
browsing-target-field = Ciljno polje:
browsing-today = Danes
browsing-treat-input-as-regular-expression = Obravnavaj vnos kot običajno izjavo
browsing-type-here-to-search = <vnesite sem, če želite poiskati; pritisnite enter za prikaz trenutnega paketa>
browsing-whole-collection = Celotna zbirka
browsing-you-must-have-at-least-one = Imeti morate vsaj en stolpec.
