card-stats-first-review = Prvi pregled
card-stats-latest-review = Zadnji pregled
card-stats-average-time = Povprečni čas
card-stats-total-time = Skupni čas
card-stats-new-card-position = Položaj
card-stats-card-template = Tip kartice
card-stats-note-type = Tip zapiska
card-stats-review-log-rating = Ocena
card-stats-review-log-type = Tip
card-stats-review-log-date = Datum
card-stats-review-log-time-taken = Čas
card-stats-review-log-type-filtered = Filtrirano
card-stats-review-log-type-rescheduled = Prerazporedi
