card-templates-front-template = Predloga prednje strani
card-templates-back-template = Predloga zadnje strani
card-templates-template-styling = Stiliziranje
card-templates-front-preview = Predogled pisave
card-templates-back-preview = Predogled zadnje strani
card-templates-anki-couldnt-find-the-line-between = Povezave med vprašanjem in odgovorom ni bilo mogoče najti. Za zamenjavo vprašanja in odgovora ročno prilagodite predlogo.
card-templates-card = Kartica { $val }
card-templates-card-types = Tipi kartic
card-templates-card-types-for = Tipi kartic za { $val }
card-templates-cloze = Zapri
card-templates-enter-deck-to-place-new = Uredite zbirko, da umestite { $val } novih kartic ali pustite prazno:
card-templates-enter-new-card-position-1 = Vnesite mesto nove kartice (1...{ $val }):
card-templates-flip = Obrni
card-templates-form = Oblika
card-templates-off =  (izklopljeno)
card-templates-on =  (vklopljeno)
