custom-study-cards = kartice
custom-study-custom-study-session = Učna ura po meri
custom-study-increase-todays-new-card-limit = Povečaj omejitev današnjih novih kartic
custom-study-increase-todays-new-card-limit-by = Povečaj omejitev današnjih novih kartic za
custom-study-increase-todays-review-card-limit = Povečaj omejitev današnjih kartic za pregled
custom-study-increase-todays-review-limit-by = Povečaj omejitev današnjih kartic za pregled za
custom-study-no-cards-matched-the-criteria-you = Glede na kriterije, ki ste jih vnesli, ni mogoče najti nobene kartice.
custom-study-preview-new-cards = Predogled novih kartic
custom-study-preview-new-cards-added-in-the = Predogled novih kartic dodanih v zadnjem
custom-study-require-one-or-more-of-these = Zahtevaj eno ali več od naslednjih oznak:
custom-study-review-ahead = Preglej naprej
custom-study-review-ahead-by = Preglej naprej za
custom-study-review-cards-forgotten-in-last = Preglej pozabljene kartice v zadnjih
custom-study-review-forgotten-cards = Preglej pozabljene kartice
custom-study-select = Izberi
custom-study-select-tags-to-exclude = Izberite oznake, ki naj bodo izključene:
custom-study-selective-study = Študij po izbiri
