decks-add-new-deck-ctrlandn = Dodaj nov paket (Ctrl+N)
decks-are-you-sure-you-wish-to = Ali ste prepričani, da želite izbrisati { $val }?
decks-build = Zgradi
decks-cards-selected-by = kartice izbrane od
decks-create-deck = Ustvari paket
decks-decreasing-intervals = Padajoči intervali
decks-delete-deck = Izbriši zbirko kartic
decks-get-shared = Naloži javne zbirke
decks-import-file = Uvozi datoteko
decks-increasing-intervals = Vedno večji intervali
decks-latest-added-first = Najnovejše dodane prve
decks-limit-to = Omeji na
decks-minutes = minute
decks-most-lapses = Največ spodrsljajev
decks-new-deck-name = Novo ime zbirke:
decks-no-deck = [ni paketa]
decks-oldest-seen-first = Najprej vidne najstarejše
decks-order-added = Uredi dodane
decks-order-due = Uredi zapadle
decks-please-select-something = Izberite nekaj.
decks-random = Naključno
decks-reschedule-cards-based-on-my-answers = Prerazporedi kartice glede na moje odgovore v tem paketu
decks-study = Študiraj
decks-study-deck = Paket za učenje
decks-the-provided-search-did-not-match = Izraz za iskanje ni našel nobenih kartic. Bi ga radi popravili?
