exporting-all-decks = Vsi paketi
exporting-anki-20-deck = Paket Anki 2.0
exporting-anki-deck-package = Anki paket
exporting-collection = zbirka
exporting-couldnt-save-file = Datoteke { $val } ni bilo mogoče shraniti
exporting-export = Izvozi ...
exporting-export-format = <b>Izvozi format</b>:
exporting-include = <b>Vključi</b>:
exporting-include-media = Vključi medijske datoteke
exporting-include-scheduling-information = Vključi podatke za časovno planiranje
exporting-include-tags = Vključi oznake
exporting-notes-in-plain-text = Zapiski v golem besedilu
