fields-add-field = Dodaj polje
fields-delete-field-from = Izbrišem polje iz { $val }?
fields-editing-font = Urejanje pisave
fields-field = Polje:
fields-field-name = Ime polja:
fields-fields-for = Polja za { $val }
fields-font = Pisava:
fields-new-position-1 = Novo mesto (1...{ $val }):
fields-notes-require-at-least-one-field = Zapiski zahtevajo vsaj eno polje.
fields-remember-last-input-when-adding = Zapomni si zadnji vnos med dodajanjem
fields-reverse-text-direction-rtl = Obratna smer besedila (RTL)
fields-size = Velikost:
fields-sort-by-this-field-in-the = Uredi po tem polju v brskalniku
fields-that-field-name-is-already-used = To ime polja je že uporabljeno.
