notetypes-add-reverse-field = Dodaj obratno
notetypes-text-field = Besedilo
notetypes-basic-reversed-name = Osnovna (in obrnjena kartica)
notetypes-basic-optional-reversed-name = Osnovna (in izbirno obrnjena kartica)
notetypes-cloze-name = Zapri
notetypes-card-2-name = Kartica 2
notetypes-card-1-name = Kartica 1
notetypes-add = Dodaj: { $val }
notetypes-add-note-type = Dodaj tip zapiska
notetypes-cards = Kartice...
notetypes-clone = Podvoji: { $val }
notetypes-copy = Kopija { $val }
notetypes-delete-this-note-type-and-all = Izbrišem ta tip zapiska in vse povezane kartice?
notetypes-delete-this-unused-note-type = Izbrišem ta neuporabljen tip zapiska?
notetypes-fields = Polja...
notetypes-footer = &Noga
notetypes-header = Glava
notetypes-note-types = Tipi zapiskov
notetypes-options = Možnosti...
notetypes-please-add-another-note-type-first = Najprej dodajte tip zapiska.
notetypes-type = Tip
