preferences-automatically-sync-on-profile-openclose = Pri odpiranju/zapiranju profila samodejno sinhroniziraj
preferences-backups = Varnostne kopije
preferences-backups2 = varnostne kopije
preferences-backupsanki-will-create-a-backup-of = <b>Varnostne kopije</b><br>Anki bo izdelal varnostno kopijo vaše zbirke vsakič, ko se program zapre ali ko se sinhronizirajo podatki.
preferences-change-deck-depending-on-note-type = Spremeni paket glede na tip zapiska
preferences-hours-past-midnight = ur od polnoči
preferences-interface-language = Jezik vmesnika:
preferences-keep = Obdrži
preferences-learn-ahead-limit = Omejitev učenja vnaprej
preferences-mins = minut
preferences-network = Omrežje
preferences-next-day-starts-at = Naslednji dan se začne ob
preferences-note-media-is-not-backed-up = Opozorilo: Medijske datoteke nimajo varnostne kopije. Priporočamo, da občasno naredite varnostno kopijo mape Anki.
preferences-paste-clipboard-images-as-png = Prilepi slike z odložišča kot PNG
preferences-preferences = Možnosti
preferences-scheduling = Določi nov razpored
preferences-show-next-review-time-above-answer = Pokaži čas za naslednji pregled nad gumbi za odgovore
preferences-show-remaining-card-count-during-review = Pokaži število preostalih kartic med pregledom
preferences-some-settings-will-take-effect-after = Nekatere nastavitve bodo pričele delovati po ponovnem zagonu Ankija.
preferences-synchronisation = <b>Sinhronizacija</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sinhronizacija</b><br> Ni trenutno omogočena; Omogočite jo s klikom na gumb Sinhroniziraj v glavnem oknu.
preferences-synchronize-audio-and-images-too = Sinhroniziraj tudi zvok in slike
preferences-timebox-time-limit = Časovna omejitev
preferences-when-adding-default-to-current-deck = Med dodajanjem naj bo privzet trenutni paket
