studying-again = Znova
studying-bury = Umakni
studying-bury-note = Skrij zapisek
studying-card-was-a-leech = Kartica je bila pijavka.
studying-cards-will-be-automatically-returned-to = Kartice bodo samodejno vrnjene v izvirne pakete, ko jih boste pregledali.
studying-delete-note = Izbriši zapisek
studying-deleting-this-deck-from-the-deck = Izbris tega paketa iz seznama paketov bo vrnil vse preostale kartice v njihove izvorne pakete.
studying-easy = Enostavno
studying-edit = Uredi
studying-empty = Prazno
studying-good = Dobro
studying-hard = Zahtevno
studying-it-has-been-suspended = Je bila odložena.
studying-more = Dodatno
studying-note-buried = Zapisek skrit.
studying-note-suspended = Zapisek odložen.
studying-record-own-voice = Posnemi svoj glas
studying-replay-own-voice = Znova predvajaj svoj glas
studying-show-answer = Prikaži odgovor
studying-space = Razmik
studying-study-now = Študiraj sedaj
studying-suspend = Odloži
studying-suspend-note = Odloži zapisek
studying-this-is-a-special-deck-for = Ta poseben paket je namenjen za učenje zunaj običajnega urnika.
studying-to-review = Za pregled
studying-type-answer-unknown-field = Vnesi odgovor: neznano polje { $val }
studying-you-havent-recorded-your-voice-yet = Niste še posneli svojega glasu.
