actions-add = Afegeix
actions-blue-flag = Marca blava
actions-cancel = Anuŀla
actions-choose = Tria
actions-close = Tanca
actions-copy = Copia
actions-custom-study = Estudi personalitzat
actions-decks = Piles
actions-delete = Elimina
actions-export = Exporta
actions-filter = Filtre
actions-green-flag = Marca verda
actions-help = Ajuda
actions-import = Importa
actions-manage = Gestionar…
actions-name = Nom:
actions-new = Nou
actions-new-name = Nou nom:
actions-options = Opcions
actions-options-for = Opcions per { $val }.
actions-orange-flag = Bandera Taronja
actions-preview = Previsualització
actions-rebuild = Reconstrueix
actions-red-flag = Marca vermella
actions-rename = Reanomena
actions-rename-deck = Canviar el nom del mall
actions-rename-tag = Renombrar Etiquets
actions-remove-tag = Eliminar Etiqueta
actions-replay-audio = Reprodueix só
actions-reposition = Reposició
actions-save = Guardar
actions-search = Cercar
actions-shortcut-key = Tecla de drecera: { $val }
actions-suspend-card = Suspendre targeta
