browsing-add-notes = Afegei Notes...
browsing-add-tags = Afegeix etiquetes
browsing-add-tags2 = Afegeix etiquetes...
browsing-added-today = Afegides avui
browsing-addon = Complement
browsing-again-today = De nou avui
browsing-all-card-types = Tots els tipus de targetes
browsing-all-fields = Tots els camps
browsing-answer = Resposta
browsing-any-cards-mapped-to-nothing-will = Totes les targetes no assignades s'eliminaran. Si una nota no té cap targeta assignada, es perdrà. Segur que vols continuar?
browsing-any-flag = Qualsevol marca
browsing-browser-appearance = Aspecte del navegador
browsing-browser-options = Opcions del navegador
browsing-buried = Enterrades
browsing-card = Targeta
browsing-card-list = Llista de targetes
browsing-card-state = Estat de tarjeta
browsing-cards-cant-be-manually-moved-into = Les targetes no es poden moure manualment a un mall filtrat.
browsing-change-deck = Canviar de mall
browsing-change-deck2 = Canviar mall...
browsing-change-note-type = Canvia tipus de nota
browsing-change-note-type2 = Canvia tipus de nota...
browsing-change-to = Canvia { $val } a:
browsing-clear-unused = Eliminar les no utilitzades
browsing-clear-unused-tags = Neteja etiquetes no utilitzades
browsing-created = S'ha afegit
browsing-ctrlandshiftande = Ctrl+Shift+E
browsing-current-deck = Mall actual
browsing-current-note-type = Tipus de nota actual:
browsing-delete-notes = Elimina les notes
browsing-delete-tags = Elimina les etiquetes
browsing-duplicate = duplicat
browsing-ease = Facilitat
browsing-end = Acabar
browsing-enter-tags-to-add = Entreu les etiquetes que voleu afegir:
browsing-enter-tags-to-delete = Entreu les etiquetes que voleu suprimir:
browsing-filter = Filtrar...
browsing-filtered = (filtrat)
browsing-find = <b>Cerca</b> :
browsing-find-and-replace = Cerca i reemplaça
browsing-find-duplicates = Cerca duplicats
browsing-first-card = Primera targeta
browsing-flag = Marcar
browsing-font = <b>Lletra</b>:
browsing-font-size = <b>Mida de la lletra</b>:
browsing-found-as-across-bs = S'han trobat %(a)s d'entre %(b)s.
browsing-home = Inici
browsing-ignore-case = Ignoreu les majúscules
browsing-in = <b>A</b> :
browsing-interval = Interval
browsing-last-card = Última targueta
browsing-learning = (aprenent)
browsing-line-size = <b>Mida de la línia</b>:
browsing-manage-note-types = Gestiona els Tipus de Nota...
browsing-move-cards = Moure cartes
browsing-move-cards-to-deck = Moure les cartes al mall:
browsing-nd-names = %(n)d: %(name)s
browsing-new = (nou)
browsing-new-note-type = Nou tipus de nota
browsing-no-flag = Sense Marca
browsing-note = Nota
browsing-notes-tagged = Notes etiquetades.
browsing-nothing = Res
browsing-only-new-cards-can-be-repositioned = Només les cartes noves poden ser reposicionades.
browsing-optional-filter = Filtre opcional:
browsing-override-back-template = Substitueix plantilla del revers:
browsing-override-font = Substitueix font:
browsing-override-front-template = SObreescriute la plantilla del anvers.
browsing-place-at-end-of-new-card = Col·locar al final de la cua de targetes noves
browsing-place-in-review-queue-with-interval = Col·locar en la cua de repàs amb intervals entre:
browsing-please-give-your-filter-a-name = Sisplau, anomena el filtre:
browsing-please-select-cards-from-only-one = Sisplau, selecicona targetes d'un sol tipus de nota.
browsing-preview-selected-card = Previsualitzar la targueta seleccionada ({ $val })
browsing-question = Pregunta
browsing-queue-bottom = Últim de la cua: { $val }
browsing-queue-top = Primer de la cua: { $val }
browsing-randomize-order = Ordre aleatòri
browsing-remove-current-filter = Eliminar filtre actual...
browsing-remove-from-your-saved-searches = ¿Eliminar { $val } de les teves cerques guardades?
browsing-remove-tags = Eliminar etiquetes...
browsing-replace-with = <b>Substitueix per</b>:
browsing-reposition = Reposicionar...
browsing-reposition-new-cards = Reposicionar noves targetes
browsing-reschedule = Torna a planificar
browsing-save-current-filter = Guardar el filtre actual...
browsing-search-in = Buscar en :
browsing-search-within-formatting-slow = Buscar en elements de format (lent)
browsing-shift-position-of-existing-cards = Canviar la posició de les targetes existents
browsing-sidebar = Barra lateral
browsing-sort-field = Camp ordenat
browsing-sorting-on-this-column-is-not = No és possible canviar l'ordre en aquesta columna. Si us plau, tria una altra.
browsing-start-position = Posició inicial:
browsing-step = Pas:
browsing-studied-today = Estudiades avui.
browsing-suspended = Suspès
browsing-tag-duplicates = Etiquetar duplicats
browsing-target-field = Camp destí:
browsing-today = Avui
browsing-toggle-mark = Commuta Marcar
browsing-toggle-suspend = Commuta Suspendre
browsing-treat-input-as-regular-expression = Tracta l'entrada com una expressió regular
browsing-type-here-to-search = <escriu aquí per cercar; prem la tecla de retorn per veure el mall actual>
browsing-whole-collection = Col·lecció sencera
browsing-you-must-have-at-least-one = Hi ha d'haver almenys una columna.
