card-stats-added = Apondut
card-stats-first-review = Primièra revision
card-stats-latest-review = Revision ultime
card-stats-interval = Intervallo
card-stats-ease = Facile
card-stats-review-count = Revisions
card-stats-lapse-count = Caditas
card-stats-average-time = Durada mejana
card-stats-total-time = Durada totala
card-stats-new-card-position = Posició
card-stats-card-template = Tipe de carta
card-stats-note-type = Typo de nota
card-stats-deck-name = Paquet
card-stats-note-id = ID de nota
card-stats-card-id = Identificant carta
card-stats-review-log-rating = Valor
card-stats-review-log-type = Inserer
card-stats-review-log-date = Data
card-stats-review-log-time-taken = Tempore
card-stats-review-log-type-learn = Apprender
card-stats-review-log-type-review = Contrarotlar
card-stats-review-log-type-relearn = Reapprender
card-stats-review-log-type-filtered = Filtrate
card-stats-review-log-type-rescheduled = Re-programmation
