custom-study-must-rename-deck = Si us plau, canvieu primer el nom del mall de l'Estudi Personalitzat existent.
custom-study-all-cards-in-random-order-dont = Totes les targetes en ordre aleatori (sense reprogramar)
custom-study-all-review-cards-in-random-order = Totes les cargetes per repasar en ordre aleatori
custom-study-cards = targetes
custom-study-cards-from-the-deck = targetes del mall
custom-study-choose-tags = Escull etiquetes
custom-study-custom-study-session = Sessió d'estudi personalitzada
custom-study-due-cards-only = Només targetes programades.
custom-study-increase-todays-new-card-limit = Incrementa el límit per cartes noves d'avui
custom-study-increase-todays-new-card-limit-by = Incrementa el límit per cartes noves d'avui per
custom-study-increase-todays-review-card-limit = Augmentar el ímit de repassos per avui
custom-study-increase-todays-review-limit-by = Augmentar el ímit de repassos d'avui en
custom-study-new-cards-in-deck-over-today = Targetes noves en el mall per sobre del limit d'avui: { $val }
custom-study-new-cards-only = Només noves cartes
custom-study-no-cards-matched-the-criteria-you = No hi ha cap targeta que sadisfaci el criteri que has proporcionat.
custom-study-ok = D'acord
custom-study-preview-new-cards = Previsualitzar targetes noves.
custom-study-preview-new-cards-added-in-the = Previsualitzar les targetes noces afeguides en els últims
custom-study-require-one-or-more-of-these = Es requereix una o més d'aquestes etiquetes
custom-study-review-ahead = Repasar per adelantat
custom-study-review-ahead-by = Repasar per adelantat per
custom-study-review-cards-forgotten-in-last = Repasar cartes oblidades en el últims
custom-study-review-forgotten-cards = Repassar targetes oblidades
custom-study-reviews-due-in-deck-over-today = Revisions vençudes per sobre del límit d'avui: { $val }
custom-study-select = Selecciona
custom-study-select-tags-to-exclude = Selecciona les etiquetes a excluir:
custom-study-selective-study = Estudi selectiu
custom-study-study-by-card-state-or-tag = Estudiar segons estat o etiqueta de la targeta
