decks-add-new-deck-ctrlandn = Afegeix mall (Ctrl+N)
decks-build = Genera
decks-cards-selected-by = targetes seleccionades per
decks-create-deck = Crea un mall
decks-custom-steps-in-minutes = Passos personalitzats (en minuts)
decks-deck = Mall
decks-decreasing-intervals = Intervals decreixents
decks-delete-deck = Suprimeix el mall
decks-enable-second-filter = Activa el segon filtre
decks-filter = Filtre:
decks-filter-2 = Filtre 2
decks-get-shared = Malls compartits
decks-import-file = Importa un fitxer
decks-increasing-intervals = Intervals creixents
decks-latest-added-first = Últimes afegides primer
decks-limit-to = Limita a
decks-minutes = minuts
decks-most-lapses = Més lapses
decks-new-deck-name = Nou nom del mall:
decks-no-deck = [sense mall]
decks-oldest-seen-first = Mostra primer les més antigues
decks-order-added = Ordre afegit
decks-order-due = Ordre de programades
decks-please-select-something = Seleccioneu alguna cosa.
decks-random = Aleatori
decks-relative-overdueness = Endarreriment relatiu
decks-repeat-failed-cards-after = Repeteix les targetes fallides després
decks-reschedule-cards-based-on-my-answers = Reprograma les targetes en funció de les meves respostes en aquest mall
decks-study = Estudia
decks-study-deck = Estudia el mall
decks-filtered-deck-search-empty = No s'ha trobat cap targeta coincident. És possible que algunes targetes s'hagin exclòs perquè estan suspeses o es troben en un mall filtrat diferent.
decks-unmovable-cards = Mostra qualsevol targeta exclosa
