decks-add-new-deck-ctrlandn = Afegeix mall (Ctrl+N)
decks-build = Construeix
decks-cards-selected-by = targetes seleccionades per
decks-create-deck = Crear mall
decks-custom-steps-in-minutes = passos personalitzats (en minuts)
decks-deck = Mall
decks-decreasing-intervals = Intervals decreixents
decks-delete-deck = Eliminar el mall
decks-enable-second-filter = Activar el segon filtre
decks-filter = Filtre:
decks-filter-2 = Filtre 2
decks-get-shared = Piles compartides
decks-import-file = Importa un fitxer
decks-increasing-intervals = Intervals creixents
decks-latest-added-first = Últimes afegides primer
decks-limit-to = Limita a
decks-minutes = minuts
decks-most-lapses = Més lapses
decks-new-deck-name = Nou nom del mall:
decks-no-deck = [sense mall]
decks-oldest-seen-first = Veure primer les més antigues
decks-order-added = Ordre afegit
decks-order-due = Ordre de programades
decks-please-select-something = Sisplau, selecciona alguna cosa.
decks-random = Aleatori
decks-relative-overdueness = Endarreriment relatiu
decks-repeat-failed-cards-after = Repeteix les targuetes fallides després
decks-reschedule-cards-based-on-my-answers = Reprogramar targetes en funció de les meves respostes en aquest mall
decks-study = Estudiar
decks-study-deck = Estudiar mall
decks-filtered-deck-search-empty = Cap targeta coincideixi amb la cerca proporcionada. És possible que algunes targetes s'hagin exclòs perquè es troben en un mall filtrat diferent o s'han suspès.
decks-unmovable-cards = Mostra qualsevol de les targetes excloses
