editing-add-media = Afegeix arxiu multimèdia
editing-an-error-occurred-while-opening = S'ha produït un error al obrir { $val }
editing-attach-picturesaudiovideo-f3 = Adjuntar imàtges/àudio/vídeo (F3)
editing-bold-text-ctrlandb = Text en negreta (Ctrl+B)
editing-cards = Targetes
editing-change-colour-f8 = Canviar de color (F8)
editing-cloze-deletion-ctrlandshiftandc = Blanc per omplir (Ctrl+Shift+C)
editing-couldnt-record-audio-have-you-installed = No s'ha pogut grabar l'audio. Has instalat "lame"?
editing-customize-card-templates-ctrlandl = Personalitzar plantilles de targuetes (Ctrl+L)
editing-customize-fields = Personalizar camps
editing-cut = Talla
editing-edit-current = Edita l'actual
editing-edit-html = Edita l'HTML
editing-fields = Camps
editing-html-editor = Editor HTML
editing-italic-text-ctrlandi = Text en cursiva (Ctrl+I)
editing-jump-to-tags-with-ctrlandshiftandt = Saltar a etiquetes amb Ctrl+Shift+T
editing-latex = LaTeX
editing-latex-equation = Equació LaTeX
editing-latex-math-env = Entorn matemàtic LaTeX
editing-mathjax-block = Bloc de MathJacx
editing-mathjax-chemistry = química MathJax
editing-mathjax-inline = MathJacx d'una línia
editing-media = Mèdia
editing-paste = Enganxa
editing-record-audio-f5 = Enrregistrar audio (F5)
editing-remove-formatting-ctrlandr = Eliminar format (Ctrl+R)
editing-set-foreground-colour-f7 = Establir color de primer plà (F7)
editing-show-duplicates = Mostra duplicats
editing-subscript-ctrland = Subíndex (Ctrl+=)
editing-superscript-ctrlandand = Superíndex (Ctrl++)
editing-tags = Etiquetes
editing-to-make-a-cloze-deletion-on = Per crear respostes anidades en una nota existent, primer ha de canviar a un tipus de nota de preguntes anidades, mitjançant 'Edita> Canvia el tipus de nota'.
editing-underline-text-ctrlandu = Subrallar text (Ctrl+U)
editing-warning-cloze-deletions-will-not-work = En compte, els blancs per omplir no funcionaran tret que canviïs el tipus de nota a Blancs per omlir.
