fields-add-field = Afegeix camp
fields-delete-field-from = Voleu eliminar el camp de { $val }?
fields-editing-font = Editant tipus de lletra
fields-field = Camp:
fields-field-name = Nom del camp:
fields-fields-for = Camps per { $val }
fields-font = Tipus de lletra:
fields-new-position-1 = Nova posició (1...{ $val }):
fields-notes-require-at-least-one-field = Les Notes requereixen almenys un camp.
fields-remember-last-input-when-adding = Recordar l'última entrada al afegir
fields-reverse-text-direction-rtl = Text de dreta a esquerra (RTL)
fields-size = Mida:
fields-sort-by-this-field-in-the = Ordenar segons aquest camp al navegador
fields-that-field-name-is-already-used = Aquest nom de camp ja està en ús.
fields-name-first-letter-not-valid = El com del camp no hauria de començar per #, ^ or /.
fields-name-invalid-letter = El nom del camp no hauria de contenir :, ", { "{" } or { "}" }.
