importing-failed-debug-info = La importació ha fallat. Informació de depuració:
importing-aborted = Interromput: { $val }
importing-added-duplicate-with-first-field = Afegueix duplicada amb el primer camp: { $val }
importing-allow-html-in-fields = Permet l'HTML als camps
importing-anki-files-are-from-a-very = Els arxius .anki són d'una versió anterior molt antiga 'Anki. Pot importar-los amb Anki 2.0, el qual està disponible en la web d'Anki.
importing-anki2-files-are-not-directly-importable = Els arxius -anki2 no es poden importar directament - si us plau importi els arxius .apkg o .zip que ha rebut en el seu lloc.
importing-appeared-twice-in-file = Ha aparegut per segona vegada: { $val }
importing-by-default-anki-will-detect-the = Per defecte, Anki detectarà el caràcter entre camps, com  un tabulador, una coma o similar. Si Anki detecta malament el caràcter,  podeu introduir-lo aquí. Useu \t per representar el tabulador.
importing-change = Canvia
importing-colon = Dos punts
importing-comma = Coma
importing-empty-first-field = Primer camp està buit: { $val }
importing-field-mapping = Mapejat de camp
importing-field-of-file-is = El camp <b>{ $val }</b> del fitxer és:
importing-fields-separated-by = Camps separats per: { $val }
importing-file-version-unknown-trying-import-anyway = La versió de l'arxiu és desconeguda, intentant importar de totes formes.
importing-first-field-matched = Primer camp coincident: { $val }
importing-identical = Idèntic
importing-ignore-field = Ignorar camp.
importing-ignore-lines-where-first-field-matches = Ignorar línies on el primer camp coincideixi amb una nota existent.
importing-ignored = <ignorat>
importing-import-even-if-existing-note-has = Importar encara que existeixi una nota amb el mateix primer camp
importing-import-options = Opcions d'importació
importing-importing-complete = Importació completa.
importing-invalid-file-please-restore-from-backup = Arxiu invàlid. Sis us plau, restauri des d'una còpia de seguretat.
importing-map-to = Associa a { $val }
importing-map-to-tags = Associa a les etiquetes
importing-mapped-to = mapejat a <b>{ $val }</b>
importing-mapped-to-tags = mapejat a <b>Etiquetes</b>
importing-mnemosyne-20-deck-db = Mall Mnemosyne 2.0 (*.db)
importing-multicharacter-separators-are-not-supported-please = Los separadores de més d'un caràcter no son vàlids. Sisplau, introdueix un únic caràcter.
importing-notes-added-from-file = Notes afegides des dede l'arxiu: { $val }
importing-notes-found-in-file = Notes trobades en l'arxiu: { $val }
importing-notes-skipped-as-theyre-already-in = S'han omés les notes, atès que ja es troben en la teva col·lecció: { $val }
importing-notes-that-could-not-be-imported = Notes que no s'han pogut importat degut a un canvi de tipus de nota: { $val }
importing-notes-updated-as-file-had-newer = Notes actualitzades, l'arxiu contenía una versió més recent: { $val }
importing-packaged-anki-deckcollection-apkg-colpkg-zip = Mall d'anki comprès/ Col·lecció (*.apkg *.colpkg *.zip)
importing-pauker-18-lesson-paugz = Llicó de Pauker (*.pau.gz)
importing-rows-had-num1d-fields-expected-num2d = '%(row)s' amb %(num1)d camps, s'esperava %(num2)d
importing-selected-file-was-not-in-utf8 = L'arxiu seleccionat no estava en format UTF-8. Si us plau, llegeix la secció "importació" del manual.
importing-semicolon = Punt i coma
importing-skipped = Omès
importing-supermemo-xml-export-xml = Exporta a Supermemo XML (*.xml)
importing-tab = Tabulació
importing-tag-modified-notes = Etiqueta les notes modificades:
importing-text-separated-by-tabs-or-semicolons = Text separat per tabulacions o punt i coma (*)
importing-the-first-field-of-the-note = El primer camp del tipus de nota ha de ser assignat a alguna cosa.
importing-the-provided-file-is-not-a = L'arxiu proporcionat no és un arxiu .apkg valgut.
importing-this-file-does-not-appear-to = Aquest fitxer no sembla ser un arxiu .apkg vàlid. Si estàs obtenint aquest error amb un arxiu descarregat des AnkiWeb, és possible que els vostres recursos en qüestió. Si us plau, torna a intentar-ho, i si el problema continua, torna a intentar-ho amb un altre navegador.
importing-this-will-delete-your-existing-collection = Això eliminarà la teva col·lecció actual i la reemplaçarà amb les dades de l'arxiu que estàs important. Estàs segur?
importing-unable-to-import-from-a-readonly = No és possible importar des d'un fitxer de només lectura.
importing-unknown-file-format = Format de fitxer desconegut.
importing-update-existing-notes-when-first-field = Actualitzar les targetes existents quan el primer camp coincideixi
importing-updated = Actualitzat
