notetypes-front-field = Fronte
notetypes-back-field = Verso
notetypes-add-reverse-field = Apondre lo verso
notetypes-text-field = Texto
notetypes-basic-name = Elementari
notetypes-basic-reversed-name = Generalitats (dos senses)
notetypes-basic-optional-reversed-name = Generalitats (convèrsa facultativa)
notetypes-cloze-name = Tèxte amb traucs
notetypes-basic-type-answer-name = Basic (insere in le responsa)
notetypes-card-2-name = Carta 2
notetypes-card-1-name = Carta 1
