preferences-anki-21-scheduler-beta = Planificador de Anki 2.1 (beta)
preferences-automatically-sync-on-profile-openclose = Sincronitza automàticament en obrir o tancar un perfil
preferences-backups = Còpies de seguretat
preferences-backups2 = còpies de seguretat
preferences-backupsanki-will-create-a-backup-of = <b>Còpies de seguretat</b><br>Anki farà una còpia de seguretat de la col·lecció de l'usuari cada cop que el tanqueu o sincronitzeu.
preferences-basic = Bàsica
preferences-change-deck-depending-on-note-type = Canviar el mall en funció del tipus de nota
preferences-changes-will-take-effect-when-you = Els canvis tindran efecte quan reiniciis Anki.
preferences-hardware-acceleration-faster-may-cause-display = Acceleració per hardware (més ràpid, pot causar problemes)
preferences-hours-past-midnight = hores passada la mitjanit
preferences-interface-language = Idioma de la interfase
preferences-interrupt-current-audio-when-answering = Interrompre el audio actual al respondre
preferences-keep = Manté
preferences-learn-ahead-limit = Límit d'estudi per adalantat
preferences-mins = mins.
preferences-network = Xarxa
preferences-next-day-starts-at = El  següent dia comença en
preferences-night-mode = Mode nocturn
preferences-note-media-is-not-backed-up = Nota: no es fan còpies de seguretat dels arxius multimèdia. Si us plau, fes còpies de seguretat de la teva carpeta de Anki periòdicament per assegurar-la.
preferences-on-next-sync-force-changes-in = En la propera sincronització, força els canvis en una direcció
preferences-paste-clipboard-images-as-png = Enganxa les imatges del portapapers com a PNG
preferences-paste-without-shift-key-strips-formatting = Enganxa sense premer la tecla Mayús per eliminar el format
preferences-periodically-sync-media = Sincronitzar arxius multimèdia periòdicament
preferences-please-restart-anki-to-complete-language = Sisplau, reinicia l'Anki per a completar el canvi d'idioma.
preferences-preferences = Preferències
preferences-scheduling = Planificació
preferences-show-learning-cards-with-larger-steps = Mostrar les targuetes en aprenentatge amb esglaons més grans abans dels repassos
preferences-show-next-review-time-above-answer = Mostra interval de proper repàs sobre dels botons de resposta
preferences-show-play-buttons-on-cards-with = Mostrar botons de reproducció en tarjetes amb audio
preferences-show-remaining-card-count-during-review = Mostra el nombre de targetes restants durant el repàs
preferences-some-settings-will-take-effect-after = Alguna configuració no tindrà efecte fins a reiniciar l'Anki.
preferences-synchronisation = <b>Sincronització</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronització</b><br> No està activada; feu clic al botó de sincronització de la pantalla principal per activar-la.
preferences-synchronize-audio-and-images-too = Sincronitzar també els sons i les imatges
preferences-this-will-reset-any-cards-in = Aixó resetarà qualsevol carta en aprenentatge, buidarà malls filtrats, i canviarà la versió del planificador. Vols porcedir?
preferences-timebox-time-limit = Límit de sessió d'estudi
preferences-user-interface-size = Mida de l'interfase d'usuari
preferences-when-adding-default-to-current-deck = En afegir, fer-ho al mall actual per defecte
preferences-you-can-restore-backups-via-fileswitch = Pot restaurar còpies de seguretat amb  Arxiu->Cambiar de perfil.
