preferences-automatically-sync-on-profile-openclose = Sincronitza automàticament en obrir o tancar un perfil
preferences-backups = Còpies de seguretat
preferences-basic = Bàsica
preferences-change-deck-depending-on-note-type = Canvia el mall en funció del tipus de nota
preferences-changes-will-take-effect-when-you = Els canvis s'aplicaran quan reinicieu Anki.
preferences-hours-past-midnight = hora/hores passada la mitjanit
preferences-interface-language = Idioma de la interfície:
preferences-interrupt-current-audio-when-answering = Interromp el so actual en respondre
preferences-learn-ahead-limit = Límit d'estudi per endavant
preferences-mins = minut(s)
preferences-network = Xarxa
preferences-next-day-starts-at = El dia següent comença a les
preferences-note-media-is-not-backed-up = Nota: no es fan còpies de seguretat dels arxius multimèdia. Per a assegurar aquest contingut, feu una còpia de la vostra carpeta d'Anki de manera periòdica.
preferences-on-next-sync-force-changes-in = En la pròxima sincronització, força els canvis en una direcció
preferences-paste-clipboard-images-as-png = Enganxa les imatges del portapapers com a PNG
preferences-paste-without-shift-key-strips-formatting = Enganxa sense prémer la tecla de majúscules per a eliminar-ne el format
preferences-periodically-sync-media = Sincronitza els fitxers multimèdia periòdicament
preferences-please-restart-anki-to-complete-language = Reinicieu Anki per a completar el canvi d'idioma.
preferences-preferences = Preferències
preferences-scheduling = Planificació
preferences-show-learning-cards-with-larger-steps = Mostra les targetes que estic aprenent amb passos més grans abans dels repassos
preferences-show-next-review-time-above-answer = Mostra l'interval de repàs pròxim sobre dels botons de resposta
preferences-show-play-buttons-on-cards-with = Mostra els botons de reproducció en les targetes que tenen so
preferences-show-remaining-card-count-during-review = Mostra el nombre de targetes restants durant el repàs
preferences-some-settings-will-take-effect-after = Alguns canvis no s'aplicaran fins que reinicieu Anki.
preferences-synchronisation = <b>Sincronització</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronització</b><br> La sincronització està desactivada. Feu clic en el botó de sincronització de la pantalla principal per a activar-la.
preferences-synchronize-audio-and-images-too = Sincronitza també els sons i les imatges
preferences-timebox-time-limit = Límit de sessió d'estudi
preferences-user-interface-size = Mida de l'interfície d'usuari
preferences-when-adding-default-to-current-deck = Afegeix al mall actual per defecte
preferences-you-can-restore-backups-via-fileswitch = Podeu restaurar còpies de seguretat des del menú Arxiu → Canviar de perfil.
preferences-legacy-timezone-handling = Gestió de zones horàries antiga (tot i que té errors, és necessària si feu servir AnkiDroid 2.14 o inferior)
preferences-default-search-text = Text de cerca per defecte
preferences-default-search-text-example = per exemple: 'deck:current'
preferences-theme-label = Tema { $theme }
preferences-theme-follow-system = segons el sistema
preferences-theme-light = clar
preferences-theme-dark = fosc
preferences-v3-scheduler = V3 del planificador
preferences-ignore-accents-in-search = Ignora els accents quan cerquis (més lent)
preferences-backup-explanation =
    Anki fa una còpia de seguretat periòdica de la vostra col·lecció. Quan les còpies compleixin 2 dies,
    Anki començarà a eliminar-ne algunes per tal d'alliberar espai en el disc.
preferences-daily-backups = Còpies de seguretat diàries que cal mantenir:
preferences-weekly-backups = Còpies de seguretat setmanals que cal mantenir:
preferences-monthly-backups = Còpies de seguretat mensuals que cal mantenir:
preferences-minutes-between-backups = Minuts que ha d'haver-hi entre còpies de seguretat automàtiques:
