actions-add = Adaugă
actions-all-selected = Toate Selectate
actions-any-selected = Oricare Selectată
actions-cancel = Anulare
actions-choose = Alege
actions-close = Închide
actions-copy = Copiază
actions-create-copy = Crează o Copie
actions-custom-study = Studiu personalizat
actions-decks = Pachete
actions-delete = Șterge
actions-export = Exportă
actions-filter = Filtrează
actions-help = Ajutor
actions-import = Importă
actions-manage = Administrare...
actions-name = Nume:
actions-new = Nou
actions-new-name = Nume nou:
actions-options = Opțiuni
actions-options-for = Opțiuni pentru { $val }
actions-preview = Previzualizare
actions-rebuild = Reconstruiește
actions-rename = Redenumește
actions-rename-deck = Redenumește pachet
actions-rename-tag = Redenumește Marcaj
actions-rename-with-parents = Redenumește cu Părinți
actions-remove-tag = Elimină Marcaj
actions-replay-audio = Repetă Audio
actions-reposition = Repoziționează
actions-save = Salvează
actions-search = Caută
actions-select = Selectează
actions-shortcut-key = Tastă(e) de comandă rapidă
actions-suspend-card = Suspendă fișa
actions-set-due-date = Stabilește dată scadentă
actions-answer-card = Fișă de răspuns
actions-unbury-unsuspend = Dezgroapă/Anulează Suspendarea
actions-add-deck = Adaugă Pachet
actions-add-note = Adaugă Notă
actions-update-tag = Actualizează Marcaj
actions-update-note = Actualizează Notă
actions-update-card = Actualizează Fișa
actions-update-deck = Actualizează Pachet
actions-forget-card = Uită Fișa
actions-build-filtered-deck = Construiește Pachet
actions-add-notetype = Adaugă Fișă tip
actions-remove-notetype = Elimină Fișă tip
actions-update-notetype = Actualizează Fișă tip
actions-update-config = Actualizează Configurarea
actions-card-info = Informații Fișă
actions-previous-card-info = Informațiile Fișei Anterioare

## Flags

actions-flag-number = Fanion/Flag
actions-flag-red = Roșu
actions-flag-orange = Portocaliu
actions-flag-green = Verde
actions-flag-blue = Albastru
actions-flag-pink = Roz
actions-flag-turquoise = Turcoaz
actions-flag-purple = Violet
actions-set-flag = Adaugă Fanion/Flag
