actions-add = Adaugă
actions-blue-flag = Fanion albastru
actions-cancel = Anulare
actions-choose = Alege
actions-close = Închide
actions-copy = Copiaza
actions-custom-study = Studiu personalizat
actions-decks = Pachete
actions-delete = Șterge
actions-export = Exportă
actions-filter = Filtru
actions-green-flag = Fanion verde
actions-help = Ajutor
actions-import = Importă
actions-manage = Administrare...
actions-name = Nume:
actions-new = Noi
actions-new-name = Nume nou:
actions-options = Opțiuni
actions-options-for = Opțiuni pentru { $val }
actions-preview = Previzualizare
actions-red-flag = Fanion roșu
actions-rename = Redenumește
actions-rename-deck = Redenumire pachet
actions-reposition = Repoziționează
actions-save = Salvează
actions-search = Caută
actions-suspend-card = Suspendă card
