card-templates-front-template = Șablon față
card-templates-back-template = Șablon verso
card-templates-front-preview = Previzualizare față
card-templates-back-preview = Previzualizare verso
card-templates-preview-box = Previzualizare
card-templates-anki-couldnt-find-the-line-between = Anki n-a putut găsi linia dintre întrebare și răspuns. Te rog să ajustezi manual șablonul pentru a comuta între întrebare și răspuns.
card-templates-at-least-one-card-type-is = E nevoie de cel puțin un tip de card.
card-templates-card = Card { $val }
card-templates-card-types = Tipuri de carduri
card-templates-card-types-for = Tipuri de card pentru { $val }
card-templates-cloze = Test cu cuvinte lipsă
card-templates-delete-the-as-card-type-and = Ștergi tipul de card '%(a)s' împreună cu %(b)s lui?
card-templates-enter-deck-to-place-new = Introdu pachetul pentru a plasa cele { $val } carduri noi sau lasă-l necompletat:
card-templates-enter-new-card-position-1 = Introdu noua poziție a cardului (1...{ $val }):
card-templates-flip = Inversează
card-templates-form = Formular
card-templates-off =  (oprit)
card-templates-on =  (pornit)
