decks-add-new-deck-ctrlandn = Adăugă pachet nou (Ctrl+N)
decks-are-you-sure-you-wish-to = Sigur vrei să ștergi { $val }?
decks-build = Construieşte
decks-cards-selected-by = carduri selectate de
decks-create-deck = Creează pachet
decks-custom-steps-in-minutes = Pași personalizați (în minute)
decks-deck = Pachet
decks-decreasing-intervals = Intervale de scădere
decks-delete-deck = Ştergere pachet
decks-enable-second-filter = Activează al doilea filtru
decks-filter = Filtru:
decks-filter-2 = Filtru 2
decks-get-shared = Obține partajate
decks-import-file = Importă fișier
decks-increasing-intervals = Creștere intervale
decks-latest-added-first = Ultimele adăugate mai întâi
decks-limit-to = Limitează la
decks-minutes = minute
decks-most-lapses = Cele mai multe greșeli
decks-name-for-deck = Nume pentru pachet:
decks-new-deck-name = Nume nou pentru pachet:
decks-no-deck = [fără pachet]
decks-order-added = Ordine carburi adăugate
decks-order-due = Ordine dată scadentă
decks-random = Aleator
decks-study-deck = Studiază pachet
