exporting-all-decks = Toate pachetele
exporting-anki-20-deck = Pachet Anki 2.0
exporting-anki-deck-package = Grup de pachete Anki
exporting-cards-in-plain-text = Carduri în Plain Text
exporting-collection = colecție
exporting-collection-exported = Colecție exportată.
exporting-couldnt-save-file = Nu s-a putut salva fişierul: { $val }
exporting-export = Exportă...
exporting-export-format = <b>Format export</b>:
exporting-include = <b>Include</b>:
exporting-include-media = Include media
exporting-include-scheduling-information = Include planificarea
exporting-include-tags = Include etichete
exporting-selected-notes = Șterge notițele
