importing-failed = Import eșuat.
importing-failed-debug-info = Import nereușit. Informații de depanare:
importing-aborted = Nereușite: { $val }
importing-added-duplicate-with-first-field = Adaugă duplicat cu primul câmp: { $val }
importing-allow-html-in-fields = Permite HTML în câmpuri
importing-appeared-twice-in-file = A apărut de două ori în fișierulȘ { $val }
importing-by-default-anki-will-detect-the = Anki detectează caracterul dintre câmpuri, cum ar fi taburi, virgule, etc. Dacă Anki nu detectează corect caracterul, îl puteți specifica aici. Folosiți \t pentru tab.
importing-change = Modifică
importing-colon = Două puncte
importing-comma = Virgulă
importing-empty-first-field = Golește primul câmp: { $val }
importing-field-mapping = Transformare câmpuri
importing-field-of-file-is = Câmpul <b>{ $val }</b> al fișierului este:
importing-fields-separated-by = Câmpuri separate de: { $val }
importing-first-field-matched = Primul câmp potrivit: { $val }
importing-ignore-field = Ignoră câmpul
importing-ignore-lines-where-first-field-matches = Ignoră liniile în care primul câmp se potrivește cu nota existentă
importing-ignored = <ignorat>
importing-import-even-if-existing-note-has = Importă chiar dacă nota existentă are același prim câmp
importing-import-options = Opțiuni la importare
importing-importing-complete = Import complet.
importing-invalid-file-please-restore-from-backup = Fișier invalid. Te rog să-l restaurezi dintr-o copie de siguranță.
importing-map-to = Transformă în { $val }
importing-map-to-tags = Transformă în etichete
importing-mapped-to = transformat în <b>{ $val }</b>
importing-mapped-to-tags = transformat în <b>etichete</b>
importing-mnemosyne-20-deck-db = Pachet Mnemosyne 2.0 (*.db)
importing-rows-had-num1d-fields-expected-num2d = '%(row)s' are %(num1)d câmpuri, din %(num2)d prevăzute
importing-supermemo-xml-export-xml = XML exportat din Supermemo (*.xml)
