notetypes-front-field = Față
notetypes-back-field = Verso
notetypes-add-reverse-field = Adaugă verso
notetypes-text-field = Text
notetypes-basic-name = De bază
notetypes-basic-reversed-name = De bază (și cu card întors)
notetypes-basic-optional-reversed-name = De bază (opțional cu card întors)
notetypes-cloze-name = Test cu cuvinte lipsă
notetypes-basic-type-answer-name = De bază(tastați răspunsul)
notetypes-card-2-name = Card 2
notetypes-card-1-name = Card 1
notetypes-add = Adaugă: { $val }
notetypes-add-note-type = Adaugă tip de notă
notetypes-cards = Carduri…
notetypes-clone = Clonează: { $val }
notetypes-copy = Copie a { $val }
notetypes-delete-this-note-type-and-all = Ștergi acest tip de notă și toate cardurile lui?
notetypes-delete-this-unused-note-type = Ștergi acest tip de notă nefolosit?
notetypes-fields = Câmpuri...
notetypes-footer = Subsol
notetypes-header = Antet
notetypes-note-types = Tipuri notă
notetypes-options = Opțiuni…
notetypes-type = Tip
