notetypes-front-field = Față
notetypes-back-field = Verso
notetypes-add-reverse-field = Adaugă verso
notetypes-text-field = Text
notetypes-basic-name = De bază
notetypes-basic-reversed-name = De bază (și cu card întors)
notetypes-basic-optional-reversed-name = De bază (opțional cu card întors)
notetypes-cloze-name = Test cu cuvinte lipsă
notetypes-basic-type-answer-name = De bază(tastați răspunsul)
notetypes-card-2-name = Card 2
notetypes-card-1-name = Card 1
