preferences-automatically-sync-on-profile-openclose = Sincronizare automată la deschiderea / închiderea profilului
preferences-backups = Salvări de siguranță
preferences-backups2 = copii de rezervă
preferences-backupsanki-will-create-a-backup-of = <b> Backup </ b> <br> Anki va crea o copie de rezervă a colecției de fiecare dată când este închisă sau sincronizată.
preferences-basic = De bază
preferences-change-deck-depending-on-note-type = Schimbă pachetul în funcție de tipul notei
preferences-hours-past-midnight = ore trecute de miezul nopții
preferences-interface-language = Limba interfeței:
preferences-keep = Păstrează
preferences-learn-ahead-limit = Limita de sus pentru cele învățate
preferences-mins = minute
preferences-network = Rețea
preferences-next-day-starts-at = Ziua următoare începe la
preferences-preferences = Preferințe
preferences-scheduling = Re-planifică
preferences-some-settings-will-take-effect-after = Unele configurări vor intra în vigoare după ce reporniți Anki
preferences-synchronisation = <b>Sincronizare</b>
preferences-synchronizationnot-currently-enabled-click-the-sync = <b>Sincronizare</b><br> În acest moment sincronizarea nu este activată; apasă pe butonul de sincronizare din fereastra principală.
preferences-synchronize-audio-and-images-too = Sincronizarea fişierelor audio şi a imaginilor
