sync-media-check-required = A apărut o problemă în timp ce se sincronizau fișierele media. Te rog să folosești Instrumente->Verifică media, apoi să sincronizezi din nou pentru a corecta problema.
sync-wrong-pass = ID-ul AnkiWeb sau parola au fost incorecte, te rog să încerci din nou.
sync-download-from-ankiweb = Descarcă de la AnkiWeb
sync-cancel-button = Anulare
sync-downloading-from-ankiweb = Descărcare de la AnkiWeb...
sync-syncing = Sincronizare...
sync-checking = Se verifică…
sync-ankiweb-id-label = ID-ul AnkiWeb
sync-password-label = Parolă:
sync-account-required =
    <h1>Cont obligatoriu</h1>
    Un cont gratuit este necesar pentru a păstra sincronizată colecția. Te rog, <a href="{ $link }">înscrie-te</a> pentru un cont, apoi introdu detaliile tale.
sync-connecting = Se conectează...
