actions-add = Add
actions-all-selected = All selected
actions-any-selected = Any selected
actions-cancel = Cancel
actions-choose = Choose
actions-close = Close
actions-discard = Discard
actions-copy = Copy
actions-create-copy = Create Copy
actions-custom-study = Custom Study
actions-decks = Decks
actions-delete = Delete
actions-export = Export
actions-filter = Filter
actions-help = Help
actions-import = Import
actions-manage = Manage...
actions-name = Name:
actions-new = New
actions-new-name = New name:
actions-options = Options
actions-options-for = Options for { $val }
actions-preview = Preview
actions-rebuild = Rebuild
actions-rename = Rename
actions-rename-deck = Rename Deck
actions-rename-tag = Rename Tag
actions-rename-with-parents = Rename with Parents
actions-remove-tag = Remove Tag
actions-replay-audio = Replay Audio
actions-reposition = Reposition
actions-save = Save
actions-search = Search
actions-select = Select
actions-shortcut-key = Shortcut key: { $val }

## Flags

actions-auto-advance-activated = Auto Advance enabled
actions-auto-advance-deactivated = Auto Advance disabled
