actions-add = Hozzáadás
actions-all-selected = összes kiválasztva
actions-cancel = Mégsem
actions-choose = Kiválasztás
actions-close = Bezárás
actions-copy = Másolás
actions-create-copy = Másolat készítése
actions-custom-study = Egyéni tanulás
actions-decks = Paklik
actions-delete = Törlés
actions-export = Exportálás
actions-filter = Szűrő
actions-help = Súgó
actions-import = Importálás
actions-manage = Műveletek...
actions-name = Név:
actions-new = Új
actions-new-name = Új név:
actions-options = Beállítások
actions-options-for = Beállítások ehhez: { $val }
actions-preview = Előnézet
actions-rebuild = Újraépítés
actions-rename = Átnevezés
actions-rename-deck = Pakli átnevezése
actions-rename-tag = Címke átnevezése
actions-remove-tag = Címke eltávolítása
actions-replay-audio = Hang lejátszása újból
actions-reposition = Sorrendmódosítás
actions-save = Mentés
actions-search = Keresés
actions-select = Kijelölés
actions-shortcut-key = Gyorsbillentyű: { $val }
actions-suspend-card = Kártya felfüggesztése
actions-set-due-date = Az esedékesség beállítása

## Flags

actions-flag-red = Piros
actions-flag-orange = Narancssárga
actions-flag-green = Zöld
actions-flag-blue = Kék
actions-flag-pink = Rózsaszin
actions-flag-turquoise = Türkiz
actions-flag-purple = Lila
