actions-add = Hozzáadás
actions-all-selected = összes kiválasztva
actions-any-selected = Minden kiválasztott
actions-cancel = Mégsem
actions-choose = Kiválasztás
actions-close = Bezárás
actions-discard = Eldobni
actions-copy = Másolás
actions-create-copy = Másolat készítése
actions-custom-study = Egyéni tanulás
actions-decks = Paklik
actions-decrement-value = Érték csökkentése
actions-delete = Törlés
actions-export = Exportálás
actions-filter = Szűrő
actions-help = Súgó
actions-increment-value = Érték növelése
actions-import = Importálás
actions-manage = Műveletek...
actions-name = Név:
actions-new = Új
actions-new-name = Új név:
actions-options = Beállítások
actions-options-for = Beállítások ehhez: { $val }
actions-preview = Előnézet
actions-rebuild = Újraépítés
actions-rename = Átnevezés
actions-rename-deck = Pakli átnevezése
actions-rename-tag = Címke átnevezése
actions-rename-with-parents = Átnevezés szülőkkel
actions-remove-tag = Címke eltávolítása
actions-replay-audio = Hang lejátszása újból
actions-reposition = Sorrendmódosítás
actions-save = Mentés
actions-search = Keresés
actions-select = Kijelölés
actions-shortcut-key = Gyorsbillentyű: { $val }
actions-suspend-card = Kártya felfüggesztése
actions-set-due-date = Az esedékesség beállítása
actions-answer-card = Válaszkártya
actions-unbury-unsuspend = Félretevés/felfüggesztés megszüntetése
actions-add-deck = Pakli hozzáadása
actions-add-note = Jegyzet hozzáadása
actions-update-tag = Címke frissítése
actions-update-note = Jegyzet frissítése
actions-update-card = Kártya frissítése
actions-update-deck = Pakli frissítése
actions-forget-card = Kártya alaphelyzetbe állítása
actions-build-filtered-deck = Pakli építése
actions-add-notetype = Jegyzettípus hozzáadása
actions-remove-notetype = Jegyzettípus eltávolítása
actions-update-notetype = Jegyzettípus frissítése
actions-update-config = Konfiguráció frissítése
actions-card-info = Kártya információ
actions-previous-card-info = Előző kártya információ
# By convention, the name of a menu action is suffixed with "..." if additional
# input is required before it can be performed. E.g. "Export..." vs. "Delete".
actions-with-ellipsis = { $action }...
actions-fullscreen-unsupported = A teljes képernyős módot nem támogatja a videó illesztőprogram. Próbáljon meg másikra váltani a beállítások képernyőn.

## Flags

actions-flag-number = Zászló { $number }
actions-flag-red = Piros
actions-flag-orange = Narancssárga
actions-flag-green = Zöld
actions-flag-blue = Kék
actions-flag-pink = Rózsaszin
actions-flag-turquoise = Türkiz
actions-flag-purple = Lila
actions-set-flag = Zászló beállítása
actions-nothing-to-undo = Nincs mit visszacsinálni
actions-nothing-to-redo = Nincs mit újracsinálni
actions-auto-advance = Autómatikus előrelépés
actions-auto-advance-activated = Autómatikus előrelépés bekapcsolva
actions-auto-advance-deactivated = Autómatikus előrelépés kikapcsolva
