editing-actual-size = Tényleges méret
editing-add-media = Média hozzáadása
editing-align-left = Balra igazítás
editing-align-right = Jobbra igazítás
editing-an-error-occurred-while-opening = { $val } fájl megnyitása során hiba történt.
editing-attach-picturesaudiovideo = Képek/hangfelvétel/videó csatolása
editing-bold-text = Fékövér
editing-cards = Kártyák
editing-center = Közép
editing-change-color = Szín módosítása
editing-cloze-deletion = Lyukas szöveg (új kártya)
editing-cloze-deletion-repeat = Lyukas szöveg (ugyanaz a kártya)
editing-copy-image = Kép másolása
editing-couldnt-record-audio-have-you-installed = Nem sikerült hangfelvételt készíteni. Telepítetted a 'lame'-et?
editing-customize-card-templates = Kártya sablonok személyreszabása
editing-customize-fields = Mezők testreszabása
editing-cut = Kivágás
editing-double-click-image = kettős kattintás a képen
editing-double-click-to-expand = kettős kattintás a nagyításhoz
editing-double-click-to-collapse = kettős kattintás a kicsinítéshez
editing-edit-current = Aktuális jegyzet szerkesztése
editing-edit-html = HTML szerkesztése
editing-fields = Mezők
editing-float-left = Balra rendezés
editing-float-right = Jobbra rendezés
editing-float-none = Nincs rendezés
editing-indent = Behúzás növelése
editing-italic-text = Dőlt
editing-jump-to-tags-with-ctrlandshiftandt = Címkékre ugrás: Ctrl+Shift+T.
editing-justify = Sorkizárt
editing-latex = LaTeX
editing-latex-equation = LaTeX egyenlet
editing-latex-math-env = LaTeX matematikai környezet
editing-mathjax-block = MathJax blokk
editing-mathjax-chemistry = MathJax kémia
editing-mathjax-inline = MathJax elem
editing-mathjax-placeholder = Nyomd meg a { $accept } billenyűt az elfogadáshoz, { $newline } billenyűt új sor beszúrásához!
editing-media = Médiaállomány
editing-open-image = Kép megnyitása
editing-show-in-folder = Megjelenítés a mappában
editing-ordered-list = Számozott lista
editing-outdent = Behúzás csökkentése
editing-paste = Beillesztés
editing-record-audio = Hangfelvétel rögzítése
editing-remove-formatting = Formázás eltávolítása
editing-restore-original-size = Visszaállítás az eredeti méretére
editing-select-remove-formatting = Eltávolítandó formázás
editing-show-duplicates = Duplikáltak megjelenítése
editing-subscript = Alsó index
editing-superscript = Felső index
editing-tags = Címkék
editing-tags-add = Címke hozzáadása
editing-tags-copy = Címkék másolása
editing-tags-remove = Címkék törlése
editing-tags-select-all = Minden címke kiválasztása
editing-text-color = Betűszín
editing-text-highlight-color = Háttérszín
editing-to-make-a-cloze-deletion-on = Ha egy meglévő jegyzetet lyukas szövegként (cloze) szeretnél használni, előbb át kell állítani „lyukas szöveg” típusra a Szerkesztés > Jegyzettípus módosítása menüponttal.
editing-toggle-html-editor = HTML szerkesztő
editing-toggle-visual-editor = Vizuális szerkesztő
editing-toggle-sticky = Rögzítés
editing-expand = Kinyitás
editing-collapse = Összecsukás
editing-expand-field = Mező kinyitása
editing-collapse-field = Mező összecsukása
editing-underline-text = Aláhúzás
editing-unordered-list = Számozatlan lista
editing-warning-cloze-deletions-will-not-work = Figyelem: a lyukas szöveg addig nem működik, amíg a fenti típust be nem állítod Lyukas szövegre.
editing-mathjax-preview = MathJax előnézet
editing-shrink-images = Képek kicsínytése
editing-close-html-tags = Automatikus HTML záró tag
editing-from-clipboard = Vágólapról
editing-alignment = Igazítás
editing-equations = Egyenletek
editing-no-image-found-on-clipboard = Nem található kép a vágólapon
editing-image-occlusion-mode = Képfedés mód
editing-image-occlusion-zoom-out = Kicsinyítés
editing-image-occlusion-zoom-in = Nagyítás
editing-image-occlusion-zoom-reset = Nagyítás visszaállítása
editing-image-occlusion-toggle-translucent = Átlátszóság
editing-image-occlusion-delete = Törlés
editing-image-occlusion-duplicate = Duplikált
editing-image-occlusion-group = Csoportosítás
editing-image-occlusion-ungroup = Csoportbontás
editing-image-occlusion-select-all = Minden kiválasztása
editing-image-occlusion-alignment = Igazítás
editing-image-occlusion-align-left = Balra igazítás
editing-image-occlusion-align-h-center = Vízszintesen középre igazítás
editing-image-occlusion-align-right = Jobbra igazítás
editing-image-occlusion-align-top = Felülre igazítás
editing-image-occlusion-align-v-center = Függőlegesen középre igazítás
editing-image-occlusion-align-bottom = Alulra igazítás
editing-image-occlusion-select-tool = Kijelölés
editing-image-occlusion-zoom-tool = Nagyítás
editing-image-occlusion-rectangle-tool = Téglalap
editing-image-occlusion-ellipse-tool = Ellipszis
editing-image-occlusion-polygon-tool = Sokszög
editing-image-occlusion-text-tool = Szöveg
editing-image-occlusion-fill-tool = Egyszínű kitöltés
editing-image-occlusion-toggle-mask-editor = Maszk szerkesztő
editing-image-occlusion-reset = Képfedés visszaállítása
editing-image-occlusion-confirm-reset = Biztosan vissza akarod állítani a képfedést?

## You don't need to translate these strings, as they will be replaced with different ones soon.

editing-html-editor = HTML-szerkesztő
